### PR TITLE
Modify CI docker SD behavior to match dev env

### LINKED ISSUE #3839: Remove CircleCI docker divergence
## Description

The docker remote machine executor is great in terms of saving us potential $$$ but is disastrous for debugging. Let's use the circleci `machine` executor so we can use volume mapping with `docker`. If they end up charging an arm and a leg for it in the future we can move to another platform but at least then our test logic will match development env.

## User Stories

As a developer, it is super frustrating to have two parallel testing/building strategies for development and production.

### PR DESCRIPTION
**Pull request by msheiny**
## Status

Ready for review -- uncovered what look like legit linting failures

## Description of Changes

Fixes #3839 

Changes proposed in this pull request:

* Utilize higher :dollar:  cost `machine` executor (at least they plan to charge more for it in the "future")
* Revamp docker caching to only rebuild when `Dockerfile` changes.

## Testing

How should the reviewer test this PR?

* Ensure you can still spin up docker locally (tests and dev env)
* Ensure CI doesn't break :crossed_fingers: 

## Deployment

Any special considerations for deployment? Consider both:

NOPE - only affects dev + CI

### If you made changes to the server application code:

Umm  I didn't questionnaire... why you all up in my bizness!?

### If you made changes to `securedrop-admin`:

HEY! Whats with all the :fire: ?

### If you made changes to the system configuration:

I swear to god... 

### If you made non-trivial code changes:

- [x] I have written a test plan and validated it for this PR

### If you made changes to documentation:

Docs!? we have docs!?

### CODE REVIEW

**Comment by msheiny** [comment]
holy $#!# - i want on a huge tangent trying to improve the story here and opened up a can of worms. This PR is def. WIP... not ready for review. feel free to unpack and improve if you are feeling gutsy

**Comment by msheiny** [comment]
I want to point out here that `lint` is failing but:
* a majority of the shellcheck ones seem to be a side-effect of bumping the shellcheck version
* i'm actually confused on the mypy failure here though. I also get failures on `develop` when i run it locally. I thought maybe it was just a grsec thing but I'm getting the same error in CI here.

@kushaldas can you eye the mypy failure to make sure I'm not crazy?

**Comment by redshiftzero** [comment]
> i'm actually confused on the mypy failure here though. I also get failures on develop when i run it locally. I thought maybe it was just a grsec thing but I'm getting the same error in CI here.

I get the same mypy error, so this is a legitimate issue, switching `pages-layout` to `pageslayout` _should_ resolve (dashes in Python packages are not allowed)

**Comment by heartsucker** [comment]
Nit that we should use `pages_layout` just for readability.

**Comment by redshiftzero** [comment]
PEP 8 discourages underscores but it is not explicitly disallowed, so either is fine

**Pull request merged**
