### PR TITLE
Added boundary check on image crop in pagelayout tests

### PR DESCRIPTION
**Pull request by zenmonkeykstop**
## Status

Ready for review 

## Description of Changes

Fixes intermittent failure in `test_account_edit_hotp_secret` pagelayout test.

## Testing

- [x] CI is passing
- [x] `securedrop/bin/dev-shell bin/run-test -m pagelayout` completes successfully locally
- [ ] screenshots in `securedrop/tests/pagelayouts/screenshots` look correct.

### CODE REVIEW

**Comment by legoktm** [comment]
The screenshots look fine except journalist-admin_edit_hotp_secret.png, which is a 1024x12 white rectangle...

journalist-admin_edit_hotp_secret

^ I attached it and because it's just white you can't see anything...

**Comment by zenmonkeykstop** [comment]
:grimacing: that's what I'd expect to see now instead of the CI fail (basically when whatever causes the bug happens, the image y-index is constrained to 0 (+12) pixels instead of getting into negative values.

**Comment by zenmonkeykstop** [comment]
Maybe instead of just letting it ride we should get it to default to the full height for the crop, I'll take another shot at it in a bit if this doesn't pass for you.

**Comment by legoktm** [comment]
For the developer experience, I'll take the screenshot silently failing over CI constantly failing, and will approve. But I'll file a follow-up task so we remember that this isn't really fixed.

**Review by legoktm — APPROVED** [review]
Fixes CI failure, though underlying problem still remains.

**Pull request merged**
