### PR TITLE
fixed line spacing

### PR DESCRIPTION
**Pull request by harlo**
…as per https://github.com/freedomofpress/securedrop/issues/1082

### CODE REVIEW

**Comment by conorsch** [comment]
Nice catch on the formatting, definitely an improvement. 

While we're here, do we want to update the logo size recommendation? We're currently telling folks that custom logos should be `500px x 450px`, but #1079 changed the default logo to `1000px x 1000px`. Probably fine as-is, but wanted to call attention to it.

**Comment by harlo** [comment]
i'll open a new PR, @conorsch

**Comment by conorsch** [comment]
:+1:

**Comment by conorsch** [comment]
New PR is #1085, by the way.

**Comment by garrettr** [comment]
Good catch, @harlo! However, `release/0.3.4` is not the right branch since we've already transitioned to that release. Can you close this PR and:

1. Re-submit with `develop` as the merge target?
2. Mark it with the 0.3.5 milestone (if you think this docs fix should be included in the next release, I think that would be a good idea) so we can remember to include it.

**Comment by harlo** [comment]
yep

**Pull request closed without merging**
