### PR TITLE
Update `werkzeug` to 2.2.3, `markupsafe` to 2.1.2, and `Flask-SQLAlchemy` to 2.5.1

### PR DESCRIPTION
**Pull request by eaon**
## Description of Changes

Updates `werkzeug` from 2.0.2 to 2.2.3 in the application requirements, in response to this advisory: https://github.com/pallets/werkzeug/security/advisories/GHSA-xg9f-g7g7-2323

Updating `werkzeug` in turn requires `markupsafe` to be updated from 2.0.1 to 2.1.2, as well as `Flask-SQLAlchemy` from 2.4.1 to 2.5.1.

## Testing

- [x] CI is passing
- [ ] (optional) basic site functionality is working (in particular, SI file uploads, JI login+2fa)

## Deployment
- No special deployment issues

### If you added or updated a production code dependency:

Production code dependencies are defined in:

- `admin/requirements.in`
- `admin/requirements-ansible.in`
- `securedrop/requirements/python3/requirements.in`

If you changed another `requirements.in` file that applies only to development
or testing environments, then no diff review is required, and you can skip
(remove) this section.

Choose one of the following:

- I have performed a diff review and pasted the contents to [the packaging wiki](https://github.com/freedomofpress/securedrop-debian-packaging/wiki)
   - [x] Diff review for `werkzeug` 2.0.2 ➡️ 2.2.3 was posted
   - [x] Diff review for `markupsafe` 2.0.1 ➡️ 2.1.2 was posted
   - [x] Diff review for `Flask-SQLAlchemy` 2.4.1 ➡️ 2.5.1 was posted
- [x] I would like someone else to do the diff review

### CODE REVIEW

**Comment by eaon** [comment]
`werkzeug` and `Flask-SQLAlchemy` seem have some strange interaction that breaks SQLAlchemy before version 2.4.3:

```
Traceback (most recent call last):
  File "./manage.py", line 29, in <module>
    from db import db  # noqa: E402
  File "/home/eaon/code/securedrop/securedrop/db.py", line 3, in <module>
    db = SQLAlchemy()
  File "/opt/venvs/securedrop-app-code/lib/python3.8/site-packages/flask_sqlalchemy/__init__.py", line 715, in __init__
    self.session = self.create_scoped_session(session_options)
  File "/opt/venvs/securedrop-app-code/lib/python3.8/site-packages/flask_sqlalchemy/__init__.py", line 748, in create_scoped_session
    scopefunc = options.pop('scopefunc', _app_ctx_stack.__ident_func__)
AttributeError: 'LocalStack' object has no attribute '__ident_func__'
```

Changes between 2.4.1 and 2.5.1 are easy to review though, so there's no reason not to bump up a little higher.

Diff review here: https://github.com/freedomofpress/securedrop-builder/wiki/Flask-SQLAlchemy-2.4.1-to-Flask-SQLAlchemy-2.5.1

**Comment by eaon** [comment]
Diff review for MarkupSafe: https://github.com/freedomofpress/securedrop-builder/wiki/MarkupSafe-2.0.1-to-MarkupSafe-2.1.2

**Comment by zenmonkeykstop** [comment]
Werkzeug review complete.

**Review by zenmonkeykstop — APPROVED** [review]
CI looks good, basic functionality unchanged.

LGTM!

**Pull request merged**
