### PR TITLE
Added reseticon to button in HTML

### LINKED ISSUE #2423: Reset password button does not have "reset icon"
# Bug

## Description

See title.

## Steps to Reproduce

screenshot_2017-10-08_15-30-33

## Expected Behavior

The button has the icon.

## Actual Behavior

The button does not have the icon.

### PR DESCRIPTION
**Pull request by lbu32**
## Status

Ready for review

## Description of Changes

Fixes #2423

Add refresh icon in from the RESET PASSWORD button

## Testing

* login as admin journalist
* go to the admin panel
* edit a user
* Verify the refresh icon shows as follows:

s

## Deployment

User facing only

### If you made changes to the app code:

- [x] Unit and functional tests pass on the development VM

### CODE REVIEW

**Comment by dachary** [comment]
I verified the fix is correct, using the same HTML as the other buttons showing the same icon in the same page. Could you please remove the other commit and just keep the one titled **Added icon to resetbutton** ? The **rel_datetime_format** modification can be discussed separately, it should not prevent the merge of this perfectly good fix :-)

**Comment by heartsucker** [comment]
Hey @lbu32. It looks like what happened here is that you picked up the changes from your other branch in here. You can do the following to fix that.

```
git checkout develop
git cherry-pick be65c44517c5bfee4879029f3b54be86cc831de8
git branch -D reseticon
git checkout -b reseticon
git push -f --set-upstream origin reseticon
```

This will take you back to the original branch, grab just the commit you want, and push it back up to gitub. There's other ways to fix this with rebasing, but that's a little harder to explain. If you have questions, come find us on [gitter](https://gitter.im/freedomofpress/securedrop).

**Comment by dachary** [comment]
@lbu32 I'm happy to make this small change for you in case you don't have time right now. Just let me know ;-)

**Comment by dachary** [comment]
@lbu32 rebased your commit and pushed it to https://github.com/freedomofpress/securedrop/pull/2467 to run tests one last time before it can be merged.

**Pull request closed without merging**
