### PR TITLE
Haveged waterline

### PR DESCRIPTION
**Pull request by garrettr**
Adjusts haveged settings, specifically the "fill line" that triggers the haveged daemon to inject more entropy into the pool. By setting this to the minimum amount of entropy needed to generate a GPG key (2400 bits according to some experimentation, see #303) we can dramatically reduce (potentially eliminating entirely) the occurrences of the "flag for reply" flow.

### CODE REVIEW

**Comment by fowlslegs** [comment]
I see two problems with this PR:

1. This gives us enough entropy for a 2048 bit key, but as we default to 4096 for these keys, we should use `-w 4096`.
* If the default value is changed from 1024 the ansible configure_haveged task will no longer modify the relevant stanza of `/etc/default/haveged`.

**Comment by conorsch** [comment]
For reference, the `/etc/default/haveged` config was improved as part of #1196, specifically in 802dc545850b561d2069364699b8107a8669f654.

**Comment by garrettr** [comment]
> This gives us enough entropy for a 2048 bit key, but as we default to 4096 bits for these keys, we should use -w 4096

There isn't a direct correspondence between the haveged waterline (which corresponds to the amount of entropy reported by `/proc/sys/kernel/random/entropy_avail`) and the size of the GPG keys. See https://github.com/freedomofpress/securedrop/issues/303#issuecomment-39627807 for context. So this recommendation doesn't make sense.

It is important to note that all of this is based on GPG's [weird CSPRNG](https://www.gnupg.org/documentation/manuals/gcrypt/Random_002dNumber-Subsystem-Architecture.html), which—besides having a crypto design that's more 90's than the [Carlton Dance](http://blog.cryptographyengineering.com/2014/08/whats-matter-with-pgp.html)—needlessly blocks on random bytes from `/dev/random`, which leads to the completely unnecessary "entropy depletion" attack that forced us to create the flawed "flag for reply" feature in the first place.

In a future iteration of SecureDrop, I would like to move away from the use of GPG entirely. Among other beenfits, that would allow us to use sensible cryptographic implementations that don't suffer from unnecessary "features" like this one.

**Comment by fowlslegs** [comment]
> There isn't a direct correspondence between the haveged waterline (which corresponds to the amount of entropy reported by /proc/sys/kernel/random/entropy_avail) and the size of the GPG keys. See #303 (comment) for context.

I saw that, but it makes intuitive sense you need an absolute minimum of 4096 bits of entropy to make a psuedorandom 4096 bit key. Since GPG seems to want more bits of entropy than the corresponding key it generates (at least in the case of the 2048 bit keys), it seems like it would be better to have 4800+ bits of entropy. Since 4096 is the maximum "size" of the entropy pool, it makes sense to me to always keep it at this maximum.

> It is important to note that all of this is based on GPG's weird CSPRNG, which—besides having a crypto design that's more 90's than the Carlton Dance—needlessly blocks on random bytes from /dev/random, which leads to the completely unnecessary "entropy depletion" attack that forced us to create the flawed "flag for reply" feature in the first place.

Made a note to read these links tomorrow.

> In a future iteration of SecureDrop, I would like to move away from the use of GPG entirely. Among other beenfits, that would allow us to use sensible cryptographic implementations that don't suffer from unnecessary "features" like this one.

I agree. A PFS scheme is the way to go, but that seems nearly impossible to implement given the architecture of SD.

**Comment by garrettr** [comment]
> I saw that, but it makes intuitive sense you need an absolute minimum of 4096 bits of entropy to make a psuedorandom 4096 bit key. Since GPG seems to want more bits of entropy than the corresponding key it generates (at least in the case of the 2048 bit keys), it seems like it would be better to have 4800+ bits of entropy. Since 4096 is the maximum "size" of the entropy pool, it makes sense to me to always keep it at this maximum.

Again, this is based on the bad assumption that entropy is a finite resource that can run out. Once you have enough for your initial seed, there's no need to worry about how much entropy you are consuming. The only reason we even have to deal with this is to appease GPG.

**Pull request merged**
