### PR TITLE
threat_model.rst: Updated URL to Pond threat model

### PR DESCRIPTION
**Pull request by elimisteve**

### CODE REVIEW

**Comment by elimisteve** [comment]
I linked to the latest version of the document that archive.org has: <https://web-beta.archive.org/web/*/https://pond.imperialviolet.org/threat.html>

**Comment by conorsch** [comment]
Thanks, @elimisteve. Yes, as long as we're still linking to this document, we should make sure the URL is accurate.

**Comment by elimisteve** [comment]
You bet! And if you're interested in making SecureDrop a focus of an upcoming Cypherpunks Write Code hackathon, let's talk; I run a weekly privacy hackathon ~every Saturday at Noisebridge!

**Comment by elimisteve** [comment]
And thank you for your work on SecureDrop; very important project.

**Pull request merged**
