### PR TITLE
Tails compatible printer (and extra clarification to network_firewall and install docs)

### PR DESCRIPTION
**Pull request by harlo**
Usually, I'm good at separating pull requests by branches specific to the issue/bug, but I forgot I already did a language-update to those other two files and they got grandfathered in.  LMK if this needs to be cherry-picked...

### CODE REVIEW

**Comment by garrettr** [comment]
This Tails printing guide looks great to me, @harlo! Would you mind squashing it into a single commit (or two, if you think the changes to `prod-specific.yml` would be better made in their own commit) for me to merge?

**Comment by conorsch** [comment]
Changes to `prod-specific.yml` should be made as a separate PR. Admins stash and pop changes to `prod-specific.yml` while checking out signed tags for upgrades, so we'll need to test how changes to the vars file, even just in comments, affects that process.

**Comment by harlo** [comment]
OK, will roll-back on prod-specific.yaml and squash everything left into
one commit.

**Comment by garrettr** [comment]
Agreed, thanks @conorsch for pointing that out. The changes to prod-specific.yml should be done in a separate PR, both because it's logically unrelated to printing on Tails and because it must be done carefully to avoid breaking admin's workflows. Otherwise this lgtm and is ready to merge once it's squashed.

**Comment by garrettr** [comment]
@harlo I'll try rebasing it

**Comment by garrettr** [comment]
These commits were rebased and merged with #1043.

**Pull request closed without merging**
