### PR TITLE
Table of airgap-safe, Tails-compatible printers

### PR DESCRIPTION
**Pull request by garrettr**
This is a partial list of airgap-safe and Tails-compatible printers
compiled from our initial round of testing.

### CODE REVIEW

**Comment by garrettr** [comment]
@harlo Please review!

**Comment by dolanjs** [comment]
lgtm but don't have the printers to test personally. Since the list is only two printers later on we could add screen shots of setting the two up in a printer specific doc since most journalists aren't use to tails.

**Comment by garrettr** [comment]
@harlo I rebased your commits from #1056 and pushed them to this branch. I made sure to preserve your authorship (commit author is "Harlo Holmes <harlo@freedom.press>"). Review plz?

**Comment by conorsch** [comment]
New printing guide with screenshots, plus the readable table, are both huge improvements to our docs. Will wait to merge till @harlo signs off. 

Closes #1056.

**Comment by harlo** [comment]
lgtm, thx!

**Pull request merged**
