### PR TITLE
Support building packages on noble

### PR DESCRIPTION
**Pull request by legoktm**
## Status

Ready for review

## Description of Changes

Basically this adds support for building noble packages without breaking focal builds. It's not exactly but is practically a no-op for focal. The packages have not been tested to work, just that they roughly look right (which should be sufficient for merging, fixes will come later, we just need this in place to actually test the rest of the system).

See commit messages for individual changes. 

Refs #7210 

## Testing

How should the reviewer test this PR?

* [ ] Try out `UBUNTU_VERSION=noble make build-debs`
* [ ] Also `UBUNTU_VERSION=noble make build-debs-ossec`
* [ ] CI passes (esp. staging build, which should verify no focal regressions)

## Deployment

Any special considerations for deployment? Should be a no-op for focal.

## Checklist

- [ ] Linting (`make lint`) and tests (`make test`) pass in the development container
- [ ] [Configuration tests](https://docs.securedrop.org/en/latest/development/testing_configuration_tests.html) pass
- [ ] I have written a test plan and validated it for this PR
- [ ] These changes do not require documentation
- [ ] ~~I have performed a diff review and pasted the contents to [the packaging wiki](https://github.com/freedomofpress/securedrop-debian-packaging/wiki)~~ - n/a, pip and setuptools dependencies are exempt as they're maintained by PyPA

### CODE REVIEW

**Comment by legoktm** [comment]
The ossec-agent/ossec-server packages still have hardcoded `libssl1.1` dependencies that need to be removed...

**Comment by zenmonkeykstop** [comment]
Noble build failing, looks like we're not dropping `libssl.1` that easily:

```
...
dpkg-shlibdeps: error: cannot find library libssl.so.1.1 needed by debian/securedrop-app-code/opt/venvs/securedrop-app-code/lib/python3.12/site-packages/redwood/redwood.cpython-38-x86_64-linux-gnu.so (ELF format: 'elf64-x86-64' abi: 'ELF:64:l:amd64:0'; RPATH: '')
...
```

Will poke at a bit on Monday.

**Comment by legoktm** [comment]
Make sure you're building from a clean folder, there's some cache pollution across focal/noble builds that I thought I had fixed but I guess not.

**Comment by legoktm** [comment]
I tacked on the last two commits a bit late because I hit them when testing the actual packages; happy to drop them from this PR and submit them independently.

**Review by zenmonkeykstop — APPROVED** [review]
Builds succeeding across focal and noble, packages look... packagey.

**Pull request merged**
