### PR TITLE
Fix yamllint warnings + enable strict mode

### LINKED ISSUE #6575: Fix yamllint warnings, enable strict mode
*This is a good first issue for new contributors to take on, if you have any questions, please ask on the task or in our [Gitter room](https://gitter.im/freedomofpress/securedrop)!*

## Description

We currently have some yamllint warnings:

```
$ make yamllint
███ Linting YAML files...
./.circleci/config.yml
  78:221    warning  line too long (293 > 220 characters)  (line-length)
  256:221   warning  line too long (222 > 220 characters)  (line-length)
  262:221   warning  line too long (224 > 220 characters)  (line-length)

./install_files/ansible-base/roles/validate/tasks/validate_tails_environment.yml
  81:4      warning  wrong indentation: expected 4 but found 3  (indentation)

./install_files/ansible-base/roles/restore/tasks/perform_restore.yml
  112:9     warning  too many spaces after hyphen  (hyphens)

./install_files/ansible-base/group_vars/securedrop_application_server.yml
  12:5      warning  too many spaces after hyphen  (hyphens)
```

These should be fixed. Then we can enable `--strict` mode (in `devops/scripts/yaml-lint.sh`) so that any future warnings will cause CI to fail.

### PR DESCRIPTION
**Pull request by IlyesSemlali**
## Status

Work in progress

## Description of Changes

Fixes #6575 

Changes proposed in this pull request:

Removed empty spaces, and put bash commands in new lintes

## Testing

The CI should be able to run successfully

### CODE REVIEW

**Review by legoktm — CHANGES_REQUESTED** [review]
Thanks! Could you also enable `--strict` mode (in `devops/scripts/yaml-lint.sh`) so that any future warnings will cause CI to fail?

**Comment by IlyesSemlali** [comment]
Sure ! (Sorry, I fortgot to put WIP: in my PR)

**Comment by IlyesSemlali** [comment]
@legoktm I think everything is OK now, thank's for the reminder !

**Review by legoktm — APPROVED** [review]
LGTM! Thanks for your first contribution to SecureDrop 🎆 !

**Pull request merged**
