### PR TITLE
[xenial] Updated release-upgrades Prompt for Trusty, Xenial as appropriate

### LINKED ISSUE #4104: [xenial] Reinstate LTS upgrade notification
In #3546, we set `Prompt` to `never` in  `/etc/update-manager/release-upgrades` to suppress premature OSSEC notifications. In order to perform the update to Xenial via `do-release-upgrade`, it needs to be reset to `lts`. We can do so in postinst so the admin does not have to do it manually.

To avoid spurious 18.04 notifications, this should be done on Trusty, while on Xenial `Prompt` should be set to `never`. We can inspect `lsb_release -sc` to avoid forking the build logic.

As a stretch goal, we should consider customizing the OSSEC notification that will be sent to 14.04 users. The default notification will say:

```
/etc/cron.weekly/update-notifier-common:
New release '16.04.1 LTS' available.
Run 'do-release-upgrade' to upgrade to it.
```

Ideally, the notification should point to: 

  https://securedrop.org/xenial-upgrade

This is the redirect also pointed to via #4055. Having the OSSEC alert point to this link will help prevent admins from attempting the upgrade without following the documentation.

Part of #3204.

### PR DESCRIPTION
**Pull request by heartsucker**
## Status

Ready for review

## Description of Changes

Fixes #4104

Update the `Prompt` in the release manage file depending on system codename. Additionally, attempt to rewrite the OSSEC alerts to prevent admins from running `do-release-upgrade` and breaking everything.

## Testing

1. Trusty
    - Build trusty debs
    - Install on trusty box
    - Verify that `/etc/update-manager/release-upgrades` contains `Prompt=lts`
    - Verify that `/usr/lib/ubuntu-release-upgrader/check-new-release` contains "Visit https://securedrop.org/xenial-upgrade for more information" (and so does  `/var/lib/ubuntu-release-upgrader/release-upgrade-available` if it exits)
2. Xenial
    - Build xenial debs
    - Install on xenial box
    - Verify that `/etc/update-manager/release-upgrades` contains `Prompt=never`
    - Verify that `/usr/lib/ubuntu-release-upgrader/check-new-release` does not contain "Visit https://securedrop.org/xenial-upgrade for more information" (and neither does  `/var/lib/ubuntu-release-upgrader/release-upgrade-available` if it exits)

## Deployment

All installs on Trusty will have files modified to the state SD requires. All installs on Xenial will have their files reverted to the default state.

### If you made changes to the system configuration:

- [x] [Configuration tests](https://docs.securedrop.org/en/latest/development/testing_configuration_tests.html) pass

### If you made non-trivial code changes:

- [x] I have written a test plan and validated it for this PR

### CODE REVIEW

**Comment by conorsch** [comment]
These changes appear well structured, based on visual review. Will step through the test plan to validate functionality. Flagging that we should add config tests to verify the LTS upgrade strings are set correctly on both Trusty & Xenial.

**Comment by redshiftzero** [comment]
We should also verify as part of review that the OSSEC notification that is triggered includes the expected text: `"* Visit https://securedrop.org/xenial-upgrade for more information"`

**Comment by conorsch** [comment]
Stepped through Trusty test plan today:


* [x] Build trusty debs
* [x] Install on trusty box
* [x] Verify that /etc/update-manager/release-upgrades contains Prompt=lts
* [x] Verify that /usr/lib/ubuntu-release-upgrader/check-new-release contains "Visit https://securedrop.org/xenial-upgrade for more information" 
* [ ] :red_circle: and so does /var/lib/ubuntu-release-upgrader/release-upgrade-available if it exits)
* [ ] OSSEC notification that is triggered includes the expected text: "* Visit https://securedrop.org/xenial-upgrade for more information"

Will leave these VMs running overnight to see if OSSEC emails contain the correct text (although I used staging machines, I made sure to configure OSSEC via email). Given that the `/var/lib/ubuntu-release-upgrader/release-upgrade-available` file didn't satisfy the test plan (file was zero-bytes on both app-staging and mon-staging), perhaps not.

**Comment by emkll** [comment]
Went through the Xenial test plan, LGTM: 
- [x] Build xenial 
- [x] Install on xenial box
- [x] Verify that `/etc/update-manager/release-upgrades` contains `Prompt=never`
- [x] Verify that `/usr/lib/ubuntu-release-upgrader/check-new-release` does not contain "Visit https://securedrop.org/xenial-upgrade for more information" (and neither does  `/var/lib/ubuntu-release-upgrader/release-upgrade-available` if it exits)

Also did an upgrade test under trusty, since these will be shipped to Trusty installs via the securedrop-config package, LGTM:
- [x] local upgrade successful
- [x] Verify that `/etc/update-manager/release-upgrades` contains `Prompt=never`
- [x] Verify that `/usr/lib/ubuntu-release-upgrader/check-new-release` does not contain "Visit https://securedrop.org/xenial-upgrade for more information" (and neither does  `/var/lib/ubuntu-release-upgrader/release-upgrade-available` if it exits)

I am (seemingly unrelated) error while upgrading, likely introduced by #4080, for which I will open an issue/PR:
```
+ pip install --no-index --find-links=/var/securedrop/wheelhouse --upgrade -r /var/www/securedrop/requirements/securedrop-app-code-requirements.txt
Ignoring indexes: https://pypi.python.org/simple/
Requirement already up-to-date: alembic==0.9.9 in /usr/local/lib/python2.7/dist-packages (from -r /var/www/securedrop/requirements/securedrop-app-code-requirements.txt (line 7))
Could not find any downloads that satisfy the requirement argon2-cffi==18.1.0 in /usr/local/lib/python2.7/dist-packages (from -r /var/www/securedrop/requirements/securedrop-app-code-requirements.txt (line 8))
Downloading/unpacking argon2-cffi==18.1.0 (from -r /var/www/securedrop/requirements/securedrop-app-code-requirements.txt (line 8))
Cleaning up...
No distributions at all found for argon2-cffi==18.1.0 in /usr/local/lib/python2.7/dist-packages (from -r /var/www/securedrop/requirements/securedrop-app-code-requirements.txt (line 8))
Storing debug log for failure in /home/vagrant/.pip/pip.log
dpkg: error processing package securedrop-app-code (--configure):
 subprocess installed post-installation script returned error exit status 1
Errors were encountered while processing:
 securedrop-app-code
E: Sub-process /usr/bin/dpkg returned an error code (1)
```

**Comment by heartsucker** [comment]
Someone other than myself or @conorsch needs to sign on off on this since now we've both pushed here and @conorsch would be the primary reviewer. I've look at his additions, and it looks good. @emkll wanna give us the thumbs up here?

**Comment by emkll** [comment]
Happy to do so, @heartsucker . 

I am also seeing the same behavior @conorsch is experiencing when upgrading in trusty:

After running the cron.weekly updater-notifier-common, `/var/lib/ubuntu-release-upgrader/release-upgrade-available` is 0 bytes. No OSSEC emails are sent as a result.

**Comment by heartsucker** [comment]
I'm in the middle of another PR review right now so I can't start up a VM, but I think what's happening is that the permissions are wrong on that file and it's breaking things because cron cant' access it.

**Comment by heartsucker** [comment]
I think what's happening is in some cases the `/usr/lib/ubuntu-release-upgrader/release-upgrade-motd` part of all of the above runs with a `&` (in the background), so the file `/var/lib/ubuntu-release-upgrader/release-upgrade-available` doesn't exist yet when we `sed` it. On a staging machine, if I remove that file then run `dpkg-reconfigure securedrop-config`, everything seems to work. Should we add a force `rm` to that in the `postinst` just to ensure we blow it up to trigger it's recreation? I'm still not totally sure how this ends up in the OSSEC alerts (plugin/rule?) but I think this should do the trick.

**Comment by heartsucker** [comment]
I just added a line that should trigger all the above logic. If that's not actually the fix, feel free to remove it.

**Comment by conorsch** [comment]
Confirming that the `/var/lib/ubuntu-release-upgrader/release-upgrade-available` file is now correctly populated for me. Built twice on Trusty and it was true both times.

Why the `&` in the postinst, though? If it's to avoid aborting the script due to a non-zero exit code, then we should use `|| true` instead. If it's to avoid long run times of the postinst, it appears to save only 1-1.5s. At first I was concerned we had a race condition here, and we'd need a corresponding `wait` for that process to exit, but as long as we don't care about success, it doesn't seem cause problems.

Have not yet verified the Xenial story functionality, nor confirmed the OSSEC emails, so more testing still required.

**Comment by emkll** [comment]
Thanks for the fix @heartsucker ! I can also confim that `/var/lib/ubuntu-release-upgrader/release-upgrade-available` is now properly populated in the trusty scenario.
Also tested again in Xenial and the test plan is successful. 

The final piece is the ossec alert and unfortunately I still have not received an ossec alert requesting me to upgrade. I do get a syscheck alert informing me that the file was changed.

I can't seem to find a relevant ossec alert/rule for this in the upstream repo [0]
[0] : https://github.com/ossec/ossec-hids/tree/master/etc/rules


The easiest path would be to add a custom ossec notification (that would require xenial-specific logic to remove):
```
diff --git a/install_files/securedrop-ossec-agent/var/ossec/etc/ossec.conf b/install_files/securedrop-ossec-agent/var/ossec/etc/ossec.conf
index 9b14f4a81..651fff66d 100644
--- a/install_files/securedrop-ossec-agent/var/ossec/etc/ossec.conf
+++ b/install_files/securedrop-ossec-agent/var/ossec/etc/ossec.conf
@@ -115,6 +115,12 @@
   </localfile>
 
   <localfile>
+    <log_format>full_command</log_format>
+    <command>/usr/lib/ubuntu-release-upgrader/check-new-release -q</command>
+    <frequency>864900</frequency> <!-- 24 hours -->
+  </localfile>
+
+  <localfile>
     <log_format>syslog</log_format>
     <location>/var/log/kern.log</location>
   </localfile>
diff --git a/install_files/securedrop-ossec-server/var/ossec/rules/local_rules.xml b/install_files/securedrop-ossec-server/var/ossec/rules/local_rules.xml
index 97f0cfe62..9994f6c37 100644
--- a/install_files/securedrop-ossec-server/var/ossec/rules/local_rules.xml
+++ b/install_files/securedrop-ossec-server/var/ossec/rules/local_rules.xml
@@ -200,4 +200,11 @@
   </rule>
 </group>
 
-
+<group name="Daily dist upgrade notifications">
+  <rule id="400700" level="7" >
+    <if_sid>530</if_sid>
+    <options>alert_by_email</options> <!-- force email to be sent -->
+    <match>ossec: output: '/usr/lib/ubuntu-release-upgrader/check-new-release -q</match>
+    <description>This alert is to inform admins to upgrade to Xenial</description>
+  </rule>
```

**Comment by heartsucker** [comment]
> Why the `&` in the postinst, though?

That Python script will download the `do-release-upgrade` and other required packages in the background it seems. I think it can be a very heavy process, and it's ok if it doesn't exit in `postinst`. There were some posts complaining about it being very slow so it seems like to avoid that we don't want to run in the foreground.

**Comment by heartsucker** [comment]
About that OSSEC rule, I think we could ship either two different deb packges or two different conf files and then move the right one into place on `postinst`. I guess we could also apply/unapply the diff with `diff` too. Thoughts?

**Comment by heartsucker** [comment]
So as this stands, we don't have the OSSEC rule for this. Since @conorsch seems to do the most Debian packaging stuff here, it would be good to get your feedback on whether or not we should update those rules via some `postinst` logic.

**Comment by emkll** [comment]
Given the short timeline for 0.12.0 and the complexities around the management of separate ossec rules, we could also write a very simple cron job on the mon server that simply calls `send_encrypted_alarm.sh` to send an email to the admin, only if the base os is Trusty.

**Comment by heartsucker** [comment]
@emkll, take a peeksy at the change I pushed. This should do the thing.

**Comment by emkll** [comment]
@heartsucker thanks for the change. We've discussed this in the engineering meeting and concluded that perhaps more research was required on the ossec front. Any objections to removing ce49036 and opening a follow up to monitor/update the ossec rule? We can keep the scope of this PR to only the release-upgrades for the purposes of admins running  `do-release-upgrade`
The release-upgrades is a very important/significant change, and might be best to merge just that part for QA, and following up on the ossec portion later.
What do you think?

**Comment by heartsucker** [comment]
I think that's reasonable. I'll for push with this change yanked.

**Comment by heartsucker** [comment]
@kushaldas Can you stamp this one again? I added a commit since your review, then removed it, so it's unchanged since your last approval.

**Pull request merged**
