### PR TITLE
Remove apparmor rule for the shell execution of /bin/dash (#5084)

### PR DESCRIPTION
**Pull request by evilaliv3**
Implement correction as for ticket #5084

### CODE REVIEW

**Comment by zenmonkeykstop** [comment]
Happy 2020 @evilaliv3 and thanks for this! It looks like `shell=True` is only going to be set for Windows systems in our current python-gnupg version, so this should be a change with no functional effect. Do you consider it ready for review? And if so, do you think there are any specific test cases we should be looking at?

**Comment by evilaliv3** [comment]
Thank you @zenmonkeykstop; best wishes to you as well!

In my opinion yes the pull request is ready for merge and the restriction it applies is important as it fixes basically the main important failure in the design of python gnupg but unfortunately i don't think we have any option for a unit test here. I'm confident you should be enabling dash just in relation to previous versions of python gnupg that were requiring that in relation to popen but others of your team may confirm as well if this is the case.

**Comment by zenmonkeykstop** [comment]
Thanks @evilaliv3 - I'll run through the usual functional tests on a production system (for that full apparmor experience :) ) and see how it goes. I'd agree with your assessment and it's unlikely we'll be downgrading the library to one that requires shell=True anytime soon.

**Comment by zenmonkeykstop** [comment]
FTR - rough test plan is:

- [ ] the installation completes successfully on a prod system (HW or VM), with SI and JI available
- [ ] apparmor is enabled on the servers
- [ ]  source reply keys are generated successfully when a source account is created
- [ ]  submissions are encrypted successfully using the submission key
- [ ]  replies are encrypted successfully using the appropriate source reply key
- [ ]  replies are decrypted successfully in the SI
- [ ]  there are no apparmor errors in system logs

extra credit:
- [ ] basic server tests and application acceptance tests from 1.2.0 test plan pass.

**Comment by zenmonkeykstop** [comment]
Just as a heads-up, I'm getting 2 `/bin/dash` apparmor denies on the initial request to the source or journalist interfaces, so something else relies on it. My guess is mod_wsgi but I'm still looking.

**Comment by zenmonkeykstop** [comment]
dash is run when starting the WSGI daemon process, so unfortunately I don't think this apparmor change is applicable to SecureDrop, unless mod_wsgi can be reconfigured.

**Comment by evilaliv3** [comment]
Ah! bummer! thank you for the update @zenmonkeykstop 

Actually what we could do probably is to sandbox the app in a different way so that each component stays in its sandbox.

E.g. giving /bin/sh to wsagi we are giving the entire codebase of securedrop this capability but maybe we could grant this to wsagi only and sandbox all the rest in a more precise manner.

**Comment by evilaliv3** [comment]
Ah! bummer! thank you for the update @zenmonkeykstop 

Actually what we could do probably is to sandbox the app in a different way so that each component stays in its sandbox.

E.g. giving /bin/sh to wsagi we are giving the entire codebase of securedrop this capability but maybe we could grant this to wsagi only and sandbox all the rest in a more precise manner.

**Comment by zenmonkeykstop** [comment]
No problem @evilaliv3 - #1389 is probably relevant here. I'm going to close this PR but it would be great to have your thoughts on the gunicorn+nginx architecture change mentioned in that ticket...

**Pull request closed without merging**
