### PR TITLE
Update translations for 0.13.0

### PR DESCRIPTION
**Pull request by rmol**
## Status

Ready for review

## Description of Changes

New translations for 0.13.0 release.

## Testing

For each supported language, check that each of the three strings changed in 0.13.0 has a plausible-looking translation. 

Check out this branch, then run `securedrop/bin/dev-shell ./i18n_tool.py --verbose translate-messages --compile` to create the `.mo` files.

Then save this script as `check_translations.py`:

```python
#!/usr/bin/env python3

import gettext
import os
import sys


SUPPORTED_LANGUAGES = [
    "ar",
    "de_DE",
    "es_ES",
    "en_US",
    "el",
    "fr_FR",
    "it_IT",
    "nb_NO",
    "nl",
    "pt_BR",
    "tr",
    "zh_Hant",
]

TESTS = [
    "Sorry we haven't responded yet!",
    (
        "Our SecureDrop recently experienced a surge of activity. For security "
        "reasons, the creation of a two-way communication channel was delayed until "
        "you checked in again."
    ),
    (
        "Please rest assured that we were able to download your submission, and check "
        "back again later for a reply."
    ),
]


if __name__ == "__main__":
    translation_dir = sys.argv[1]

    for lang in SUPPORTED_LANGUAGES:
        print("Checking {}...".format(lang))
        os.environ["LANGUAGE"] = lang
        gettext.bindtextdomain("messages", translation_dir)
        missing = False
        for t in TESTS:
            translation = gettext.gettext(t)
            print("  {}".format(translation))
            if lang != "en_US" and translation == t:
                missing = True
                print('MISSING TRANSLATION FOR "{}"'.format(t), file=sys.stderr)

        if not missing:
            print("Looks good.")
```

When run with the translations directory as its only argument (e.g. `check_translations.py securedrop/translations`, from the root of your working copy), you should see the three strings translated for each supported language, with no reports of missing translations, and no markup or other suspicious content in the translated strings.

Additionally (edited by @redshiftzero):

- [ ] Ensure there is a passing CI translation job (ran on all pages-layout tests) - you need to do this by triggering a CI run from the shared remote
- [ ] Review the diff manually to verify there are no unusual or unexpected changes in the diff

### If you made changes to the server application code:

- [x] Linting (`make lint`) and tests (`make -C securedrop test`) pass in the development container

### CODE REVIEW

**Comment by redshiftzero** [comment]
Triggered translation CI job in this workflow: https://circleci.com/workflow-run/6945f950-a923-4090-bc12-1094bc310d55

**Comment by zenmonkeykstop** [comment]
Confirmed script output as described. LGTM!

**Comment by emkll** [comment]
Good to merge once layout tests pass in this branch (there as there were changes pushed since @redshiftzero ran the tests in https://github.com/freedomofpress/securedrop/pull/4475#issuecomment-496702107) :

https://circleci.com/workflow-run/6bf5c116-65b3-4be1-bd89-e0028a19b209

**Comment by redshiftzero** [comment]
Workflow to watch for passing translation test job: https://circleci.com/workflow-run/39d06bdb-6c89-4a0d-adb2-9247bfcd72ac

**Comment by emkll** [comment]
App tests flake? https://circleci.com/gh/freedomofpress/securedrop/28571
Restarting app tests

**Comment by emkll** [comment]
still seeing the timeout for app tests: https://circleci.com/gh/freedomofpress/securedrop/28589

**Comment by redshiftzero** [comment]
Once https://circleci.com/gh/freedomofpress/securedrop/28578 passes, we should merge regardless. This is because the app-test job only was executed due to CI bug #4479. Since this diff only touches translated strings (and not source strings) and the translation-test job, it should be sufficient for merge.

**Pull request merged**
