### PR TITLE
fix: Handle case of disconnected submissions

### LINKED ISSUE #5315: api: GET /api/v1/submissions produces 500 when there are disconnected submissions
## Description

The API's submission endpoint should gracefully handle the case where there is a "disconnected" submission.

## Steps to Reproduce

0. `make dev`
1. docker exec into the container
2. `cd /var/lib/securedrop/`
3. `sqlite3 db.sqlite`
4. `delete from sources where id=1;`
5. While authenticated to the journalist API, `GET /api/v1/submissions`

## Expected Behavior

OSSEC alert starts appearing indicating that there are disconnected submissions, encouraging the admin to clean up.

## Actual Behavior

500 occurs: 
```
Traceback (most recent call last):
  File "/opt/venvs/securedrop-app-code/lib/python3.5/site-packages/flask/app.py", line 2309, in __call__
    return self.wsgi_app(environ, start_response)
  File "/opt/venvs/securedrop-app-code/lib/python3.5/site-packages/flask/app.py", line 2295, in wsgi_app
    response = self.handle_exception(e)
  File "/opt/venvs/securedrop-app-code/lib/python3.5/site-packages/flask/app.py", line 1741, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/opt/venvs/securedrop-app-code/lib/python3.5/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/opt/venvs/securedrop-app-code/lib/python3.5/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/opt/venvs/securedrop-app-code/lib/python3.5/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/opt/venvs/securedrop-app-code/lib/python3.5/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/opt/venvs/securedrop-app-code/lib/python3.5/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/opt/venvs/securedrop-app-code/lib/python3.5/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/opt/venvs/securedrop-app-code/lib/python3.5/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/redshiftzero/Documents/Github/securedrop-1.2.0-rc1/securedrop/securedrop/journalist_app/api.py", line 48, in decorated_function
    return f(*args, **kwargs)
  File "/Users/redshiftzero/Documents/Github/securedrop-1.2.0-rc1/securedrop/securedrop/journalist_app/api.py", line 303, in get_all_submissions
    submission in submissions]}), 200
  File "/Users/redshiftzero/Documents/Github/securedrop-1.2.0-rc1/securedrop/securedrop/journalist_app/api.py", line 303, in <listcomp>
    submission in submissions]}), 200
  File "/Users/redshiftzero/Documents/Github/securedrop-1.2.0-rc1/securedrop/securedrop/models.py", line 218, in to_json
    source_uuid=self.source.uuid),
AttributeError: 'NoneType' object has no attribute 'uuid'
```

## Comments

Bit of a weird STR, but the submissions endpoint producing a 500 is unfortunate.

### PR DESCRIPTION
**Pull request by prateekj117**
## Status

Ready for Review

## Description of Changes

Fixes #5315 .

Changes proposed in this pull request:

Handled the case of disconnected submissions and added a test for the same.

### If you made changes to the server application code:

- [X] Linting (`make lint`) and tests (`make test`) pass in the development container

### If you made changes to `securedrop-admin`:

- [X] Linting and tests (`make -C admin test`) pass in the admin development container

### If you made changes to the system configuration:

- [X] [Configuration tests](https://docs.securedrop.org/en/latest/development/testing_configuration_tests.html) pass

### If you made non-trivial code changes:

- [X] I have written a test plan and validated it for this PR

### If you made changes to documentation:

- [X] Doc linting (`make docs-lint`) passed locally

### CODE REVIEW

**Comment by prateekj117** [comment]
@eloquence Found some issues. Not ready for review. :sweat:

**Comment by prateekj117** [comment]
@rmol @eloquence @redshiftzero So sqlalchemy does a cascade delete, on the other hand, directly running the query `delete from sources where id=1;` doesn't. So this test is not the right way to check this code. Can you guide me on how I should go about writing the test here?

**Comment by rmol** [comment]
You could use that query in the test instead of deleting the source in the usual way:
```python
        # db.session.delete(test_submissions['source'])
        db.session.execute(
            "DELETE FROM sources WHERE id = :id",
            {"id": test_submissions["source"].id}
        )
```

**Comment by prateekj117** [comment]
@rmol Oh yes. Ofc. Thanks.

**Comment by prateekj117** [comment]
@rmol Done. Ready for review. Tested the test on local. Didn't face the earlier issue. Works fine now. :+1: 
@eloquence Ready for review. :smile:

**Review by rmol — DISMISSED** [review]
This looks good. The test works. I've gone through the STR and verified that the `Submission.to_json` changes solve the 500.

I had a bit of last-minute indecision about whether the `get_all_submissions` API endpoint should even be returning disconnected submissions, instead of omitting those without a source, but the very name suggests it should. I checked the client code and it should properly deal with downloaded submissions which don't have a source -- if a new submission has no source, it is simply not added, and if the submission exists locally (which should only happen if the local source hasn't been deleted during a sync yet) it will be updated.

**Comment by prateekj117** [comment]
@rmol mmmm, ok. Ya sounds right not to return them. Let me know if we need to do that and I will edit the PR according to that.

**Comment by rmol** [comment]
Yeah, when actually _running_ the client I discovered that its handling of disconnected submissions is fine, but the SDK throws an exception when the source doesn't exist. And there are similar problems with the `get_all_replies` endpoint, for which I'll file a separate issue. 

For this PR, adding a check of the source to `api.get_all_submissions` will exclude the disconnects and avoid sending problematic data to the SDK and client:
```python
        return jsonify({'submissions': [s.to_json() for
                                        s in submissions if s.source]}), 200
```

Thanks for persevering, @prateekj117!

**Comment by prateekj117** [comment]
@rmol Sure. Will make those changes.

**Comment by prateekj117** [comment]
@rmol Done. Ready for another review.

**Comment by rmol** [comment]
Thanks! I was hoping to just add the filtering of source-less submissions in `get_all_submissions` while keeping the improvements to `Submission.to_json` -- could you restore that change to this final version? I don't want to deter you, so I can add it if you'd prefer to be done with this.

**Comment by prateekj117** [comment]
@rmol Not an issue. Will do that change.

**Comment by prateekj117** [comment]
@rmol Done.

**Comment by eloquence** [comment]
(CI failure likely unrelated, kicking)

**Review by rmol — APPROVED** [review]
:+1: Looks great, thanks for all your work on this @prateekj117.

**Pull request merged**
