### PR TITLE
Update locations of logs on app server for OSSEC syscheck

### LINKED ISSUE #2153: OSSEC syscheck log locations need updating on app server
OSSEC's `syscheck` (integrity checking process) is configured to monitor logs that don't exist. On `app-staging`: 

* `/var/log/apache2/source-access.log` is monitored, but this does not exist as we intentionally do not have access logs for the source interface.

* `/var/www/securedrop/securedrop.log` is monitored, but this does not exist and log events from the application logger are currently being sent to `/var/log/apache2/source-error.log` and `/var/log/apache2/journalist-error.log` (these two files are monitored).

### PR DESCRIPTION
**Pull request by redshiftzero**
## Status

Ready for review

## Description of Changes

Fixes #2153

Changes proposed in this pull request:
* Stop `syscheck` monitoring log files that do not exist

## Testing

1. Provision staging locally
2. Verify that `/var/log/apache2/log/source-access.log` does not exist
3. Verify that `/var/www/securedrop/securedrop.log` does not exist.

If you are concerned and want to check that logging is working, you can put an `app.logger.error("TEST <name of interface>")` in the `index()` function of `source.py` and `journalist.py`, visit the interfaces, and verify these events were logged (I did do this).

## Deployment

`/var/ossec/etc/ossec.conf` is distributed through the `securedrop-ossec-agent` deb package, so this should land on the app servers without issue. 

### If you made changes to the system configuration:

- [ ] [Configuration tests](https://docs.securedrop.org/en/latest/development/testing_configuration_tests.html) pass

### If you made changes to documentation:

- [x] Doc linting passed locally

### CODE REVIEW

**Comment by conorsch** [comment]
Reviewing! This one looks much simpler than the other OSSEC PRs (#2143, #2152).

**Comment by conorsch** [comment]
Rebased on top of latest develop to make sure these changes play nicely with the other OSSEC config updates.

**Comment by redshiftzero** [comment]
:clap: to config tests for logs!

**Comment by redshiftzero** [comment]
Travis failing due to `flake8` linting failures

**Comment by redshiftzero** [comment]
All tests passing (needs restamp)

**Pull request merged**
