### PR TITLE
user logout on password reset

### LINKED ISSUE #2303: Failure to invalidate session when user resets their own password
## Description

When a user resets their own password, their session is not invalidated. 

## Steps to Reproduce

1. User logs in
2. User resets password

## Expected Behavior

User is logged out and is requested to use their new password to login

## Actual Behavior

User can continue to browse without having to enter their new password again

## Comments

Related tickets: #2300, #880

### PR DESCRIPTION
**Pull request by trankmichael**
## Status

Ready for review 

## Description of Changes

Logs the user out when the user resets their password.

Fixes #2303.

Changes proposed in this pull request:
- clear session values on password reset 

## Testing

How should the reviewer test this PR?
1. reset password on journalist application
2. attempt to navigate journalist page e.g. /account/account route and confirm that the session is invalid
3. login with the new password to confirm that the password was reset 

## Deployment

Any special considerations for deployment? Consider both:
1. Upgrading existing production instances.
2. New installs.

No

### If you made changes to the app code:

- [x] Unit and functional tests pass on the development VM

### CODE REVIEW

**Comment by dachary** [comment]
Great ! Would you mind adding a test somewhere in securedrop/tests/test_journalist.py ? I'd be happy to guide you if needed.

**Comment by dachary** [comment]
@trankmichael I may have misinterpreted your 👍 . I thought it meant you will add tests. But maybe it meant that you're in need of guidance ?

**Comment by dachary** [comment]
@trankmichael the tests were added to verify your change works. And it does :-)

**Comment by trankmichael** [comment]
hi @dachary thanks so much I was planning on adding the tests but Ive been away for the holidays.

**Pull request merged**
