### PR TITLE
Fix Apache logging formatting

### PR DESCRIPTION
**Pull request by fowlslegs**
Fixes https://github.com/freedomofpress/securedrop/issues/1606.

### CODE REVIEW

**Comment by conorsch** [comment]
Blocking here until we get #1616, so the tests can be updated to track this change. There's currently a test marked "expected failure" in that PR that targets these log formats.

**Comment by conorsch** [comment]
#1616 is merged, so will add tests to track regression here, then we're good for merge.

**Comment by fowlslegs** [comment]
@conorsch I'd actually like to write the tests here, but I wanted to ask you what you'd do here first. Would it be sufficient to just test that this line is present in this file, or would you actually try to parse the log to make sure it's sensible? I'm guessing probably just the former, but was just wondering if there's anything more robust (but perhaps less complicated than log parsing) I could do.

**Comment by conorsch** [comment]
A few considerations:

1. Under no circumstances should a line in the journalist interface log match `^combined$`; (currently they all do). So that should be its own test, to guard against regressions here.
2. Match for a rough approximation of the format we're looking for; we don't want false failures because an overly specific regex didn't consider certain allowed characters or patterns in the log.
3. The log will be empty unless the Journalist Interface has been interacted with.

Mostly 3 will cause problems; we don't yet have a cohesive "run all the tests" flow, so it's hard to predict that the log lines will be present prior to running the config tests. But as long as we have 1 landing int his PR, I'm happy.

**Comment by conorsch** [comment]
Rebased on top of latest develop.

**Comment by conorsch** [comment]
Rebased on top of latest develop. Made some modifications to the new local packages logic (#1612) to support running the application tests inside app-staging, to help with testing that the config change works as expected. Update the associated config test (which was previously marked as an expected failure) so we can track this regression going forward.

**Pull request merged**
