### PR TITLE
Upgrade box update

### LINKED ISSUE #3649: Add in upgrade test box for 0.8 stable
## Description

Normally part of the release, I've been slacking and hit some issues before that are fixed. Lets get this in ASAP.

### PR DESCRIPTION
**Pull request by msheiny**
## Status

Ready for review

## Description of Changes

Fixes #3649 

Changes proposed in this pull request:

## Testing

* `molecule converge -s upgrade`
* wait a while... this will download 3GB + from S3
* confirm tor onion address is running 0.8 in tor browser

## Other

Only affects upgrade test scenario locally in dev env

### CODE REVIEW

**Comment by kushaldas** [comment]
I think I am doing something wrong.

```
$ molecule converge -s upgrade
--> Test matrix
    
└── upgrade
    ├── create
    ├── dependency
    └── converge
    
ERROR: The source path '/home/kdas/code/securedrop/molecule/upgrade/.molecule/../../install_files/ansible-base/group_vars' does not exist.
```

**Comment by conorsch** [comment]
@kushaldas That is an interesting error! Will try to reproduce. Confirm that you have the "proper" Molecule version by running `pip install -r securedrop/requirements/develop-requirements.txt` ?

**Comment by conorsch** [comment]
Able to proceed through the first several tasks of the converge action, so cannot reproduce the problem that @kushaldas reports. Double-check that Molecule version? It may also help to run a `make clean` action beforehand.

**Comment by kushaldas** [comment]
>@kushaldas That is an interesting error! Will try to reproduce. Confirm that you have the "proper" Molecule version by running pip install -r securedrop/requirements/develop-requirements.txt ?

I missed that `missing step` :) Things seem to be running now. :+1:

**Comment by conorsch** [comment]
Roger that, @kushaldas. The create action will take a long time, so Molecule needs to download the new base boxes in the background. If you can get a successful converge action out of the "upgrade" scenario on this branch, that should be sufficient for merge. I'll run the same in the background today to confirm.

**Comment by zenmonkeykstop** [comment]
Testing on Ubuntu 16.04, molecule 2.13.1, vagrant 1.9.1.
Ran molecule converge -s upgrade, got most of the way through but following error:
```
    TASK [Delete existing signature] ***********************************************
    ok: [apt]
    
    TASK [Sign release file] *******************************************************
    fatal: [apt]: FAILED! => {"changed": false, "cmd": ["gpg", "-b", "-u", "C5D5CD3B6D65484B", "-o", "/var/repos/base/dists/trusty/Release.gpg", "/var/repos/base/dists/trusty/Release"], "delta": "0:00:00.007585", "end": "2018-07-23 18:04:17.171868", "msg": "non-zero return code", "rc": 2, "start": "2018-07-23 18:04:17.164283", "stderr": "gpg: can't open `/var/repos/base/dists/trusty/Release': No such file or directory\ngpg: signing failed: file open error", "stderr_lines": ["gpg: can't open `/var/repos/base/dists/trusty/Release': No such file or directory", "gpg: signing failed: file open error"], "stdout": "", "stdout_lines": []}
    
    RUNNING HANDLER [jdauphant.nginx : restart nginx] ******************************
    
    RUNNING HANDLER [jdauphant.nginx : reload nginx] *******************************
    
    PLAY RECAP *********************************************************************
    app-staging                : ok=44   changed=11   unreachable=0    failed=0
    apt                        : ok=25   changed=17   unreachable=0    failed=1   
    mon-staging                : ok=61   changed=11   unreachable=0    failed=0
    
    
ERROR: 
```

**Comment by zenmonkeykstop** [comment]
OK, as @conorsch pointed out, I needed to rebuild local debs first. Revised plan:
```
molecule destroy -s upgrade && make clean 
make build-debs
molecule converge -s upgrade
```
Confirmed that source hidden service is up and is version 0.8.0.

Ran:
```
molecule side-effect -s upgrade
```
Confirmed that source hidden service is up and is version 0.9.0~rc1

**Comment by conorsch** [comment]
Ran through the testing steps, LGTM. As @zenmonkeykstop points out, you need fresh debs, as well as a manual upgrade action to confirm the transition from 0.8.0 -> 0.9.0~rc1 in the VMs.

**Pull request merged**
