### PR TITLE
Fix column/button alignment problems on source start page

### LINKED ISSUE #4891: misalignment on buttons on source interface page
## Description

I just noticed while reviewing new supported languages that the index page is a bit off for some non-English languages. My expectation is that the two large buttons (one blue and one white) would be aligned in the vertical direction:

Screen Shot 2019-10-09 at 12 04 29 PM

### PR DESCRIPTION
**Pull request by rmol**
## Status

Ready for review

## Description of Changes

Fixes #4891.

Certain combinations of language and viewport size could result in the two columns on the source start page not lining up with each other. This changes the columns' `justify-content` property to push the top and bottom containers apart, and controls the borders and content of the buttons to align them better.

## Testing

Run `make dev` and visit the source interface start page. Use the language chooser to confirm that the columns' contents are always in alignment. The header and explanatory text should always start at the top of the column. The buttons should always align at the bottom, and stay the same height.

Resize the browser window, reducing the width until you force a vertical layout. At no point in the horizontal layout should the button text wrap, causing the buttons' heights to differ, nor should the column headings ever appear at different vertical positions (they may wrap).

## Deployment

This only affects the UI.

### If you made changes to the server application code:

- [x] Linting (`make lint`) and tests (`make test`) pass in the development container

### If you made non-trivial code changes:

- [x] I have written a test plan and validated it for this PR

### CODE REVIEW

**Comment by eloquence** [comment]
Thanks @rmol, I think we introduced this regression when we were making final tweaks to the spacing. Flagging the spacing changes this PR would introduce (in the English index page) for visibility to @ninavizz:

Before: Screen Shot 2019-10-09 at 16 45 40-fullpage

After: Screen Shot 2019-10-09 at 16 45 33-fullpage

**Comment by ninavizz** [comment]
Mmh... not ok with the buttons being that far away from the `body` blabs. I realize it's only a 5-10px difference between the before and after, but that's just enough to have the buttons start to feel disconnected from the texts above them. If that could be rectified, I'd be most pleased with the PR, otherwise. :)

**Comment by rmol** [comment]
@ninavizz How's this?

image

**Comment by eloquence** [comment]
LGTM :)

## Before
Screen Shot 2019-10-11 at 14 40 19-fullpage
Screen Shot 2019-10-11 at 14 40 14-fullpage

## After
Screen Shot 2019-10-11 at 14 41 03-fullpage
Screen Shot 2019-10-11 at 14 41 08-fullpage

## Mobile views

<details>
<summary>
Click to expand
</summary>

### Before
Screen Shot 2019-10-11 at 14 40 17-fullpage
Screen Shot 2019-10-11 at 14 40 22-fullpage

### After
Screen Shot 2019-10-11 at 14 41 10-fullpage
Screen Shot 2019-10-11 at 14 41 06-fullpage
</details>

**Pull request merged**
