### PR TITLE
Make sources.filesystem_id non-nullable

### PR DESCRIPTION
**Pull request by legoktm**
## Status

Ready for review

## Description of Changes

We already set this field all the time and in all places expect it to be
a string, not checking if its None first.

Discovered by the mypy work I'm doing in #6346.

Refs #6226.

## Testing

* [ ] Before applying this patch, create a source, log in with it. Then check out this branch, in the dev container run `alembic upgrade head` to apply this schema change, and try to log in with the source. Verify you can log in properly.
* [ ] CI passes

## Deployment

Any special considerations for deployment? No, just a normal schema change.

## Checklist

- [ ] Linting (`make lint`) and tests (`make test`) pass in the development container
- [x] I have written a test plan and validated it for this PR
- [x] These changes do not require documentation

### CODE REVIEW

**Comment by legoktm** [comment]
I tried to git blame on whether we were ever intentionally writing NULLs to filesystem_id and didn't really find anything (but also the filesystem_id column dates back to the initial SQLAlchemy commit, so it's super old!).

I am relatively confident that there aren't NULLs lying around because SD would blow up pretty quickly in the app code if filesystem_id was NULL, so moving this to ready for review.

**Comment by zenmonkeykstop** [comment]
Poked around a bit as well (including manually setting a source's filesystem_id to null and seeing what happens) - returning users are authenticated by generating the expected filesystem_id  and querying the database for it. So, if a source's filesystem_id field is ever set to null, they can't log back in.

Probably what this means for this PR is that just deleting sources with a null filesystem_id value is a valid migration strategy, as their submissions are already effectively orphaned and will get swept up in the nightly jobs to detect disconnected files/entries.

**Comment by legoktm** [comment]
Deleting a source is not the easiest thing in alembic because we need to clean up referential tables, but it seems doable.

**Comment by legoktm** [comment]
Moving back to draft state, I pushed my work from today but there's still a bit more to do in the migration, we delete stuff out of sources, replies, submissions, but aren't then deleting stuff that refer to those replies and submissions...

**Review by zenmonkeykstop — APPROVED** [review]
Tested as follows:
- set up 2.3.1 prod VM environment, created multiple sources, nulled out the filesystem ID for one of them. 
- [x] Confirmed that a 500 error is thrown on the All Sources page due to the missing filesystem_id (so this unlikely scenario would have been immediately noticeable)
- used the upgrade scenario procedure to update the prod instance with debs built from this branch
- [x] confirmed that the All Sources page no longer 500s out and displays only the non-nulled sources.
- [x] confirmed that replies and message from those sources are still available for download
- [x] confirmed that the nulled source was deleted from the database
- [x] confirmed that the filesystem_id field has nullable=false applied.

LGTM!

**Pull request merged**
