### PR TITLE
tests: pytest-catchlog is obsolete

### LINKED ISSUE #2787: tests: pytest-catchlog functionality has been upstreamed into pytest
As of 3.3.1 pytest-catchlog is actually just ignored by pytest -- it is safe to remove. See https://docs.pytest.org/en/latest/logging.html

### PR DESCRIPTION
**Pull request by dachary**
## Status

Ready for review

## Description of Changes

Fixes #2787

https://docs.pytest.org/en/latest/logging.html is a drop-in
replacement for the pytest-catchlog plugin and they will conflict with
each other

## Testing

This is an upgrade of the tests with no impact on anything but the tests themselves. If the CI passes it shows the capture log API change introduced by pytest 3.3.1 was fixed

## Deployment

N/A

### CODE REVIEW

**Comment by dachary** [comment]
@tmc I propose this PR because I've fixed the API change in another pull request and it turns out to not be so complicated. Also we understand what all this is about right now and if we upgrade in a few months from now chances are we will not remember about it and will have to re-discover the problem and the solution again.

**Comment by dachary** [comment]
Transient error again https://travis-ci.org/freedomofpress/securedrop/builds/323790084?utm_source=github_status&utm_medium=notification this is happening very frequently

<pre>
(1.25-2) ...", "Setting up libjson-perl (2.61-1) ...", "Setting up libjson-xs-perl (2.340-1build1) ...", "Setting up liblist-moreutils-perl (0.33-1build3) ...", "Setting up libnet-http-perl (6.06-1) ...", "Setting up libwww-robotrules-perl (6.01-1) ...", "Setting up libperlio-gzip-perl (0.18-1build3) ...", "Setting up libtext-levenshtein-perl (0.06~01-2) ...", "Setting up libtie-ixhash-perl (1.23-1) ...", "Setting up hardening-includes (2.5ubuntu2.close failed in file object destructor:
sys.excepthook is missing
lost sys.stderr
The command "ansible-playbook -i inventory -vv --connection=local install_files/ansible-base/securedrop-development.yml
  " failed and exited with 1 during .
Your build has been stopped.
</pre>

**Comment by dachary** [comment]
completely unrelated error, trying again to verify it is not transient: https://circleci.com/gh/freedomofpress/securedrop/5712?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link

<pre>
    TASK [ossec-agent : Add firewall exemption for OSSEC agent registration.] ******
    Monday 01 January 2018  15:28:19 +0000 (0:00:01.015)       0:06:35.476 ********
    fatal: [app-staging]: FAILED! => {"failed": true, "msg": "The conditional check 'hostvars[groups.securedrop_monitor_server.0].ossec_agent_already_registered == false and iptables_rules_check_result.stat.exists == true' failed. The error was: error while evaluating conditional (hostvars[groups.securedrop_monitor_server.0].ossec_agent_already_registered == false and iptables_rules_check_result.stat.exists == true): 'dict object' has no attribute 'ossec_agent_already_registered'\n\nThe error appears to have been in '/root/sd/install_files/ansible-base/roles/ossec-agent/tasks/agent_config.yml': line 17, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n- name: Add firewall exemption for OSSEC agent registration.\n  ^ here\n"}
</pre>

**Comment by tmc** [comment]
This is great. I was making the change without bumping the pytest version. Looks like the api improved a bit.

**Pull request merged**
