### PR TITLE
Updated source workflow to be less dependent on outside docs

### LINKED ISSUE #1437: Improve UX for sources
I have noticed a few problems with sources sending us things.

### 1. Sources don't "get" SecureDrop
It is rather obvious that many of the source who send us docs or messages have not read the the docs provided by FPF and do not fully understand the security ramifications of their actions. This includes linking to documents hosted on their (presumably) personal Gmail/Dropbox/etc. accounts. I think the expectation that sources will read any docs prior to submitting is unreasonable. GlobalLeaks does a little bit to inform the user during their leaking workflow.

A possible solution would be to include a warning page that a use has to click through before leaking their first doc that explains some Do's and Don't's.

### 2. Sources don't understand the importance of their user name
We get a number of leaks under different user names that are clearly from the same person. This could be N documents in a series, or the person referencing things in a separate conversion that the would only know if they had access to that account.

There was a recent change to hide the username behind a disappearing CSS div which I think is the opposite of what should have been done. A user should have to type and submit their username into a box and submit before they can leak, thus confirming that they understand what it is.

### PR DESCRIPTION
**Pull request by heartsucker**
Fixes  #1437

Currently a WIP with some ugliness and unrefined edges, but the PR is open for initial review before I put too much effort into it.

### CODE REVIEW

**Comment by fowlslegs** [comment]
Really not a fan of the 4 separate checkboxes, each with it's own scary warning UI. I feel like the experience is overwhelming, unclear, and will only serve to scare away sources. We clearly strive to protect sources, but we also don't want to scare them away; I believe too presenting too much information that a technical person will likely be unable to fully comprehend, and properly process right before making a decision to possibly whistle-blow on a powerful institution or individual may deter them from going through with it.

On the generate page, there is existing text explaining the importance of the codename. (Not that I don't think this text could be improved slightly.) The only other thing I'd like to see on that page is a box at the bottom that forces the client to re-type their codename to help enforce it's significance. After typing that the client can be redirected to the educate page. This should require no additional client-session dictionary keys, or database modifications to accomplish.

The educate page should have no checkboxes, and only a "Got it!" box, that redirects to the "lookup" page (no idea why it's named "lookup", but that's another story). The text should be simplified only to include advice about avoiding using/ linking to Google Drive, and instead using SecureDrop to upload all documents if at all possible (or potentially negotiating another secure manner with a journalist--this has had to happen for some very large leaks). I'm not convinced it really needs anything additional, even metadata warnings for the reasons we discussed in #1437.

Back to your point on the importance of the codename being unclear to source--one other thing that might really help this is changing the text on the homepage. I could see how it might be confusing for someone who wishes to upload additional documents to click the "check for a response" box, under the "Already submitted something?" header.

Also, you're probably aware the code is broken as is and will know how to fix that part.

2016-11-07-160534_1642x729_scrot

**Comment by fowlslegs** [comment]
I've assigned @trevortimm as well, who wants to sign off on any new language that goes into this one.

**Comment by heartsucker** [comment]
@fowlslegs @trevortimm I pushed the changes (but not the accompanying tests, so CI will break). Let me know if this is closer to what you were thinking.

**Comment by fowlslegs** [comment]
I'm not able to test your PR for some reason. VMs were coming up on `0.0.0.0`, and even after forcing `127.0.0.1` by changing `{source,journalist}.py`, I can't actually connect to them from my browser. I'm wondering if the problem is related to the new code in https://github.com/freedomofpress/securedrop/pull/1458. Anyway, the text looks much better, but I am concerned that linking to the source documentation can significantly increase the risk of de-anonymization via website fingerprinting, especially when you consider the orthogonal de-anonymization vector of DNS monitoring (see https://nymity.ch/tor-dns/), and the fact docs.securedrop.org disappointingly hosts 3rd-party resources from Google Analytics, and Rack CDN. Would appreciate input/help from @conorsch regarding networking, @trevortimm regarding content (mostly just read `educate.html`), and @redshiftzero regarding threats to anonymity.

**Comment by heartsucker** [comment]
@fowlslegs Good point about the fingerprinting. I can remove that link, especially since there really isn't much covered in docs that at source couldn't figure out from the UI anyway.

**Comment by fowlslegs** [comment]
I'm retrying the Travis build since it failed on `apt update`. As soon as Travis passes, and @trevortimm signs off on the new content here, I'll get on testing this.

**Comment by heartsucker** [comment]
@fowlslegs This won't pass CI yet since I haven't updated the tests yet. I was going to wait until the workflow / language was decided before adding that.

**Comment by fowlslegs** [comment]
Waiting on @trevortimm, who has some feedback he just needs to type up, and also are going to contact a UI/UX person to get some more outside feedback on this one.

**Comment by heartsucker** [comment]
> are going to contact a UI/UX person to get some more outside feedback

Good call.

**Comment by trevortimm** [comment]
Hey @heartsucker, thanks for proposing and working on these changes! I especially like a couple of them, like the new tips section you made. A couple I'm still unsure of, but regardless:

Because changing the source interface can potentially be scary to sources (even though, admittedly, you make some  point about how they are already confused), we think that we should run these changes by a UX/UI expert before we merge them in. This is something we've wanted to do for the source interface in general for a while, and this pull request will give us a great excuse to do it ASAP. We have someone we're going to approach here in SF and we'll report back after we do. Might be tough with the holidays, but hopefully we can do it in the next week or two.

**Comment by heartsucker** [comment]
Hey guys, since this seems like it's a bit of a dead PR, there are a couple of commits that are useful and i think should be merged in (85e7947, 32f7d22, and some of 63baa49). Should I open a new PR for these?

**Comment by bivol** [comment]
Hey Guys, Happy New Year,

Tried to install the new securedrop and failed :(

Atanas Tchobanov (Атанас Чобанов)
editor in Bivol.bg (Биволъ)
mail: atanas@bivol.bg
cell: +33 6 32 69 11 28
cell: +359 884 06 01 03
fax: +33 1 73 76 92 29
twitter: @bivolbg
facebook: https://www.facebook.com/bivolnews
PGP public key id: 4D564134

**Comment by fowlslegs** [comment]
@bivol This is not the appropriate place for support requests. Please sign up for an account at https://support.freedom.press and we'll be happy to help you there.

**Comment by fowlslegs** [comment]
@trevortimm said he wants to sign off on any UI changes, so I can't say if you should open a new PR for those. I would just let this one stay open for now. I'll try to follow up next time he's in the office (probably next week). I also reached out to a frontend person for comment, but got no response.

**Comment by fowlslegs** [comment]
Alright, relaying on some comments made to me that I mostly agree with: we don't want to change the UI/UX often, and we want to do so only in consultation with design experts, and after user testing.

We've been in touch with @ninavizz lately, who's made some nice wireframes of a new design (see https://github.com/freedomofpress/securedrop/issues/1490#issuecomment-270820226). I think you've raised some really good issues, and I've pointed out this PR and corresponding issue to her already.

I apologize that I have not advised anyone on major interface changes before (or made them myself), and wasn't aware of the stringent considerations the org has put in place as far as accepting such changes go. It makes sense, but it just wasn't something I had fully considered before. As stated elsewhere, you're a great contributor and I hate to see any of your work go to waste. We may come back to a couple commits here and merge them later, but I'm going to close this for now.

**Comment by heartsucker** [comment]
@fowlslegs All good. I have a few friends in UI/UX that will sing praise to the effort y'all are taking to be pro about this instead of just letting backend engineers like me do it (ha).

**Pull request closed without merging**
