### PR TITLE
Merge 0.4 release changes into develop

### LINKED ISSUE #1922: Release SecureDrop 0.4
This is a tracking issue for the upcoming release of SecureDrop 0.4 - tasks may get added or modified.

# Pre-release
- [x] Prepare changelog - @redshiftzero
- [x] Send 0.4 pre-release notification to admins to give them sufficient time to prepare - @redshiftzero

# Finish release candidate (0.4-rc1)
- [x] Branch release/0.4 off develop once all necessary milestone issues are completed - @redshiftzero
- [x] Merge in any last minute PRs (#1926, #1934) - @redshiftzero
- [x] Build test debs - @conorsch
- [x] Stand up test apt server with 0.4-rc1 packages - @conorsch

# QA (0.4-rc1)

- [x] Unit tests pass on 0.4 staging VMs - @redshiftzero
- [x] Test upgrade from 0.3.12 works on prod w/ test repo debs - @msheiny, @conorsch 
- [x] Test install (not upgrade) of 0.4 works on prod w/ test repo debs - @redshiftzero
- [ ] Test upgrade from 0.3.12 works on hardware w/ test repo debs without running playbooks  [skipped until second round of test debs]
- [ ] Test upgrade from 0.3.12 works on hardware w/ test repo debs and re-running Ansible playbooks from admin workstation [skipped until second round of test debs]
- [x] Test fresh install (not upgrade) of 0.4 works on hardware w/ test repo debs - @redshiftzero

# Documentation

- [x] Make documentation changes against `release/0.4`

# Finish release candidate (0.4-rc2)
- [x] Merge in remainder of fixes from 0.4-rc1
- [x] Build test debs - @conorsch 
- [x] Stand up test apt server with 0.4-rc2 packages - @conorsch 

# QA (0.4-rc2)

- [x] Test upgrade from 0.3.12 works on hardware w/ test repo debs without running playbooks - @conorsch
- [x] Test upgrade from 0.3.12 works on hardware w/ test repo debs and re-running Ansible playbooks from admin workstation - @conorsch
- [x] Test fresh install (not upgrade) of 0.4 works on hardware w/ test repo debs - @redshiftzero

# Release

- [x] Build final Debian packages for 0.4 - @conorsch
- [x] Release 0.4
- [x] Publish blog post about 0.4 Debian package release and instructions for admins - @redshiftzero

# Post-release

- [ ] Merge release changes into master branch - @redshiftzero
- [ ] Merge release changes into development branch - @redshiftzero

### PR DESCRIPTION
**Pull request by redshiftzero**
## Status

Ready for review

## Description of Changes

Post 0.4 release cleanup (closes #1922): Maintenance merge of `release/0.4` into `develop`

Notes:
1. We're now linting a lot of the SecureDrop app code, so had to fix one flake8 issue
2. We converted our functional tests to use `pytest` in  #1987, so I converted the functional test added in #1981 (not doing this led to test failures)
3. Had to resolve one conflict in: `securedrop/tests/functional/source_navigation_steps.py`

## Testing

Wait for CI to pass

## Deployment

None, these changes are now in prod

### If you made changes to the app code:

- [x] Unit and functional tests pass on the development VM

### If you made changes to the system configuration:

- [ ] [Configuration tests](https://docs.securedrop.org/en/latest/development/testing_configuration_tests.html) pass (CI)

### If you made changes to documentation:

- [x] Doc linting passed locally

### CODE REVIEW

**Comment by dachary** [comment]
@redshiftzero a conflict needs resolving (I don't think github notifies you when that's the case... not sure though)

**Comment by dachary** [comment]
a flake8 error:
<pre>
tests/functional/source_navigation_steps.py:164:9: F841 local variable 'notification' is assigned to but never used
</pre>
which should not be fixed by 0540bd372890bd529713016b4fe72fe015bf5c09 but with a rebase on develop since https://github.com/freedomofpress/securedrop/pull/1985/files was merged including a better fix

**Comment by conorsch** [comment]
@redshiftzero Echoing @dachary's comment above (https://github.com/freedomofpress/securedrop/pull/2048#issuecomment-318268906), can we not use a rebase on top of develop to resolve all conflicts? If we must have a merge commit in the PR branch, fine—and this is an incredibly long list of commits to wrangle—but I'd prefer to avoid it if we have to.

**Comment by redshiftzero** [comment]
OK, will run through this again

**Comment by dachary** [comment]
@redshiftzero after careful examination of the last three commits I withdraw my comment. The merge commit resolves the conflict in a minimal way, which is good. You then introduce a flake8 fix at b77bca0 that was missing from release/0.4 because test_sources was not verified at the time. Your last commit 35f7b70 converts a function that was introduced in release/0.4 and missed the pytest transition.

I think you did the merge in the best possible way and that it is good to go.

**Comment by dachary** [comment]
@conorsch I favor the merge over a rebase because it clarifies what happened and can be matched with the corresponding merge in master.

**Comment by dachary** [comment]
A nit for the next time: it's great to have a comment in the merge commit (or cherry-pick) explaining why the conflict happened and how it was resolved. This is relatively simple so it does not matter much in this case ;-)

**Comment by redshiftzero** [comment]
Thanks for your reviews @conorsch and @dachary. Good point re: explaining the conflict resolution. We should do that in the future :+1:. Merging!

**Pull request merged**
