### PR TITLE
Merges 0.3.7 release into develop branch

### LINKED ISSUE #1313: Merge changes from 0.3.7 into develop
This is a follow-up issue to track merging the changes from the 0.3.7 release into the development branch for the next minor release, 0.4.

### PR DESCRIPTION
**Pull request by conorsch**
Backports changes from the 0.3.7 release on top of the develop branch. Does *not* include changes from:

* 0.3.7-post1 (tracked in #1345)
* 0.3.8 (tracked in #1346)

Conflicts were plentiful, mostly to documentation and Ansible playbooks. All were resolved manually. One merge conflict stood out as deserving particular attention:

```
diff --cc securedrop/crypto_util.py
index c24e94d,487b22a..0000000
--- a/securedrop/crypto_util.py
+++ b/securedrop/crypto_util.py
@@@ -157,17 -154,11 +157,25 @@@ def encrypt(plaintext, fingerprints, ou
          fingerprints = [fingerprints, ]
      fingerprints = [fpr.replace(' ', '') for fpr in fingerprints]
  
++<<<<<<< HEAD
 +    if isinstance(plaintext, unicode):
 +        plaintext = plaintext.encode('utf8')
 +
 +    encrypt_fn = gpg.encrypt if isinstance(
 +        plaintext,
 +        str) else gpg.encrypt_file
 +    out = encrypt_fn(plaintext,
 +                     *fingerprints,
 +                     output=output,
 +                     always_trust=True,
 +                     armor=False)
++=======
+     out = gpg.encrypt(plaintext,
+                       *fingerprints,
+                       output=output,
+                       always_trust=True,
+                       armor=False)
++>>>>>>> 0.3.7
      if out.ok:
          return out.data
      else:
```

Looks like the develop branch had a commit revising the encrypt function, traceable to          657dfa9f8034a5895f68a06e89d518347e3d6114. In resolving this conflict, **I accepted the 0.3.7 version of the file,** to ease the way forward with backporting release branches onto develop (see #1345, #1346).

Closes #1313.

### CODE REVIEW

**Comment by conorsch** [comment]
Automated tests are failing:

```
The command "sudo chown root:root securedrop/config.py" exited with 0.
1.44s$ sudo sh -c "export DISPLAY=:1; cd securedrop && ./manage.py test"
usage: py.test [options] [file_or_dir] [file_or_dir] [...]
py.test: error: unrecognized arguments: --cov
  inifile: /home/travis/build/freedomofpress/securedrop/setup.cfg
  rootdir: /home/travis/build/freedomofpress/securedrop
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/usr/lib/python2.7/unittest/__main__.py", line 12, in <module>
    main(module=None)
  File "/usr/lib/python2.7/unittest/main.py", line 94, in __init__
    self.parseArgs(argv)
  File "/usr/lib/python2.7/unittest/main.py", line 149, in parseArgs
    self.createTests()
  File "/usr/lib/python2.7/unittest/main.py", line 158, in createTests
    self.module)
  File "/usr/lib/python2.7/unittest/loader.py", line 130, in loadTestsFromNames
    suites = [self.loadTestsFromName(name, module) for name in names]
  File "/usr/lib/python2.7/unittest/loader.py", line 100, in loadTestsFromName
    parent, obj = obj, getattr(obj, part)
AttributeError: 'module' object has no attribute 'submit_and_retrieve_message'
```

Two interesting errors there:

* `py.test: error: unrecognized arguments: --cov`
* `AttributeError: 'module' object has no attribute 'submit_and_retrieve_message'`

**Comment by garrettr** [comment]
Diff looks good. I'll check out the automated test failures now.

**Comment by garrettr** [comment]
@conorsch I investigated the issues with the tests last night and fixed them in 0230293.

**Comment by garrettr** [comment]
Looks like the unit tests are passing consistently now, but the functional tests are failing intermittently. When I run `./manage.py test` in a local **development** VM, they sometimes pass, but sometimes fail with the following error message:

<details>
<summary>Functional test WebDriverException traceback</summary>
```
test_submit_and_retrieve_happy_path (tests.functional.submit_and_retrieve_message.SubmitAndRetrieveMessage) ...  * Running on http://127.0.0.1:59135/ (Press CTRL+C to quit)
 * Running on http://127.0.0.1:53698/ (Press CTRL+C to quit)
ERROR

======================================================================
ERROR: test_submit_and_retrieve_happy_path (tests.functional.submit_and_retrieve_message.SubmitAndRetrieveMessage)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "tests/functional/submit_and_retrieve_message.py", line 15, in setUp
    functional_test.FunctionalTest.setUp(self)
  File "tests/functional/functional_test.py", line 82, in setUp
    self.driver = self._create_webdriver()
  File "tests/functional/functional_test.py", line 46, in _create_webdriver
    return webdriver.Firefox(firefox_binary=firefox)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/firefox/webdriver.py", line 103, in __init__
    self.binary, timeout)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/firefox/extension_connection.py", line 51, in __init__
    self.binary.launch_browser(self.profile, timeout=timeout)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/firefox/firefox_binary.py", line 68, in launch_browser
    self._wait_until_connectable(timeout=timeout)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/firefox/firefox_binary.py", line 106, in _wait_until_connectable
    % (self.profile.path))
WebDriverException: Message: Can't load the profile. Profile Dir: /tmp/tmpCTniCL If you specified a log_file in the FirefoxBinary constructor, check it for details.


----------------------------------------------------------------------
Ran 1 test in 30.246s

FAILED (errors=1)
```
</details>

@fowlslegs Can you take a look at this? IIRC you investigated a similar issue recently and might have a better contextual understanding than I do.

**Comment by conorsch** [comment]
@garrettr Excellent, thanks for resolving the dependencies oversight! Should have flagged that explicitly for extra review as well.

Regarding the sometimes-yet-not-always failing tests in Travis, I vote we move that to another issue to track progress there in develop (#844 is a good candidate). Once this is merged, I'll continue the backporting marathon until we're fully in sync between develop and the release branches.

**Comment by fowlslegs** [comment]
@garrettr I never resolved the exact issue that was causing that error, but did determine upgrading to the latest version of Selenium fixed it.

**Comment by garrettr** [comment]
> Regarding the sometimes-yet-not-always failing tests in Travis, I vote we move that to another issue to track progress there in develop (#844 is a good candidate).

@conorsch Strong disagree. These functional test failures are new, *much* more frequent than the intermittent test failures from #844, and may have been caused by some aspect of this merge. We should not continue until they are resolved.

In general, continuing a series of merges with ***known-broken tests*** is a recipe for sadness.

**Comment by fowlslegs** [comment]
See https://github.com/freedomofpress/securedrop/issues/1351.

**Comment by conorsch** [comment]
> In general, continuing a series of merges with known-broken tests is a recipe for sadness.

@garrettr Fair, I'll back off on the backporting for now. Given the report #1351, however, I suggest moving the test debugging to that thread, since the error messages match. We'll block here until #1351 is resolved.

**Comment by garrettr** [comment]
@conorsch Sounds good. I think we can get away with just upgrading Selenium from the current 2.53.2 to the latest stable, 25.3.6, for now. That should allow us to run the full test suite after merging this into develop, which will enable us to continue leveraging the test suite as we continue to merge changes from the rest of the recent 0.3.x releases.

There are other Python dependencies that are also out of date, but we should focus on upgrading only the subset that we need to get the tests working and to make sure there are no regressions caused by the merge from 0.3.7. Generally upgrading out-of-date Python dependencies is being tracked in #1352 and is WIP by @fowlslegs.

**Comment by garrettr** [comment]
With ac12657, the full test suite is passing consistently on my local **development** VM.

**Pull request merged**
