### PR TITLE
Replace Font Awesome icons with PNGs

### LINKED ISSUE #5546: Consider replacing FontAwesome glyphs with PNGs
## Description

The Journalist Interface uses FontAwesome for various icons in the UI, which are rendered as Unicode placeholder glyphs is FontAwesome is not present, which is the case in Tor Browser's "Safest" security setting:

Screenshot from 2020-09-30 15-23-34

The current implementation is based on the reasoning that it's not necessary to use Tor Browser in "Safest" mode in the Journalist Interface, given defense in depth against unauthorized use (2FA login, authorization token). However, we do ask users to use "Safest" to visit the *Source Interface*, and journalists may make the assumption that they should do so for the *Journalist Interface* as well (we have little evidence one way or the other).

To avoid unexpected breakage, it seems reasonable to replace these glyphs with static PNG assets, rendered a high enough resolution to scale well on HiDPI displays.

### LINKED ISSUE #5576: JUI Web UI nits
## Just some Nina Nits
_Possibly to squeeze-into the forthcoming deletion flow work. Because I'm me, I had to._

- [ ] Capitalize the "F" in "Filter by codename"
- [ ] Replace the fontawesome icons with PNGs, for more graceful degradation. See tofu, below.

image

### PR DESCRIPTION
**Pull request by DrGFreeman**
## Status

Work in progress

## Description of Changes

Fixes #5546
Fixes #5576

Changes proposed in this pull request:

**Replace Font Awesome icons with PNGs in Journalist Interface.**
    
Replace all Font Awesome icons in JI with PNGs so they are displayed correctly with Tor Browser in "Safest" setting (#5546 & #5576).
    
**Related changes included:**
- Increase font size of source submission counts text in `/`
- Ensure consistent vertical spacing in users table in `/admin/`

**Other changes:**
- Capitalize "F" in "Filter by codename" placeholder text in `/` (#5576)
- Add "«" in "Back to admin interface" link text in `/admin/edit/<user_id>` for consistency with other admin pages.

## Testing

How should the reviewer test this PR?
Write out any special testing steps here.

## Deployment

Any special considerations for deployment? Consider both:

1. Upgrading existing production instances.
2. New installs.

### If you made changes to the server application code:

- [ ] Linting (`make lint`) and tests (`make test`) pass in the development container

### If you made changes to `securedrop-admin`:

- [ ] Linting and tests (`make -C admin test`) pass in the admin development container

### If you made changes to the system configuration:

- [ ] [Configuration tests](https://docs.securedrop.org/en/latest/development/testing_configuration_tests.html) pass

### If you made non-trivial code changes:

- [ ] I have written a test plan and validated it for this PR

### If you made changes to documentation:

- [ ] Doc linting (`make docs-lint`) passed locally

### If you added or updated a code dependency:

Choose one of the following:

- [ ] I have performed a diff review and pasted the contents to [the packaging wiki](https://github.com/freedomofpress/securedrop-debian-packaging/wiki)
- [ ] I would like someone else to do the diff review

### CODE REVIEW

**Comment by DrGFreeman** [comment]
Hey @ninavizz & @eloquence, here's a first pass for feedback.  Screenshots taken with Tor Browser at "Safest" setting below:

**JI homepage** (Updated)

image


**Source page**

image

**Admin interface**

image

**Add user page**

image

**Edit user page** (lower portion where icons are used)

image

**Config page**

image

**Comment by DrGFreeman** [comment]
## Notes

1. Hover behavior on the source star in `/`, trash buttons and trash icon in `/admin/` is functional.  However, **I had to disable the tooltip on the trash icon in `/admin` to make the hover work**.  There is certainly a way to get it to work but this is beyond my knowledge of CSS at this point.
I suspect I would need to modify these [two selectors](https://github.com/DrGFreeman/securedrop/blob/ea36d78b56b0a2cd474a626f26183a0407a1edb0/securedrop/sass/modules/_button.sass#L118-L122) to also capture the images that are [inside the `<i>` element](https://github.com/DrGFreeman/securedrop/blob/ea36d78b56b0a2cd474a626f26183a0407a1edb0/securedrop/journalist_templates/admin.html#L43-L46) which is currently deactivated. I will read a bit on css selectors and try to make it work.

1. I have not cleaned up the repository of unused font-awesome files. I could include this in the changes if desired.

1. The `securedrop/static/i/` folder also contains many icons in PNG format I suspect are note used anymore (though some are used in flash messages). I could remove the unused icons if desired.

1. I put the new icons in `securedrop/static/icons` for now to avoid mixing up with the other icons in `securedrop/static/i` as per the previous note. I can move them inside `securedrop/static/i` if I clean the unused icons and ensure there is no filename collision.

1. The `securedrop/journalist_templates/flag.html` template uses the `fa-info-circle` icon. I have not replaced it yet as I could not figure how to access this page through the JI.

1. (**updated see below**) ~~At this time, did not specify the vertical alignment of the icons in the source and submission rows (bottom aligned with text baseline as default):~~
    image
    
    ~~As per @ninavizz's [comment](https://github.com/freedomofpress/securedrop/issues/5546#issuecomment-711097195), the alignment looks a bit odd, mainly because the submission counts font size is small compared to the icons (despite the fact I increased it already).  I have tried `vertical-align: center` on the icons but it even more odd to me. I will reproduce it and provide screenshots.  For reference, the star in the current JI uses `vertical-align: center` and looks mis-aligned compared to the rest of the line:~~
    image

**Comment by ninavizz** [comment]
Thx so much for this @DrGFreeman! I personally feel the icons are in better balance with all the elements in the layout, at the size that they are—but then how all items are aligned within each "line item," is clearly a bigger issue (which separately, had already been a bug up my bonnet). Thank you for taking the time to look into that and explain it above. 

Because the icons themselves are the focus of this PR and not fixing what is likely a very messy CSS problem, I'd be ok punting on it as its own issue for a later PR. My own $0.02, @eloquence is the conductor of our train and I leave the call in his capable hands.

**Comment by DrGFreeman** [comment]
@ninavizz, I managed to improve the vertical alignment of the icons and checkbox in the source rows. I also restored the padding to the right of the files and messages icons which was lost in the changes. This is what it looks like now:

image

**Comment by eloquence** [comment]
Great progress @DrGFreeman! To ensure read access to these files in a staging/production environment, we'll need to update the AppArmor profile in https://github.com/freedomofpress/securedrop/blob/develop/install_files/ansible-base/roles/build-securedrop-app-code-deb-pkg/files/usr.sbin.apache2 to enumerate the new PNG files.

**Comment by DrGFreeman** [comment]
Looks like I managed to mess up the branch trying to rebase it. I will close this PR and submit a new one from a clean branch (easier than trying to fix this one).

**Pull request closed without merging**
