### PR TITLE
Override from address on outbound ossec emails

### PR DESCRIPTION
**Pull request by msheiny**
This allows re-mapping of the default ossec@server_name address that
is seen on the FROM line coming out of the ossec box. Post fix is
handling this rather than ossec.

Added this for customization and because some SMTP servers will
not allow sending email from an address that is not the address
associated with the user account. Noticed this specifically as a default
rule on Office365 recently.

### CODE REVIEW

**Comment by conorsch** [comment]
Good catch. Closes #1220, where this was first mentioned.

Unfortunately we cannot trivially update `prod-specific.yml` because it will cause merge conflicts with site-specific changes. Make sure to test how it merges:

1. edit `prod-specific.yml` with custom vars
2. `git stash save site-specific-changes`
3. checkout this feature branch
4. `git stash pop`

If you have to resolve conflicts manually, we'll need another way. Often appending the new var to the edit of the prod-specific.yml file helps avoid conflicts, but that's quite unintuitive, given that all the OSSEC vars are grouped together. We might need a smarter way to manage site vars in 0.4.

**Comment by msheiny** [comment]
> If you have to resolve conflicts manually, we'll need another way. Often appending the new var to the edit of the prod-specific.yml file helps avoid conflicts, but that's quite unintuitive, given that all the OSSEC vars are grouped together. We might need a smarter way to manage site vars in 0.4.

What about? We make a new `example-prod-specific.yml` with example data and then we `gitignore` the `prod-specific.yml` file?

**Comment by conorsch** [comment]
We will most likely have to migrate completely away from prod-specific.yml and require a new vars layout, yes. But for the nonce I'd prefer to retain backwards compatibility on the prod-specific.yml file, simply because we haven't broken it yet, and I want to keep that streak going, even in develop (for now).

**Comment by msheiny** [comment]
@conorsch i removed the var from `prod-specific.yml` for now. Definitely want to revisit the vars issue though in a later release.

**Comment by fowlslegs** [comment]
Closes https://github.com/freedomofpress/securedrop/issues/894.

**Comment by conorsch** [comment]
We've recently had Admins contact us to debug the OSSEC alerts, and the changes proposed in this PR resolved the issue. Since mail handlers are increasingly restricting the allowed from values, in an attempt to fight spam, we need to fix this issue for 0.4. Without these changes, the OSSEC setup cannot work with many mail providers.

Since @msheiny removed the new variable from prod-specific.yml, sidestepping any stash/pop conflicts, I no longer have concerns about breaking the Admin workflow. Still, several changes should be made prior to merge:

* saner declaration of default vars (e.g. via role defaults, rather than in template)
* update OSSEC docs to include this option in the troubleshooting

I'll handle implementing those during review.

**Comment by conorsch** [comment]
Rebased on top of latest develop, to take advantage of new config tests.

**Comment by conorsch** [comment]
Out of an abundance of caution, we're preserving the existing default behavior of the FROM line for OSSEC emails being set to `ossec@ossec.server`. That's not a value we can change the default for lightly, given that it could break alerting for Admins with currently working setups. The addition to the OSSEC guide documentation should clarify the issue for anyone who runs into problems—I placed the new entry near the top of the troubleshooting guide because it's becoming an increasingly common issue.

**Comment by conorsch** [comment]
Satisfied with the latest changes. Added a config test. @redshiftzero can you sanity-check the prose in the docs addition? If you're OK with that then we're good for merge here.

**Comment by redshiftzero** [comment]
Docs look good to me!

**Pull request merged**
