### PR TITLE
Update Hi-DPI displays note

### PR DESCRIPTION
**Pull request by KwadroNaut**
Tails 2.0 release is out since a week, the bug about high resolution displays (https://labs.riseup.net/code/issues/8659 ) is resolved. Only a minor issue remains.

### CODE REVIEW

**Comment by fowlslegs** [comment]
Even if Tor Browser may block enumeration of plugins (anti-fingerprinting), there could be other detectable or otherwise unexpected behavior of a 3rd-party addon. Therefore, we cannot recommend the installation of the addon you mention. If you want to change your commit to instead suggest people go into `about:config` and instead set `layout.css.devPixelsPerPx` to a value between 1.1 to 1.5, I would be happy to merge it.

**Comment by garrettr** [comment]
@KwadroNaut I haven't had a chance to test Tails 2.0 yet, is there a problem with the Tor Browser toolbar is small and hard to use on Hi-DPI displays?

**Comment by KwadroNaut** [comment]
I've been getting conflicting feedback regarding such displays. @fowlslegs comment is very important and true (don't install plugins). Maybe, until someone else comes by and tests, it's better to change the wording to prefer non High-DPI displays and give feedback if you *do* use them. I'll adapt the wording accordingly tomorrow.

**Comment by garrettr** [comment]
How about we just remove the "A note about Hi-DPI displays" section entirely?

**Comment by conorsch** [comment]
> How about we just remove the "A note about Hi-DPI displays" section entirely?

A voice of reason! This sounds like the best choice, although I hesitate to implement the change until I've seen the hidpi problem resolved with my own eyes.

**Comment by garrettr** [comment]
@conorsch It's marked as resolved on the upstream Tails issue tracker as of 2.0: https://labs.riseup.net/code/issues/8659. I have confirmed that Tails 2.x has a reasonable screen resolution on my MacBook Pro with a Retina display (there are a few little pieces of the UI that appear kinda small, but overall it's pretty good).

**Comment by KwadroNaut** [comment]
Sounds good.

**Comment by garrettr** [comment]
Great, thanks for updating the PR @KwadroNaut! :+1:

**Pull request merged**
