### PR TITLE
Remove runtime javascript minification

### LINKED ISSUE #6415: Remove JS minification from the web applications.
## Description

In order to improve performance of the web applications, support for minification for JS and CSS files was added in https://github.com/freedomofpress/securedrop/commit/e74b39075fa4d407bf929ab8bc5ab24abad79f70, using `flask-assets`, `cssmin`, and `jsmin`.

Since then the application has started using SASS for CSS minification (see #2808), meaning only JS is being minified. Only 2 files are currently being minified, `static/js/{source,journalist}.js`, with savings of <1k and <2k respectively. 

To reduce code complexity at the cost of 1-2k in page size, it would make sense to drop JS minification as well. Alternatively, the files could be minified during the build process (tho IMO it's overkill given the minimal gains).

One other disadvantage of server-side minification is that the Apache user needs to be able to write the minified files somewhere on the webroot. Removing it would allow for tightening up the relevant apparmor profile, removing the related write perms

## User Research Evidence
n/a

## User Stories
n/a

### PR DESCRIPTION
**Pull request by zenmonkeykstop**
## Status

Ready for review

## Description of Changes

Fixes #6415

- serves static/js resources instead of gen/js resources
- removes flask-assets, jsmin, and webassets dependencies and related code
- updates apparmor profile to remove rw access to /gen/
- updates builder functionality/tests to ensure gen/ not present
- updates postinst to remove gen/, .webassets-cache/ if present

## Testing

- checkout this branch
- run `git clean -dfx` to ensure old generated files aren't left hanging around
- run `make dev-tor`
  - [x] confirm that applications start successfully
  - [x] confirm that `source.js` on the SI home page is served from `/static/js/`, not `/static/gen`
  - [x] visit the SI via a tor2web proxy and verify that you are immediately redirected to the `/tor2web-warning` page on visiting the SI home page
  - [x] log into the JI and confirm that `journalst.js` on the JI All Source page is served from `/static/js/`, not `/static/gen`
  - [x] confirm that the source filter still works
- [x] run `make build-debs`, confirm that the package build completes without error
- [x] run `make staging`, and confirm that staging servers are provisioned without error and that `source.js` and `journalist.js` are served from `/static/js` on the   SI and JI respectively

### Upgrade testing (optional)
- [ ] run through the upgrade scenario with this branch and confirm that the upgrade completes without error and that `source.js` and `journalist.js` are served from `/static/js` on the   SI and JI respectively

## Deployment

This  PR modifies the `securedrop-app-code` `postint` to remove the `/static/gen` and `/static/.webassets-cache` directories in the webroot, so upgrade testing should be performed prior to release.

### If you made changes to the server application code:

- [ ] Linting (`make lint`) and tests (`make test`) pass in the development container

### If you made changes to `securedrop-admin`:

- [x] Linting and tests (`make -C admin test`) pass in the admin development container

### If you added or removed a file deployed with the application:

- [x] I have updated AppArmor rules to include the change

### If you made non-trivial code changes:

- [x] I have written a test plan and validated it for this PR

Choose one of the following:

- [ ] I have opened a PR in the [docs repo](https://github.com/freedomofpress/securedrop-docs) for these changes, or will do so later
- [ ] I would appreciate help with the documentation
- [x] These changes do not require documentation

### CODE REVIEW

**Comment by legoktm** [comment]
(rebased on top of develop so the /tor2web-warning endpoint isn't throwing 500 errors, was fixed in cfae1e6d9af597f0ea98cb65b0287859be33e7fa)

**Review by legoktm — COMMENTED** [review]
debs are still building, but I think we can remove the `gen` and `.webassets-cache` folders from the "Create static asset directories" step.

**Review by legoktm — CHANGES_REQUESTED** [review]
This is the build failure I got:
```
    =================================== FAILURES ===================================
    _ test_deb_package_contains_no_generated_assets[docker://focal-sd-dpkg-verification] _
    [gw1] linux -- Python 3.7.3 /home/user/securedrop/.venv/bin/python3
    
    securedrop_app_code_contents = 'drwxr-xr-x root/root         0 2022-05-06 14:05 ./\ndrwxr-xr-x root/root         0 2022-05-06 14:05 ./etc/\ndrwxr-xr-...n3 -> /usr/bin/python3\nlrwxrwxrwx root/root         0 2022-05-06 14:05 ./opt/venvs/securedrop-app-code/lib64 -> lib\n'
    
        def test_deb_package_contains_no_generated_assets(securedrop_app_code_contents: str):
            """
            Ensures the `securedrop-app-code` package does not ship minified
            static assets previously built at runtime via Flask-Assets under /gen, and
            which may be present in the source directory used to build from.
            """
            # static/gen/ directory not should exist
    >       assert not re.search(
                r"^.*\./var/www/securedrop" "/static/gen/$", securedrop_app_code_contents, re.M
            )
    E       AssertionError: assert not <re.Match object; span=(523650, 523730), match='drwxr-xr-x root/root         0 2022-05-06 14:05 .>
    E        +  where <re.Match object; span=(523650, 523730), match='drwxr-xr-x root/root         0 2022-05-06 14:05 .> = <function search at 0x7080ed8d21e0>('^.*\\./var/www/securedrop/static/gen/$', 'drwxr-xr-x root/root         0 2022-05-06 14:05 ./\ndrwxr-xr-x root/root         0 2022-05-06 14:05 ./etc/\ndrwxr-xr-...n3 -> /usr/bin/python3\nlrwxrwxrwx root/root         0 2022-05-06 14:05 ./opt/venvs/securedrop-app-code/lib64 -> lib\n', <RegexFlag.MULTILINE: 8>)
    E        +    where <function search at 0x7080ed8d21e0> = re.search
    E        +    and   <RegexFlag.MULTILINE: 8> = re.M
    
    tests/test_securedrop_deb_package.py:273: AssertionError
    =========================== short test summary info ============================
    FAILED tests/test_securedrop_deb_package.py::test_deb_package_contains_no_generated_assets[docker:/focal-sd-dpkg-verification]
    ======= 1 failed, 143 passed, 1 skipped, 1 xfailed in 143.10s (0:02:23) ========
```

**Comment by zenmonkeykstop** [comment]
D'oh! apologies on missing the CR @legoktm, PR is updated now.

**Review by legoktm — APPROVED** [review]
Fantastic, LGTM!

**Pull request merged**
