### PR TITLE
WIP - documentation CI branch detection

### PR DESCRIPTION
**Pull request by msheiny**
WORK IN PROGRESS -- DO NOT MERGE

Test PR to demonstrate staging does not run under a branch with `docs-` naming convention. Under active testing right now.

### CODE REVIEW

**Comment by redshiftzero** [comment]
I think you'll need to push another commit here that is _not_ present in #2149 to test this, because since the commits in this PR and #2150 are the same, only one CircleCI build is running (and it's running the full staging tests).

**Comment by msheiny** [comment]
> I think you'll need to push another commit here that is not present in #2149 to test this, because since the commits in this PR and #2150 are the same, only one CircleCI build is running (and it's running the full staging tests).

Ohh dang i see what you mean -- good call.

**Comment by msheiny** [comment]
okayyy ^^ all good now 👍

**Comment by msheiny** [comment]
Umm dont actually merge this PR tho

**Comment by redshiftzero** [comment]
haha yeah - I won't 😇

**Comment by redshiftzero** [comment]
Verifying in [this build](https://circleci.com/gh/freedomofpress/securedrop/1207) that the full staging test suite did not run, but the build passed.

**Pull request closed without merging**
