### PR TITLE
Qualify Debian packages with target distribution

### PR DESCRIPTION
**Pull request by rmol**
## Status

Ready for review

## Description of Changes

Includes the Ubuntu distribution in our .deb package names. Tries to normalize what we call the distribution/release/platform in all the packaging and deployment tooling.  Reduces the number of places `update_version.sh` has to update.

Partially addresses https://github.com/freedomofpress/securedrop-dev-packages-lfs/issues/85 by allowing `reprepro` to add all the files for both Ubuntu releases.

## Testing

- `git checkout -b qualify-debs origin/qualify-debs`
- `make build-debs`
- `make build-debs-focal`
- verify that all packages have the distribution in their names
- clone the `securedrop-dev-packages-lfs` repo
- in the root of the `securedrop-dev-packages-lfs` repo, run `sed -i 's/SignWith.*//' repo/conf/distributions` so `reprepro` doesn't complain that it can't sign files. 
- `reprepro --basedir ~/src/fpf/securedrop-dev-packages-lfs/repo --outdir /tmp/reprepro/ --dbdir /tmp/repreprodb includedeb xenial ~/src/fpf/securedrop/build/xenial/*.deb`
- `reprepro --basedir ~/src/fpf/securedrop-dev-packages-lfs/repo --outdir /tmp/reprepro/ --dbdir /tmp/repreprodb includedeb focal ~/src/fpf/securedrop/build/focal/*.deb`

There should be no errors from the second `reprepro` run about [files with different hashes](https://github.com/freedomofpress/securedrop-dev-packages-lfs/issues/85#issuecomment-765677012). The repo should contain the full set of files for each Ubuntu distribution.

- Try a staging environment for each distribution, e.g. `make staging` and `make staging-focal`, or run the configuration tests.

## Deployment

This should just affect package naming and metadata.

### If you made changes to the server application code:

- [ ] Linting (`make lint`) and tests (`make test`) pass in the development container

### If you made changes to the system configuration:

- [ ] [Configuration tests](https://docs.securedrop.org/en/latest/development/testing_configuration_tests.html) pass

### If you made non-trivial code changes:

- [x] I have written a test plan and validated it for this PR

Choose one of the following:

- [ ] I have opened a PR in the [docs repo](https://github.com/freedomofpress/securedrop-docs) for these changes, or will do so later
- [ ] I would appreciate help with the documentation
- [x] These changes do not require documentation

### CODE REVIEW

**Comment by conorsch** [comment]
Thanks, @rmol! Haven't reviewed yet. @creviera mentioned she was interested in taking a look, so I'm explicitly requesting her review here. Happy to pile on later.

**Comment by sssoleileraaa** [comment]
happy to review and take this off conor's plate

**Comment by sssoleileraaa** [comment]
just to note what i did was run through the test plan and saw that there is now a `focal` and `xenial` string in _all_ the deb names. no errors, nothing looks incorrect to me. i was interested in following [these steps here](https://github.com/freedomofpress/securedrop-dev-packages-lfs/issues/85#issuecomment-765677012) for xenial, but got stuck on trying to do a clean install (the `./securedrop-admin install` step which errors with an apt-cache issue, will poke around more). conor is also reviewing and i think it makes the most sense for his stamp of approval instead of mine.

**Comment by conorsch** [comment]
Visually, these changes look great! Overall it reduces a lot of duplication in the build logic, so I'm a fan. Haven't stepped through the manual test plan yet, so I'll do that prior to merging, hopefully tomorrow, so as not to block hardware installs.

In terms of closing https://github.com/freedomofpress/securedrop-dev-packages-lfs/issues/85, we'll want to consider version strings for the kernel image packages, as well. That logic won't reside here, but @emkll mentioned recently that we don't have distro-specific strings there. I'll look into that as part of #5479.

**Review by conorsch — APPROVED** [review]
Works beautifully. The distribution is included in the version string for all packages, regardless of distro, so it's important to confirm that dpkg resolves the changes as "higher" versions, which it does:

```
$ dpkg --compare-versions 3.6.0 lt 3.6.0+xenial && echo success
success
```

After creating the local reprepro respositories as described in the test plan, you can serve that directory locally with `python3 -m http.server` or similar and browse through, confirming side-by-side packages for each. 

After merging, we'll have to upload both to apt-test and confirm that unblocks Focal hardware installs. I've just built the debs as part of review, so I volunteer to upload those packages, too.

**Pull request merged**
