### PR TITLE
Bugfix: Update installer.patch against latest tails-installer 5.0.4

### LINKED ISSUE #3105: Update installer.patch (mentioned in the virtualizing_tails.rst) with respect to Tails 3.5
# Bug

## Description

The [installer.patch](https://docs.securedrop.org/en/latest/development/virtualizing_tails.html) is outdated (fails on Tails 3.5).

## Steps to Reproduce
1. In tails VM create a file installer.patch (copy and paste the patch from virtualizing_tails.rst)
2. Run the following command in the terminal `sudo patch -p0 -d/ < installer.patch`  

## Actual Behavior
`root@amnesia:/home/amnesia/temp# sudo patch -p0 -d/ < installer.patch
patching file /usr/lib/python2.7/dist-packages/tails_installer/creator.py
Reversed (or previously applied) patch detected!  Assume -R? [n] n
Apply anyway? [n] y
Hunk #1 FAILED at 615.
1 out of 1 hunk FAILED -- saving rejects to file /usr/lib/python2.7/dist-packages/tails_installer/creator.py.rej
patching file /usr/lib/python2.7/dist-packages/tails_installer/gui.py
Hunk #1 FAILED at 483.
1 out of 1 hunk FAILED -- saving rejects to file /usr/lib/python2.7/dist-packages/tails_installer/gui.py.rej`

### PR DESCRIPTION
**Pull request by ageis**
[tails-installer](https://anonscm.debian.org/git/pkg-privacy/packages/tails-installer.git) is a Python application, currently at version 5.0.4+dfsg. That version was tagged on January 22nd and uploaded to [Debian repositories](https://packages.debian.org/sid/tails-installer) on Feb 3rd plus [Launchpad PPA](https://launchpad.net/~tails-team/+archive/ubuntu/tails-installer) on Feb 4th, causing the included patch in this document to fail because some lines in `gui.py` and `creator.py` had changed.

See: https://klistrain.se/p/0491dbc, bug was discovered by @Anonymous26.
```
root@amnesia:/home/amnesia/temp# sudo patch -p0 -d/ < installer.patch
patching file /usr/lib/python2.7/dist-packages/tails_installer/creator.py
Reversed (or previously applied) patch detected!  Assume -R? [n] n
Apply anyway? [n] y
Hunk #1 FAILED at 615.
1 out of 1 hunk FAILED -- saving rejects to file /usr/lib/python2.7/dist-packages/tails_installer/creator.py.rej
patching file /usr/lib/python2.7/dist-packages/tails_installer/gui.py
Hunk #1 FAILED at 483.
1 out of 1 hunk FAILED -- saving rejects to file /usr/lib/python2.7/dist-packages/tails_installer/gui.py.rej
```

This updates the patch in the "virtualizing Tails" documentation based on the latest version of tails-installer.

Here is the new patch ([link](https://paste.cointel.pro/?7b5492e3840adfaa#jdd32xc0lILACFZRozLiDRPwYTdR8SvrIZB9N3IZF2c=)):
```
--- /usr/lib/python2.7/dist-packages/tails_installer/creator.py      2018-01-22 14:59:40.000000000 +0100
+++ /usr/lib/python2.7/dist-packages/tails_installer/creator.py.mod  2018-03-05 05:15:00.000000000 -0800
@@ -595,16 +595,6 @@ class LinuxTailsInstallerCreator(TailsInstallerCreator):
                 self.log.debug('Skipping non-removable device: %s'
                                % data['device'])

-            # Only pay attention to USB and SDIO devices, unless --force'd
-            iface = drive.props.connection_bus
-            if iface != 'usb' and iface != 'sdio' \
-               and self.opts.force != data['device']:
-                self.log.warning(
-                    "Skipping device '%(device)s' connected to '%(interface)s' interface"
-                    % {'device': data['udi'], 'interface': iface}
-                )
-                continue
-
             # Skip optical drives
             if data['is_optical'] and self.opts.force != data['device']:
                 self.log.debug('Skipping optical device: %s' % data['device'])
--- /usr/lib/python2.7/dist-packages/tails_installer/gui.py      2018-01-22 14:59:40.000000000 +0100
+++ /usr/lib/python2.7/dist-packages/tails_installer/gui.py.mod  2018-03-05 05:15:00.000000000 -0800
@@ -568,16 +568,6 @@ class TailsInstallerWindow(Gtk.ApplicationWindow):
                     self.devices_with_persistence.append(info['parent'])
                     continue
                 pretty_name = self.get_device_pretty_name(info)
-                # Skip devices with non-removable bit enabled
-                if not info['removable']:
-                    message =_('The USB stick "%(pretty_name)s"'
-                               ' is configured as non-removable by its'
-                               ' manufacturer and Tails will fail to start on it.'
-                               ' Please try installing on a different model.') % {
-                               'pretty_name':  pretty_name
-                               }
-                    self.status(message)
-                    continue
                 # Skip too small devices, but inform the user
                 if not info['is_device_big_enough_for_installation']:
                     message =_('The device "%(pretty_name)s"'
```

## Status

Ready for review.

## Description of Changes

Updates `installer.patch` in the "virtualizing Tails" documentation to work with tails-installer 5.0.4, which was released one month ago. Fixes #3105.

## Testing

Needs to be tested against actual Tails 3.5, with the full procedure described in the documentation of installing to a virtual hard disk image.

### CODE REVIEW

**Comment by Anonymous26** [comment]
@ageis just opening the isuue regarding this

**Comment by ageis** [comment]
tails_vm_patch
My patch succeeded in a Tails 3.5 VirtualBox VM, and tails-installer executes without any errors. Believe @kushaldas is also providing review and @Anonymous26 is actually going to use it to install Tails to the virtual hard disk image (VDI).

**Comment by redshiftzero** [comment]
I just applied this patch on Tails 3.6~rc1 and it doesn't apply cleanly due to changes in the Tails Installer in Tails 3.6 (being released in 1 week). Thought: how about we just instruct users to open the `creator.py` and `gui.py` in `gedit` (because it's easiest to use for new people) and remove those two stanzas manually? The reason I'm suggesting this is for maintainability - every Tails release I don't want us to have to update these docs. What do you think?

**Comment by ageis** [comment]
> The reason I'm suggesting this is for maintainability - every Tails
release I don't want us to have to update these docs. What do you think?

For maintaibility, the patches should be their own files in VC rather than
embedded in the .rst. Secondly, I think this should be submitted upstream
as a feature (simple enable/disable checkbox) to tails-installer, which is
a slightly separately maintained component of Tails...

**Comment by redshiftzero** [comment]
Well, my point was to avoid maintaining the patch files entirely, which is unrelated to whether the patch files should be stored in separate files or not. Anyway, I'm just going to merge this PR as it does indeed minimally update the patch for Tails 3.5 (tested in fresh Tails 3.5 VM). 

I don't think upstream changes (especially changes that would complicate a simple UI) would be wise solely for the benefit of us doing SecureDrop QA in VMs :) That said, eventually we may not need to do this patching due to [other](https://labs.riseup.net/code/issues/8422) [changes](https://labs.riseup.net/code/issues/10731) upstream.

**Pull request merged**
