### PR TITLE
[1.6.0] Cherry pick 5550 5549

### PR DESCRIPTION
**Pull request by kushaldas**
## Status

Ready for review

## Description of Changes

Cherry picking commits from #5550 and #5549 PRs.

Had to solve the merge conflicts. 

Make sure no other dependencies were added/modified/removed in the rebase operation / conflict resolution

## Testing

How should the reviewer test this PR?
Write out any special testing steps here.

## Deployment

Any special considerations for deployment? Consider both:

1. Upgrading existing production instances.
2. New installs.

### If you made changes to the server application code:

- [ ] Linting (`make lint`) and tests (`make test`) pass in the development container

### If you made changes to `securedrop-admin`:

- [ ] Linting and tests (`make -C admin test`) pass in the admin development container

### If you made changes to the system configuration:

- [ ] [Configuration tests](https://docs.securedrop.org/en/latest/development/testing_configuration_tests.html) pass

### If you made non-trivial code changes:

- [ ] I have written a test plan and validated it for this PR

### If you made changes to documentation:

- [ ] Doc linting (`make docs-lint`) passed locally

### If you added or updated a code dependency:

Choose one of the following:

- [ ] I have performed a diff review and pasted the contents to [the packaging wiki](https://github.com/freedomofpress/securedrop-debian-packaging/wiki)
- [ ] I would like someone else to do the diff review

### CODE REVIEW

**Comment by kushaldas** [comment]
I think I made mistake while doing conflict fix for `port_for==0.3.1`

**Comment by kushaldas** [comment]
Trying again

**Comment by zenmonkeykstop** [comment]
This probably isn't going to pass CI unless the changes in #5520 are backported as well - lint job is failing because docs python dependencies are no longer present.

**Comment by emkll** [comment]
Updated this branch with local changes preserving docs requirements. CI should now pass on this branch

**Review by zenmonkeykstop — APPROVED** [review]
LTGM, securedrop-app-code deps unchanged

**Pull request merged**
