### PR TITLE
Removes Xenial related parts from codebase

### LINKED ISSUE #5725: Remove all Xenial-specific code from the codebase
SecureDrop 2.0.0 will be the first release to no longer support Ubuntu 16.04 (Xenial). As part of that release (but no sooner), we should remove all Xenial-specific code from the codebase, including any Xenial-specific application code, provisioning logic, or developer tooling.

## Next steps

- [x] Update Vagrantfile
- [x] Remove the following molecule scenarios
- [x] `builder-xenial`,  `libvirt-staging-xenial`, `qubes-staging-xenial`, `virtualbox-staging-xenial`
- [x] Update `make build-debs` to `make build-debs-focal` and remove the second
- [x] Update `make build-debs-notest` to `make build-debs-notest-focal` and remove the second
- [x] Update `make staging` to same of `make staging-focal` and remove the second
- [x] Update `make dev` to same of `make dev-focal` and remove the second
- [x] Update `ci-deb-tests` to `ci-deb-tests-focal` and remove the second
- [x] Update CI to remove all `Xenial` based jobs, make sure that all scripts have `focal` as default
- [ ] Next, look at the source and journalist code to find all Python3.5 related points

### PR DESCRIPTION
**Pull request by kushaldas**
## Status

Ready for review.

## Description of Changes

Fixes #5725 

Removes major `Xenial` changes from the codebase.

## Testing

- [ ] CI should be green
- [ ] visual inspection of the change

## Deployment

Any special considerations for deployment? Consider both:

1. Upgrading existing production instances.
2. New installs.

### If you made changes to the server application code:

- [ ] Linting (`make lint`) and tests (`make test`) pass in the development container

### If you made changes to `securedrop-admin`:

- [ ] Linting and tests (`make -C admin test`) pass in the admin development container

### If you made changes to the system configuration:

- [ ] [Configuration tests](https://docs.securedrop.org/en/latest/development/testing_configuration_tests.html) pass

### If you added or removed a file deployed with the application:

- [ ] I have updated AppArmor rules to include the change

### If you made non-trivial code changes:

- [ ] I have written a test plan and validated it for this PR

Choose one of the following:

- [ ] I have opened a PR in the [docs repo](https://github.com/freedomofpress/securedrop-docs) for these changes, or will do so later
- [ ] I would appreciate help with the documentation
- [ ] These changes do not require documentation

### If you added or updated a code dependency:

Choose one of the following:

- [ ] I have performed a diff review and pasted the contents to [the packaging wiki](https://github.com/freedomofpress/securedrop-debian-packaging/wiki)
- [ ] I would like someone else to do the diff review

### CODE REVIEW

**Comment by rmol** [comment]
I updated the Focal Dockerfile to get the layer cache updated.

**Comment by kushaldas** [comment]
Should we remove/update the Debian packaging logic in all the packages for making them only `Focal`? Keeping them same will make the PR easier to review and lesser chances of breaking anything.

**Comment by emkll** [comment]
> Should we remove/update the Debian packaging logic in all the packages for making them only Focal? Keeping them same will make the PR easier to review and lesser chances of breaking anything.

We should definitely remove the Xenial specific files and conditionals in the build logic where we test for Focal or Xenial, preserving only the Focal path. Our test coverage should detect any issue, provided we remove those as part of a separate commit. If that's too much in this PR, we can handle it in a separate PR.

**Comment by conorsch** [comment]
@kushaldas So far, so good! Heads up you'll need a rebase due to recent changes to CI config in https://github.com/freedomofpress/securedrop/pull/5907. Other than that, looks straightforward to press on and excise Xenial completely. :+1:

**Comment by conorsch** [comment]
@kushaldas Please take another look. I took the liberty of appending more removals, based on grepping around for "xenial" and similar strings. The results look pretty solid to me. There are a few exemptions that I've intentionally deferred:

* `molecule/{upgrade,vagrant-packager}/` we'll likely remove that entirely, but we've got it tracked in #5512 
* `install_files/ansible-base/roles/app/tasks/configure_haveged.yml` the longstanding #1584 is within reach again!
* changelog entries (we've still got the Trusty changelog around, seems reasonable to keep the Xenial one too)

Other than that, we should be covered here. If you agree, please mark as ready-for-review, and I'll give it a final close look!

**Comment by kushaldas** [comment]
Still can not figure out why are we seeing this particular CI failure due to the `rebase-ci.sh` file. The correct is present, screenshot below.

Screenshot from 2021-04-29 15-45-48

**Comment by conorsch** [comment]
Looks like CI is passing now—I'll take another look!

**Review by conorsch — CHANGES_REQUESTED** [review]
Pretty complete here, the only missing changes I can point out are some of the EOL strings still present in the JI templates. See comment in-line. Once those changes are made, we'll need to update the strings queued up for translation, to remove the associated strings from the `.po`. I tried that locally, via `make translate`, but encountered an error, so I didn't push up any changes. Please take a look and see if you can round it out, @kushaldas.

If you'd prefer to follow up on the strings changes separately, then I'll say explicitly that the rest of the PR looks good to me!

**Comment by kushaldas** [comment]
@conorsch I just now pushed the change with journalist template update and also updated strings for translation.

**Review by conorsch — APPROVED** [review]
Looks great! Thanks for adding the string changes!

**Pull request merged**
