### PR TITLE
Fix i18n_tool's list-translators function

### PR DESCRIPTION
**Pull request by rmol**
## Status

Ready for review

## Description of Changes

I needed to update it for my change to the commit format at 0.13.0, and the commit range examined for recent contributions needed to be improved to look until the last sync from Weblate.

## Testing

- Check out this branch.
- Run `make list-translators`. The output should only contain the contributors since the last Weblate sync (0aa921908). You can compare the list for a given language with a command like:
```
git log --format="%aN" 0aa921908..i18n/i18n securedrop/translations/ca/LC_MESSAGES/messages.po | sort | uniq
```
(Substitute the language you want to check for `ca` in the path.)

- Run `make list-all-translators`. Each language's contributor list should match the output of this:
```
git log --format="%aN:%s" i18n/i18n securedrop/translations/nl/LC_MESSAGES/messages.po | grep "Translated using Weblate" | sort | uniq | awk -F: '{print $1}'
```
Again, replace `ca` with the code you're trying to check.

## Deployment

The `list-translators` function should not affect deployment, but it's possible, so all tests should pass.

### If you made changes to the server application code:

- [x] Linting (`make lint`) and tests (`make -C securedrop test`) pass in the development container

### If you made non-trivial code changes:

- [x] I have written a test plan and validated it for this PR

### CODE REVIEW

**Comment by kushaldas** [comment]
Tests timedout, rerunning.

**Comment by kushaldas** [comment]
I can see the `replies` id as the test is expecting, digging more. 

i_can_see_replies_id

**Comment by kushaldas** [comment]
If I put a `time.sleep(5)` before that assertion, it goes to next and fails again.

```

/home/kdas/code/securedrop/securedrop/tests/functional/test_source.py:20: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <tests.functional.test_source.TestSourceInterface object at 0x7fc8f6c48550>

    def _source_sees_no_codename(self):
        codename = self.driver.find_elements_by_css_selector(".code-reminder")
        time.sleep(60)
>       assert len(codename) == 0
E       AssertionError

```

**Comment by kushaldas** [comment]
If I check manually then I don't see any codename, as shown in the screenshot below.

no_codename

But, the VNC for the test shows that there is a codename in the same page.

why_codename

**Comment by zenmonkeykstop** [comment]
Output of provided git command doesn't match output of make:

- for `make list-translators`, Thalia Rahme is listed under `ar` but using git commands is listed under `ca`
- for `make list-all-translators` there are several other listings that are swapped or just appear in either make or git output.

**Comment by rmol** [comment]
Thanks @zenmonkeykstop.  I think the `list-all-translators` discrepancies might be due to i18n_tool.py looking at the `.po` files for both the app and the desktop icons -- I only provided an example git command for checking the app `.po` file. So for example, one person contributed to the Spanish desktop icon translation (`install_files/ansible-base/roles/tails-config/templates/es_ES.po`), so shows up in `list-all-translators`, but wouldn't appear in the history of `securedrop/translations/es_ES/LC_MESSAGES/messages.po`.

I cannot explain how you saw Thalia Rahme under Catalan, though. I can't see a contribution from her to anything but Arabic in the git history. Could you leave the git command you used here?

**Comment by zenmonkeykstop** [comment]
That checks out as an explanation - I was using the given git commands, concatenating results for all languages. Not able to reproduce the Arabic/Catalan discrepancy now, going to put it down to an issue with the concatenation. Good to go.

**Pull request merged**
