### PR TITLE
doc: documentation_guidelines: clone before pip install

### PR DESCRIPTION
**Pull request by dachary**
## Status

Ready for review

## Description of Changes

Cloning the repository must be done before accessing the files it
contains.

### CODE REVIEW

**Comment by garrettr** [comment]
@dachary Can you provide an explanation of why you think this change should be made? You didn't include an initial description, nor did you mention a related issue. We prefer all pull requests be associated with an issue as much as possible.

In addition, I would argue that your changes might not be desirable. You are correct in noting that `develop-requirements.txt` includes the dependencies for building the documentation; however, it also includes additional dependencies which are only useful if you are working on the code. The Documentation Guidelines intentionally only specify the subset of dependencies necessary for working on the documentation, since we have some contributors who _only_ contribute to the documentation.

You could argue that having multiple approaches here is unnecessary, or confusing, or could be improved—a good place to have such a discussion would be a new GitHub issue.

**Comment by dachary** [comment]
@garrettr sorry for the terse pull request. I inverted the instructions because you can't pip install from a file that is found in the git repository unless you first clone said repository ;-)

**Comment by fowlslegs** [comment]
Sorry for the delay between approval and comment. Just got interrupted by our daily stand-up.

It would be helpful if you started making use of the PR template @dachary, even if you just use the commit message(s) as the description. Feel free to strip out the irrelevant sections: usually you only need about 2 to 4 of them (e.g., https://github.com/freedomofpress/securedrop/pull/1830 uses 3).

> In addition, I would argue that your changes might not be desirable. You are correct in noting that develop-requirements.txt includes the dependencies for building the documentation; however, it also includes additional dependencies which are only useful if you are working on the code. The Documentation Guidelines intentionally only specify the subset of dependencies necessary for working on the documentation, since we have some contributors who only contribute to the documentation.

> You could argue that having multiple approaches here is unnecessary, or confusing, or could be improved—a good place to have such a discussion would be a new GitHub issue.

I'm not sure what you're trying to say @garrettr as the docs here already instruct docs contributors to install the `development-requirements.txt`. There is no `docs-contributor-requirements.txt` file, so people are already instructed to install the "addditional dependencies which are only useful if you are working on the code." This commits just putting two instructions in their intended order, without changing the content of the instructions, or how we group development dependencies.

**Comment by garrettr** [comment]
> I'm not sure what you're trying to say @garrettr as the docs here already instruct docs contributors to install the development-requirements.txt.

My mistake, I was looking at the stable documentation at the time: https://docs.securedrop.org/en/stable/development/documentation.html. It lists the specific `pip` dependencies to install and does not mention `develop-requirements.txt`.

**Comment by dachary** [comment]
@garrettr @fowlslegs updated the PR description with a minimal part from the template, apologies for being lazy on this one.

**Pull request merged**
