### PR TITLE
Update smtp.gmail.com fingerprint

### PR DESCRIPTION
**Pull request by garrettr**
The certificate was rotated this morning, as SMTP delivery with the old
fingerprint was working during some testing I was doing yesterday afternoon.

This is a temporary fix that allows staging environments to continue working by default. A long-term fix for this problem is tracked in #1076

### CODE REVIEW

**Comment by dolanjs** [comment]
@garrettr I think you should also change it in the ossec_alerts.md otherwise looks good.

**Comment by conorsch** [comment]
Also in `spec_tests/spec/mon-staging/ossec_server_spec.rb`.

**Comment by conorsch** [comment]
On second thought, don't update the spec tests in this PR; I'll add the change to #1070, which is still pending. Reason being that the target file has moved as of #1070 so updating the fingerprint for the tests over there will prevent a merge conflict.

**Comment by garrettr** [comment]
Rebased and merged into develop in d6f9386e9a512cadadf7b608cad199be8345fce8.

**Comment by garrettr** [comment]
Note: I merged the branch locally, then rebased and pushed. It would've been better to rebase the feature branch and push it here, _then_ merge. That would have avoided the "Closed with unmerged commits" message, and would make it easier to associate commits in the PR with commits on the develop branch.

**Pull request closed without merging**
