### PR TITLE
Fixes #5285 upgrades sphinx for developer requirements

### LINKED ISSUE #5285: Upgrade sphinx for develop requirements
## Description

This is caught by `safety` tool.

```
Checking file ./securedrop/requirements/python3/develop-requirements.txt
safety report
checked 123 packages, using default DB
---
-> sphinx, installed 1.6.3, affected <3.0.4, id 38330
Sphinx 3.0.4 updates jQuery version from 3.4.1 to 3.5.1 for security reasons.
--
Makefile:139: recipe for target 'safety' failed
make: *** [safety] Error 1
make: Leaving directory '/home/circleci/project'
```

### PR DESCRIPTION
**Pull request by kushaldas**
## Status

Ready for review

## Description of Changes

Fixes #5285 

Upgrades sphinx version.

Also adds proper code block value at 3 places in the documentation. 

## Testing

-  [ ] test `make lint` command output.

## Deployment

Any special considerations for deployment? Consider both:

1. Upgrading existing production instances.
2. New installs.

### If you made changes to the server application code:

- [ ] Linting (`make lint`) and tests (`make test`) pass in the development container

### If you made changes to `securedrop-admin`:

- [ ] Linting and tests (`make -C admin test`) pass in the admin development container

### If you made changes to the system configuration:

- [ ] [Configuration tests](https://docs.securedrop.org/en/latest/development/testing_configuration_tests.html) pass

### If you made non-trivial code changes:

- [ ] I have written a test plan and validated it for this PR

### If you made changes to documentation:

- [ ] Doc linting (`make docs-lint`) passed locally

### If you added or updated a code dependency:

Choose one of the following:

- [ ] I have performed a diff review and pasted the contents to [the packaging wiki](https://github.com/freedomofpress/securedrop-debian-packaging/wiki)
- [ ] I would like someone else to do the diff review

### CODE REVIEW

**Comment by kushaldas** [comment]
Failed with 

```
  Downloading https://files.pythonhosted.org/packages/74/3d/1ee25a26411ba0401b43c6376d2316a71addcc72ef8690b101b4ea56d76a/zipp-0.6.0-py2.py3-none-any.whl
Requirement already satisfied: pip==19.1 in /opt/venvs/securedrop-app-code/lib/python3.5/site-packages (from -r requirements/python3/develop-requirements.txt (line 694)) (19.1)
Requirement already satisfied: setuptools==46.0.0 in /opt/venvs/securedrop-app-code/lib/python3.5/site-packages (from -r requirements/python3/develop-requirements.txt (line 697)) (46.0.0)
Collecting importlib-resources; python_version < "3.7" (from pre-commit==1.18.3->-r requirements/python3/develop-requirements.txt (line 407))
ERROR: In --require-hashes mode, all requirements must have their versions pinned with ==. These do not:
    importlib-resources; python_version < "3.7" from https://files.pythonhosted.org/packages/7f/2d/88f166bcaadc09d9fdbf1c336ad118e01b7fe1155e15675e125be2ff1899/importlib_resources-1.5.0-py2.py3-none-any.whl#sha256=85dc0b9b325ff78c8bef2e4ff42616094e16b98ebd5e3b50fe7e2f0bbcdcde49 (from pre-commit==1.18.3->-r requirements/python3/develop-requirements.txt (line 407))
WARNING: You are using pip version 19.1, however version 20.1.1 is available.
```

But, it should not use that `importlib_resources` as it is marked for python < 3.7. Asked upstream `pip` for help.

**Comment by kushaldas** [comment]
Also possible error with pygments,

```

███ Linting documentation...
make[1]: Entering directory '/home/kdas/code/securedrop/docs'
rm -rf _build/*
make[1]: Leaving directory '/home/kdas/code/securedrop/docs'
Running Sphinx v3.0.4
making output directory... done
building [mo]: targets for 0 po files that are out of date
building [html]: targets for 81 source files that are out of date
updating environment: [new config] 81 added, 0 changed, 0 removed
reading sources... [100%] yubikey_setup                                                                                                                                      
looking for now-outdated files... none found
pickling environment... done
checking consistency... done
preparing documents... done
writing output... [100%] yubikey_setup                                                                                                                                       

Warning, treated as error:
/home/kdas/code/securedrop/docs/development/virtualizing_tails.rst:72:Could not lex literal_block as "python". Highlighting skipped.
make: *** [Makefile:87: docs-lint] Error 2
```

**Comment by kushaldas** [comment]
@emkll that is an excellent find. I am searching for answer/fix.

**Comment by kushaldas** [comment]
Found the issue, our theme was also million years old :D Now upgraded to a modern one. @emkll you can have a look after CI is green.

**Comment by kushaldas** [comment]
Yes, as we use a theme written by someone else, we have to use what ever they provide.

**Comment by eloquence** [comment]
No objections from me to merging this PR. The only thing I'm noticing that I would characterize as a regression due to the new theme is that links in definitions are no longer clearly identifiable due the formatting. The only page I was able to spot where this is an issue is 

https://docs.securedrop.org/en/master/development/apt_repo.html

which looks like this in the new theme:

linkregression

Note that you can no longer tell which of the headings are clickable. Otherwise, the new style does make apparent a few more existing formatting issues with our docs, such as this:

weblate-docs

This bullet list item should really not be formatted as a definition (it's bold in the old theme, which is also incorrect). So in my view there's a couple of minimal follow-up actions:
- move some links around for clarity, or otherwise work around issue above
- clear up legacy formatting issues that are now more visible

We could also override the new styling, but to minimize maintenance effort, it may be best to stick with the stock theme for now until we really replace it with something custom.

**Comment by conorsch** [comment]
Good points from @eloquence noting the slight regressions. Fine for now, let's keep an eye out for further improvements as we step through the docs prior to release.

**Pull request merged**
