### PR TITLE
Document workaround for potential `gpg --recv-key` failure

### LINKED ISSUE #1797: gpg --recv-key hangs on tails-3.0
# Bug

## Description

docs/set_up_admin_tails.rst suggests:

<pre>
    gpg --recv-key "2224 5C81 E3BA EB41 38B3 6061 310F 5612 00F4 AD77"
</pre>

but it hangs and timesout.

## Steps to Reproduce

* Install https://tails-dl.urown.net/tails/stable/tails-amd64-3.0/tails-amd64-3.0.iso with persistence and boot with an admin password.
* Connect to internet (via wifi, no firewall)
* Verify connectivity with sudo apt-get update
* Open a terminal
* $ cat /home/amnesia/.gnupg/dirmngr.conf 
use-tor
keyserver hkp://jirk5u4osbsr34t5.onion
* gpg --debug-all --recv-key "2224 5C81 E3BA EB41 38B3 6061 310F 5612 00F4 AD77"

## Expected Behavior

The key is imported.

## Actual Behavior

gpg: reading options from '/home/amnesia/.gnupg/gpg.conf'
gpg: enabled debug flags: packet mpi crypto filter iobuf memory cache memstat trust hashing ipc clock lookup extprog
gpg: DBG: [not enabled in the source] start
gpg: DBG: chan_3 <- # Home: /home/amnesia/.gnupg
gpg: DBG: chan_3 <- # Config: /home/amnesia/.gnupg/dirmngr.conf
gpg: DBG: chan_3 <- OK Dirmngr 2.1.18 at your service
gpg: DBG: connection to the dirmngr established
gpg: DBG: chan_3 -> GETINFO version
gpg: DBG: chan_3 <- D 2.1.18
gpg: DBG: chan_3 <- OK
gpg: DBG: chan_3 -> KS_GET -- 0x22245C81E3BAEB4138B36061310F561200F4AD77
gpg: keyserver receive failed: Connection timed out

## Comments

It is entirely possible I'm doing something stupid, this is my first time with tails ;-) I tried --keyserver but gpg would not accept that option.

### PR DESCRIPTION
**Pull request by garrettr**
## Status

Ready for review

## Description of Changes

I got tired of the back and forth in #1804 and I decided it would be quicker and easier to make the addition to the documentation myself. This is based on #1804, so @dachary still gets credit for his initial work.

* Resolves #1797.
* Supersedes #1804.

## Deployment

No special considerations for deployment.

### If you made changes to documentation:

- [x] Doc linting passed locally

### CODE REVIEW

**Comment by fowlslegs** [comment]
As noted in https://github.com/freedomofpress/securedrop/pull/1804#issuecomment-308567106 this command failed for me on Tails 3 beta 4 running on hardware. I'll have to test on Tails 3 on hardware before approving.

**Comment by garrettr** [comment]
> As noted in #1804 (comment) this command failed for me on Tails 3 beta 4 running on hardware. I'll have to test on Tails 3 on hardware before approving.

@fowlslegs Remember that the keyserver pool is just that, a pool—of GPG keyservers, run by volunteers. Sometimes the pool returns a server that isn't working well, and the command fails. In this case, re-running the command usually results in a different server being chosen, and in practice this means the command might succeed. This is unfortunately a consequence of using a GPG keyserver pool in the first place—they are not, strictly speaking, reliable.

In my testing, repeated use of the HKP keyservers on Tails 3 typically resulted in failure, although I did actually see it a few times. I ran `journalctl -e` simultaneously and noted that there were a number of errors related to DNS resolution being output during `gpg --recv-key` with the HKP keyserver pool. I decided not to spend time digging into it further to determine the underlying cause. When I tested `--recv-key` with the HKPS keyserver pool multiple times, I did not see these errors, which lead me to believe it is probably the more reliable choice. Sorry; I should've documented that in this issue, or in #1804, but since I didn't have a solid explanation for the behavior I was seeing I decided not to.

If, in your testing, you reliably have issues using the HKPS server when testing on Tails 3 _stable_, then I would say the proposed workaround in this issue deserves reconsideration. Otherwise, I think it should be acceptable.

I would additionally note that, unless it is totally unreliable, HKPS is naturally preferable to HKP because it tunnels HKP over HTTPS, which provides additional benefits for privacy and integrity.

**Comment by fowlslegs** [comment]
Just wanted to be safe on this one in terms of successfully testing before approving, but I think you're probably right regarding the general unreliability of keyservers being the culprit in why it failed in my previous testing.

I have a Tails 3 stable image almost ready for testing on hardware. Will try multiple times if it fails at first this time.

**Comment by conorsch** [comment]
Tested the following commands in Tails 3 (final, not beta or rc). For the most part, all of the commands discussed completed successfully, but I was able to manage a single fail on the default command, so the changes proposed here make sense. Results of testing are below. Between testing rounds, I bounced the tor service to ensure a new circuit to the keyservers. Between gpg invocations, I deleted the key from the local keyring (not that that's strictly necessary).

### Round 1

* :white_check_mark: `gpg --recv-key "2224 5C81 E3BA EB41 38B3 6061 310F 5612 00F4 AD77"`
* :white_check_mark: `gpg --keyserver hkps://hkps.pool.sks-keyservers.net --recv-key "2224 5C81 E3BA EB41 38B3 6061 310F 5612 00F4 AD77"`
* :white_check_mark: `gpg --keyserver hkp://pool.sks-keyservers.net --recv-key "2224 5C81 E3BA EB41 38B3 6061 310F 5612 00F4 AD77"`

### Round 2
* :white_check_mark: `gpg --recv-key "2224 5C81 E3BA EB41 38B3 6061 310F 5612 00F4 AD77"`
* :white_check_mark: `gpg --keyserver hkps://hkps.pool.sks-keyservers.net --recv-key "2224 5C81 E3BA EB41 38B3 6061 310F 5612 00F4 AD77"`
* :white_check_mark: `gpg --keyserver hkp://pool.sks-keyservers.net --recv-key "2224 5C81 E3BA EB41 38B3 6061 310F 5612 00F4 AD77"`

### Round 3
* :red_circle:  `gpg --recv-key "2224 5C81 E3BA EB41 38B3 6061 310F 5612 00F4 AD77"`
* :white_check_mark: `gpg --keyserver hkps://hkps.pool.sks-keyservers.net --recv-key "2224 5C81 E3BA EB41 38B3 6061 310F 5612 00F4 AD77"`
* :white_check_mark: `gpg --keyserver hkp://pool.sks-keyservers.net --recv-key "2224 5C81 E3BA EB41 38B3 6061 310F 5612 00F4 AD77"`

On the failed run, error output was:

```
gpg: WARNING: Tor is not properly configured
gpg: keyserver receive failed: Permission denied
```
So the proposed changes LGTM for merge. As a sidenote, I think the Admin install docs are extremely note-heavy, with nearly as much text in pop-out blocks as is present in inline prose, but that's best handled elsewhere.

**Comment by fowlslegs** [comment]
I tried `gpg --keyserver hkps://hkps.pool.sks-keyservers.net --recv-key "2224 5C81 E3BA EB41 38B3 6061 310F 5612 00F4 AD77"` thrice and it worked each time. I also tried the default command thrice with three successes.

**Comment by fowlslegs** [comment]
The only possible change I would consider is to add to the note that sometimes you just have to try more than once because of the nature of SKS pools. Good to merge with or without that addition though, so already gave me :white_check_mark:.

**Comment by garrettr** [comment]
> The only possible change I would consider is to add to the note that sometimes you just have to try more than once because of the nature of SKS pools.

@fowlslegs I agree, and just pushed a commit that adds that suggestion to the tip in the admin docs. Requested a re-review from you.

**Comment by fowlslegs** [comment]
I figure you want to rebase, so I'm not going to merge.

**Pull request merged**
