### PR TITLE
Updated securedrop-keyring version to 0.1.6

### PR DESCRIPTION
**Pull request by zenmonkeykstop**
## Status
Ready for review

## Description of Changes

This version of the securedrop-keyring package includes an updated signing public key with an expiration of 2023-07-04.

## Testing

- [x] Import key locally, ensure the expiration date and uid are set correctly
- [x] Verify key only has the new 2021 key 
- [x] Import keyring locally, ensure expiration date and uid are set correctly
- [x] Verify keyring only has the new 2021 key
- [x] Verify old tags can be verified using the new key  
- [x] Can sign and verify test file using new key 
- [x] CI should pass

## Deployment

After this is merged we'll:

- [ ] Upload key to keys.openpgp.org
- [ ] Update key on securedrop.org
- [ ]  update WKD config on freedom.press
- [ ] (if time allows) backport into 2.4.0 release or (if time forbids) issue a point release containing the new pubkey only.

### If you made changes to the system configuration:

- [ ] [Configuration tests](https://docs.securedrop.org/en/latest/development/testing_configuration_tests.html) pass

### If you made non-trivial code changes:

- [x] I have written a test plan and validated it for this PR

### CODE REVIEW

**Review by legoktm — CHANGES_REQUESTED** [review]
Extended expiry looks good, but I thought we had discussed having it not land on a major US holiday? 2023-07-05 is a Wednesday, I think that would be a better option?
```
user@dev ~/g/f/securedrop> gpg --import ./install_files/ansible-base/roles/install-fpf-repo/files/fpf-signing-key-2021.pub
gpg: key 188EDD3B7B22E6A3: "SecureDrop Release Signing Key <securedrop-release-key-2021@freedom.press>" 2 new signatures
gpg: Total number processed: 1
gpg:         new signatures: 2
user@dev ~/g/f/securedrop> gpg --finger 188EDD3B7B22E6A3
pub   rsa4096 2021-05-10 [SC] [expires: 2023-07-04]
      2359 E653 8C06 13E6 5295  5E6C 188E DD3B 7B22 E6A3
uid           [ unknown] SecureDrop Release Signing Key <securedrop-release-key-2021@freedom.press>
sub   rsa4096 2021-05-10 [E] [expires: 2023-07-04]
```

~~You also need to update the `securedrop-keyring.gpg` file in the install_files/securedrop-keyring folders. From git history (c1cf240dbcb93f3c5d9441ed341798154c40f937) the command should be something like:~~

```
gpg --no-default-keyring --keyring \
        install_files/securedrop-keyring/etc/apt/trusted.gpg.d/securedrop-keyring.gpg \
        --import \
        install_files/ansible-base/roles/install-fpf-repo/files/fpf-signing-key-2021.pub
```

Oops, missed that it *was* updated.
```
user@dev ~/g/f/securedrop> gpg --delete-key 188EDD3B7B22E6A3
gpg (GnuPG) 2.2.27; Copyright (C) 2021 Free Software Foundation, Inc.
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.


pub  rsa4096/188EDD3B7B22E6A3 2021-05-10 SecureDrop Release Signing Key <securedrop-release-key-2021@freedom.press>

Delete this key from the keyring? (y/N) y
user@dev ~/g/f/securedrop> gpg --import install_files/securedrop-keyring/etc/apt/trusted.gpg.d/securedrop-keyring.gpg
gpg: key 188EDD3B7B22E6A3: public key "SecureDrop Release Signing Key <securedrop-release-key-2021@freedom.press>" imported
gpg: Total number processed: 1
gpg:               imported: 1
user@dev ~/g/f/securedrop> gpg --finger 188EDD3B7B22E6A3
pub   rsa4096 2021-05-10 [SC] [expires: 2023-07-04]
      2359 E653 8C06 13E6 5295  5E6C 188E DD3B 7B22 E6A3
uid           [ unknown] SecureDrop Release Signing Key <securedrop-release-key-2021@freedom.press>
sub   rsa4096 2021-05-10 [E] [expires: 2023-07-04]
```

LGTM, so then just the question of when we want the expiry to be..

**Comment by eloquence** [comment]
Looks good to me as well.

```
pub   rsa4096 2021-05-10 [SC] [expires: 2023-07-04]
      2359E6538C0613E652955E6C188EDD3B7B22E6A3
uid           [ unknown] SecureDrop Release Signing Key <securedrop-release-key-2021@freedom.press>
sub   rsa4096 2021-05-10 [E] [expires: 2023-07-04]
```

I was able to verify tag 2.3.0 with the updated key without issues, and I confirmed that the sha256sum matches the key @zenmonkeykstop  provided through a separate verification channel. I don't have opinions on the expiry date - we'll typically want to get the bump out well before the actual expiry, so I'm not sure it makes much of a difference in practice whether it's a holiday or not.

**Comment by legoktm** [comment]
In the case that we did miss updating some step, I would much rather give it an extra day so in the unexpected case something does break, we didn't set ourselves up for failure by having it happen on a holiday. And any issues could need manual intervention from instance admins or at least nag them with emails/alerts, which isn't that great for a holiday either.

**Comment by eloquence** [comment]
Fair points - I defer to @zenmonkeykstop on the final date for this year's bump, happy to re-check if needed.

**Comment by sssoleileraaa** [comment]
I think we should just leave the key to expire on the 4th of July, since it's already done + one day doesn't make much of a difference (but if others strongly disagree and we end up changing it, it would make sense to move it a week later or earlier, since many people take extended holiday around the 4th).

Also, in case others missed it: https://github.com/freedomofpress/securedrop/issues/6449#issuecomment-1128075006.

**Comment by zenmonkeykstop** [comment]
I agree with @eloquence on this one, this expiry date should never be a surprise or eventful. Setting it to bump on a US national holiday might actually make a bit of sense - there will be fewer users around so if something does go awry the impact will be smaller while non-US folks fix it :stuck_out_tongue:

**Review by legoktm — APPROVED** [review]
Alright then. I updated the test plan to reflect all the different ways we verified the new key/keyring files.

**Pull request merged**
