### PR TITLE
Pytest fixtures for management commands

### PR DESCRIPTION
**Pull request by heartsucker**
## Status

Ready for review

## Description of Changes

Towards #2877 

`pytest` fixtures for `test_manage.py`.

## Testing

```
make test TESTFILES=test/test_manage.py
```

### If you made changes to the server application code:

- [x] Linting (`make ci-lint`) and tests (`make -C securedrop test`) pass in the development container

### CODE REVIEW

**Comment by heartsucker** [comment]
This is a WIP, but I would like a review on the commit `pytest fixtures: test_handle_invalid_secret`. The mocking/pactching gets a little nasty because we can't use decorators in combination with `pytest`.

The other options is:

```python

def test_something(a_fixture):
    do_test_something(a_fixture)

@mock.patch('foo.bar')
def do_test_something(a_fixture, mock_foo_bar):
    # actual test here
```

Or at least I think that will work. Opinions and comments welcome.

**Comment by redshiftzero** [comment]
@heartsucker and I discussed this one in chat - he is going to look at using the [`pytest-mock` plugin](https://pypi.python.org/pypi/pytest-mock) for cases like 937a0e295b091e857074e0c174dec8c9468b9bfa

**Comment by heartsucker** [comment]
@redshiftzero dude such a good call. `pytest-mock` is so much cleaner *eeeeeeeeeee*

**Comment by heartsucker** [comment]
So codecov is super lying. There is zero difference in coverage between this branch and `develop`. *sigh*

**Comment by heartsucker** [comment]
@redshiftzero Yeah, I can yank those classes.

**Pull request merged**
