### PR TITLE
Reduce setup time per test by cloning GPG homedir

### PR DESCRIPTION
**Pull request by heartsucker**
## Status

Ready for review

## Description of Changes

Create one master GPG dir and clone it. Each GPG home creation takes ~2 seconds on my laptop, so even running a single module's tests can be minutes longer than necessary.

## Testing

Does CI pass?

### If you made changes to the server application code:

- [x] Linting (`make ci-lint`) and tests (`make -C securedrop test`) pass in the development container

### CODE REVIEW

**Comment by eloquence** [comment]
As discussed today, this requires clearer specification and technical input from the rest of the team, once that's done we can consider it for the next sprint. :)

**Comment by eloquence** [comment]
Thanks @heartsucker and sorry for the late response. We agreed that this is still potentially a worthwhile improvement if it does not cause test flakiness; adding to near-term backlog for consideration in a future sprint.

**Comment by nabla-c0d3** [comment]
A logic similar to this PR (ie. re-using the GPG directory to speed up the tests) was implemented in https://github.com/freedomofpress/securedrop/pull/5683 .

**Comment by eloquence** [comment]
This was resolved via a new, independent PR, #5683.

**Pull request closed without merging**
