### PR TITLE
tests: flake8 store.py

### PR DESCRIPTION
**Pull request by dachary**
## Status

Ready for review

## Description of Changes

Run flake8 on store.py with travis so that it stays clean, more can be added as we make progress

## Testing

Wait for travis to succeed & check the output

### CODE REVIEW

**Comment by dachary** [comment]
Adding flake8 to develop-requirements.in is for developers, I suppose travis already has it installed

**Comment by fowlslegs** [comment]
>Adding flake8 to develop-requirements.in is for developers, I suppose travis already has it installed

Travis installs them just two lines up from your change https://github.com/freedomofpress/securedrop/pull/1903/files#diff-354f30a63fb0907d4ad57269548329e3R59

**Comment by dachary** [comment]
@fowlslegs ah shoot, thanks for the tip :-)

**Comment by dachary** [comment]
travis ran flake8 store.py successfully at https://travis-ci.org/freedomofpress/securedrop/builds/248166031#L1422

**Pull request merged**
