### PR TITLE
update logo dimensions

### PR DESCRIPTION
**Pull request by harlo**
to 1000px x 1000px as per https://github.com/freedomofpress/securedrop/issues/1084

### CODE REVIEW

**Comment by conorsch** [comment]
In #1084 I recommended that the custom logo size be adjusted in the docs, in order to match the new dimensions provided by #1079. @garrettr clarified, however, that #1079 only changed the logo resolution of the file used in the docs, _not_ the logo used in the actual web interface. Therefore I don't think these changes are necessary right now, although that might change if we decide to update the logo used in the web interface to match the higher-quality, transparent one used in the docs.

**Comment by harlo** [comment]
that's fine-- it can stay on the back burner until then...

**Comment by harlo** [comment]
...and orange you glad it's in a separate PR?

**Comment by conorsch** [comment]
Textbook example of git fu!

**Comment by garrettr** [comment]
Yeah, `500px x 450px` is still the preferred resolution IMHO. Closing this for now.

**Pull request closed without merging**
