### PR TITLE
Stores Trusty & Xenial deb packages side by side

### LINKED ISSUE #3961: [xenial] Support branched Trusty/Xenial packaging build logic
Debian packages should be stored in `build/trusty` or `build/xenial`, depending on build target. We need to clean up build targets and directory usage to avoid clobbering.

Branched build logic is necessary because dependencies for the `securedrop-app-code` package have changed; `apache2` should be explicitly required; `apache2-mpm-worker` should be omitted.

Part of #3204.

### LINKED ISSUE #4051: Flaky container timeouts when building deb packages
## Description

The `make build-debs` target occasionally emits errors on build, related to the `gather_facts` step run by Ansible after container creation.

## Steps to Reproduce

Run `make build-debs` five times. You'll likely get a failure at least once. If you don't, I want to know!

## Expected Behavior

`make build-debs` completes reliably without error. (Not counting the test failure notifying about unapplied apt updates). 

## Actual Behavior

`make build-debs` emits an error:

```
    PLAY [Build SecureDrop application Debian package from local repository.] ******
    
    TASK [Gathering Facts] *********************************************************
    An exception occurred during task execution. To see the full traceback, use -vvv. The error was: TimeoutError: Timer expired after 10 seconds
    fatal: [trusty-sd-app]: FAILED! => {"changed": false, "cmd": "/sbin/udevadm info --query property --name /dev/mapper/Tyr--vg-root", "msg": "Timer expired after 10 seconds", "rc": 257}                                                                                                                                                                     
    ok: [trusty-sd-config]
    ok: [trusty-sd-generic-ossec-agent]
    ok: [trusty-sd-sec-update]
    ok: [trusty-sd-generic-ossec-server]
    changed: [trusty-sd-generic-ossec-server] => (item=/tmp/build/ossec-server)
    ok: [trusty-sd-generic-ossec-server] => (item=/tmp/build)
```

## Comments
It's not reliable _which_ container fails, so it feels rather like a race condition. It may be heavy load that contributes to the timeout, but even with no other applications running, I can generate the error. Have tested both Debian Stretch and Qubes for build host, and the problem exists on both.

Seems to be related to the Ansible version upgrade (#3945), where this problem was first reported. We may be able to bump the gather_facts timeout to accommodate. Removing build parallelism (by excising the `strategy: free` param in the build playbook) reduces the frequency of the failure, but is not a perfect solution.

### PR DESCRIPTION
**Pull request by conorsch**
## Status

Work in progress.

## Description of Changes

Fixes #3961. Fixes #4051.

Changes proposed in this pull request:

* **Removes tor-apt repo** ; tor debs are now stored in a single, consolidated apt repo
* Adds customization of `securedrop-app-code` package for discrete dependencies under Trusty & Xenial
* Builds Xenial debs inside Xenial container
* Deb packages are now stored in subdirs: `build/trusty/` and `build/xenial/`. 

## Testing

Given the magnitude of changes here, we must confirm that both staging and prod environments are fully functioning, on both Trusty and Xenial. 

### Staging environment
* [ ] `make build-debs && make staging` passes without error
* [ ] All infra tests pass `molecule verify -s {libvirt,virtualbox}-staging` 
* [ ] `make build-debs-xenial && make staging-xenial` passes without error
* [ ] All infra tests pass `molecule verify -s {libvirt,virtualbox}-staging-xenial` 

** Note that due to https://github.com/freedomofpress/securedrop/issues/3916 some PaX-related tests might fail, and there should be a note referring to that issue in the output.
### Production environment
```
vagrant box add bento/ubuntu-16.04
# Ensure you have vagrant mutate installed
vagrant plugin install vagrant-mutate
vagrant mutate bento/ubuntu-16.04 libvirt
```

If testing xenial, you must change the base box in the `Vagrantfile`: replace `bento/ubuntu-14.04` with `bento/ubuntu-16.04` for `app-prod` and `mon-prod`

```
vagrant up --no-provision /prod/
```

In Tails, update the vars to use the `apt-test` server. Specifically, that entails:
1. In `install_files/ansible-base/roles/install-fpf-repo/defaults/main.yml`, set  `apt_repo_url: https://apt-test.freedom.press` 
2. `cp install_files/ansible-base/roles/install-fpf-repo/files/{apt-test-signing-key,fpf-signing-key}.pub`

Then, proceed with testing. Confirm the following in your report:

* [ ] Clean installation (prod vms) on Xenial using `apt-test.freedom.press` completes without error (Basic server testing is successful)
* [ ] Clean installation (prod vms) on Trusty using `apt-test.freedom.press` completes without error (Basic server testing is successful)

## Deployment

At present, the "xenial" apt channel is only served up from non-prod URLs. We'll update the prod config to do the same as part of the 0.12.0 release.

Developers can now retain platform-specific deb packages built from the develop branch for faster iteration on testing the Xenial migration. 

### Visual review
- [ ] Ensure the logic and changes introduced in this pr are sound

### If you made changes to `securedrop-admin`:

- [X] Linting and tests (`make -C admin test`) pass in the admin development container

### If you made changes to the system configuration:

- [X] [Configuration tests](https://docs.securedrop.org/en/latest/development/testing_configuration_tests.html) pass

### If you made non-trivial code changes:

- [x] I have written a test plan and validated it for this PR

### If you made changes to documentation:

- [x] Doc linting (`make docs-lint`) passed locally

### CODE REVIEW

**Comment by emkll** [comment]
Clean install on Trusty looks good with current apt setup:
```
vagrant@app-prod:~$ apt-cache policy tor
tor:
  Installed: 0.3.4.9-1~trusty+1
  Candidate: 0.3.4.9-1~trusty+1
  Version table:
 *** 0.3.4.9-1~trusty+1 0
        500 https://apt-test-xenial.freedom.press/ trusty/main amd64 Packages
        100 /var/lib/dpkg/status
     0.3.2.10-1~trusty+1 0
        500 https://apt-test-xenial.freedom.press/ trusty/main amd64 Packages
     0.2.4.27-1ubuntu0.1 0
        500 http://archive.ubuntu.com/ubuntu/ trusty-updates/universe amd64 Packages
        500 http://security.ubuntu.com/ubuntu/ trusty-security/universe amd64 Packages
     0.2.4.20-1 0
        500 http://archive.ubuntu.com/ubuntu/ trusty/universe amd64 Packages
vagrant@app-prod:~$ apt-cache policy securedrop-app-code
securedrop-app-code:
  Installed: 0.12.0~rc1+trusty
  Candidate: 0.12.0~rc1+trusty
  Version table:
 *** 0.12.0~rc1+trusty 0
        500 https://apt-test-xenial.freedom.press/ trusty/main amd64 Packages
        100 /var/lib/dpkg/status
     0.11.1 0
        500 https://apt-test-xenial.freedom.press/ trusty/main amd64 Packages
     0.11.0 0
        500 https://apt-test-xenial.freedom.press/ trusty/main amd64 Packages
     0.10.0 0
        500 https://apt-test-xenial.freedom.press/ trusty/main amd64 Packages
     0.9.1 0
        500 https://apt-test-xenial.freedom.press/ trusty/main amd64 Packages
     0.9.0 0
        500 https://apt-test-xenial.freedom.press/ trusty/main amd64 Packages
vagrant@app-prod:~$ apt-cache policy ossec-agent   
ossec-agent:
  Installed: 3.0.0
  Candidate: 3.0.0
  Version table:
 *** 3.0.0 0
        500 https://apt-test-xenial.freedom.press/ trusty/main amd64 Packages
        100 /var/lib/dpkg/status
     2.8.2 0
        500 https://apt-test-xenial.freedom.press/ trusty/main amd64 Packages
```

**Comment by conorsch** [comment]
Ready for review! Looking for input from @kushaldas in particular. See the test plan above. Given the large amount of testing (staging & prod under both Trusty & Xenial), consider breaking up the testing work with e.g. @zenmonkeykstop. Perhaps @kushaldas can take the staging environments, and @zenmonkeykstop the prod.

**Comment by conorsch** [comment]
@kushaldas Those failures look an awful lot like #3916 to me—mind posting a comment over there? It may be that the problem doesn't occur on Xenial boxes, in which case we can remove the strict setting on those tests. I suspect the ultimate solution is still to reorder the role includes, otherwise tests passing is dependent on the build time of the box, which certainly isn't what we want.

@zenmonkeykstop Thanks for flagging the `havaged` profile; see https://github.com/freedomofpress/securedrop/commit/017ba1fae490a6056300d2195a15f74490ab9d3b, which came in as part of #3833. We could shoehorn addressing that into #3964, but we should probably open a dedicated issue to evaluate AppArmor policies across the board for Xenial. What do you think?

**Comment by conorsch** [comment]
Thanks for re-review, @kushaldas!

**Pull request merged**
