### PR TITLE
update builder image to version tagged 2023_02_22

### PR DESCRIPTION
**Pull request by zenmonkeykstop**
## Status

Ready for review 
## Description of Changes

Towards #6749 .

Updates builder image to version tagged 2023_02_22.

## Testing

- [x] CI is passing
- [x] `make build-debs` passes locally.

### CODE REVIEW

**Review by cfm — CHANGES_REQUESTED** [review]
Alas, @zenmonkeykstop, it looks like `libxpm4` is a late-breaking update!

https://app.circleci.com/pipelines/github/freedomofpress/securedrop/5518/workflows/abcd03d6-3443-4fec-8a6a-5362cd4fcdfa/jobs/67616?invite=true#step-104-360

**Comment by zenmonkeykstop** [comment]
rebuilt, let's hope we don't have to escalate to a full al(as|ack).

**Review by cfm — CHANGES_REQUESTED** [review]
Still showing `libxpm4`.

https://app.circleci.com/pipelines/github/freedomofpress/securedrop/5519/workflows/63b06771-7783-457a-86c5-84e0580c2994/jobs/67619?invite=true#step-104-356

**Review by cfm — APPROVED** [review]
Third time's the charm!  CI is happy and so is `make build-debs`.

**Pull request merged**
