### PR TITLE
Ditch Travis CI in favor of Circle CI

### LINKED ISSUE #2790: Remove Travis from CI runner
# Feature request

## Description

We've moved a lot of functionality out of Travis and into Circle. I think it's finally time to take Travis out of the CI equation. It's more difficult to maintain both environments consistently and it's more debug work for us lonely ops folks.

## User Stories

As a CircleCI sales person, I want SecureDrop to no longer use Travis and stick with CircleCI.

### PR DESCRIPTION
**Pull request by redshiftzero**
## Status

Ready for Review

## Description of Changes

Fix #2790. 

## Testing

Does circle CI pass?

## Deployment

CI only

### If you made changes to documentation:

- [x] Doc linting passed locally

### CODE REVIEW

**Comment by msheiny** [comment]
rebased on develop, sprinkled in some fixes to hopefully address #2800

**Comment by msheiny** [comment]
hey @redshiftzero -- looks like im causing the failure here... im going to revert some of my additions (rather than rebase and purge em, i might want to bring em back later - tweaked of course).

**Comment by redshiftzero** [comment]
Sure, sounds good @msheiny

**Comment by msheiny** [comment]
shaking out multiple issues -- ended up rebasing this on `HotFixReduceAWSCallsCI`

**Comment by msheiny** [comment]
For historical reference -- this PR also took over #2882 and #2886 in an effort to quickly stabilize CI on this day of our SecureDrop 2018

**Comment by conorsch** [comment]
This one got a bit cluttered, but it's because we've got multiple CI issues at present, and in order to evaluate one we've got to patch the other in order to get working builds. Fortunately, the great work of fixing CI has been accomplished—at least for today. 

Looks like we're now closing both #2790 and #2881.

**Comment by redshiftzero** [comment]
Merging!

**Pull request merged**
