### PR TITLE
Creates Xenial staging scenario

### LINKED ISSUE #3206: [xenial] Add staging VMs for Ubuntu 16.04
Part of https://github.com/freedomofpress/securedrop/issues/3204 (Xenial epic):

In order for developers to be able to test the installation of SecureDrop on Ubuntu 16.04 (Xenial), we should add optional staging VMs specifically for that purpose. These should not interfere in any way with the development or production environment.

Most likely candidate is bento/ubuntu-16.04.

### PR DESCRIPTION
**Pull request by conorsch**
## Status

Ready for review.

## Description of Changes

Closes #3206. 

Changes proposed in this pull request:

* Creates new Xenial-based staging scenarios for libvirt and virtualbox (not implemented for Qubes yet).
* Tweaks Ansible logic to support overrides of apt repo channels, so we can install "trusty" packages on "xenial" hosts for debugging
* Slightly modifies dependencies for `securedrop-app-code` _when Xenial support is enabled_. 
* Created new Makefile targets `staging-xenial` and `build-debs-xenial`. 
* Wrote docs to explain the above

The install flow is not perfect here—errors _will_ be encountered periodically. Still, the goal here is to provide a foothold for developers to start fixing these errors in a way that preserves Trusty compatibility. As such, 

## Testing
1. Confirm `make build-debs` has all tests passing (packaging behavior should not change).
2. Confirm `make build-debs-xenial` emits a `securedrop-app-code` package that has modified dependencies; specifically, `apache2` is now explicitly included, and `apache2-mpm-worker` is omitted.
3. Run `make staging-xenial` and report how far the install gets. It won't get all the way to the end; at the very least, the `apache2-mpm-worker` is still re-included in the Ansible logic (which can probably be removed, given the deb package dependencies). 
4. Re-run `make staging-xenial` and see if the install gets further than last time.

Review the docs presented and comment if any additional changes should be made. Tried to cross-link with prior research efforts to begin centralizing the upcoming fix-it tasks as we push toward Xenial support.

## Deployment

Shouldn't be, but requires testing. Some tweaks (off-by-default) were made to packaging logic, and minor adjustments to the Ansible logic. All were intended to preserve the existing default behavior when run against Trusty.

### If you made changes to the server application code:

- [ ] Linting (`make ci-lint`) and tests (`make -C securedrop test`) pass in the development container

### If you made changes to `securedrop-admin`:

- N/A

### If you made changes to the system configuration:

- [ ] [Configuration tests](https://docs.securedrop.org/en/latest/development/testing_configuration_tests.html) pass (Yes, changes were made here, but the config tests don't support Xenial yet; I suggest we defer to a future ticket)

### If you made non-trivial code changes:

- [x] I have written a test plan and validated it for this PR

### If you made changes to documentation:

- [x] Doc linting (`make docs-lint`) passed locally

### CODE REVIEW

**Comment by conorsch** [comment]
@kushaldas points out that folks'll need to mutate the 16.04 boxes for use with libvirt, same as we've documented for the 14.04 boxes. Please run through that setup locally, @kushaldas, and comment here with any additional commands you needed to run in order to review!

**Comment by kushaldas** [comment]
@conorsch It reaches to the step it should (installing the `apache2-mpm-worker`) package and then it fails as it should.

**Comment by redshiftzero** [comment]
Just discussed this with @conorsch briefly, let's keep #3206 open until we resolve the remaining failing config tests here

**Comment by redshiftzero** [comment]
Just kidding - @eloquence filed #3825 to track this :-)

**Comment by redshiftzero** [comment]
One more thing: can you make sure to write out any clarifications / additional steps that were necessary for review @kushaldas? Both in the spirit of ensuring that as much as possible is captured in GitHub/async comms and for posterity.

**Comment by msheiny** [comment]
> Re-run make staging-xenial and see if the install gets further than last time.

heyy @conorsch can you clarify the scope of this testing plan? What is expected to fail and what is expected to pass? As-is, the playbook will continually fail each time cause of the ansible install logic -- if thats expected thats okay with me.. i just wanted to know what you were looking for as conditions for approval here.

**Comment by msheiny** [comment]
*cough* i mean it will continually fail at the piece you mentioned in ansible.. the apache dependencies. which you made a note/comment about.

**Comment by conorsch** [comment]
> The install flow is not perfect here—errors will be encountered periodically. Still, the goal here is to provide a foothold for developers to start fixing these errors in a way that preserves Trusty compatibility

@msheiny The fact that you're able to spin up the Xenial VMs and target them with Ansible, log in to debug, is sufficient for approval here. Regarding the failures, yes, they're to be expected. I'll shortly be following up with a PR for #3825 which should resolve both the Ansible errors and the config test failures.

> the apache dependencies.

Yes, the forthcoming PR will resolve that, as well—at least, it'll allow us to get past it. I look forward to your thoughts on the implementation during review. :wink:

**Pull request merged**
