### PR TITLE
tests: squelch gnupg debug messages

### LINKED ISSUE #2595: Remove annoying GPG debug output
# Description

On a test failure there is a ton of annoying debug output, e.g. [this build](https://travis-ci.org/freedomofpress/securedrop/builds/302385185). Let's remove this. 

## User Stories

As a SecureDrop developer, I want test failure output to help me identify the issues leading to the failure, not obfuscate them.

### PR DESCRIPTION
**Pull request by tmc**
## Status

Ready for Review

## Description of Changes

Fixes #2595 

Changes proposed in this pull request:
separates gnupg logging level management from app verbosity.

## Testing

How should the reviewer test this PR?
run 
```sh
pytest -s -v
```
and compare to
```sh
GNUPG_LOG_LEVEL=INFO pytest -s -v
```

## Deployment
N/A

### CODE REVIEW

**Comment by dachary** [comment]
When we run **./manage.py** from the command line, it is not in debug mode. I'm not sure where **pyttest** sets all logging to debug mode. I don't remember this is a default and it's not obvious when reading **securedrop/tests/conftest.py**. Any idea ?

**Comment by tmc** [comment]
Not certain offhand but can try to track that down.

**Comment by dachary** [comment]
It may make sense to disable verbosity in **pytest** instead of **manage.py**, don't you think ?

**Comment by tmc** [comment]
I suspect the i18n tests are triggering the debug messages in gnupg but haven't confirmed. A number of them call the setup_verbosity helper in manage.py which is why I was led there. Perhaps we have enough control in conftest.py to control it there. Not super familiar with they pytest executables entry/control points.

**Comment by tmc** [comment]
Changed to do this in conftest.py but this is insufficient -- test_manage.py ends up triggering DEBUG output in gnupg when it runs (and it appears to persist). Marking WIP.

**Comment by dachary** [comment]
> test_manage.py ends up turning gnupg back up to DEBUG output hen it runs. 

I suppose
<pre>
logging.getLogger(__name__).setLevel(logging.DEBUG)
</pre>
does not limit itself to the manager.py script as it should, when in the context of pytest ?

**Comment by tmc** [comment]
Good news! I believe I was mistaken about it persisting. https://circleci.com/gh/freedomofpress/securedrop/4062 you can review full verbose output here.

**Comment by dachary** [comment]
I think it's good to merge. Would you mind adding a note about GNUPG_LOG_LEVEL=INFO and GNUPG_LOG_LEVEL=DEBUG in the documentation ? Around
<pre>
Some Selenium tests are decorated to produce before and after screenshots to aid
</pre>
would be good enough.

**Comment by tmc** [comment]
@dachary good call. pushing a diff now that adds some basic doc mention.

**Comment by dachary** [comment]
@tmc I opened https://github.com/freedomofpress/securedrop/issues/2616 to report the CircleCI error but ... I wonder why the run [seems to be in your name](https://circleci.com/gh/tmc/securedrop/344?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link) ?

**Comment by dachary** [comment]
@tmc I re-pushed your PR changing nothing but the hash of the last commit to verify the unrelated CircleCI shows again (or not ;-).

**Comment by redshiftzero** [comment]
Changes merged in #2619. Thanks again @tmc

**Pull request closed without merging**
