### PR TITLE
Provide 0.12.2 upgrade boxes 

### LINKED ISSUE #4329: Upgrade scenario fails on develop
## Description

Running upgrade scenario on `develop` returns the following error:
```
    TASK [app-test : Install pip dependencies for running the unit and functional tests.] ***
    fatal: [app-staging]: FAILED! => {"msg": "The task includes an option with an undefined variable. The error was: 'securedrop_code' is undefined\n\nThe error appears to have been in '/tmp/molecule/securedrop/upgrade/sd-orig/install_files/ansible-base/roles/app-test/tasks/dev_setup_xvfb_for_functional_tests.yml': line 2, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n---\n- name: Install pip dependencies for running the unit and functional tests.\n  ^ here\n"}
    
    NO MORE HOSTS LEFT *************************************************************
    
    NO MORE HOSTS LEFT *************************************************************
    
    PLAY RECAP *********************************************************************
    app-staging                : ok=4    changed=2    unreachable=0    failed=1   
    mon-staging                : ok=2    changed=1    unreachable=0    failed=0
    
    
ERROR: 
Makefile:175: recipe for target 'upgrade-test-local' failed
```

## Steps to Reproduce

1. git checkout develop
2. make build-debs
3. make upgrade-start
4. make upgrade-test-local

## Expected Behavior

Upgrade scenario should complete without error.

## Actual Behavior

Upgrade scenario returns error (see above)

## Comments

It appears that reverting 102afb57bcf4798cd466001b9aaeec1bf1a58577 resolves the issue for me locally.

### LINKED ISSUE #4338: Release SecureDrop 0.12.2
This is a tracking issue for the upcoming release of SecureDrop 0.12.2 - tasks may get added or modified. 

**Feature freeze:** EOD Pacific time, Tuesday, April 16
**String freeze:** EOD Pacific time, Tuesday, April 16
**Pre-release announcement:** N/A - point releases will not have pre-release announcements
**Release date:** EOD Pacific time, Thursday, April 25

**Release manager:** @emkll
**Deputy release manager:** @rmol  
 
_SecureDrop maintainers and testers:_ As you QA 0.12.2, please report back your testing results as comments on this ticket. File GitHub issues for any problems found, tag them "QA: Release", and associate them with the 0.12.2 milestone for tracking (or ask a maintainer to do so). 

Test debian packages will be posted on https://apt-test.freedom.press signed with [the test key](https://gist.githubusercontent.com/conorsch/ec4008b111bc3142fca522693f3cce7e/raw/2968621e8ad92db4505a31fcc5776422d7d26729/apt-test%2520apt%2520pubkey). An Ansible playbook testing the upgrade path is [here](https://gist.github.com/conorsch/e7556624df59b2a0f8b81f7c0c4f9b7d).

# Prepare release candidate (0.12.2~rc1)
- [x] Prepare 0.12.2-rc1 release changelog - @emkll  
- [x] Branch off release/0.12.1 into release/0.12.2 - @emkll 
- [x] Build debs (including new Tor package) and put up `0.12.2~rc1` on test apt server - @rmol   

# Prepare release candidate (0.12.2~rc2)
- [x] Prepare 0.12.2-rc2 release changelog - @emkll  
- [x] Build debs (including new Tor package) and put up `0.12.2~rc1` on test apt server - @rmol   

# [QA Matrix for 0.12.2](https://docs.google.com/spreadsheets/d/1Ha6qKm2hYjoQQ2HTFvLmZ8tknm2jv76oBslpzOfT4Wg/edit?usp=sharing)
# [Test Plan for 0.12.2](https://github.com/freedomofpress/securedrop/wiki/0.12.2-Test-Plan)

After each test, please update the QA matrix and post details for Basic Server Testing, Application Acceptance Testing and 0.12.2-specific testing below in comments to this ticket.

# Final release
- [x] Ensure builder in release branch is updated and/or update builder image - @emkll
- [x] Push signed tag - @redshiftzero / @emkll
- [x] Build final Debian packages for 0.12.2 (including Tor packages) - @conorsch 
- [x] Upload Debian packages to apt-qa - @conorsch 
- [x] Pre-Flight: Test install and upgrade (both cron-apt on Trusty, and Ansible on Xenial) of 0.12.2 works w/ prod repo debs - @rmol @kushaldas @zenmonkeykstop @emkll 
- [x] Pre-Flight: Test GUI Updater @zenmonkeykstop @kushaldas @emkll 
- [x] Prepare and distribute release messaging - @eloquence 
- [x] Update GitHub release object - @redshiftzero 

# Post release

- [x] Merge changelog back to `develop` - @rmol #4389  
- [ ] Update upgrade testing boxes - @emkll (might be blocked on https://github.com/freedomofpress/securedrop/issues/4329) 
- [x] Update roadmap wiki page - @eloquence

### PR DESCRIPTION
**Pull request by emkll**
## Status

Work in progress : we need to finish uploading historical boxes to the new s3 bucket and update URLs in this PR

## Description of Changes

Closes #4338, closes #4329.

Changes proposed in this pull request:

## Testing

- checkout this branch
- run `make build-debs`
- [ ] `make upgrade-start` pulls in the newly-built 0.12.2 box (see Source Interface)
- [ ] `make upgrade-test-local` upgrades the box to 0.13.0~rc1 without error (see Source Interface)
- [ ] `make upgrade-trusty-start` pulls in the newly-built 0.12.2 box (see Source Interface)
## Deployment

Developer environment only

### If you made non-trivial code changes:

- [x] I have written a test plan and validated it for this PR

### CODE REVIEW

**Comment by conorsch** [comment]
@msheiny is already working on pushing up the historical images to the new bucket. Once that's done, let's update the all the URLs in the JSON files to use the new bucket, then we should be ready for final review.

**Comment by emkll** [comment]
Thanks for updating the links @msheiny , this should be now ready for review !

**Comment by conorsch** [comment]
Confirmed _most_ of the test plan so far, still need to run the Trusty steps just to be sure. Will circle back on that tomorrow.

**Comment by conorsch** [comment]
- checkout this branch
- run `make build-debs`
- [x] `make upgrade-start` pulls in the newly-built 0.12.2 box (see Source Interface)
- [x] `make upgrade-test-local` upgrades the box to 0.13.0~rc1 without error (see Source Interface)
- [ ] :large_orange_diamond: `make upgrade-trusty-start` pulls in the newly-built 0.12.2 box (see Source Interface)

The Trusty boxes pulled successfully. Given that building Trusty packages no longer works, due to dependency changes in #4297, the `make upgrade-trusty-start` action reports failure before the Source Interface comes up. I copied over the Xenial packages to satisfy the package discovery logic, and 0.12.2 running on Trusty came up successfully: the Source Interface showed the "We're sorry, our SecureDrop is currently offline" message.

**Pull request merged**
