### PR TITLE
Merge 0.5.1 changes into master

### PR DESCRIPTION
**Pull request by redshiftzero**
## Status

Ready for review

## Description of Changes

Resolves final checkbox in #2813

## Testing

Do you notice any issues with how conflicts were resolved? 

## Deployment

Already in prod

### If you made changes to the app code:

- [x] Unit and functional tests pass on the development VM

### If you made changes to the system configuration:

- [ ] [Configuration tests](https://docs.securedrop.org/en/latest/development/testing_configuration_tests.html) pass

### CODE REVIEW

**Comment by redshiftzero** [comment]
Here were the conflicts manually resolved:

```
CONFLICT (content): Merge conflict in securedrop/version.py
CONFLICT (content): Merge conflict in securedrop/translations/pt_BR/LC_MESSAGES/messages.po
CONFLICT (content): Merge conflict in securedrop/translations/nl/LC_MESSAGES/messages.po
CONFLICT (content): Merge conflict in securedrop/translations/nb_NO/LC_MESSAGES/messages.po
CONFLICT (content): Merge conflict in securedrop/translations/messages.pot
CONFLICT (content): Merge conflict in securedrop/translations/fr_FR/LC_MESSAGES/messages.po
CONFLICT (content): Merge conflict in securedrop/translations/es_ES/LC_MESSAGES/messages.po
CONFLICT (content): Merge conflict in securedrop/translations/de_DE/LC_MESSAGES/messages.po
CONFLICT (modify/delete): securedrop/translations/ar/LC_MESSAGES/messages.po deleted in HEAD and modified in release/0.5.1. Version release/0.5.1 of securedrop/translations/ar/LC_MESSAGES/messages.po left in tree.
CONFLICT (content): Merge conflict in securedrop/tests/test_journalist.py
CONFLICT (content): Merge conflict in molecule/builder/tests/vars.yml
CONFLICT (content): Merge conflict in install_files/securedrop-ossec-server/DEBIAN/control
CONFLICT (content): Merge conflict in install_files/securedrop-ossec-agent/DEBIAN/control
CONFLICT (content): Merge conflict in install_files/securedrop-keyring/DEBIAN/control
CONFLICT (content): Merge conflict in install_files/securedrop-app-code/usr/share/doc/securedrop-app-code/changelog.Debian
CONFLICT (content): Merge conflict in install_files/securedrop-app-code/DEBIAN/control
CONFLICT (content): Merge conflict in install_files/ansible-base/roles/tails-config/templates/desktop-source-icon.j2
CONFLICT (content): Merge conflict in install_files/ansible-base/roles/tails-config/templates/desktop-journalist-icon.j2
CONFLICT (modify/delete): install_files/ansible-base/roles/tails-config/templates/ar.po deleted in HEAD and modified in release/0.5.1. Version release/0.5.1 of install_files/ansible-base/roles/tails-config/templates/ar.po left in tree.
CONFLICT (content): Merge conflict in install_files/ansible-base/group_vars/all/securedrop
CONFLICT (content): Merge conflict in docs/set_up_admin_tails.rst
CONFLICT (content): Merge conflict in docs/development/i18n.rst
CONFLICT (content): Merge conflict in docs/conf.py
CONFLICT (content): Merge conflict in changelog.md
```

**Comment by conorsch** [comment]
Thanks for reporting the conflicts explicitly, @redshiftzero—that's a lot of conflicts. I'll run through the merge locally in disposable branches and confirm that I see what you see. I'd like to understand why all those control files are conflicting....

**Comment by dachary** [comment]
hum, something's not right, I'm curious to understand why

**Comment by dachary** [comment]
release/0.5 is the same as origin/master, there is that
<pre>
$ git --no-pager  log --oneline --cherry-mark --right-only origin/master...origin/release/0.5
*nothing*
</pre>

But there are a few commits from release/0.5 that are *not* in develop

<pre>
$ git --no-pager  log --oneline --cherry-mark --right-only origin/develop...origin/release/0.5
= e4fded23 SecureDrop 0.5
+ 37ccc263 Merge pull request #2676 from freedomofpress/wip-dachary-0.5-arabic
= 3906f5e4 Tests: Remove 'ar' from test_render_locales
+ 31ac7411 Fix tests after pulling out Arabic translations
= c6cc6f58 l18n: arabic is postponed to the next version
= a426c2a9 SecureDrop 0.5-rc6
+ 267f50eb Merge pull request #2672 from freedomofpress/wip-i18n
= 1799e4c4 l10n: sync ar de_DE es_ES fr_FR nb_NO nl pt_BR translations
</pre>

**Comment by dachary** [comment]
I think the following happened:

* After 0.5 was released we forgot to merge release/0.5 back to develop. I proposed merges back to develop on a daily basis during the release cycle. But I did not do it **after** the release was published
* We never noticed the missing files commits because we did not review translations while developing and that all updates to weblate incorporated the latest translations because it is based on a fork.
* We notice the problem now because the translations in master were never commited to develop.

For the translations the right way to resolve the problem is to unconditionally use the files from the release/0.5.1 branch.
<pre>
CONFLICT (content): Merge conflict in securedrop/translations/pt_BR/LC_MESSAGES/messages.po
CONFLICT (content): Merge conflict in securedrop/translations/nl/LC_MESSAGES/messages.po
CONFLICT (content): Merge conflict in securedrop/translations/nb_NO/LC_MESSAGES/messages.po
CONFLICT (content): Merge conflict in securedrop/translations/messages.pot
CONFLICT (content): Merge conflict in securedrop/translations/fr_FR/LC_MESSAGES/messages.po
CONFLICT (content): Merge conflict in securedrop/translations/es_ES/LC_MESSAGES/messages.po
CONFLICT (content): Merge conflict in securedrop/translations/de_DE/LC_MESSAGES/messages.po
CONFLICT (modify/delete): securedrop/translations/ar/LC_MESSAGES/messages.po deleted in HEAD and modified in release/0.5.1. Version release/0.5.1 of securedrop/translations/ar/LC_MESSAGES/messages.po left in tree.
</pre>

**Comment by dachary** [comment]
The remainder of the divergence between develop and master is this (removed the files owned by weblate for clarity):
<pre>
$ git --no-pager  diff --stat origin/develop...origin/master
 .travis.yml                                                                          |    3 +-
 changelog.md                                                                         |    4 +-
 docs/conf.py                                                                         |    4 +-
 docs/development/i18n.rst                                                            |    4 +-
 docs/install.rst                                                                     |    1 -
 docs/set_up_admin_tails.rst                                                          |    4 +-
 install_files/ansible-base/group_vars/all/securedrop                                 |    2 +-
 install_files/ansible-base/securedrop-configure.yml                                  |    2 +-
 install_files/securedrop-app-code/DEBIAN/control                                     |    2 +-
 install_files/securedrop-app-code/usr/share/doc/securedrop-app-code/changelog.Debian |   28 +-
 install_files/securedrop-keyring/DEBIAN/control                                      |    2 +-
 install_files/securedrop-ossec-agent/DEBIAN/control                                  |    2 +-
 install_files/securedrop-ossec-server/DEBIAN/control                                 |    2 +-
 molecule/builder/tests/vars.yml                                                      |    2 +-
 securedrop/test                                                                      |    2 +-
 securedrop/tests/test_journalist.py                                                  |    2 +-
 securedrop/version.py                                                                |    2 +-
</pre>

**Comment by dachary** [comment]
Although we added Arabic in 0.5.1, we also did not add it to the page-layout tests, reason why there is no conflict and if we had, it would be the same sooooo, no harm done here.

<pre>
diff --git a/.travis.yml b/.travis.yml
index 690a19f3..70769e4d 100644
--- a/.travis.yml
+++ b/.travis.yml
@@ -47,8 +47,7 @@ script:
   # are time consuming.
   # * en_US: source strings
   # * fr_FR: left-to-right translations
-  # * ar: right-to-left translations
-  - sh -c "export DISPLAY=:1 ; cd securedrop && PAGE_LAYOUT_LOCALES='en_US,ar,fr_FR' pytest -v tests --page-layout"
+  - sh -c "export DISPLAY=:1 ; cd securedrop && PAGE_LAYOUT_LOCALES='en_US,fr_FR' pytest -v tests --page-layout"
   - pip freeze -l
   - SECUREDROP_TESTINFRA_TARGET_HOST=travis testinfra -v testinfra/development/
 after_success:
</pre>

**Comment by dachary** [comment]
The following files are version change only such as
<pre>
-securedrop_version: "0.5-rc5"
+securedrop_version: "0.5"
 </pre>
the diff from release/0.5.1 are unconditional used to resolve the conflict:

<pre>
changelog.md
docs/conf.py
docs/set_up_admin_tails.rst
install_files/ansible-base/group_vars/all/securedrop
install_files/securedrop-app-code/DEBIAN/control
install_files/securedrop-keyring/DEBIAN/control
install_files/securedrop-ossec-agent/DEBIAN/control
install_files/securedrop-ossec-server/DEBIAN/control
securedrop/version.py
</pre>

**Comment by dachary** [comment]
install_files/securedrop-app-code/usr/share/doc/securedrop-app-code/changelog.Debian does not contain useful information or history and the version from release/0.5.1 can prevail.

<pre>
--- a/install_files/securedrop-app-code/usr/share/doc/securedrop-app-code/changelog.Debian
+++ b/install_files/securedrop-app-code/usr/share/doc/securedrop-app-code/changelog.Debian
@@ -1,32 +1,8 @@
-securedrop-app-code (0.5-rc5) trusty; urgency=medium
+securedrop-app-code (0.5) trusty; urgency=medium
 
   * See changelog.md
 
- -- SecureDrop Team <securedrop@freedom.press>  Sun, 03 Dec 2017 02:21:03 +0000
-
-securedrop-app-code (0.5-rc4) trusty; urgency=medium
-
-  * See changelog.md
-
- -- SecureDrop Team <securedrop@freedom.press>  Sat, 02 Dec 2017 07:19:35 +0000
-
-securedrop-app-code (0.5-rc3) trusty; urgency=medium
-
-  * See changelog.md
-
- -- SecureDrop Team <securedrop@freedom.press>  Fri, 01 Dec 2017 01:30:56 +0000
-
-securedrop-app-code (0.5-rc2) trusty; urgency=medium
-
-  * See changelog.md
-
- -- SecureDrop Team <securedrop@freedom.press>  Wed, 29 Nov 2017 19:59:52 +0000
-
-securedrop-app-code (0.5-rc1) trusty; urgency=medium
-
-  * See changelog.md 
-
- -- SecureDrop Team <securedrop@freedom.press>  Wed, 29 Nov 2017 00:36:28 +0000
+ -- SecureDrop Team <securedrop@freedom.press>  Tue, 05 Dec 2017 17:39:00 +0000
 
 securedrop-app-code (0.4.4) trusty; urgency=medium
 
</pre>

**Comment by dachary** [comment]
The remainer of the files are about removing the Arabic translation because it was not ready and for all of them the version from release/0.5.1 should prevail since Arabic was restored.

<pre>
diff --git a/docs/development/i18n.rst b/docs/development/i18n.rst
index a609c7b3..1453fd7f 100644
--- a/docs/development/i18n.rst
+++ b/docs/development/i18n.rst
@@ -152,7 +152,7 @@ to the ``develop`` branch via pull requests for merge on a regular basis.
       $ git fetch lab
       $ git checkout -b wip-i18n origin/develop
       $ git checkout lab/i18n -- securedrop/translations \
-        install_files/ansible-base/roles/tails-config/templates/{ar,nl,fr,de_DE,nb_NO,pt_BR,es_ES}.po
+        install_files/ansible-base/roles/tails-config/templates/{nl,fr,de_DE,nb_NO,pt_BR,es_ES}.po
       $ git add translations
       $ vagrant ssh development
       $ cd /vagrant/securedrop ; ./manage.py --verbose translate-desktop --compile
@@ -165,7 +165,7 @@ Verify the translations are not broken:
 
       $ vagrant ssh development
       $ cd /vagrant/securedrop
-      $ PAGE_LAYOUT_LOCALES='ar,de_DE,es_ES,fr_FR,nb_NO,nl,pt_BR' \
+      $ PAGE_LAYOUT_LOCALES='de_DE,es_ES,fr_FR,nb_NO,nl,pt_BR' \
           pytest -v --page-layout tests/pages-layout
 
 Go to https://github.com/freedomofpress/securedrop and propose a pull request.
diff --git a/docs/install.rst b/docs/install.rst
index 3e405f06..21b7baab 100644
--- a/docs/install.rst
+++ b/docs/install.rst
@@ -31,7 +31,6 @@ Localization of the source and journalist interfaces
 The source and journalist interface are translated in the following
 languages:
 
-* Arabic (ar)
 * German (de_DE)
 * Spanish (es_ES)
 * French (fr_FR)
diff --git a/install_files/ansible-base/securedrop-configure.yml b/install_files/ansible-base/securedrop-configure.yml
index 535269a4..0c08eb16 100644
--- a/install_files/ansible-base/securedrop-configure.yml
+++ b/install_files/ansible-base/securedrop-configure.yml
@@ -112,7 +112,7 @@
 
     - name: securedrop_supported_locales
       # the list is from the securedrop/translations repository
-      prompt: Space separated list of additional locales to support (ar de_DE en_US es_ES fr_FR nb_NO nl)
+      prompt: Space separated list of additional locales to support (de_DE en_US es_ES fr_FR nb_NO nl)
       default: ""
       private: no
 
diff --git a/securedrop/test b/securedrop/test
index b15e71a5..38d98425 100755
--- a/securedrop/test
+++ b/securedrop/test
@@ -19,7 +19,7 @@ trap cleanup EXIT
 
 mkdir -p "/tmp/test-results/logs"
 
-export PAGE_LAYOUT_LOCALES="en_US,ar,fr_FR"
+export PAGE_LAYOUT_LOCALES="en_US,fr_FR"
 pytest \
   --page-layout \
   --durations 10 \
diff --git a/securedrop/tests/test_journalist.py b/securedrop/tests/test_journalist.py
index 330cb563..5355766f 100644
--- a/securedrop/tests/test_journalist.py
+++ b/securedrop/tests/test_journalist.py
@@ -1198,7 +1198,7 @@ class TestJournalistApp(TestCase):
         try:
             if supported:
                 del config.SUPPORTED_LOCALES
-            config.SUPPORTED_LOCALES = ['en_US', 'fr_FR', 'ar']
+            config.SUPPORTED_LOCALES = ['en_US', 'fr_FR']
 
             source, _ = utils.db_helper.init_source()
             self._login_user()
</pre>

**Comment by dachary** [comment]
As a conclusion the conflict resolution is actually very simple: we can override any change in master with the latest from release/0.5.1. And I'll make sure release/0.5.1 is proposed to be merged back to develop this time.

I did the merge like so:
<pre>
All conflicts automatically resolved by prefering the version from
release/0.5.1 with:

   git checkout -b wip-master origin/master
   git merge -m 'merge release/0.5.1 into master' -s recursive -X theirs origin/release/0.5.1

Manually restoring deleted Arabic translation with updated version from
release/0.5.1

Conflicts:
	install_files/ansible-base/roles/tails-config/templates/ar.po
	securedrop/translations/ar/LC_MESSAGES/messages.po
</pre>

And pushed it to https://github.com/freedomofpress/securedrop/tree/wip-dachary-master for comparing with this branch:

<pre>
$ git diff --stat origin/resolve-conflicts-051-into-master origin/wip-dachary-master 
 changelog.md                                          |  16 ++++++-------
 securedrop/translations/fr_FR/LC_MESSAGES/messages.po | 102 +++++++++++++++++++++++++++++++++++++++---------------------------------------
 securedrop/translations/messages.pot                  |   1 +
 3 files changed, 60 insertions(+), 59 deletions(-)
</pre>

These are only whitespace changes but we should not have them otherwise we'll get conflicts. And the whitespace changes in the French translation are actually significant because they are small non breakable space and should not be converted to space.

**Comment by conorsch** [comment]
I was able to merge `release/0.5.1` into `master` cleanly, with no conflicts, during local testing just now. Thanks for the detailed feedback, @dachary! Are you also seeing conflicts, just fewer than @redshiftzero did? One difference _may_ be:

```
$ git config --get pull.rebase
true
```

Otherwise I expect we're running the same commands. To be clear, I tried (yes, some of these commands are redundant, just trying to be explicit):

```
git fetch
git checkout master
git pull origin master
git checkout -b try-merging-0.5.1-into-master
git merge release/0.5.1
# no conflicts
```

**Comment by dachary** [comment]
Here is what I have
<pre>
(virtualenv) loic@raise:~/software/securedrop$ git clone https://github.com/freedomofpress/securedrop s
Cloning into 's'...
remote: Counting objects: 45884, done.
remote: Compressing objects: 100% (147/147), done.
remote: Total 45884 (delta 75), reused 138 (delta 46), pack-reused 45672
Receiving objects: 100% (45884/45884), 64.99 MiB | 2.71 MiB/s, done.
Resolving deltas: 100% (30098/30098), done.
(virtualenv) loic@raise:~/software/securedrop$ cd s
(virtualenv) loic@raise:~/software/securedrop/s$ git fetch
(virtualenv) loic@raise:~/software/securedrop/s$ git checkout master
Branch master set up to track remote branch master from origin.
Switched to a new branch 'master'
(virtualenv) loic@raise:~/software/securedrop/s$ git pull origin master
From https://github.com/freedomofpress/securedrop
 * branch              master     -> FETCH_HEAD
Current branch master is up to date.
(virtualenv) loic@raise:~/software/securedrop/s$ git checkout -b try-merging-0.5.1-into-master
Switched to a new branch 'try-merging-0.5.1-into-master'
(virtualenv) loic@raise:~/software/securedrop/s$ git merge origin/release/0.5.1
Removing testinfra/vars/apptestclient.yml
Auto-merging securedrop/version.py
CONFLICT (content): Merge conflict in securedrop/version.py
Auto-merging securedrop/translations/pt_BR/LC_MESSAGES/messages.po
CONFLICT (content): Merge conflict in securedrop/translations/pt_BR/LC_MESSAGES/messages.po
Auto-merging securedrop/translations/nl/LC_MESSAGES/messages.po
CONFLICT (content): Merge conflict in securedrop/translations/nl/LC_MESSAGES/messages.po
Auto-merging securedrop/translations/nb_NO/LC_MESSAGES/messages.po
CONFLICT (content): Merge conflict in securedrop/translations/nb_NO/LC_MESSAGES/messages.po
Auto-merging securedrop/translations/messages.pot
CONFLICT (content): Merge conflict in securedrop/translations/messages.pot
Auto-merging securedrop/translations/fr_FR/LC_MESSAGES/messages.po
CONFLICT (content): Merge conflict in securedrop/translations/fr_FR/LC_MESSAGES/messages.po
Auto-merging securedrop/translations/es_ES/LC_MESSAGES/messages.po
CONFLICT (content): Merge conflict in securedrop/translations/es_ES/LC_MESSAGES/messages.po
Auto-merging securedrop/translations/de_DE/LC_MESSAGES/messages.po
CONFLICT (content): Merge conflict in securedrop/translations/de_DE/LC_MESSAGES/messages.po
CONFLICT (modify/delete): securedrop/translations/ar/LC_MESSAGES/messages.po deleted in HEAD and modified in origin/release/0.5.1. Version origin/release/0.5.1 of securedrop/translations/ar/LC_MESSAGES/messages.po left in tree.
Auto-merging securedrop/tests/test_journalist.py
CONFLICT (content): Merge conflict in securedrop/tests/test_journalist.py
Removing securedrop/static/i/flags/zh.png
Removing securedrop/static/i/flags/nl.png
Removing securedrop/static/i/flags/nb.png
Removing securedrop/static/i/flags/fr.png
Removing securedrop/static/i/flags/es.png
Removing securedrop/static/i/flags/en.png
Removing securedrop/static/i/flags/de.png
Removing securedrop/static/i/flags/br.png
Removing securedrop/static/i/flags/ar.png
Removing securedrop/sass/modules/_flag.sass
Auto-merging securedrop/sass/modules/_button.sass
Auto-merging securedrop/sass/libraries/_normalize.sass
Auto-merging securedrop/sass/libraries/_font-awesome-iconography.sass
Removing securedrop/requirements/securedrop-requirements.txt
Auto-merging securedrop/requirements/securedrop-app-code-requirements.in
Auto-merging securedrop/bin/test
Auto-merging molecule/builder/tests/vars.yml
CONFLICT (content): Merge conflict in molecule/builder/tests/vars.yml
Auto-merging molecule/aws/tests/test_tor_interfaces.py
Auto-merging install_files/securedrop-ossec-server/DEBIAN/control
CONFLICT (content): Merge conflict in install_files/securedrop-ossec-server/DEBIAN/control
Auto-merging install_files/securedrop-ossec-agent/DEBIAN/control
CONFLICT (content): Merge conflict in install_files/securedrop-ossec-agent/DEBIAN/control
Auto-merging install_files/securedrop-keyring/DEBIAN/control
CONFLICT (content): Merge conflict in install_files/securedrop-keyring/DEBIAN/control
Auto-merging install_files/securedrop-app-code/usr/share/doc/securedrop-app-code/changelog.Debian
CONFLICT (content): Merge conflict in install_files/securedrop-app-code/usr/share/doc/securedrop-app-code/changelog.Debian
Auto-merging install_files/securedrop-app-code/DEBIAN/control
CONFLICT (content): Merge conflict in install_files/securedrop-app-code/DEBIAN/control
Auto-merging install_files/ansible-base/securedrop-configure.yml
Auto-merging install_files/ansible-base/roles/tails-config/templates/desktop-source-icon.j2
CONFLICT (content): Merge conflict in install_files/ansible-base/roles/tails-config/templates/desktop-source-icon.j2
Auto-merging install_files/ansible-base/roles/tails-config/templates/desktop-journalist-icon.j2
CONFLICT (content): Merge conflict in install_files/ansible-base/roles/tails-config/templates/desktop-journalist-icon.j2
CONFLICT (modify/delete): install_files/ansible-base/roles/tails-config/templates/ar.po deleted in HEAD and modified in origin/release/0.5.1. Version origin/release/0.5.1 of install_files/ansible-base/roles/tails-config/templates/ar.po left in tree.
Removing install_files/ansible-base/roles/grsecurity/meta/main.yml
Auto-merging install_files/ansible-base/group_vars/all/securedrop
CONFLICT (content): Merge conflict in install_files/ansible-base/group_vars/all/securedrop
Auto-merging docs/set_up_admin_tails.rst
CONFLICT (content): Merge conflict in docs/set_up_admin_tails.rst
Auto-merging docs/install.rst
Removing docs/google_authenticator.rst
Auto-merging docs/development/i18n.rst
CONFLICT (content): Merge conflict in docs/development/i18n.rst
Auto-merging docs/conf.py
CONFLICT (content): Merge conflict in docs/conf.py
Auto-merging changelog.md
CONFLICT (content): Merge conflict in changelog.md
Auto-merging .travis.yml
Automatic merge failed; fix conflicts and then commit the result.
</pre>

**Comment by redshiftzero** [comment]
Ah, let's use your branch `wip-dachary-master` since it preserves the whitespace - I can close this PR

**Comment by conorsch** [comment]
> I was able to merge release/0.5.1 into master cleanly, with no conflicts, during local testing just now. 

**False.** The testing instructions I [claimed above](https://github.com/freedomofpress/securedrop/pull/2888#issuecomment-358493614) were inaccurate. Specifically, there's no `git pull` action in the terminal session, and my report inaccurately stated that step was performed. Full terminal session here for review: https://gist.github.com/conorsch/0a928c232dba646e545e661c556ba33c

While following your duplicated instructions in a clean repo, I can reproduce the conflicts you describe, @dachary. Apologies for sending you on a wild goose chase.

**Comment by redshiftzero** [comment]
Closing in favor of #2889

**Pull request closed without merging**
