### PR TITLE
Increase unit test coverage to 100% for store.py

### PR DESCRIPTION
**Pull request by redshiftzero**
## Status

Ready for review

## Description of Changes

Noticed during review of #2256 that the test coverage on `store.py` was poor, this commit increases test coverage to 100% in that file.

## Testing

1. CI should pass
2. Inspect the diff and verify the tests are correctly testing the expected behavior of the functions in `store.py`

## Deployment

Tests only

### If you made changes to the app code:

- [x] Unit and functional tests pass on the development VM

### CODE REVIEW

**Comment by redshiftzero** [comment]
This is one for @dachary and @heartsucker in particular to take a look at when time permits

**Comment by redshiftzero** [comment]
Looks like the staging failure is #2253: 

```
TASK [Wait for server to come back.] *******************************************
ok: [mon-staging -> localhost]
fatal: [app-staging -> localhost]: FAILED! => {"changed": false, "elapsed": 301, "failed": true, "msg": "Timeout when waiting for search string OpenSSH in ec2-13-56-229-10.us-west-1.compute.amazonaws.com:22"}
	to retry, use: --limit @/root/sd/install_files/ansible-base/securedrop-staging.retry
```

Restartin'

**Comment by dachary** [comment]
Coverage is not yet 100% but very close.
<pre>
store.py                                  77      0     24      2    98%   144->157, 146->157
</pre>

**Comment by redshiftzero** [comment]
Ah drat, that cursed 2%! Thanks for review :)

**Pull request merged**
