### PR TITLE
Merge 0.4.4 post-release changes into develop

### PR DESCRIPTION
**Pull request by redshiftzero**
## Status

Ready for review

## Description of Changes

Fixes one checkbox in #2474.

## Testing

Does CI pass?

## Deployment

None, these changes are already in prod: https://securedrop.org/news/securedrop-044-released

### If you made changes to the system configuration:

- [ ] [Configuration tests](https://docs.securedrop.org/en/latest/development/testing_configuration_tests.html) pass

### CODE REVIEW

**Comment by redshiftzero** [comment]
The merge commit 1732352 lists the file that had conflicts manually resolved during the merge

**Comment by emkll** [comment]
It appears this error is related to the Ansible version bump, I've reproduced it in local staging environment while trying to update the develop-requirements.

**Comment by msheiny** [comment]
b3b3b1c  -- seems to be getting us farther *fingers crossed* -- seems like it was a conflict with ansible 2.3+ and our forked synchronize module. That was needed when we were running under <ansible 2.3 which had a lot of missing functionality.

**Comment by msheiny** [comment]
>    TASK [Dump instance config] ****************************************************
    Thursday 02 November 2017  19:55:23 +0000 (0:00:00.042)       0:01:10.755 *****
    An exception occurred during task execution. To see the full traceback, use -vvv. The error was: RepresenterError: cannot represent an object: 54.183.244.219
    fatal: [localhost]: FAILED! => {"failed": true, "msg": "Unexpected failure during module execution.", "stdout": ""}
    
I saw this the other day... think I got a fix for it. Its probably molecule related.

**Comment by redshiftzero** [comment]
Thanks @heartsucker @msheiny !

**Pull request merged**
