### PR TITLE
i18n: add flags for a few more languages

### PR DESCRIPTION
**Pull request by dachary**
## Status

Ready for review

## Description of Changes

Slightly adapted from:

https://www.sketchappsources.com/free-source/823-flag-set-sketch-freebie-resource.html

## Testing

* vagrant ssh development
* cd /vagrant/securedrop
* add **SUPPORTED_LOCALES = ['es_ES', 'nb_NO', 'nl', 'ar', 'fr_FR', 'zh_Hant', 'en_US']** in config.py
* ./manage.py run
* firefox http://localhost:8080
* verify that all locales have a flag when clicking on the menu

a

## Deployment

None

### If you made changes to the app code:

- [x] Unit and functional tests pass on the development VM

### CODE REVIEW

**Comment by dachary** [comment]
@toast the flags are also sorted now in the CSS file to facilitate maintenance

**Comment by dachary** [comment]
also added the menu to the journalist interface

**Comment by redshiftzero** [comment]
*Note:* Testers will need to make `zh_Hant` and `es_ES` folders in the translations directory or the app will bail out

**Comment by dachary** [comment]
@redshiftzero nice catch with the apparmor !

**Pull request merged**
