### PR TITLE
Add upgrade boxes for SecureDrop 1.1.0

### LINKED ISSUE #4887: Release SecureDrop 1.1.0
This is a tracking issue for the upcoming release of SecureDrop 1.1.0 - tasks may get added or modified. 

**String and feature freeze:** 2019-10-08 (1700 PDT)
**String comment period:** 2019-10-08 (1700 PDT) to 2019-10-15 (2000 PDT)
**Feature freeze:** 2019-10-08 (1700 PDT) (release branch will be cut AM Eastern time on September 3rd)
**Translation period:** 2019-10-08 (1700 PDT) to 2019-10-18 (1700 PDT)
**Pre-release announcement:** 2019-10-15
**Translation freeze:** 2019-10-18 (1700 PDT)
**Release date:** 2019-10-21

**Release manager:** @kushaldas  
**Deputy release manager:** @emkll 
**Localization manager:** @rmol
**Deputy localization manager:** @redshiftzero 
 
_SecureDrop maintainers and testers:_ As you QA 1.1.0, please report back your testing results as comments on this ticket. File GitHub issues for any problems found, tag them "QA: Release", and associate them with the 1.1.0 milestone for tracking (or ask a maintainer to do so). 

Test debian packages will be posted on https://apt-test.freedom.press signed with [the test key](https://gist.githubusercontent.com/conorsch/ec4008b111bc3142fca522693f3cce7e/raw/2968621e8ad92db4505a31fcc5776422d7d26729/apt-test%2520apt%2520pubkey). An Ansible playbook testing the upgrade path is [here](https://gist.github.com/conorsch/e7556624df59b2a0f8b81f7c0c4f9b7d).

# [QA Matrix for 1.1.0](https://docs.google.com/spreadsheets/d/1fxjwa1rzVSHT3jrdQMBQeUXWsIb6IrW1pRKwBmUPtzk/edit#gid=0)

# [Test Plan for 1.1.0](https://github.com/freedomofpress/securedrop/wiki/1.1.0-Test-plan)

# Prepare release candidate (1.1.0~rc1)
- [x] Prepare 1.1.0-rc1 release changelog - @emkll   
- [x] Branch off release/1.1.0 - @redshiftzero  
- [x] Prepare 1.1.0~rc1 - @emkll 
- [x] Build debs and put up `1.1.0~rc1` on test apt server (this is now done via a PR into [this repository](https://github.com/freedomofpress/securedrop-dev-packages-lfs)) - @emkll
- [x] Commit build logs to https://github.com/freedomofpress/build-logs - @emkll 

# Prepare release candidate (1.1.0~rc2)
- [x] Prepare 1.1.0-rc2 release changelog - @emkll   
- [x] Prepare 1.1.0~rc2 - @emkll 
- [x] Build debs and put up `1.1.0~rc2` on test apt server (this is now done via a PR into [this repository](https://github.com/freedomofpress/securedrop-dev-packages-lfs)) - @emkll
- [x] Commit build logs to https://github.com/freedomofpress/build-logs - @emkll 

# Prepare release candidate (1.1.0~rc3)
- [x] Prepare 1.1.0-rc3 release changelog - @kushaldas   
- [x] Prepare 1.1.0~rc3 - @kushaldas  
- [x] Build debs and put up `1.1.0~rc3` on test apt server (this is now done via a PR into [this repository](https://github.com/freedomofpress/securedrop-dev-packages-lfs)) - @emkll
- [ ] Commit build logs to https://github.com/freedomofpress/build-logs - @emkll I forgot :(

# Prepare release candidate (1.1.0~rc4)
- [x] Prepare 1.1.0-rc4 release changelog - @emkll    
- [x] Prepare 1.1.0~rc4 - @emkll   
- [x] Build debs and put up `1.1.0~rc4` on test apt server (this is now done via a PR into [this repository](https://github.com/freedomofpress/securedrop-dev-packages-lfs)) - @emkll : https://github.com/freedomofpress/securedrop-dev-packages-lfs/pull/19
- [x] Commit build logs to https://github.com/freedomofpress/build-logs - @emkll

# Prepare release candidate (1.1.0~rc5)
- [x] Prepare 1.1.0-rc5 release changelog - @emkll    
- [x] Prepare 1.1.0~rc5 - @emkll   
- [x] Build debs and put up `1.1.0~rc5` on test apt server (this is now done via a PR into [this repository](https://github.com/freedomofpress/securedrop-dev-packages-lfs)) - @emkll
- [x] Commit build logs to https://github.com/freedomofpress/build-logs - @emkll

# Other pre-release tasks

- [x] Prepare and distribute pre-release messaging - @eloquence 

After each test, please update the QA matrix and post details for Basic Server Testing, Application Acceptance Testing and 1.1.0-specific testing below in comments to this ticket.

# Final release
- [x] Ensure builder in release branch is updated and/or update builder image - @emkll 
- [x] Merge final translations @rmol 
- [x] Push signed tag @emkll 
- [x] Build final Debian packages for 1.1.0 (and preserve build logs) @conorsch 
- [x] Commit package build logs to https://github.com/freedomofpress/build-logs @conorsch : https://github.com/freedomofpress/build-logs/blob/master/core/20191021-securedrop-1.1.0.log
- [x] Upload Debian packages to apt QA server @conorsch 
- [x] Pre-Flight: Test install and upgrade (both cron-apt on Xenial, and Ansible on Xenial) of 1.1.0 works w/ prod repo debs, test updater logic in Tails @zenmonkeykstop @redshiftzero @emkll 
- [x] Prepare and distribute release messaging @eloquence 

# Post release
- [x] Create GitHub release object @emkll 
- [x] Merge changelog back to `develop`
- [x] Bump version on `develop` in prep for 1.2.0 release
- [ ] Update upgrade testing boxes
- [x] Update roadmap wiki page @emkll

### PR DESCRIPTION
**Pull request by emkll**
## Status

Ready for review
## Description of Changes

Closes #4887 

Add upgrade boxes for SecureDrop 1.1.0
## Testing
- make upgrade start
- [ ] Source interface is accessible over Tor v3 service and version string is 1.1.0
- make build-debs
- [ ] make upgrade-test-local succeeds
- [ ] Source and journalist interfaces come up, version string is 1.2.0~rc1
## Deployment

Dev env only

### If you made non-trivial code changes:

- [x] I have written a test plan and validated it for this PR

### CODE REVIEW

**Comment by kushaldas** [comment]
My Vagrant + libvirt + molecule setup decided not to play together :(

**Comment by redshiftzero** [comment]
hey @kushaldas - can you explain what problem(s) you encountered so that we can try to resolve them?

**Comment by kushaldas** [comment]
> can you explain what problem(s) you encountered so that we can try to resolve them?

Just regular odd molecule + vagrant + libvirt errors. 

For example:

```
### 2019-10-24 12:20:06 ###
### 2019-10-24 12:20:06 ###
An action 'up' was attempted on the machine 'app-staging',
but another process is already executing an action on the machine.
Vagrant locks each machine for access by only one process at a time.
Please wait until the other Vagrant process finishes modifying this
machine, then try again.

If you believe this message is in error, please check the process
listing for any "ruby" or "vagrant" processes and kill them. Then
try again.

```

```
### 2019-10-24 12:20:19 ###
### 2019-10-24 12:20:19 ###
Volume for domain is already created. Please run 'vagrant destroy' first.
```

Everytime for a different VM in the molecule run, means again trying to clean up first and then trying to re-run the whole scenario (make upgrade-start). `molecule destroy -s upgrade` or other destroy commands also can not shutdown vms properly and make the system un-usable (same behavior from last year).

**Comment by redshiftzero** [comment]
can you provide steps to reproduce for getting to either of those error messages? I think it's worth identifying if the challenge here is insufficient documentation, upstream issues, or shortcomings of our development environments that we should resolve.

**Comment by rmol** [comment]
@kushaldas I've had the same sort of trouble with Vagrant, though I'm not sure if libvirt shares any of the blame. I'm pretty sure I saw this back when I was using Vagrant and Virtualbox. As the error message suggests, I can usually get the Molecule commands to complete after killing those stuck processes. And sometimes cleaning up in virt-manager or virsh.

**Comment by kushaldas** [comment]
>can you provide steps to reproduce for getting to either of those error messages? I think it's worth identifying if the challenge here is insufficient documentation, upstream issues, or shortcomings of our development environments that we should resolve.

I don't see any proper reproducer, sometimes it happens with any `molecule converge` command and sometimes it does not.

**Comment by rmol** [comment]
OK. I'll try to review this.

**Comment by conorsch** [comment]
Ran through the test plan here to evaluate libvirt behavior. Encountered no problems running the VM tooling. Further changes appear to be required, however. Results of testing:

- make upgrade start
- [x] Source interface is accessible over Tor v3 service and version string is 1.1.0
- make build-debs
- [x] make upgrade-test-local succeeds
- [x] Source and journalist interfaces come up, version string is 1.2.0~rc1

There was a small tweak required for Ansible 2.7 compatibility, specifically within the `upgrade` scenario, which I've pushed. 

Regarding the libvirt problems reported above, that's most likely related to Molecule's use of an "ephemeral" directory for tracking VM state. During "create/converge" actions, Molecule writes YAML files containing VM information to `/tmp/`. After a reboot, that state info will be destroyed, but the VM volumes will still exist in libvirt's directories. So a subsequent "create/converge" action will result in Molecule requesting a new VM be created, but libvirt will refuse, since it's already aware of a volume matching the requested name. To resolve, use `virt-manager` to clean up old VMs, or run `virsh` and purge the volumes manually. To prevent the issue, make sure to clean up VMs when you're done with them. For example, after using the upgrade scenario: `molecule destroy -s upgrade`.

**Pull request merged**
