### PR TITLE
Vendor pretty_bad_protocol

### LINKED ISSUE #6807: Vendor pretty-bad-protocol and strip it down to what is needed
https://github.com/isislovecruft/python-gnupg is unmaintained these days and we've monkeypatched it a bit. Part of migrating to Sequoia is to move away from this library. But we will need bits of it around for the online migration of secret keys (#6802), so we should simply vendor it and strip it down to only what we need.

We can also get rid of the monkeypatching at this time and treat it as SecureDrop-owned code instead of upstream.

### PR DESCRIPTION
**Pull request by legoktm**
## Status

Ready for review

## Description of Changes

Vendor pretty_bad_protocol and apply minimal fixes to get it to pass CI. Then remove our monkey patching from EncryptionManager.

Each commit should have a description of what is happening and why.

Fixes #6807.

## Testing

How should the reviewer test this PR?

* [x] CI passes
* [x] Basic smoke test in dev environment, submit a message/file, and then decrypt it as a journalist
* [x] Basic smoke test in a staging/prod environment (to verify apparmor, etc.), submit a message/file, and then decrypt it as a journalist

## Deployment

Any special considerations for deployment? Just the standard-ish ones.

## Checklist

- [x] Linting (`make lint`) and tests (`make test`) pass in the development container
- [x] I have updated AppArmor rules to include the change
- [ ] I have written a test plan and validated it for this PR
- [x] These changes do not require documentation

### CODE REVIEW

**Comment by legoktm** [comment]
I still need to verify this in staging, but everything else seems to check out.

**Comment by legoktm** [comment]
okay it's broken in staging/prod >.> debugging...

**Comment by legoktm** [comment]
> okay it's broken in staging/prod >.> debugging...

I had forgotten to add the new folder to `d/securedrop-app-code.install` so it wasn't even in the package. Fixed now and looks good on staging.

**Comment by legoktm** [comment]
```
Jun 13 19:30:19 app kernel: [55802.309949] audit: type=1400 audit(1686684619.955:22): apparmor="DENIED" operation="open" profile="/usr/sbin/apache2" name="/var/www/securedrop/pretty_bad_protocol/" pid=135658 comm="apache2" requested_mask="r" denied_mask="r" fsuid=33 ouid=0
Jun 13 19:30:19 app kernel: [55802.322290] audit: type=1400 audit(1686684619.967:23): apparmor="DENIED" operation="open" profile="/usr/sbin/apache2" name="/var/www/securedrop/pretty_bad_protocol/" pid=135659 comm="apache2" requested_mask="r" denied_mask="r" fsuid=33 ouid=0
```

stupid me, I didn't add the directory itself to apparmor, just the individual files. Really should get around to scripting this...

**Review by eaon — APPROVED** [review]
I did not expect vendoring pbp to feel good, but this feels good. Great work!

**Pull request merged**
