### PR TITLE
Backport 7175

### PR DESCRIPTION
**Pull request by zenmonkeykstop**
## Status

Ready for review

## Description of Changes

Backport of #7175.

## Testing

* [x] CI is passing
* [x] base is `release/2.9.0`
* [x] Only contains changes from #7175.

### CODE REVIEW

**Review by cfm — APPROVED** [review]
Looks good pending CI and #7183:

```sh-session
user@sd:~/securedrop$ git checkout backport-7175
Switched to branch 'backport-7175'
Your branch is up to date with 'origin/backport-7175'.
user@sd:~/securedrop$ git merge --no-commit origin/6933-pow
Automatic merge went well; stopped before committing as requested
user@sd:~/securedrop$ git diff 
user@sd:~/securedrop$ git diff --cached
diff --git a/Makefile b/Makefile
index 9aaf058df..c8b7d3d3d 100644
--- a/Makefile
+++ b/Makefile
@@ -188,6 +188,7 @@ safety:  ## Run `safety check` to check python dependencies for vulnerabilities.
                --ignore 67599 \
                --ignore 70612 \
                --ignore 71064 \
+               --ignore 70895 \
                --full-report -r $$req_file \
                && echo -e '\n' \
                || exit 1; 
```

**Comment by cfm** [comment]
Actually, @zenmonkeykstop, it looks like this is blocked on (rebase after) #7183.

**Comment by zenmonkeykstop** [comment]
> Actually, @zenmonkeykstop, it looks like this is blocked on (rebase after) #7183.

OK, will sort it out once the other lands.

**Review by cfm — APPROVED** [review]
The only diff in <https://github.com/freedomofpress/securedrop/compare/3368edaa4d6c13949735641bdc7fd47728c8b2c7..5eaa469d5e6363c90aed441e433c8fbf091f19e7> is #7183.

**Pull request merged**
