### PR TITLE
Converts Vagrantfile to Molecule for staging

### PR DESCRIPTION
**Pull request by conorsch**
## Status

Ready for review.

## Description of Changes

Progress towards #3208. So far, only the libvirt scenario has been ported. We also need support for VirtualBox, which should be straightforward. I propose sprinkling a wee wrapper into the mix, so that we can have a `make staging` that will work on Virtualbox, Libvirt, or Qubes (#3624), as appropriate.

There's also a small change in here to satisfy #3629, which should work equally well in prod and staging environments, with the same logic applicable to staging regardless of developer OS. 

The major win will come when we integrate the config tests into Molecule, as well as begin testing against Xenial as an additional platform. Those changes are not presented here, but will open up shortly.

### Libvirt
**Requires a libvirt-enabled workstation.** 

1. Run `make staging`. 
2. Confirm it defaults to the libvirt scenario, based on stdout.
3. Confirm zero errors during provisioning.
4. Log into app: `molecule login -s libvirt-staging -h app-staging`
5. View source interface in Tor Browser, confirm it's working well.

### Qubes
**Requires a Qubes workstation.**

1. Run `make staging`.
2. Confirm it defaults to the Qubes scenario, based on stdout.
3. When machines reboot, run `qvm-start sd-app sd-mon` in `dom0` or an Admin-API-enabled dev VM, so bring the standalone machines back up.
4. Confirm final reboot task does not error out, as it did in #3629.

### VirtualBox
**Recommended testing machine: a Mac laptop.** You can also try setting `VAGRANT_DEFAULT_PROVIDER=virtualbox` beforehand, then following the steps below.
1. Run `make staging`.
2. Confirm it defaults to the VirtualBox scenario, based on stdout. 
3. Confirm zero errors during provisioning.
4. Log into app: `molecule login -s virtualbox-staging -h app-staging`
5. View source interface in Tor Browser, confirm it's working well.

## Deployment
Yes, the reboot tweak should be tested against prod VMs in Tails. All other changes are dev-env-only, so far.

### If you made changes to the server application code:

- [ ] Linting (`make ci-lint`) and tests (`make -C securedrop test`) pass in the development container

### If you made changes to `securedrop-admin`:

- [ ] Linting and tests (`make -C admin test`) pass in the admin development container

### If you made changes to the system configuration:

- [ ] [Configuration tests](https://docs.securedrop.org/en/latest/development/testing_configuration_tests.html) pass

### If you made non-trivial code changes:

- [ ] I have written a test plan and validated it for this PR

### If you made changes to documentation:

- [ ] Doc linting (`make docs-lint`) passed locally

### CODE REVIEW

**Comment by conorsch** [comment]
Having some trouble with connecting to the VMs after initial provisioning. Behavior looks like SSH is blocked. After the "wait_for" task, the machine never comes back up. @msheiny Can you take a look? Steps to reproduce:

```
molecule create -s libvirt-staging
molecule converge -s libvirt-staging # observe error on final wait_for task
molecule converge -s libvirt-staging # observe error failing to connect to VMs
```

I'm able to console into the VMs, so they're definitely up and running.

**Comment by msheiny** [comment]
@conorsch take a look at the last commit i pushed

**Comment by zenmonkeykstop** [comment]
tested libvirt scenario on Ubuntu 16.04:
```
export VAGRANT_DEFAULT_PROVIDER=libvirt
make clean
make build-debs
make staging
```
Confirmed login to app works:
```
molecule login -s libvirt-staging -h app-staging
```
Confirmed source interface available at Onion address listed in install_files/ansible-base/app-source-ths and submissions are accepted.

**Comment by zenmonkeykstop** [comment]
Tested qubes scenario on Qubes 4.0:
(Set up sd Qubes staging environment first - good docs overall, but I'd make that note about restarting sd-app and sd-mon manually during the wait_for phase an explicit instruction rather than a tip) 
```
make clean
make build-debs
export FPF_CI=true #gotta figure out how not to have to set this!
make build-debs
make staging
```
Confirmed that reboot_if_first_install task does not error out. Confirmed that source interface is available at provided Onion address and submissions are accepted.

**Comment by conorsch** [comment]
Thanks for thorough review, @zenmonkeykstop ! We'll still need someone with maintainer status to approve, so not merging for now.

**Comment by zenmonkeykstop** [comment]
FYI, not sure if it should be a blocker for merge as the existing Vagrant flow is still available, but tested virtualbox-staging scenario on macOS 10.13.6:
```
make clean
make build-debs
make staging
```
Confirmed that virtualbox environment was tested and virtualbox-staging scenario was used.
`make staging` failed with error below:
```
    TASK [reboot-if-first-install : Reboot if required due to security updates.] ***
    changed: [mon-staging]
    changed: [app-staging]

    TASK [reboot-if-first-install : Wait for server to come back.] *****************
    fatal: [mon-staging -> localhost]: FAILED! => {"changed": false, "elapsed": 301, "msg": "Timeout when waiting for search string OpenSSH in 127.0.0.1:2200"}
    fatal: [app-staging -> localhost]: FAILED! => {"changed": false, "elapsed": 301, "msg": "Timeout when waiting for search string OpenSSH in 127.0.0.1:2222"}

    NO MORE HOSTS LEFT *************************************************************

    NO MORE HOSTS LEFT *************************************************************
    	to retry, use: --limit @/Users/kog/src/securedrop/molecule/virtualbox-staging/playbook.retry

    PLAY RECAP *********************************************************************
    app-staging                : ok=168  changed=102  unreachable=0    failed=1
    localhost                  : ok=3    changed=0    unreachable=0    failed=0
    mon-staging                : ok=128  changed=75   unreachable=0    failed=1


ERROR:
make: *** [staging] Error 2
```
Checked Virtualbox and the VMs were created, but `molecule login -s virtualbox-staging -h app-staging` fails with a connection reset error.

**Comment by conorsch** [comment]
Good point on the destroy actions, @emkll. Now that we have a `make clean` target (#3532), will keep in mind additions there over time.

**Pull request merged**
