### PR TITLE
Bump upgrade testing box to 0.9.1

### LINKED ISSUE #3816: Build 0.9.1 VM images for upgrade testing
## Description

Last week we released SecureDrop 0.9.1, so we're currently developing 0.10.0~rc1, but the upgrade testing scenario still uses 0.8.0 images for upgrade testing. Let's bump those box versions using the `make vagrant-package` target.

## User Stories

As a developer, I want to ensure that changes will not break upgrades, so tooling that checks such cases should be current with planned upgrades in the wild, i.e. 0.9.1 -> 0.10.0.

### PR DESCRIPTION
**Pull request by msheiny**
## Status

Ready for review

## Description of Changes

Fixes #3816

Changes proposed in this pull request:

* Built and uploaded a 0.9.1 vagrant box to our global s3 buckets
* Tweaked upgrade_version.sh logic to upgrade a stable.ver file (used for vagrant builder ingestion)
* Made a few Makefile targets and helpers 
* Added ability (well mandate really) to select baseline version to use with the upgrade scenario.

## Testing

How should the reviewer test this PR?

First off, this will only work for Linux users with vagrant + libvirt-vagrant installed (sorry @redshiftzero  !!). To test:

```bash
$ make upgrade_start
# Confirm you see 0.9.1 in the securedrop-config versions
$ ansible -i /tmp/molecule/securedrop/upgrade/ansible_inventory.yml all -l mon-staging,app-staging -m shell -a "dpkg -s securedrop-config | grep Version"
```

## Deployment

Any special considerations for deployment? Consider both:

Only affects upgrade testing

### CODE REVIEW

**Comment by heartsucker** [comment]
I can't test this because my version of Vagrant (2.1.1) doesn't work with the Vagrantfile.

```
There was an error loading a Vagrantfile. The file being loaded
and the error message are shown below. This is usually caused by
a syntax error.

Path: /home/heartsucker/code/freedomofpress/securedrop/Vagrantfile
Line number: 5
Message: RuntimeError: can't modify frozen String
```

And if I comment out that link, I get:

```
    TASK [Create molecule instance(s)] *********************************************
    failed: [localhost] (item={'box': u'fpf/securedrop-app', 'name': u'app-staging', 'provider_override_args': [u"vm.synced_folder './', '/vagrant', disabled: true, type: 'nfs'"], 'box_url': u'../vagrant_packager/box_files/app_metadata.json', 'instance_raw_config_args': [u'ssh.insert_key = false'], 'groups': [u'securedrop_application_server', u'securedrop', u'staging'], 'memory': 1024, 'private_ip': u'10.0.1.2'}) => {"changed": false, "item": {"box": "fpf/securedrop-app", "box_url": "../vagrant_packager/box_files/app_metadata.json", "groups": ["securedrop_application_server", "securedrop", "staging"], "instance_raw_config_args": ["ssh.insert_key = false"], "memory": 1024, "name": "app-staging", "private_ip": "10.0.1.2", "provider_override_args": ["vm.synced_folder './', '/vagrant', disabled: true, type: 'nfs'"]}, "msg": "ERROR: See log file '/tmp/molecule/securedrop/upgrade/vagrant-app-staging.err'"}
    failed: [localhost] (item={'box': u'fpf/securedrop-mon', 'name': u'mon-staging', 'provider_override_args': [u"vm.synced_folder './', '/vagrant', disabled: true, type: 'nfs'"], 'box_url': u'../vagrant_packager/box_files/mon_metadata.json', 'instance_raw_config_args': [u'ssh.insert_key = false'], 'groups': [u'securedrop_monitor_server', u'securedrop', u'staging'], 'memory': 1024, 'private_ip': u'10.0.1.3'}) => {"changed": false, "item": {"box": "fpf/securedrop-mon", "box_url": "../vagrant_packager/box_files/mon_metadata.json", "groups": ["securedrop_monitor_server", "securedrop", "staging"], "instance_raw_config_args": ["ssh.insert_key = false"], "memory": 1024, "name": "mon-staging", "private_ip": "10.0.1.3", "provider_override_args": ["vm.synced_folder './', '/vagrant', disabled: true, type: 'nfs'"]}, "msg": "ERROR: See log file '/tmp/molecule/securedrop/upgrade/vagrant-mon-staging.err'"}
    failed: [localhost] (item={'box': u'bento/ubuntu-14.04', 'provider_override_args': [u"vm.synced_folder './', '/vagrant', disabled: true, type: 'nfs'"], 'name': u'apt', 'groups': [u'aptservers'], 'memory': 256}) => {"changed": false, "item": {"box": "bento/ubuntu-14.04", "groups": ["aptservers"], "memory": 256, "name": "apt", "provider_override_args": ["vm.synced_folder './', '/vagrant', disabled: true, type: 'nfs'"]}, "module_stderr": "", "module_stdout": "--> Validating schema /home/heartsucker/code/freedomofpress/securedrop/molecule/upgrade/molecule.yml.\nValidation completed successfully.\n", "msg": "MODULE FAILURE", "rc": 0}
```

And the error log is:

```
### 2018-09-25 12:50:41 ###
### 2018-09-25 12:50:41 ###
The box you're attempting to add doesn't support the provider
you requested. Please find an alternate box or use an alternate
provider. Double-check your requested provider to verify you didn't
simply misspell it.

If you're adding a box from HashiCorp's Vagrant Cloud, make sure the box is
released.

Name: fpf/securedrop-mon
Address: file:///home/heartsucker/code/freedomofpress/securedrop/molecule/vagrant_packager/box_files/mon_metadata.json
Requested provider: [:virtualbox]
### 2018-09-25 12:52:06 ###
### 2018-09-25 12:52:06 ###
The box you're attempting to add doesn't support the provider
you requested. Please find an alternate box or use an alternate
provider. Double-check your requested provider to verify you didn't
simply misspell it.

If you're adding a box from HashiCorp's Vagrant Cloud, make sure the box is
released.

Name: fpf/securedrop-mon
Address: file:///home/heartsucker/code/freedomofpress/securedrop/molecule/vagrant_packager/box_files/mon_metadata.json
Requested provider: [:virtualbox]
```

**Comment by zenmonkeykstop** [comment]
@heartsucker it probably shouldn't be using the vlrtualbox provider, but libvirt. Have you previously done the libvirt conversion dance as described here?:  https://docs.securedrop.org/en/release-0.9/development/virtual_environments.html#switch-vagrant-provider-to-libvirt

Gonna run through test plan now myself, see if I can get the same error.

**Comment by msheiny** [comment]
Yeppp - I think @zenmonkeykstop is on the right path. I got a ticket here to add support for virtualbox support (and thus mac OSX and friends) but right now its stuck at libvirt cause my system doesnt support virtualbox (grrrrrrrsec!! *shakes fist at sky*).

**Comment by zenmonkeykstop** [comment]
On Ubuntu 18.04, checked out branch fresh and ran:
```
make build-debs
make upgrade_start
```
This failed for me, saying it couldn't find the tor-hidden-services role.

Poked about a bit and changed ANSIBLE_ROLES_PATH in `/molecule/upgrade/molecule.yml` to `../shared/.molecule/sd-orig/install_files/ansible-base/roles:.molecule/roles`, and ran `make upgrade_start` again. It failed again, but near the very end:

```
    TASK [Spit out tor details] ****************************************************
 [WARNING]: Unable to find '.molecule/sd-orig/install_files/ansible-base/app-
source-ths' in expected paths.

    fatal: [localhost]: FAILED! => {"msg": "An unhandled exception occurred while running the lookup plugin 'file'. Error was a <class 'ansible.errors.AnsibleError'>, original message: could not locate file in lookup: .molecule/sd-orig/install_files/ansible-base/app-source-ths"}
```
Updated `molecule/upgrade/molecule.yml` to find source interface details at `../shared/.molecule/sd-orig/install_files/ansible-base/app-source-ths`, ran `make upgrade_start` again. It completed successfully!

Then checked securedrop-config versions:
```
mon-staging | SUCCESS | rc=0 >>
Version: 0.1.1+0.9.1

app-staging | SUCCESS | rc=0 >>
Version: 0.1.1+0.9.1
```

SUCCESS! (with path tweaks as mentioned above, which may just be coz something is weird on my side).

**Comment by msheiny** [comment]
yo @zenmonkeykstop you found a super interesting bug that didnt show up on my box due to the way we are git ignoring the `.molecule` ephemeral directory. At some point, molecule moved this directory to `/tmp/molecule....`. 

I pushed a commit that should fix this and move that SD clone action to /tmp so it should really get wiped upon reboots and we dont have to count on someone running a molecule destroy action. thanks for flagging and let me know if you are still seeing the error on latest branch HEAD here.

**Comment by zenmonkeykstop** [comment]
Tested as above on a fresh clone, it completed successfully with the /tmp/molecule change. :+1:

**Pull request merged**
