### PR TITLE
Remove docs, update CI config & tooling

### PR DESCRIPTION
**Pull request by eloquence**
Docs removal and tooling changes in support of standalone docs repo. Blocked until https://docs.securedrop.org/ is switched over.

Further towards #5435.

## Description
- Removes docs from repository. 
- Clarifies README.
- Updates CI config, including removal of docs-specific branch filtering logic (on both `docs*` and `stable` branches) and docs version update logic (cf. https://github.com/freedomofpress/securedrop-docs/pull/6).
- Removes documentation logic form `update_version.sh` (see https://github.com/freedomofpress/securedrop-docs/pull/6).
- Updates development requirements to remove Sphinx.
- Updates `i18n_tool.py` to require a repo directory when updating the list of languages.
- Updates `update-user-guides` target to support a `DOCS_REPO_DIR` environment variable.

## Note to reviewer
- The commits are quite distinct and you may prefer a commit-by-commit review.

## Test plan 
- [ ] Observe that `./update_version.sh` still operates as expected while no longer attempting to modify documentation.
- [ ] Observe that `python3 securedrop/i18n_tool.py update-docs` (updates list of languages) is self-documenting and works as expected in combination with a docs repo checkout. Easiest to test by removing a valid language from `docs/includes/l10n.txt` in the docs repo checkout via a test commit.
- [ ] Observe that `make update-user-guides` is self-documenting and works in combination with a docs repo checkout.

### CODE REVIEW

**Comment by eloquence** [comment]
Pending CI results, I believe this is ready for formal review now, but keeping in draft mode until the new docs repo is live at https://docs.securedrop.org/

To wrap up the migration, we'll need to also update contributor guidelines and release management docs; Joan and I will tackle that next over in the securedrop-docs repo.

**Comment by conorsch** [comment]
Took an initial pass through, in conjunction with https://github.com/freedomofpress/securedrop-docs/pull/8 

- :red_circle: Observe that `./update_version.sh` still operates as expected while no longer attempting to modify documentation.

Testing locally, I see
```
$ ./update_version.sh 1.8.4
sed: can't read install_files/securedrop-app-code/debian/control: No such file or directory
```

Which doesn't appear to be a problem with this PR, but one we need to resolve all the same. Blame suggests #5465 broke it, which I merged. Mea culpa! Since 1.6.0~rc1 was already configured in develop, we didn't catch this when branching to `release/1.6.0` earlier today, but we'll certainly hit it when bumping to rc2.

- [x] Observe that `python3 securedrop/i18n_tool.py update-docs` (updates list of languages) is self-documenting and works as expected in combination with a docs repo checkout. Easiest to test by removing a valid language from `docs/includes/l10n.txt` in the docs repo checkout via a test commit.
- [x] Observe that `make update-user-guides` is self-documenting and works in combination with a docs repo checkout.

For both scripts, it seems reasonable to me to set a default value of "../securedrop-docs" and not complain if that dir is found, but we needn't do that on day one. Most important, running the scripts without any customizations makes it very obvious how to resolve, which is a pleasant experience.

**Comment by eloquence** [comment]
> For both scripts, it seems reasonable to me to set a default value of "../securedrop-docs" and not complain if that dir is found

I was hesitant to that because copying a large number of files or making commits beyond the context of a single repo seemed to me the kind of operation a user should always explicitly parametrize to avoid surprises, but I'm happy to go with whatever the team consensus is on this one.

**Comment by eloquence** [comment]
https://docs.securedrop.org/ is now built from https://github.com/freedomofpress/securedrop-docs , so promoting this to ready. Squashed into three distinct commits.

**Review by conorsch — APPROVED** [review]
- [x] Observe that `./update_version.sh` still operates as expected while no longer attempting to modify documentation.
- [x] Observe that `python3 securedrop/i18n_tool.py update-docs` (updates list of languages) is self-documenting and works as expected in combination with a docs repo checkout. Easiest to test by removing a valid language from `docs/includes/l10n.txt` in the docs repo checkout via a test commit.
- [x] Observe that `make update-user-guides` is self-documenting and works in combination with a docs repo checkout.

Works great! The scripts are quite helpful when run without the required arguments. During 1.6 release, will watch for opportunities to improve further if any surprises occur.

**Comment by conorsch** [comment]
Proceeding with merge into `develop` branch. I don't see any need to port these changes into the `release/1.6.0` branch, given that https://docs.securedrop.org/ is already serving from https://github.com/freedomofpress/securedrop-docs.

**Pull request merged**
