### PR TITLE
Docs: Fix patch for installer in Tails 3.5

### LINKED ISSUE #3105: Update installer.patch (mentioned in the virtualizing_tails.rst) with respect to Tails 3.5
# Bug

## Description

The [installer.patch](https://docs.securedrop.org/en/latest/development/virtualizing_tails.html) is outdated (fails on Tails 3.5).

## Steps to Reproduce
1. In tails VM create a file installer.patch (copy and paste the patch from virtualizing_tails.rst)
2. Run the following command in the terminal `sudo patch -p0 -d/ < installer.patch`  

## Actual Behavior
`root@amnesia:/home/amnesia/temp# sudo patch -p0 -d/ < installer.patch
patching file /usr/lib/python2.7/dist-packages/tails_installer/creator.py
Reversed (or previously applied) patch detected!  Assume -R? [n] n
Apply anyway? [n] y
Hunk #1 FAILED at 615.
1 out of 1 hunk FAILED -- saving rejects to file /usr/lib/python2.7/dist-packages/tails_installer/creator.py.rej
patching file /usr/lib/python2.7/dist-packages/tails_installer/gui.py
Hunk #1 FAILED at 483.
1 out of 1 hunk FAILED -- saving rejects to file /usr/lib/python2.7/dist-packages/tails_installer/gui.py.rej`

### PR DESCRIPTION
**Pull request by redshiftzero**
## Status

Ready for review

## Description of Changes

Follow up from #3104, fixes #3105 

Changes proposed in this pull request:
 * Fixes whitespace in `installer.patch`

## Testing

1. `make docs`
2. Navigate to http://127.0.0.1:8000/development/virtualizing_tails.html#install-tails
3. Apply patch to tails installer and verify it cleanly applies

## Deployment

None, dev only

### If you made changes to documentation:

- [x] Doc linting passed locally

### CODE REVIEW

**Comment by emkll** [comment]
Can confirm the path is correct *and* the patch applies correctly in 3.5. I don't have a 3.6-rc VM but can circle back on this tomorrow. Sorry for not catching this in the previous iteration !
screenshot from 2018-03-07 16-16-07

**Comment by pwnchief** [comment]
@redshiftzero  Just confirmed https://klistrain.se/p/6470515
Works for Tails `3.6-rc1`

**Comment by redshiftzero** [comment]
OK, I've taken the diff of the installer patch provided by @pwnchief with the patch in this PR (after building the documentation), and the only difference appears to be the dates. So given that this patch worked for @emkll _and_ it's the same as the patch provided by @pwnchief, I think this is good to go.

**Comment by redshiftzero** [comment]
Hey @emkll - can you stamp this one when you get a chance?

**Comment by redshiftzero** [comment]
Woohoo, thanks :)

**Pull request merged**
