### PR TITLE
update firewall docs for SG-2440

### PR DESCRIPTION
**Pull request by harlo**
updating firewall doc for the new pfsense box, as per https://github.com/freedomofpress/securedrop/issues/1072.  NB: line 195 references a firewall rule template (at `install_files/network_firewall/rules`) which I suppose should be modified to fit this new configuration as well.

### CODE REVIEW

**Comment by garrettr** [comment]
@harlo These docs looks good! I will test them with a fresh install later today.

**Comment by garrettr** [comment]
@harlo The firewall rules for DNS need to support `TCP/UDP` for the protocol, since [DNS may use TCP][1] is either the request or response is larger than the size of a single packet.

[1]: http://www.networkworld.com/article/2231682/cisco-subnet/cisco-subnet-allow-both-tcp-and-udp-port-53-to-your-dns-servers.html

**Comment by conorsch** [comment]
@harlo New screenshots look great! We're now correctly recommending `TCP/UDP` for DNS traffic. Looks ready for merge now, @garrettr.

**Comment by garrettr** [comment]
Great, I'm going to run through an install today using these updated docs as a final check, will then merge.

**Comment by harlo** [comment]
closing in favor of #1106

**Pull request closed without merging**
