### PR TITLE
Update docs for TorBrowser download location

### PR DESCRIPTION
**Pull request by harlo**
as per https://github.com/freedomofpress/securedrop/issues/1036. imgs added soon.

### CODE REVIEW

**Comment by conorsch** [comment]
Text looks great, glad we're addressing this now, right before a minor release. Will review again once images are added.

**Comment by garrettr** [comment]
@harlo Is this PR mistitled?

**Comment by harlo** [comment]
Yes-- please feel free to change if it's urgent. (I'm currently on foot.)

**Comment by conorsch** [comment]
Updated title. Still needs images before final review.

**Comment by dolanjs** [comment]
lgtm with the added screenshots

**Comment by garrettr** [comment]
:+1:

**Pull request merged**
