### PR TITLE
Add missing static/icons directory to debian package

### LINKED ISSUE #5625: New icons aren't included in securedrop-app-code package
## Description

In #5593 we added the `static/icons` directory. This isn't being included in the `securedrop-app-code` Debian package.

## Steps to Reproduce

- Run `make build-debs`. 
- Run `dpkg --contents build/xenial/securedrop-app-code_1.7.0~rc1+xenial_amd64.deb | grep static/icons`; nothing should be listed.
- If you `make staging` and visit the journalist interface, the icons will be missing, replaced with alt text like "starred icon".

## Comments

Need to update `securedrop/.rsync-filter` to include `static/icons`.

### PR DESCRIPTION
**Pull request by DrGFreeman**
## Status

Ready for review.

## Description of Changes

Fixes #5625 

Changes proposed in this pull request:

Add missing `static/icons` directory to  `securedrop-app-code` Debian package. The directory was added in #5593 but not included in `securedrop/.rsync-filter`.

## Testing

How should the reviewer test this PR?
Write out any special testing steps here.

1. Run `make build-debs`.
1. Check the icons are included by running the command below and verify the output equals 22.
    ```
    dpkg --contents build/xenial/securedrop-app-code_1.7.0~rc1+xenial_amd64.deb | \
        grep -e static/icons/.*\.png | wc -l
    ```
1. Run `make staging`, visit the Journalist Interface and verify that the icons are displayed correctly.

## Deployment

Any special considerations for deployment? Consider both:

1. Upgrading existing production instances.
2. New installs.

### If you made changes to the server application code:

- [ ] Linting (`make lint`) and tests (`make test`) pass in the development container

### If you made changes to `securedrop-admin`:

- [ ] Linting and tests (`make -C admin test`) pass in the admin development container

### If you made changes to the system configuration:

- [ ] [Configuration tests](https://docs.securedrop.org/en/latest/development/testing_configuration_tests.html) pass

### If you made non-trivial code changes:

- [ ] I have written a test plan and validated it for this PR

Choose one of the following:

- [ ] I have opened a PR in the [docs repo](https://github.com/freedomofpress/securedrop-docs) for these changes, or will do so later
- [ ] I would appreciate help with the documentation
- [x] These changes do not require documentation

### If you added or updated a code dependency:

Choose one of the following:

- [ ] I have performed a diff review and pasted the contents to [the packaging wiki](https://github.com/freedomofpress/securedrop-debian-packaging/wiki)
- [ ] I would like someone else to do the diff review

### CODE REVIEW

**Comment by DrGFreeman** [comment]
Note that I am not currently setup to run the staging environment so I could not check the third item in the proposed tests.

**Comment by DrGFreeman** [comment]
I'm a bit puzzled as to why the *focal-app-tests* CI check failed in this PR as well as in #5629 while it passed in #5621 which is currently the latest change in `develop`.

It's curious that the fixture fails (because there are more files in the storage than expected) during the first setup and not during the following ones.  Also, the fixture fails only on Focal, not on Xenial.

~~I wrote the fixture that is failing so I would like to understand why it fails, however, I could not run `make test-focal` (or `make dev-focal`) as it seems that there is a 404 error in Docker build when trying to reach https://www.torproject.org/dist/torbrowser/10.0.1/tor-browser-linux64-10.0.1_en-US.tar.xz ...~~

**Update:** Ran tests in Focal dev container but could not replicate the fixture setup failure.

Will keep looking for the cause but if anyone as an idea, please chime in!

**Comment by zenmonkeykstop** [comment]
I reran the tests in #5629 and they passed - which only adds to the mystery!

**Review by rmol — APPROVED** [review]
:+1: This works. I'm going to merge it because the test flake is happening elsewhere, and will be addressed separately. Thanks again @DrGFreeman.

**Pull request merged**
