### PR TITLE
WIP: Tkell test with tor browser

### PR DESCRIPTION
**Pull request by nvesely**
Fixes: #1569

Run the functional tests with Tor Browser. Supersedes #1629.

### CODE REVIEW

**Comment by fowlslegs** [comment]
This passes locally, but not on Travis. Travis does not have great debugging tools. We're switching to CircleCI soon. I'm labeling this as blocked until we switch to CircleCI, and then I'll try to get it working under CircleCI. Seems like a lot of wasted effort to make changes on Travis that may not be needed elsewhere, so I'd like to avoid that.

**Comment by fowlslegs** [comment]
@tkell Well hopefully it just works™ on CircleCI, but if not I'll have to debug since you won't have shell access. It would be helpful if you could test that this branch is currently working for you locally, and let us know which OS & Vagrant provider/ version you're using. Iirc it was failing for @redshiftzero on macOS w/ Virtualbox. I use Debian with libvirt, where it's reliably working. Hard for me to debug further when I don't have access to an environment these errors are happening on.

**Comment by tkell** [comment]
@fowlslegs, tests pass for me on MacOS with VirtualBox 5.14, and Vagrant 1.8.5.  Both those versions appear to be a bit behind the current state of things though.

**Comment by fowlslegs** [comment]
I'm going to have to ask that someone who has access to an interactive test environment where this code is failing take over this PR.

**Comment by nvesely** [comment]
https://github.com/webfp/tor-browser-selenium/pull/88 is merged now.

**Comment by dachary** [comment]
@nvesely I squashed and rebased and resolved the conflicts. I did not however address the test failures that pre-existed: this remains in a WIP state. I decided to squash the commits because they had incremental changes to functional_tests.py mostly and resolving six layers of conflicting commits on the same area of code is difficult.

**Comment by redshiftzero** [comment]
This is WIP and has been pending with failing tests for some time now, so I'm going to close for now. Any contributor or maintainer should feel free to pick this back up and try again to get it merged in - I dropped the branch name in issue #1569 for anyone who wants to do so 😃

**Pull request closed without merging**
