### PR TITLE
Docs - remove 'edit on GitHub' link

### LINKED ISSUE #2194: Docs: Links to edit/view on Github are broken
On top right and bottom left corner of every page on docs there's a link to view/edit that page on Github. Seems like all of those links are broken.

### PR DESCRIPTION
**Pull request by trankmichael**
## Status

work needed

## Description of Changes

Fixes #2194 .

Removes the "Edit on Github" link in the top right of the header in the doc template. 

Followed the fix outlined at [sphinx-doc/sphinx/#2386 ](https://github.com/sphinx-doc/sphinx/issues/2386#issuecomment-217861381)

## Testing

Local builds with `make docs` works and linting passes. I am not sure how to confirm whether or not the link is actually removed because these changes are not included when the docs are built locally with `make docs`. Builds with `make docs` have "View source" instead of "Edit on Github". Both types of links were removed in these changes. Could someone advise me on how to check whether or not the "Edit on Github" link is in fact removed? 

## Deployment

Any special considerations for deployment? Consider both:

1. Upgrading existing production instances. **No**
2. New installs. **No** 

### If you made changes to documentation:

- [x] Doc linting passed locally

### CODE REVIEW

**Comment by dachary** [comment]
@trankmichael someone with access to the readthedocs account of securedrop should

* copy your branch to the repository
* activate documentation build on this new branch
* browse the generated documentation to verify the link is gone

**Comment by b-meson** [comment]
I reviewed this implementation and it looks correctly implemented but I do not have access to read the docs. Removing myself as assigned but the implementation LGTM.

**Comment by redshiftzero** [comment]
Hey @trankmichael - I pushed these commits to `trankmickael-docs-remove_edit_on_github_link` and [built the docs](https://docs.securedrop.org/en/trankmichael-docs-remove_edit_on_github_link/development/getting_started.html) and unfortunately it does not look like the fix here worked:

screen shot 2017-12-21 at 12 20 15 pm

**Comment by dachary** [comment]
@trankmichael gentle new-year ping ? :-)

**Comment by trankmichael** [comment]
I just edited the `breadcrumbs.html ` to remove a condition that seems to overwrite the `html_context['display_github']`. 

After looking into this and I saw that on the original thread [sphinx-doc/sphinx/#2386 ](https://github.com/sphinx-doc/sphinx/issues/2386#issuecomment-217861381) someone mentioned that the fix may currently be broken due to the currently open issue [sphinx-doc/sphinx/#2442 ](https://github.com/sphinx-doc/sphinx/issues/2442). 

I am still not sure what an appropriate workflow would be for checking if this fix. Can someone check if this solved it on RTD? If it didnt Ill look into some other workarounds as mentioned above.

**Comment by dachary** [comment]
@redshiftzero @conorsch I would be happy to test if given access to the readthedocs account :-)

**Comment by dachary** [comment]
@redshiftzero @conorsch ping ?

**Comment by redshiftzero** [comment]
Thanks for ping @dachary - the permissions are pretty bad on readthedocs so I just went ahead and pushed the latest changes to the test branch `trankmichael-docs-remove_edit_on_github_link` on the shared remote for now. 

Unfortunately it doesn't look like your latest change @trankmichael [resolved the issue](https://docs.securedrop.org/en/trankmichael-docs-remove_edit_on_github_link/development/setup_development.html). Reading the issue you posted, I agree that it sounds like the functionality to resolve this isn't working on readthedocs. Thanks again for the work you've put into investigating and resolving this. Let me know if you want to focus on another issue and we can mark #2194 as blocked. 

That said, if you'd like to continue to try additional workarounds, one way to test a change of this type would be to enable building on readthedocs of your fork of this repo, I believe that should work, though you'd need to first [sign up for a readthedocs account](https://docs.readthedocs.io/en/latest/getting_started.html#sign-up-and-connect-an-external-account) (free). Alternatively, feel free to push changes here and ping us and we can push 'em to the branch we've been using :smile:

**Comment by trankmichael** [comment]
Thanks for the info! Ill make an RTD account and continue to work on this on my fork. Ill ping if i get it working

**Comment by redshiftzero** [comment]
Hey @trankmichael - since we're in a holding pattern on this one, I'm going to close for now. Feel free to re-open if you unravel the readthedocs `html_context ` mystery :smile:.

**Pull request closed without merging**
