### PR TITLE
Remove DEBUG output from functional tests, fix test requirements, add VNC server

### LINKED ISSUE #3698: [functional testing] Remove DEBUG log level output
## Description

The test output from a failed Selenium functional test provides a lot of log output at the INFO and DEBUG levels, e.g.:

```
connectionpool.py          435 DEBUG    "GET / HTTP/1.1" 200 6210
connectionpool.py          264 INFO     Starting new HTTP connection (1): localhost
connectionpool.py          395 DEBUG    Setting read timeout to None
connectionpool.py          435 DEBUG    "GET / HTTP/1.1" 302 219
connectionpool.py          310 INFO     Resetting dropped connection: localhost
connectionpool.py          395 DEBUG    Setting read timeout to None
connectionpool.py          435 DEBUG    "GET /login HTTP/1.1" 200 3866
```

This is rarely useful and it clutters up the test output significantly. The output also includes a base64 encoded Firefox profile. While this DEBUG output is also in place on `develop`, the size of the Firefox profile is much smaller (only a few lines), whereas on `tbb-0.9.0` it is a massive wall of base64 encoded text. We should resolve this to ensure that the test output is useful. 

Note that since we are using Selenium 3+ and geckodriver on `tbb-0.9.0` (we use selenium<3 on `develop`) and as such the method to resolve this is likely different between `tbb-0.9.0` and `develop`, we should resolve in the `tbb-0.9.0` branch first.

Epic: #3659

### PR DESCRIPTION
**Pull request by zenmonkeykstop**
## Status

Ready for review

## Description of Changes

Fixes #3698 , #3718 

Changes proposed in this pull request:
This PR includes @msheiny's change to selenium's output level from DEBUG to WARNING, cherrypicked from commit https://github.com/freedomofpress/securedrop/commit/a1f013408721aa4f87bb3fb8439e9f21d7e2adfc

It also includes an update to the test requirements file, to remove a duplicate entry for werkzeug that probably slipped in in a merge and was preventing the tests from running.

It also includes support for viewing functional tests in progress, using VNC on OSX and Debian workstations.

## Testing
To verify that functional tests run and do not include DEBUG-level output, from the securedrop directory, run:
```
make build-debs
cd securedrop 
./bin/dev-shell ./bin/run-test -v tests/functional/
```
Docker build should complete without error, and tests should run without debug-level output (specifically not the base64-encoded firefox profile data)

To verify that VNC is set up and available, kick off the functional tests as above, and once the Docker container has started and the tests are in progress, run:

```
make func-vnc
```
The system's default VNC viewer should start, displaying the functional tests' browsers.

### If you made non-trivial code changes:

- [x] I have written a test plan and validated it for this PR

### CODE REVIEW

**Comment by redshiftzero** [comment]
Now that torproject.org is back up, the next step is to update the version of Tor Browser on `tbb-0.9.0` (let's add to this branch @zenmonkeykstop so we can get CI fixed).

**Comment by redshiftzero** [comment]
Pushed two commits to get the docker builds working again, note I also updated the pax flags for Tor Browser 8 based on our private infrastructure repo

However we're hitting a new issue here which looks to be https://github.com/mozilla/geckodriver/issues/913 likely due to the old version of geckodriver we are using. Indeed problems with Tor Browser 8 were reported over in https://github.com/webfp/tor-browser-selenium/issues/105. Going to bump up versions of geckodriver (and Selenium if necessary) and see if that resolves...

**Comment by redshiftzero** [comment]
ok my attempts to resolve this CI issue so far are in commit 8da014e0207561661af0d9a1c61c193d7c70c030 in `tb-8-ci` (not pushing here in case we take another path). I'm at the point where I've updated geckodriver to `0.21.0`, firefox-esr to latest (>=60 is required by geckodriver 0.21.0), but I'm hitting the following on the first functional test:

```
self = <httplib.HTTPResponse instance at 0x7fbdc8448cf8>

    def _read_status(self):
        # Initialize with Simple-Response defaults
        line = self.fp.readline(_MAXLINE + 1)
        if len(line) > _MAXLINE:
            raise LineTooLong("header line")
        if self.debuglevel > 0:
            print "reply:", repr(line)
        if not line:
            # Presumably, the server closed the connection before
            # sending a valid response.
>           raise BadStatusLine(line)
E           BadStatusLine: ''

/usr/lib/python2.7/httplib.py:408: BadStatusLine
```

**Comment by kushaldas** [comment]
We should have the same version of `firefox-esr` which is being used by the `Tor Browser`.

**Comment by zenmonkeykstop** [comment]
I tried updating to 8.0 last night as well; the teardown() function didn't seem to run between tests, so docker container ended up with a few dozen sets of firefox-esr,xvfb, and firefox.real processes, before running out of memory and giving up the ghost.

**Comment by zenmonkeykstop** [comment]
As per gitter, upgrading to geckodriver 0.22.0 seems to resolve this issue. The BadStatusLine messages are happening with 0.21.0 because it sets connection keep-alives to 5sec - this has been bumped to 90sec in 0.22.0.

**Comment by zenmonkeykstop** [comment]
@msheiny stuck in a commit to skip pw prompt for remote-viewer. Works for me on Ubuntu but give it a lash on Debian?

**Comment by msheiny** [comment]
im also getting the same failures locally that are happening in CI

such as this gem
` SessionNotCreatedException: Message: Unable to find a matching set of capabilities`

i see a few github tickets that possibly reference a pathing issue .. checking

**Comment by redshiftzero** [comment]
There is some wonky CI logic in the staging-test-with-rebase job:

1. In the `tbb-0.9.0` branch, we removed the application test run. 
2. Meanwhile, in the develop branch, we removed the testinfra test run (in [this commit](https://github.com/freedomofpress/securedrop/commit/09a485722dda2712764cc77c44469e14b2dc619b#diff-8e4f3bf66d72d0e2359e0017b275305b)). 

During the rebase on latest `develop`, we didn't reconcile these two changes. This is why we see in CI output: 

```
    TASK [Dump raw test output] ****************************************************
    fatal: [app-staging]: FAILED! => {"msg": "'raw_test_results' is undefined"}
    	to retry, use: --limit @/root/sd/molecule/aws/side_effect.retry
```

**Comment by redshiftzero** [comment]
all tests passing here now... so merging

**Pull request merged**
