### PR TITLE
Improve i18n_tool.py update-from-weblate

### PR DESCRIPTION
**Pull request by rmol**
## Status

Ready for review

## Description of Changes

When committing changes to a .po file, the script assumed that it would always have committed the last change as part of the update-from-weblate task. If the file were changed outside of that workflow, and the commit message wasn't structured as expected, the script would be unable to gather translator credits correctly.

This changes the script to look past the last commit until it finds one of its commit messages.

## Testing

- Create a branch to replicate the merge of translations for 1.8.0: `git checkout -b credit-check aee4ffa6c`
- Check out `i18n_tool.py` from this branch: `git checkout origin/fix-update-from-weblate-credits -- securedrop/i18n_tool.py` 
- Reset to `HEAD` to avoid that change being picked up by the `update-from-weblate` task (just speeds things up): `git reset HEAD`
- `securedrop/bin/dev-shell ./i18n_tool.py --verbose update-from-weblate`
- `git diff develop -- securedrop/translations` should report no changes
- `securedrop/bin/dev-shell ./i18n_tool.py list-translators --target 2e52ab4e0 --since 1.7.1` should match the lists of contributors per language in the commit messages shown by `git log aee4ffa6c..`
- `securedrop/bin/dev-shell ./i18n_tool.py list-translators --all` should work, reporting many many contributors

## Deployment

No production implications.

### If you made non-trivial code changes:

- [x] I have written a test plan and validated it for this PR

Choose one of the following:

- [ ] I have opened a PR in the [docs repo](https://github.com/freedomofpress/securedrop-docs) for these changes, or will do so later
- [ ] I would appreciate help with the documentation
- [x] These changes do not require documentation

### CODE REVIEW

**Review by kushaldas — CHANGES_REQUESTED** [review]
During the test steps, all looked okay. But, `git diff develop -- securedrop/translations` showed me the difference between the branches. I think that is what it should show, but @rmol said it should not.  

I will defer the approve part till we have a quick chat about it, but, otherwise the PR is great.

**Comment by rmol** [comment]
Ah, the translations have changed on develop since I wrote the test plan, and I should have asked you to compare to 1.8.0 in the first place. Use `git diff 1.8.0 -- securedrop/translations` instead of `git diff develop -- securedrop/translations`, and you should see no differences reported.

**Review by kushaldas — APPROVED** [review]
Approved. Will have a chat with @rmol  before merging.

**Comment by rmol** [comment]
Merging per discussion in standup.

**Pull request merged**
