### PR TITLE
pylintrc: enable spell checking

### LINKED ISSUE #2779: lint: there should be spell checking in code comments + docstrings

### PR DESCRIPTION
**Pull request by tmc**
## Status

Ready for review.

## Description of Changes

Depends on #2784 

Fixes #2779.

## Testing

CI

## Deployment

N/A

### CODE REVIEW

**Comment by dachary** [comment]
@kushaldas it includes https://github.com/freedomofpress/securedrop/pull/2784 which was merged yesterday and needs rebase indeed :-)

**Comment by tmc** [comment]
@kushaldas yeah, I had it tagged as Work in progress and dependent on #2784 -- now that that landed I've gone ahead and rebased this, marking ready for review.

**Comment by tmc** [comment]
@redshiftzero rebased.

**Comment by dachary** [comment]
This looks like a transient error https://circleci.com/gh/freedomofpress/securedrop/5834?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link

<pre>
    TASK [ossec-agent : Add firewall exemption for OSSEC agent registration.] ******
    Thursday 04 January 2018  01:07:28 +0000 (0:00:01.002)       0:07:04.514 ******
    fatal: [app-staging]: FAILED! => {"failed": true, "msg": "The conditional check 'hostvars[groups.securedrop_monitor_server.0].ossec_agent_already_registered == false and iptables_rules_check_result.stat.exists == true' failed. The error was: error while evaluating conditional (hostvars[groups.securedrop_monitor_server.0].ossec_agent_already_registered == false and iptables_rules_check_result.stat.exists == true): 'dict object' has no attribute 'ossec_agent_already_registered'\n\nThe error appears to have been in '/root/sd/install_files/ansible-base/roles/ossec-agent/tasks/agent_config.yml': line 17, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n- name: Add firewall exemption for OSSEC agent registration.\n  ^ here\n"}
</pre>

**Comment by dachary** [comment]
rebased & repushed to re-run circleci

**Comment by dachary** [comment]
@kushaldas this PR was rebased to only contain the relevant commits, does that address your concern ?

**Comment by tmc** [comment]
@kushaldas ping

**Comment by dachary** [comment]
@tmc needs rebase

**Comment by dachary** [comment]
rebased & repushed. Were your comments addressed @kushaldas ?

**Comment by dachary** [comment]
@redshiftzero this was rebased as you suggested, are you ok to approve ?

**Comment by dachary** [comment]
@msheiny that's a first: it looks like codecov communication was interrupted mid-air ? https://circleci.com/gh/freedomofpress/securedrop/6267?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link

<pre>
 _____          _
 / ____|        | |
| |     ___   __| | ___  ___ _____   __
| |    / _ \ / _` |/ _ \/ __/ _ \ \ / /
| |___| (_) | (_| |  __/ (_| (_) \ V /
 \_____\___/ \__,_|\___|\___\___/ \_/
                              Bash-a269d93


/dev/fd/63: line 573: syntax error: unexpected end of file
Makefile:23: recipe for target 'test' failed
make: *** [test] Error 2
Exited with code 2
</pre>

**Comment by tmc** [comment]
rebased again.

**Comment by dachary** [comment]
@tmc rebased and resolved two conflicts as follows:

* travis is gone
* staging-test was removed by 5ecddcf294f997b1d641f714a8606f0f674b38d7 and the associated hunk is no longer needed

**Comment by dachary** [comment]
@redshiftzero are you satisfied with the changes ?

**Pull request merged**
