### PR TITLE
Backport translation changes  to release/0.13.0 branch

### PR DESCRIPTION
**Pull request by zenmonkeykstop**
## Status

Ready for review

## Description of Changes

Contains i18n changes from  `rmol:i18n-0.13.0`

## Testing
- [ ] #4475 is merged into develop
- [ ] CI passes
- [ ] Contains all commits from  `rmol:i18n-0.13.0`

### CODE REVIEW

**Comment by zenmonkeykstop** [comment]
D'oh, wrong target

**Comment by zenmonkeykstop** [comment]
Added a commit to bump TBB to 8.0.9 to resolve issues with failing page-layout tests.

**Comment by emkll** [comment]
Pushed cherry-picked the fix in #4455 and pushed 45c7fbd to fix translation tests.

We should ensure translation tests pass in https://circleci.com/workflow-run/f0b80eb2-78e8-4ffd-92a6-ff1c6306066e before merging this PR into release/0.13.0

**Comment by redshiftzero** [comment]
merging since we confirmed a successful translation test run for merge of #4475, and there were no source string changes in `release/0.13.0` after weblate was updated

**Pull request merged**
