### PR TITLE
Removed time.sleep()s, updated TBB version in Dockerfile

### LINKED ISSUE #3486: [functional testing] Remove time.sleeps where possible
In the existing Tor Browser functional testing branch, `time.sleep`s are introduced to wait for elements to appear, etc. We should use `FunctionalTest.wait_for` where needed (and increase the timeout as needed since we're testing over Tor). Otherwise, the overall test time may be unnecessarily lengthened.  

Epic: #3659

### PR DESCRIPTION
**Pull request by zenmonkeykstop**
## Status

Ready for review

## Description of Changes

Fixes #3486 

Replaces time.sleep(self.sleep_time) calls with self.wait_for (<function>, timeout=self.sleep_time), reducing the time it takes to run functional tests against the SD dev container.

Misc updates to functional and page layout tests to reduce flakiness:
- increased alert wait timeout to 60s
- wrapped problematic interactions with more wait_for()s and verification checks
- for some still-flaky clicks, replaced click action with send_keys(Keys.ENTER), or explicitly set focus with move_to()s.

Updates TBB version to 8.0.3 in dev container dockerfile (previous versions had been removed from repos).

## Testing
Run the functional tests with:
```
cd securedrop 
./bin/dev-shell ./bin/run-test tests/functional/
````
Docker build should complete successfully. Tests should complete without error.

### If you made non-trivial code changes:

- [x] I have written a test plan and validated it for this PR

### CODE REVIEW

**Comment by redshiftzero** [comment]
@kushaldas want to review this one?

**Comment by kushaldas** [comment]
Note: The latest Tor browser version is `8.0.3`.

**Comment by zenmonkeykstop** [comment]
Rebased and tidied up a bit.

**Comment by zenmonkeykstop** [comment]
@kushaldas any chance you could post or share the full output from the test run? I can't duplicate a lot of these failures.

**Comment by redshiftzero** [comment]
@kushaldas d48de8b _should_ resolve flakiness you saw in your last report 🤞 

A couple other questions:

* why are the sleeps necessary for the lines including the `# Long waits` comment?
* remind me: is there a special reason we have a `time.sleep(5)` after the modal related interaction steps? 

Happy to help on these, just wanted to clarify if these are there intentionally there for some reason

**Comment by zenmonkeykstop** [comment]
@redshiftzero  :+1: from me, thanks for help and advice!

**Pull request merged**
