### PR TITLE
Secure tempfile refactor alternative test fix

### PR DESCRIPTION
**Pull request by garrettr**
Minimal alternative fix for broken tests in #1810.

I do not think this should necessarily supersede #1810; I am just posting it as an alternative way to fix the tests. @fowlslegs' work in #1810 seems to me to be a good start on unit tests for `store.save_file_submission`, so I think ideally my work from this branch would be incorporated into #1810, which would then be merged.

@fowlslegs What do you think?

### CODE REVIEW

**Comment by fowlslegs** [comment]
This is what I wanted to do at first, but couldn't figure out how to do it. Probably just bad oversight when reading the documentation.

I agree on the final code state we want to achieve here. I think that merging this PR, closing #1810, and then making a small follow up PR including [the test here](https://github.com/freedomofpress/securedrop/pull/1863/commits/f489353293f80ad720dadf94a93d23950ff8576e#diff-e72734cd811fe95d511a138acdd0c91bR74) (modified to make use of a spy)  to increase `store` coverage will be a slightly easier way to get to that state though.

**Comment by fowlslegs** [comment]
Locally I dropped the middle two commits and then rebased on develop. Okay if I push that and then we merge?

**Comment by garrettr** [comment]
@fowlslegs Force push that branch to this PR, I'll rubber-stamp it, then it should be good to go.

**Comment by garrettr** [comment]
@fowlslegs LGTM! I can't approve this branch via GitHub review because I'm not allowed to approve my own branches, but I'd say it's good to go once CI passes.

**Pull request merged**
