### PR TITLE
[0.4.4] Rename datetimeformat into rel_datetime_format

### LINKED ISSUE #2374: Rename `datetimeformat` to prevent collisions with Babel functions
# Feature request

## Description

Babel injects a function called `datetimeformat` into the jinja environment. We do too, manually. They do not have the same args, and we get `TypeError`s. We should rename our functions to fix this.

## User Stories

As a dev, I don't want to have to track down weird errors if we don't do things in exactly the right order.

### PR DESCRIPTION
**Pull request by redshiftzero**
## Status

Ready for review

## Description of Changes

Fixes #2374. Extension of #2424. I've pulled the contributor's commit in here, leaving their PR open such that their PR will show as merged when/if this followup is merged. In another commit I've completed the renaming of `datetimeformat` -> `rel_datetime_format` and addressed @heartsucker's comments in the code review of #2424. We should merge this in for 0.4.4 prior to the code freeze EOD tomorrow.

## Testing

Does CI pass?

## Deployment

All files shipped in securedrop-app-code package.

### If you made changes to the app code:

- [x] Unit and functional tests pass on the development VM

### CODE REVIEW

**Comment by heartsucker** [comment]
Since this is minor and we want to close this before 0.4.4, you can just merge it if you make those changes. Timezones and all.

**Comment by redshiftzero** [comment]
Thanks for super fast review @heartsucker :) Good catches - fixed, squashed and repushed.

**Comment by redshiftzero** [comment]
Well the "such that their PR will show as merged when/if this followup is merged" was not true, perhaps due to me rebasing on current `develop`? Oh well.

**Comment by dachary** [comment]
@redshiftzero yes, the magic happens when the commit sha are the same ;-)

**Pull request merged**
