### PR TITLE
Set capability `dac_override` for Apache AppArmor

### LINKED ISSUE #2105: After unattended update, can't connect to SecureDrop app
# Bug

## Description

Overnight one of the unattended upgrades left the SecureDrop app server unable to be reached from Tor Browser.

## Steps to Reproduce

SecureDrop 0.4.1

1. SecureDrop had been running upgrades flawlessly.
2. An unattended upgrade last night seems to have caused the break.

## Expected Behavior

Can access SecureDrop from Tor Browser.

## Actual Behavior

Unable to connect.

## Comments

* I've tried restarting the servers twice.
* I can still ssh in to both mon & app from the Admin workstation.
* Searching issues I came across #1078

From the OSSEC logs around the time it became unreachable:

```bash
Rule: 100012 fired (level 7) -> "Apparmor denied event"
Portion of the log(s):

Aug 14 XX:00:XX app kernel: [   36.599669] audit: type=1400 audit(XXX): apparmor="DENIED" operation="capable" pid=XXXX comm="apache2" capability=1  capname="dac_override"


Rule: 1002 fired (level 2) -> "Unknown problem somewhere in the system."
Portion of the log(s):

Aug 14 XX:01:XX app Tor[XXXX]: Onion service connection to [scrubbed] failed (connection refused)
```

### PR DESCRIPTION
**Pull request by conorsch**
## Status

Ready for review.

## Description of Changes

We were previously relying on the tor apparmor abstractions to provide `capability dac_override`. When the tor package removed the capability in favor of `dac_read_search`, the apache service started
failing due to overconfinement. Editing the AppArmor profile for Apache such that the dac_override capability is now explicitly, rather than implicitly, included.

Fixes #2105.

## Testing
Confirm both clean installs on staging and upgrades from 0.4.1 restore functionality for the web applications (both Source and Journalist Interfaces).

## Deployment
Hotfix release to handle breaking changes from upstream tor package. Discussion of reducing exposure to this form of breakage is in #2106.

### If you made changes to the app code:

- [ ] Unit and functional tests pass on the development VM

### If you made changes to the system configuration:

- [x] [Configuration tests](https://docs.securedrop.org/en/latest/development/testing_configuration_tests.html) pass

### If you made changes to documentation:

- [ ] Doc linting passed locally

### CODE REVIEW

**Comment by dachary** [comment]
<pre>
E           OSError: [Errno 39] Directory not empty: '/tmp/securedrop'
</pre>
looks like tests racing against each other ?

**Comment by conorsch** [comment]
Yes, that's an easy toggle to kick off the Travis suite again, but I see that my omission of updated config tests is going to cause Circle CI to fail too. Patching commit...

**Comment by conorsch** [comment]
All CI is passing. Running through the QA checklist described in #2107 prior to merging.

**Comment by conorsch** [comment]
Confirmed upgrade resolves issue on hardware. Merging and continuing with pre-release QA process in #2107.

**Pull request merged**
