### PR TITLE
Add ssh instructions link to create_admin_account.rst

### PR DESCRIPTION
**Pull request by kstohr**
## Status

Ready for review

## Description of Changes
Changes proposed in this pull request:
https://github.com/freedomofpress/securedrop/issues/3395

## Testing
make docs-lint - passed

### CODE REVIEW

**Comment by dachary** [comment]
Could you please remove the **updated setup_development doc** commit from this PR? It sneaked in from another PR ;-)

**Comment by dachary** [comment]
> If you are installing SecureDrop yourself

Could you please clarify why this part is necessary? In which case would the reader be someone who does not install SecureDrop themselves?

**Comment by kstohr** [comment]
@dachary I am afraid I cannot clarify. I discussed this ticket with @kushaldas prior to updating the text and that wording came from @kushaldas. According to him, this part of the setup process is often supervised by SeccureDrop trainers. In general they would prefer to setup the first admin user for their partners rather than have them SSH and do it themselves. If, however, "they are installing SecureDrop themselves" then they will need to SSH in to create that first user. If this does not answer your question, I think we'd need @kushaldas to weigh in as that wording was discussed and agreed upon with him.

**Comment by dachary** [comment]
> According to him, this part of the setup process is often supervised by SecureDrop trainers

Ah, that makes sense now. I don't think we distinguish between admins being in training or on their own elsewhere in the documentation. Unless I'm mistaken we always assume the admin is on their own.

**Comment by dachary** [comment]
> If you have preferred wording, let me know.

Not changing **To** into **If you are installing SecureDrop yourself, to** would be good enough to clear the confusion.

**Comment by dachary** [comment]
@kstohr this needs rebasing because there were changes merged that conflict with yours.

**Comment by dachary** [comment]
rebased to resolve the conflict

**Pull request merged**
