### PR TITLE
Bump sequoia-openpgp to 1.20.0

### LINKED ISSUE #7177: Upgrade sequoia-openpgp to latest (1.20.0)
## Description

We've fallen a bit behind on upstream releases, let's stay up to date with the latest.

https://gitlab.com/sequoia-pgp/sequoia/-/blob/openpgp/v1.20.0/openpgp/NEWS?ref_type=tags (we're currently on 1.17.0).

### PR DESCRIPTION
**Pull request by legoktm**
## Status

Ready for review

## Description of Changes

See <https://gitlab.com/sequoia-pgp/sequoia/-/blob/openpgp/v1.20.0/openpgp/NEWS?ref_type=tags> for a list of changes, none of which should require changes on our end.

Fixes #7177.

## Testing

How should the reviewer test this PR?

* [ ] CI passes

## Deployment

Any special considerations for deployment? n/a, applies equally to both

## Checklist
- [ ] Linting (`make lint`) and tests (`make test`) pass in the development container

### CODE REVIEW

**Comment by legoktm** [comment]
CI needs https://github.com/freedomofpress/securedrop/pull/7179 to be happy.

**Review by zenmonkeykstop — DISMISSED** [review]
CI is good, LGTM

**Review by zenmonkeykstop — APPROVED** [review]
CI is good, LGTM

**Review by zenmonkeykstop — APPROVED** [review]
One more time with feeling

**Review by zenmonkeykstop — DISMISSED** [review]

**Review by zenmonkeykstop — APPROVED** [review]
LGTM

**Pull request merged**
