### PR TITLE
Update CODE_OF_CONDUCT.md

### PR DESCRIPTION
**Pull request by sssoleileraaa**
fix typos

### CODE REVIEW

**Review by conorsch — DISMISSED** [review]
Thanks, @creviera. Same edit is relevant for at least https://github.com/freedomofpress/securedrop.org/blob/6b526807f665ea2cc0aa1bcba3b10264b618998a/CODE_OF_CONDUCT.md, and there may be other spots we want to touch-up too.

**Comment by sssoleileraaa** [comment]
looks like the same updates will need to be applied across 10 different repos total. we may be missing our CoC in other repos too.

**Comment by sssoleileraaa** [comment]
i created https://github.com/orgs/freedomofpress/projects/1#card-54279621 for followup on improvements we could make to this doc/maintaining this doc across many repos. for now, just fixin typos like a human linter.

**Comment by sssoleileraaa** [comment]
prs to repos where i couldn't push directly to the main branch: 
* https://github.com/freedomofpress/qubes-template-securedrop-workstation/pull/18
* https://github.com/freedomofpress/securedrop-sdk/pull/154
* https://github.com/freedomofpress/securedrop-docs/pull/147
* https://github.com/freedomofpress/securedrop.org/pull/804
* https://github.com/freedomofpress/securedrop-workstation/pull/654
* https://github.com/freedomofpress/securedrop-client/pull/1216

**Review by emkll — APPROVED** [review]
Thanks!

**Pull request merged**
