### PR TITLE
Remove warning about insecure login in Tor Browser

### PR DESCRIPTION
**Pull request by mrphs**
## Status

Ready for review

## Description of Changes

The unfortunate underlaying issue got fixed in Tor Browser version 7.0.4 and 7.5a4.
See https://trac.torproject.org/projects/tor/ticket/21321 for more info.

Reverts PR #2038: removing the warning from journalist and source docs
Related to issue #1882

### CODE REVIEW

**Comment by dachary** [comment]
it would be good to have that in 0.4.3 don't you think ? Very good news :-)

**Comment by dachary** [comment]
@mrphs the travis errors are completely unrelated, no need to worry about them :-)

**Comment by dachary** [comment]
@mrphs I tried to change the base to release/0.4.3 but it does not do the right thing. If you agree this should be in 0.4.3, could you cherry-pick your commit to the release/0.4.3 branch and repush ? If you're not sure how to do that I can do it for you.

**Comment by redshiftzero** [comment]
Good call @dachary, I agree - let's bring this in for 0.4.3.

**Comment by redshiftzero** [comment]
Merged in @mrphs's commits in #2280 for the release tomorrow. Thanks @mrphs! Note that your commits will then get synced back to `develop` tomorrow.

**Comment by mrphs** [comment]
Hey folks! Thanks for pushing this forward. I'm sorry I was a bit afk and missed what was asked of me.

**Pull request closed without merging**
