### PR TITLE
Increase default session timeout to 120 minutes

### LINKED ISSUE #2503: Increase default session timeouts to 120 minutes
## Description

According to [this plot](https://metrics.torproject.org/torperf.html?start=2017-08-03&end=2017-11-01&source=all&server=onion&filesize=5mb), it currently takes about ~35 seconds to download a 5 MB file over Tor: 

torperf-onion-2017-08-03-2017-11-01-all-5mb

The maximum size of a SecureDrop submission is 500 MB, so the time it would take to download is 35 seconds * (500/5) = 3500 seconds, or just under an hour. As such, to be safe we should bump the session timeout to at least 120 minutes. 

## User Stories

As a SecureDrop source/journalist, I don't want to wait a very long time to upload/download a file over Tor, only to be logged out by the SecureDrop session timeout.

### PR DESCRIPTION
**Pull request by redshiftzero**
## Status

Ready for review

## Description of Changes

Fixes #2503.

Changes proposed in this pull request:
* In order to allow large file uploads to complete, increase
the session timeout to 120 minutes. 

## Testing

Ci should pass

## Deployment

Minor config change. The session expiration is not yet in prod.

### If you made changes to the app code:

- [x] Unit and functional tests pass on the development VM

### CODE REVIEW

**Comment by heartsucker** [comment]
Holding off on the merge pending @dachary's input in the original issue on this. Will merge after a few days if the conversation doesn't advance.

**Comment by redshiftzero** [comment]
Woo, tests passing. Restamp needed and then this is mergeable

**Comment by redshiftzero** [comment]
I'm closing this in favor of an approach like what is proposed in [this comment](https://github.com/freedomofpress/securedrop/issues/2503#issuecomment-344449422) to allow for multiple file uploads on the source interface (PR pending in #2573).

**Comment by redshiftzero** [comment]
#2573 did not make the merge window for 0.5, reopening this as a minimal change for 0.5

**Pull request merged**
