### PR TITLE
Merge 0.3.12 into master

### PR DESCRIPTION
**Pull request by redshiftzero**
## Status

Ready for review

## Description of Changes

In #1559 in [this comment](https://github.com/freedomofpress/securedrop/issues/1559#issuecomment-279488170), it was suggested to update `master` to the latest point release (as git-flow prescribes), which at the time this PR was submitted was 0.3.12. 

From here, we can decide if we're moving on from git-flow whether we should merge develop into master (possibly an ugly merge but I would argue it provides the cleaner git history) and retire develop, or whether retiring master is the way to go (avoids the merge). Even if we retire master, we want to have a clean history from the point where we moved from git-flow to another strategy, which this PR would provide.

Changes proposed in this pull request:

- Merges 0.3.12 into master

## Testing

1. Test that tests pass in the development VM
2. Test that tests pass in the staging VMs

### If you made changes to the app code:

- [x] [Unit and functional tests pass](https://travis-ci.org/freedomofpress/securedrop/builds/224115286) on the development VM

### If you made changes to the system configuration:

- [x] Testinfra tests pass on the development VM

### CODE REVIEW

**Comment by fowlslegs** [comment]
Really merges 0.3.5 - 0.3.12 into master. Wew!

**Comment by conorsch** [comment]
Coveralls check hasn't returned; looks like the path to the tests file is different, so we should probably update the travis config here so that it works, even if temporarily.

**Comment by redshiftzero** [comment]
Ok I've added a commit that gets the coveralls checks working. Note they weren't working because at this stage in the SecureDrop project apparently the test wrapper  in `manage.py` wasn't running `pytest` with `--cov`. So I had to patch `manage.py` to get that to work.

**Comment by fowlslegs** [comment]
When working with Vagrant 1.9.1 I got the error:

```
There are errors in the configuration of this machine. Please fix the following errors and try again:

Vagrant:
* Unknown configuration section 'hostmanager'.
```

I cherry-picked https://github.com/freedomofpress/securedrop/pull/1311/commits/6c93d6e56ebecfa76953e991b0270ea3820a415e so I could work with Vagrant to test this. Do we agree that I should push that commit here?

**Comment by redshiftzero** [comment]
Hmm, I was able to `vagrant up` without issue on this branch using `Vagrant 1.8.5`. However, if 6c93d6e56ebecfa76953e991b0270ea3820a415e fixes the issue on Vagrant 1.9.1, I think it's fine to push here.

**Comment by conorsch** [comment]
> they weren't working because at this stage in the SecureDrop project apparently the test wrapper  in `manage.py` wasn't running `pytest` with `--cov`. So I had to patch `manage.py` to get that to work. 

That's fine. We could have removed the coverage checks from master's Travis config, but I like the patch approach better. 

> I cherry-picked 6c93d6e so I could work with Vagrant to test this. Do we agree that I should push that commit here?

You can run `vagrant plugin install vagrant-hostmanager` to sidestep the error, so you don't have to cherry-pick. I say let's leave out the cherry-pick, since the goal with this PR is to bring the master branch up to date with the current release, which still contains that line.

**Comment by redshiftzero** [comment]
Ah thanks @conorsch. :+1: to skipping cherry picking in that case

**Comment by conorsch** [comment]
Hoowee! About time we got to this. Thanks for tackling it @redshiftzero. I tested a merge locally, pulling the latest `develop` branch into this one, and surprisingly there were very few conflicts that needed to be manually resolved—two, in fact, and they were simple for a human's eye.

All told I'm happy with these changes going in as-is. As a reminder, this PR is simply bringing `master` up to date with the most current release, which is a necessary step before we pull in the backlog of changes from the `develop` branch. There's a lot of back-and-forth in #1559, but in short, the next step is to reconcile develop and master, now that we've reconciled release/ and master.

**Pull request merged**
