### PR TITLE
[2.5.2]backport test and dependency fixes

### PR DESCRIPTION
**Pull request by zenmonkeykstop**
## Status

Ready for review

## Description of Changes

Towards #6749 

Backports a minimal set of recent `develop` changes into `release/2.5.2` required to get CI passing. Note that this PR does not bump the version - this is intentional, an rc1 should be cut once the pending `cryptography` and `werkzeug` updates have been backported.

## Testing
- [x] CI is passing
- [ ] (optional) `make safety` passes locally

### CODE REVIEW

**Comment by legoktm** [comment]
I think you'll also want to cherry-pick a0751e60d870a90d02e1a716d7cfbc85e05449c8 and probably 193b8d1d94059031e549e43da5bdcb6b850e5cda.

**Review by eaon — APPROVED** [review]

**Comment by zenmonkeykstop** [comment]
> I think you'll also want to cherry-pick [a0751e6](https://github.com/freedomofpress/securedrop/commit/a0751e60d870a90d02e1a716d7cfbc85e05449c8) and probably [193b8d1](https://github.com/freedomofpress/securedrop/commit/193b8d1d94059031e549e43da5bdcb6b850e5cda).

Can probably live without them, since they were motivated by changes on develop that we aren't pulling in here.

**Comment by legoktm** [comment]
> > I think you'll also want to cherry-pick [a0751e6](https://github.com/freedomofpress/securedrop/commit/a0751e60d870a90d02e1a716d7cfbc85e05449c8) and probably [193b8d1](https://github.com/freedomofpress/securedrop/commit/193b8d1d94059031e549e43da5bdcb6b850e5cda).
> 
> Can probably live without them, since they were motivated by changes on develop that we aren't pulling in here.

The response to develop changes was the other commit in that PR (2f13cf16a6c8a78adb80dca18cfada3110e5cd1f) - but if I git blamed correctly, the issue fixed in a0751e6 is a 2.5.1 staging regression, it's just that without 193b8d1 the staging CI isn't actually verifying that the SI works...

**Comment by zenmonkeykstop** [comment]
OK, fair, will pull them in with the RC bump.

**Pull request merged**
