### PR TITLE
s/are generally/is generally/ - Fix #2908.

### LINKED ISSUE #2908: docs: s/are generally/is generally/
# Bug

## Description

**Maintaining periodic backups are generally a good practice** should read **Maintaining periodic backups is generally a good practice** in [develop/docs/backup_and_restore.rst](https://github.com/freedomofpress/securedrop/blob/develop/docs/backup_and_restore.rst)

### PR DESCRIPTION
**Pull request by EdOverflow**
## Status

Ready for review

## Description of Changes

Fixes #2908 .

Changes proposed in this pull request: `s/are generally/is generally/`

## Testing

👀 

### If you made changes to documentation:

- [x] Doc linting passed locally

### CODE REVIEW

**Comment by dachary** [comment]
@EdOverflow I assume you found the issue #2908 via https://twitter.com/SecureDrop/status/960601713777418240 ? We're trying new things to make SecureDrop more inviting to newcomers and your input would be most welcome :-)

**Comment by EdOverflow** [comment]
Hi @dachary,

Yep, I came across that Tweet and wanted to give it a go. I have [reported potential security issues](https://github.com/freedomofpress/securedrop/commit/8cc163d31af77a86961754535ce98c060bbe04ed) in the past and was impressed by how organised this project was — this is further reinforced by the issue template you present contributors when submitting a PR. On top of that, your documentation is beautifully written and easy to follow.

**Comment by dachary** [comment]
Wow, thanks for the kind words, you made my day :-)

**Comment by conorsch** [comment]
Thank you, @EdOverflow! Great to see you again. 😀

**Pull request merged**
