### PR TITLE
Update version to 2.11.0

### PR DESCRIPTION
**Pull request by zenmonkeykstop**
## Status

Ready for review 

## Description of Changes

Towards #7372.

- increments version to 2.11.0 and updates changelog

## Testing

- [ ] CI is passing
- [x] base is release/2.11.0
- [ ] version is incremented correctly
- [ ] changelog looks good

### CODE REVIEW

**Comment by legoktm** [comment]
Let me see why the noble builds are failing...

**Comment by legoktm** [comment]
Oh, it's finding the dbgsym package instead of the real deb :/ weird that we haven't hit this race condition before.

**Comment by legoktm** [comment]
```patch
diff --git a/builder/tests/test_securedrop_deb_package.py b/builder/tests/test_securedrop_deb_package.py
index f4cc9b646..46c92c99a 100644
--- a/builder/tests/test_securedrop_deb_package.py
+++ b/builder/tests/test_securedrop_deb_package.py
@@ -9,7 +9,11 @@ UBUNTU_VERSION = os.environ.get("UBUNTU_VERSION", "focal")
 SECUREDROP_ROOT = Path(
     subprocess.check_output(["git", "rev-parse", "--show-toplevel"]).decode().strip()
 )
-DEB_PATHS = list((SECUREDROP_ROOT / f"build/{UBUNTU_VERSION}").glob("*.deb"))
+DEB_PATHS = [
+    pkg
+    for pkg in (SECUREDROP_ROOT / f"build/{UBUNTU_VERSION}").glob("*.deb")
+    if "dbgsym" not in pkg.name
+]
 PYTHON_VERSION = {"focal": "8", "noble": "12"}[UBUNTU_VERSION]
 SITE_PACKAGES = f"/opt/venvs/securedrop-app-code/lib/python3.{PYTHON_VERSION}/site-packages"
```

should do the trick (waiting for my local build to finish); okay if I add that to this PR @zenmonkeykstop ?

**Review by legoktm — APPROVED** [review]
Approving everything except the commit I pushed, and we're still waiting on CI (but the build-debs jobs are fixed now)

**Review by cfm — APPROVED** [review]
6de091dd0abdbb4f9e765cd5c303eb52bf777e5d looks good on visual review.  `build-debs` is happy with it, and `test_securedrop_deb_package` would have screeched if there were a problem.

**Pull request merged**
