### PR TITLE
Timing and token reuse

### PR DESCRIPTION
**Pull request by fowlslegs**
## Status

Ready for review.

## Description of Changes

Eliminates some timing leaks and prevents the same valid token from being used to authenticate twice in a row.

### If you made changes to the app code:

- [x] Unit and functional tests pass on the development VM

### If you made changes to the system configuration:

- [x] Testinfra tests pass on the development VM

### CODE REVIEW

**Comment by redshiftzero** [comment]
Hmm, builds seem to be reliably failing on Travis on this - you didn't see any test failures locally?

**Comment by conorsch** [comment]
Also seeing 22 failures locally, same as in Travis.

**Comment by conorsch** [comment]
`hmac.compare_digest()` was [added in Python 2.7.7](https://docs.python.org/2/library/hmac.html), but Ubuntu Trusty includes only Python 2.7.6. So these tests will never pass with the current implementation, nor did they prior to submission.

**Comment by conorsch** [comment]
We cannot trivially upgrade the version of Python running on SecureDrop instances, so we'll need to consider another path. Worth nothing that #1530 considers upgrading the Trusty hosts to Xenial, which would get us newer versions.

**Comment by fowlslegs** [comment]
Re-posting from Slack:

> Too much multitasking, sorry.
>
>Tests were running and I preemptively checked them, then started on something else and submitted the PR w/o thinking.

Also, re-opening because I just replaced `hmac.compare_digest` with another constant-time comparison function from Django.

**Comment by fowlslegs** [comment]
Closing for now because I know this won't get considered for merge for a really long time and will be out of date by then.

**Pull request closed without merging**
