### PR TITLE
Pybabel and German translations

### PR DESCRIPTION
**Pull request by heartsucker**
#### Added
- `pybabel` integration
- German translations
- Updated `manage.py` to take care of all translation related operations
- Updated build scripts to compile translations on `postinst`
- Updated AppArmor profile
#### Notes
- Intentionally left out internationalization of user names, passwords, and code names because:
  - Python 2 is a sad panda w.r.t. unicode
  - Multiple unicode characters represent the same glyph in some languages ([#1](https://en.wikipedia.org/wiki/Unicode_equivalence#Character_duplication), [#2](https://en.wikipedia.org/wiki/Homoglyph#Unicode_homoglyphs)) and this is a security / usability issue
- Writing tests to automatically check translations for HTML compliance was an endless hell, so I left it out since a human eye can catch most errors
#### Outstanding
- Not a regression, but "Select All" and "Select None" do nothing even with JavaScript enabled in Firefox 40.0.3 on OSX 10.10.5.
- Transifex doesn't actually link to anything since that seems like something y'all would want to set up instead of me
#### Related
- Issue #127
- PR #753
- Issue #999
- Issue #1000
- Issue #1001
#### Kudos

Some html came from @edwincheese when I branched. Translations edited by @jaseg.

### CODE REVIEW

**Comment by garrettr** [comment]
@ehartsuyker Sorry for the delay in reviewing this! I'm looking at it now.

**Comment by ehartsuyker** [comment]
Sup y'all. Any chance we could get this merged? I'm doing a lot of rebasing to keep it up to date.

**Comment by ehartsuyker** [comment]
Are any of you kids at 32C3? And if so, who wants a six pack for helping get this merged?

**Comment by mark-in** [comment]
Eric Hartsuyker:
> Are any of you kids at 32C3? And if so, who wants a six pack for helping get this merged?

Yeap, I'm there!
Right now I'm developing the i18n that does not leak source's lang
preference (#1226, it works!). I'm looking forward meeting you all so we
can hack together! Any ideas of possible rendezvous? :)

**Comment by ehartsuyker** [comment]
@mark-in I'm meeting up with the OWS / Signal kids tonight at 730 at the rocket out front of the conference center. Come if you want, otherwise we can try another time.

**Comment by ehartsuyker** [comment]
Hello again. Is there any way one of the FPF guys could take a peek at this? Some colleagues and I have been wanting to set SecureDrop up in Berlin for a while, but we kinda need to support the native language.

**Comment by ehartsuyker** [comment]
@garrettr @conorsch Hola. It's my monthly check in again to see if we can get this merged in. I have an SD set up I'm testing in Berlin (hopefully going live this weekend) and would like to support the local languages. If part of the reason this hasn't been merged yet is you need someone to manage the i18n side of things (merges, keep an eye on transifex), I can volunteer my time toward that.

**Comment by garrettr** [comment]
@ehartsuyker Thanks for pinging us, and for being so patient with us. We're currently working hard on revamping the support systems for SecureDrop, but are nearly done with that project. Once it is done, we will return our focus to the next version of SecureDrop, which will prioritize i18n/l10n. I'll update this issue again when we are moving forward.

**Comment by ehartsuyker** [comment]
@garrettr Awesome. Thanks. <3

**Comment by heartsucker** [comment]
@garrettr Hello again. I know this needs a rebase, but before I do that, how does this look for a merge? Is this (loosely) the way you'd want the code structured? Does this need to have documentation added so developers in the future know to use the translation functions on strings? Etc. etc.

**Comment by heartsucker** [comment]
Oh heyyyyy. I have rebased this again. Anyone want to take a look? @conorsch @garrettr 

- New problems that have come during this rebase. `index.html` won't translate for whatever reason (I'll keep poking at it, but for now everything else is mergeable).
- We now have strings in the CSS which means we have to server the CSS based on locale. These changes could be changed back easily so we can keep the overhead down.

**Comment by heartsucker** [comment]
I would just like to say that I am a divining rod for the world's strangest bugs.
https://github.com/python-babel/flask-babel/issues/108

This PR is likely dependent on an upstream fix unless we want some sort of hack to move the offending `html` tags to another jinja template and import it so the extraction will succeed.

**Comment by redshiftzero** [comment]
I know that there is a lot of demand for internationalization of SecureDrop and we appreciate this is incredibly important. We really want to translate and localize SecureDrop, but given some of the other [improvements](https://github.com/freedomofpress/securedrop/milestones) we're working on and the fact that we're a small team, we don't currently have the bandwidth to add this feature and begin managing translations. We really appreciate this contribution, but given that we can't add this right now and that this PR has been pending merge for almost two years, I am going to close this PR for now.

**Pull request closed without merging**
