### PR TITLE
fix for #2307, inconsistent documention breaks ansible playbook

### LINKED ISSUE #2307: Inconsistent filenames in docs
# Bug

## Description

When we advise people to export their [SecureDrop public key](https://docs.securedrop.org/en/stable/generate_securedrop_application_key.html), the documentation explicitly says to export it as `SecureDrop.pub.asc`. Later when we have them run the Ansible playbook, we tell them to copy the wrong file to the `ansible-base` folder.  

## Steps to Reproduce

Export the `SecureDrop.pub.asc` and copy it to a Transfer Device. Then execute the command in the documentation. `cp /media/[USB folder]/SecureDrop.asc install_files/ansible-base` and run your playbook.

## Expected Behavior

Playbook installs SecureDrop.

## Actual Behavior

Playbook fails to run

### PR DESCRIPTION
**Pull request by freddymartinez9**
## Status

Ready for review / Work in progress

## Description of Changes

Fixes #2307 

Changes proposed in this pull request:

## Testing

Ran the playbook with the corrected name on a live SecureDrop install. 

## Deployment

None 

### If you made changes to documentation:

- [X] Doc linting passed locally

### CODE REVIEW

**Comment by conorsch** [comment]
@freddymartinez9 Looks good! FYI, buried in the [contributor documentation](https://docs.securedrop.org/en/latest/development/documentation_guidelines.html#testing-documentation-changes) is this useful nugget:

> The CI tests by default create staging servers to test the application code. If your PR only makes documentation changes, you should prefix the branch name with `docs-` to skip the staging run. Project maintainers will still need to approve the PR prior to merge, and the linting checks will also still run.

Makes review much faster, since we don't need to wait 20-30 minutes for the full CI run to complete. Just mentioning it for the future, as you'll likely have more docs improvements in the coming days.

**Comment by redshiftzero** [comment]
[Staging failure](https://circleci.com/gh/freedomofpress/securedrop/2036) is a flake, restarting.

**Comment by redshiftzero** [comment]
*Note:* Coveralls check is decreasing but this is spurious (same issue as in [this PR](https://github.com/freedomofpress/securedrop/pull/2306#issuecomment-329632602)).

**Comment by redshiftzero** [comment]
#2253 this time, restarting:

```
TASK [Wait for server to come back.] *******************************************
ok: [app-staging -> localhost]
fatal: [mon-staging -> localhost]: FAILED! => {"changed": false, "elapsed": 301, "failed": true, "msg": "Timeout when waiting for search string OpenSSH in ec2-13-57-16-115.us-west-1.compute.amazonaws.com:22"}
	to retry, use: --limit @/root/sd/install_files/ansible-base/securedrop-staging.retry
```

**Pull request merged**
