### PR TITLE
Bump 2.0.1 version

### PR DESCRIPTION
**Pull request by zenmonkeykstop**
## Status

Ready for review

## Description of Changes

Towards #6034 

Updates version to 2.0.1

## Testing

- [ ] base is `release/2.0.1`
- [ ] version is incremented correctly
- [ ] CI is passing.

### CODE REVIEW

**Review by sssoleileraaa — APPROVED** [review]
- [x] base is `release/2.0.1`
- [x] version is incremented correctly
- [ ] CI is passing.

**Comment by sssoleileraaa** [comment]
Looks like two admin tests failing, see https://app.circleci.com/pipelines/github/freedomofpress/securedrop/2690/workflows/7c80ff74-71ad-4af0-97b0-bc96a8fa70a6/jobs/55507:

tests/test_integration.py::test_check_for_update_when_updates_not_needed FAILED
tests/test_integration.py::test_update_with_duplicate_branch_and_tag FAILED

**Comment by zenmonkeykstop** [comment]
Those are expected as per: https://github.com/freedomofpress/securedrop/issues/5864

**Comment by zenmonkeykstop** [comment]
Kicked tests after the creation of the 2.01 release, all is well. it would be good to get a fix in for this before 2.1.0 if possible

**Pull request merged**
