### PR TITLE
docs: update screenshots for 0.8.0

### PR DESCRIPTION
**Pull request by dachary**
## Status

Ready for review

## Description of Changes

https://docs.securedrop.org/en/latest/development/i18n.html#the-day-of-the-release

* git checkout release/0.8
* make -C securedrop update-user-guides
* commit
* cherry-pick to release/develop

## Testing

Verify visually that each image is changed in a sensible way.

## Deployment

N/A

### If you made changes to documentation:

- [x] Doc linting (`make docs-lint`) passed locally

### CODE REVIEW

**Comment by heartsucker** [comment]
Do all of these need to get merged? This is a lot of binary data to stuff into `git`. if two screen shots are "pretty damn close" I'd day that's good enough to leave out as long as the intent is still clear.

**Comment by msheiny** [comment]
@heartsucker what about ... enabling git-lfs here a la #3176 . it adds an extra burden on the developers but otherwise requires no change to all other tooling (like CI, Tails, etc.)

**Comment by redshiftzero** [comment]
@heartsucker makes a good point, how about we: inspect these screenshots and see which ones have more changes beyond just the version string change, and just update those? Medium term (i.e. after 0.8.0 is released) we can look into #3176 as @msheiny suggests

**Comment by redshiftzero** [comment]
ok so there are five that have UI changes:

```
journalist-clicks_on_source_and_selects_documents.png
journalist-col_flagged.png
journalist-col_has_no_key.png
journalist-composes_reply.png
journalist-index_javascript.png
```

proposal: we remove the other images and squash into one commit

**Comment by redshiftzero** [comment]
actually, in the interests of time (i.e. avoiding another CI run), i'm going to merge this in as-is so that we can get these changes in for 0.8.0, will file followup issue after release for the best practice here going forward

**Pull request merged**
