### PR TITLE
[2.1.0] Merge translations

### PR DESCRIPTION
**Pull request by conorsch**
## Status

Ready for review

## Description of Changes

Merge translations for 2.1.0. See docs at https://docs.securedrop.org/en/stable/development/i18n.html#release-day

## Testing
- [ ] CI must be green, with translation tests run.

### CODE REVIEW

**Comment by conorsch** [comment]
CI failed: https://app.circleci.com/pipelines/github/freedomofpress/securedrop/3133/workflows/98b1e555-f97f-45f9-8b00-40a7affe4e4f/jobs/57441 with a bunch of selenium timeouts. Naively re-running CI, will investigate more closely if it fails again.

**Comment by conorsch** [comment]
Failed again: https://app.circleci.com/pipelines/github/freedomofpress/securedrop/3133/workflows/2991c4e8-d67a-4a13-a8d3-b7e2cbaf0cba/jobs/57442 with messages like 

```
 <class 'selenium.common.exceptions.ElementNotInteractableException'>
	Message: Element <a id="login-button" class="btn secondary" href="/login"> could not be scrolled into view
```

@cfm, mind taking a look here? I'm not sure we've run the translation tests successfully against the accessibility changes yet.

**Comment by conorsch** [comment]
>  I'm not sure we've run the translation tests successfully against the accessibility changes yet.

If I'm reading the history correctly, we coulda/shoulda requested that #6041 be submitted from a branch named `i18n-*` to catch these failures earlier. Building these changes locally and spot-checking a few languages, I can't identify any problems. Does it make sense to you that the aria-labels would break the selen tests? Maybe I haven't identified the right language locally to check yet....

**Comment by cfm** [comment]
In investigating with @conorsch, we discovered that a string in `fr_FR` was missing a closing (escaped) quotation mark, breaking in that locale:

1. the DOM on any page that includes this string;
2. any of the `{source,journalist}_navigation_steps` that visits such a page; and thus
3. any test that includes such a step.

This is fixed in [`freedomofpres/securedrop-i18n@d7dd943`](https://github.com/freedomofpress/securedrop-i18n/commit/d7dd9431c5d043bc28be2be771385eb699126fc8) and included under test here in <https://github.com/freedomofpress/securedrop/pull/6148/commits/4baf9eb440869c3b9ea8d33c512122802aee13cd#diff-6875d0f1666d8d0824d09e3e624b6f175ce1fd4bffe415a73b59af8f18b2a9ddR745>.

**Comment by conorsch** [comment]
Aye, CI is passing! Ready for final review. After merge, we'll still need to backport into the release branch.

**Review by cfm — APPROVED** [review]
Approved per checklist:

- [x] CI must be green (at last!), with translation tests run.

**Pull request merged**
