### PR TITLE
[1.7.0] Prepare changelog and version string for final release of SecureDrop 1.7.0

### PR DESCRIPTION
**Pull request by sssoleileraaa**
## Status

Ready for review

## Description of Changes

Towards https://github.com/freedomofpress/securedrop/issues/5689

Updated screenshots in docs were merged here: https://github.com/freedomofpress/securedrop-docs/issues/121

## Testing

- [ ] Changelog is accurate
- [ ] Version updated successfully
- [ ] Target branch is `release/1.7.0`

### CODE REVIEW

**Review by emkll — APPROVED** [review]
LGTM:

- [x] Changelog is accurate
- [x] Version updated successfully
- [x] Target branch is `release/1.7.0`

**Comment by conorsch** [comment]
The CI jobs for focal packages are failing on this PR:

* https://app.circleci.com/pipelines/github/freedomofpress/securedrop/1747/workflows/2cdb69df-65f2-4594-ba37-4493726e03c2/jobs/49443
* https://app.circleci.com/pipelines/github/freedomofpress/securedrop/1747/workflows/2cdb69df-65f2-4594-ba37-4493726e03c2/jobs/49441

Those are unrelated to the ongoing release. At a glance, I suspect we need to evaluate behavior of the update-version script on Focal packages, but either way, not a release blocker for #5689.

**Comment by emkll** [comment]
Since we aren't releasing for focal, the changes to the Focal deb changelog were dropped for int his PR. This explains the two scenario failures observed here. This will be resolved post-release when we bump the version strings to 1.8.0-rc1 prior to merging the changes introduced here into develop.

This is a one-time issue, as 1.8.0+ will officially support Xenial and Focal, thus containing an entry in the Debian changelog.

**Comment by emkll** [comment]
Merging despite the two focal-specific tests failing

**Pull request merged**
