### PR TITLE
Update generate_securedrop_application_key.rst

### PR DESCRIPTION
**Pull request by mac-tech**
Prevents loss of the SecureDrop private key at first reboot.

### CODE REVIEW

**Comment by fowlslegs** [comment]
This information is already under https://docs.securedrop.org/en/latest/set_up_tails.html#enable-persistent-storage. If we were to add something to the SVS setup section of the guide to help ensure people didn't miss that, I believe it should be a warning at the beginning of the section to make sure to have set up persistence with a link back to that section.

**Comment by mac-tech** [comment]
I think that reminder with link back would be a good idea. The recommendation to just turn all features in the tails setup guide is too general and does not convey which features are actually required for what purpose.

**Comment by fowlslegs** [comment]
That sounds like a reasonable docs improvement. If you'd like to fix this PR to the issues we both just raised that would be :100:.

**Comment by fowlslegs** [comment]
Closing this PR, but opened issue #1518. If you want to make one that more precisely resolves the issue and takes into account the existing documentation on creating persistent volumes you missed, do feel encouraged to do so! Thanks.

**Pull request closed without merging**
