### PR TITLE
Remove Tor2Web flash message template remnants

### PR DESCRIPTION
**Pull request by eaon**
## Status

Ready for review

## Description of Changes

#6300 already removed the logic in the app, this removes the equivalent bits in templates

## Checklist

- [x] These changes do not require documentation

### CODE REVIEW

**Review by legoktm — COMMENTED** [review]
What about the `banner-warning` class in CSS?
```
user@dev ~/g/f/securedrop> ack banner-warning --sass
securedrop/sass/modules/_banner-warning.sass
1:=banner-warning
2:  .banner-warning

securedrop/sass/modules/_flash.sass
55:    &.error, &.banner-warning

securedrop/sass/_base.sass
66:@import "modules/banner-warning"
136:  +banner-warning
```

There's also a mention in:
```
securedrop/journalist_templates/flashed.html
4:{% if category not in ["banner-warning","logo-success","logo-error","submission-preferences-success","submission-preferences-error","org-name-success","org-name-error", "testalert-success", "testalert-error", "testalert-notification"] %}
```

**Comment by eaon** [comment]
Thanks for catching! I didn't look deep enough whether the journalist interface used this or not, but it obviously doesn't, so good riddance to more dead code!

**Comment by zenmonkeykstop** [comment]
Changes look good overall - added a commit to remove the deleted banner warning template from Apache's apparmor profile.

**Review by zenmonkeykstop — APPROVED** [review]
LGTM - no references left to the warning banner that I can see.

**Pull request merged**
