### PR TITLE
Remove tests checking that no apparmor profiles are complaining

### PR DESCRIPTION
**Pull request by legoktm**
## Status

Ready for review

## Description of Changes

Ubuntu noble now has some transmission-related profiles in complain mode. We don't really care about this, so just remove the test. Ideally distros will continue to add more apparmor profiles, even if they're complain-only to start.
## Testing

How should the reviewer test this PR?

* [ ] visual review

## Deployment

Any special considerations for deployment? n/a

### CODE REVIEW

**Comment by zenmonkeykstop** [comment]
Is transmission actually being installed tho? In that case we should be removing said package, not disabling tests that get caught up on it.

**Comment by legoktm** [comment]
No, it isn't. But Ubuntu is installing a bunch of profiles like transmission, discord, steam, etc. I didn't check which package though (can do tomorrow).

**Comment by legoktm** [comment]
Here's all the profiles the base `apparmor` package installs: https://gist.github.com/legoktm/c15059f372eab85754829b6984237c67. Since it's in the base package, there's nothing we can really do and I don't think overriding/disabling them would be worth it.

**Review by zenmonkeykstop — APPROVED** [review]
LGTM based on visual review, discussion.

**Pull request merged**
