### PR TITLE
Update AppArmor profile for Xenial

### LINKED ISSUE #3962: [xenial] Update AppArmor rules to work on Trusty, Xenial
Explicit rules are required for Apache `mpm` worker/event changes. `gpg2` policy should permit links via `/var/lib/securedrop/keys/* l` or similar.

For simplicity, we should update AppArmor rules to work for both Trusty and Xenial, using a single template file for both distros.

Part of #3204.

### PR DESCRIPTION
**Pull request by emkll**
## Status

Ready for review
## Description of Changes

Fixes #3962 . Opened #4013 as follow up, uncovered in https://github.com/freedomofpress/securedrop/issues/3962.

## Testing
Spin up a staging environment on Xenial:
- `make build-debs-xenial`
- `molecule converge -s libvirt-staging-xenial`

#### Verify there are no further AppArmor violations:
- Perform actions on source and journalist interface (for example, submit documents and reply to those documents, or run the molecule verify scenario)
- Log into the app server and confirm:
- [ ] no `apparmor="DENIED"` in `/var/log/syslog` or in `journalctl -a`

#### Verify that keys are not being monitored by syscheck:
- Log into the mon server, `sudo su `and run `./agent-control -r -a` in `/var/ossec/bin` to force a syscheck run
- Wait until `INFO: Ending syscheck scan` appears in /var/ossec/logs/ossec.log`:
- [ ] syscheck does not monitor the private keys (hashes are in `/var/ossec/queue/syscheck/(app-staging 10.0.1.2->syscheck)`

#### Ensure there is no breakage in Trusty
- `make build-debs`
- `molecule converge -s libvirt-staging`
- [ ] Ensure the application behaves as expected.

## Deployment

These settings will be provided to new and existing installs via deb packages.

### If you made changes to the system configuration:

- [x] [Configuration tests](https://docs.securedrop.org/en/latest/development/testing_configuration_tests.html) pass

### If you made non-trivial code changes:

- [x] I have written a test plan and validated it for this PR

### CODE REVIEW

**Comment by emkll** [comment]
Thanks for the review @kushaldas ! 

I'm having some trouble reproducing the error you describe locally, could you please provide steps I can use to reproduce the error you've encountered?  You state that `This is broken`: I assume you mean a submission triggers error 500? Are there any AppArmor violations?

I've also updated the test plan with the steps I've used to test the Trusty scenario.

**Comment by kushaldas** [comment]
> You state that `This is broken:` I assume you mean a submission triggers error 500? 

Yes, the step I took and the error message is given below in that comment.

**Comment by kushaldas** [comment]
@emkll Please go ahead as my vagrant+molecule seems to be in broken state.

**Comment by emkll** [comment]
Thanks for the review @conorsch, I've addressed your comments:

`. Good catch on the syscheck alert. The file you mention is a flag to indicate that the migration to GnuPG 2.1 was completed (since it's a 1-time migration) [0]. That file would produce at most a 1-time alert (which would have gotten lost in the myriad of other syscheck that might occur during an upgrade). I've nonetheless added the ignore rule in syscheck, so that will be one alert less upon upgrade.

2. I've also added a test to ensure no AppArmor violations are in syslog. I think it's a good idea, but I am not sure how effective it is in it's current form, given the lack of interaction with the application. Happy to amend that test if you have any ideas. 

[0] : https://www.gnupg.org/documentation/manuals/gnupg/GPG-Configuration.html

**Comment by conorsch** [comment]
> I am not sure how effective it is in it's current form, given the lack of interaction with the application

Certainly it will be more useful once #3661 lands, but even in the near-term, devs can still do manual browser interaction, then run the verify logic to assert no denials via AppArmor. One foot in front of the other, so to speak.

> so that will be one alert less upon upgrade.

Given the cascade of OSSEC alerts the upgrade will generate, perhaps an `upgrade` target should silence OSSEC (as well as disable Apache and other pre-upgrade steps) ; the `install` target would then hook everything back up without any changes. Relevant to #3970.

**Pull request merged**
