### PR TITLE
Support developer virtualenv in Debian 12

### LINKED ISSUE #7153: dev virtualenv setup fails with python version >= 3.11
## Description

As reported in gitter, `make venv` fails with python 3.11 and greater.

## Steps to Reproduce

Using 3.11, run `make venv`

## Expected Behavior

successful completion, virtualenv with dev deps created.

## Actual Behavior

Failure, log as follows:
<details>

```
make venv
git config core.hooksPath ".githooks"
███ Preparing Python 3 virtual environment...
Creating /usr/bin/python3 virtualenv in .venv
created virtual environment CPython3.11.2.final.0-64 in 249ms
  creator CPython3Posix(dest=/home/user/securedrop/.venv, clear=False, no_vcs_ignore=False, global=False)
  seeder FromAppData(download=False, pip=bundle, setuptools=bundle, wheel=bundle, via=copy, app_data_dir=/home/user/.local/share/virtualenv)
    added seed packages: pip==23.0.1, setuptools==66.1.1, wheel==0.38.4
  activators BashActivator,CShellActivator,FishActivator,NushellActivator,PowerShellActivator,PythonActivator
  error: subprocess-exited-with-error
  
  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [54 lines of output]
      running egg_info
      writing lib3/PyYAML.egg-info/PKG-INFO
      writing dependency_links to lib3/PyYAML.egg-info/dependency_links.txt
      writing top-level names to lib3/PyYAML.egg-info/top_level.txt
      Traceback (most recent call last):
        File "/home/user/securedrop/.venv/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/home/user/securedrop/.venv/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/home/user/securedrop/.venv/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
                 ^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-build-env-jvfxat68/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 325, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=['wheel'])
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-build-env-jvfxat68/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 295, in _get_build_requires
          self.run_setup()
        File "/tmp/pip-build-env-jvfxat68/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 311, in run_setup
          exec(code, locals())
        File "<string>", line 271, in <module>
        File "/tmp/pip-build-env-jvfxat68/overlay/lib/python3.11/site-packages/setuptools/__init__.py", line 104, in setup
          return distutils.core.setup(**attrs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-build-env-jvfxat68/overlay/lib/python3.11/site-packages/setuptools/_distutils/core.py", line 184, in setup
          return run_commands(dist)
                 ^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-build-env-jvfxat68/overlay/lib/python3.11/site-packages/setuptools/_distutils/core.py", line 200, in run_commands
          dist.run_commands()
        File "/tmp/pip-build-env-jvfxat68/overlay/lib/python3.11/site-packages/setuptools/_distutils/dist.py", line 969, in run_commands
          self.run_command(cmd)
        File "/tmp/pip-build-env-jvfxat68/overlay/lib/python3.11/site-packages/setuptools/dist.py", line 967, in run_command
          super().run_command(command)
        File "/tmp/pip-build-env-jvfxat68/overlay/lib/python3.11/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "/tmp/pip-build-env-jvfxat68/overlay/lib/python3.11/site-packages/setuptools/command/egg_info.py", line 321, in run
          self.find_sources()
        File "/tmp/pip-build-env-jvfxat68/overlay/lib/python3.11/site-packages/setuptools/command/egg_info.py", line 329, in find_sources
          mm.run()
        File "/tmp/pip-build-env-jvfxat68/overlay/lib/python3.11/site-packages/setuptools/command/egg_info.py", line 550, in run
          self.add_defaults()
        File "/tmp/pip-build-env-jvfxat68/overlay/lib/python3.11/site-packages/setuptools/command/egg_info.py", line 588, in add_defaults
          sdist.add_defaults(self)
        File "/tmp/pip-build-env-jvfxat68/overlay/lib/python3.11/site-packages/setuptools/command/sdist.py", line 102, in add_defaults
          super().add_defaults()
        File "/tmp/pip-build-env-jvfxat68/overlay/lib/python3.11/site-packages/setuptools/_distutils/command/sdist.py", line 250, in add_defaults
          self._add_defaults_ext()
        File "/tmp/pip-build-env-jvfxat68/overlay/lib/python3.11/site-packages/setuptools/_distutils/command/sdist.py", line 335, in _add_defaults_ext
          self.filelist.extend(build_ext.get_source_files())
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "<string>", line 201, in get_source_files
        File "/tmp/pip-build-env-jvfxat68/overlay/lib/python3.11/site-packages/setuptools/_distutils/cmd.py", line 107, in __getattr__
          raise AttributeError(attr)
      AttributeError: cython_sources
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
make: *** [Makefile:21: venv] Error 1
```

</details>

(On 3.11, the reporter used 3.12 so specific error may vary)

## Comments

Reported with a workaround, adding a constraints.txt file to prevent cython 3.0 from being installed.

### PR DESCRIPTION
**Pull request by zenmonkeykstop**
## Status

Ready for review 

## Description of Changes

Fixes #7153 

`make venv` fails on Python 3.11 due to incompatibility between our pinned PyYAML version and cython 3.0. As a temporary measure, this PR (approach suggested by the original reporter on Gitter) constrains the cython version to allow the venv to be created. 

(In future we should update PyYAML and development requirements in general.)

## Testing

With Python 3.9 on debian 11:
- [x] `make venv` and `make dev` complete successfully

With Python 3.11 on debian 12:
- [x] `make venv` and `make dev` complete successfully

- [x] CI passes
- [x] Visual review

## Deployment
n/a, development only.

### CODE REVIEW

**Review by cfm — CHANGES_REQUESTED** [review]
`make venv` passes for me on Python 3.9 (Debian 11) and Python 3.11 (Debian 12).  It fails for me on Python 3.12 (macOS, from MacPorts) with:

```sh-session
      _ruamel_yaml.c:28302:55: error: no member named 'ob_digit' in 'struct _longobject'
                  const digit* digits = ((PyLongObject*)x)->ob_digit;
                                        ~~~~~~~~~~~~~~~~~~  ^
      _ruamel_yaml.c:28357:55: error: no member named 'ob_digit' in 'struct _longobject'
                  const digit* digits = ((PyLongObject*)x)->ob_digit;
                                        ~~~~~~~~~~~~~~~~~~  ^
      _ruamel_yaml.c:28498:55: error: no member named 'ob_digit' in 'struct _longobject'
                  const digit* digits = ((PyLongObject*)x)->ob_digit;
                                        ~~~~~~~~~~~~~~~~~~  ^
      _ruamel_yaml.c:28553:55: error: no member named 'ob_digit' in 'struct _longobject'
                  const digit* digits = ((PyLongObject*)x)->ob_digit;
                                        ~~~~~~~~~~~~~~~~~~  ^
      _ruamel_yaml.c:28732:55: error: no member named 'ob_digit' in 'struct _longobject'
                  const digit* digits = ((PyLongObject*)x)->ob_digit;
                                        ~~~~~~~~~~~~~~~~~~  ^
      _ruamel_yaml.c:28787:55: error: no member named 'ob_digit' in 'struct _longobject'
                  const digit* digits = ((PyLongObject*)x)->ob_digit;
                                        ~~~~~~~~~~~~~~~~~~  ^
      _ruamel_yaml.c:29276:47: error: no member named 'ob_digit' in 'struct _longobject'
          const digit* digits = ((PyLongObject*)b)->ob_digit;
                                ~~~~~~~~~~~~~~~~~~  ^
      133 warnings and 12 errors generated.
      error: command '/usr/bin/clang' failed with exit code 1
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for ruamel.yaml.clib
ERROR: Could not build wheels for ruamel.yaml.clib, which is required to install pyproject.toml-based projects
make: *** [venv] Error 1
```

Let me know if you'd like me to take this over and investigate further, @zenmonkeykstop.

**Review by cfm — DISMISSED** [review]
I've tested `make venv` using this Dockerfile like so, with the same results as above:

```sh-session
user@sd:~/securedrop$ cat Dockerfile
ARG VERSION
FROM python:$VERSION

RUN apt-get update
RUN apt-get install -y git jq make
RUN apt-get install -y build-essential libssl-dev libffi-dev python3-dev dpkg-dev
RUN apt-get install -y python3-pip
RUN pip install virtualenv

RUN git clone -b 7153-cython-constraint https://github.com/freedomofpress/securedrop
WORKDIR securedrop
RUN make venv
user@sd:~/securedrop$ docker build -t 7153 . --build-arg VERSION=3.9-bullseye
[passes]
user@sd:~/securedrop$ docker build -t 7153 . --build-arg VERSION=3.11-bookworm
[passes]
user@sd:~/securedrop$ docker build -t 7153 . --build-arg VERSION=3.12-bookworm
[...]
91.69       _ruamel_yaml.c: In function ‘__Pyx_PyIndex_AsSsize_t’:
91.69       _ruamel_yaml.c:29276:45: error: ‘PyLongObject’ {aka ‘struct _longobject’} has no member named ‘ob_digit’
91.69       29276 |     const digit* digits = ((PyLongObject*)b)->ob_digit;
91.69             |                                             ^~
91.69       error: command '/usr/bin/gcc' failed with exit code 1
91.69       [end of output]
91.69   
91.69   note: This error originates from a subprocess, and is likely not a problem with pip.
91.69   ERROR: Failed building wheel for ruamel.yaml.clib
93.25 ERROR: Could not build wheels for ruamel.yaml.clib, which is required to install pyproject.toml-based projects
94.31 make: *** [Makefile:21: venv] Error 1
------
Dockerfile:12
--------------------
  10 |     RUN git clone -b 7153-cython-constraint https://github.com/freedomofpress/securedrop
  11 |     WORKDIR securedrop
  12 | >>> RUN make venv
  13 |     
--------------------
ERROR: failed to solve: process "/bin/sh -c make venv" did not complete successfully: exit code: 2
```

Since there are newer versions of `ruamel.yaml`, I began upgrading development dependencies...

```patch
--- a/securedrop/requirements/python3/develop-requirements.in
+++ b/securedrop/requirements/python3/develop-requirements.in
@@ -34,10 +34,10 @@ pytest-xdist>=3.0.2
 python-vagrant
 pyyaml>=5.4.1
 requests>=2.31.0
-ruamel.yaml>=0.16.10
+ruamel.yaml>=0.18.6
 ruff
-safety>2.2.0
-semgrep>=1.57.0
+safety>2.3.1
+semgrep>=1.74.0
 setuptools>=56.0.0
 shellcheck-py
 six==1.15.0
```

...but have run into conflicting requirements:

```sh-session
There are incompatible versions in the resolved dependencies:
  ruamel.yaml>=0.18.6 (from -r requirements/python3/develop-requirements.in (line 37))
  ruamel.yaml<1,>=0.15.37 (from ansible-lint==4.2.0->-r requirements/python3/develop-requirements.in (line 2))
  ruamel.yaml<0.18,>=0.16.0 (from semgrep==1.74.0->-r requirements/python3/develop-requirements.in (line 40))
  ruamel.yaml>=0.17.21 (from safety==3.2.0->-r requirements/python3/develop-requirements.in (line 39))
```

@zenmonkeykstop, it seems these constraints will need to be accompanied by a careful set of upgrades.  I hope this Dockerfile will make it easy to test those changes in a minimal, reproducible Python 3.12 environment.

**Comment by zenmonkeykstop** [comment]
Thanks for the effort - this is a release build blocker (for builds on modern systems), but I'll just work around it for now.

**Review by legoktm — APPROVED** [review]
LGTM!

**Pull request merged**
