### PR TITLE
Add a helper to emit screenshots before and after selenium test cases.

### PR DESCRIPTION
**Pull request by tmc**
## Status

Ready for review

## Description of Changes

Adds a helper to emit screenshots before and after selenium test cases.

Example output filenames include:
test_admin_interface.py-AdminInterface-test_admin_interface-_admin_adds_a_user-after.png
test_admin_interface.py-AdminInterface-test_admin_interface-_admin_adds_a_user-before.png

## Testing

This functionality is gated by a 'SCREENSHOTS_ENABLED' env var .

## Deployment

This a test only change. It doesn't have deployment implications.

### CODE REVIEW

**Comment by dachary** [comment]
Great idea ! I confirm this works for me in the development VM with:

<pre>
export SCREENSHOTS_ENABLED=yes
pytest -v tests/functional
</pre>

Would you mind adding a few lines about that in **docs/development/testing_application_tests.rst** ?

**Comment by tmc** [comment]
@dachary Good suggestion, added documentation note. circle failure appears to be a flake?

**Comment by tmc** [comment]
On further inspection it appears that circle test will fail unless some env vars are presented.

**Comment by garrettr** [comment]
@tmc The CircleCI issues for external contributors are (unfortunately) a known shortcoming of the current setup, see #1826 for details.

**Comment by dachary** [comment]
@tmc hey, my apologies for breaking your pull request with the change to pytest. I fixed it at https://github.com/dachary/securedrop/commits/pr-1954 ( first two commits) and took the liberty to address @redshiftzero comments while I was at it. Feel free to cherry-pick those or adapt them.

**Comment by dachary** [comment]
@tmc ping ?

**Comment by tmc** [comment]
Ah thanks. Will cherry-pick.

**Comment by dachary** [comment]
I rebased https://github.com/dachary/securedrop/commits/pr-1954 which was conflicting. @tmc if you don't have time right now I'd be happy to create a pull request with those. Just let me know ;-)

**Comment by dachary** [comment]
@tmc https://github.com/freedomofpress/securedrop/pull/2086 is a rebase of your contribution.

**Comment by redshiftzero** [comment]
These commits have been merged in PR #2086.

Thanks again for your contribution to SecureDrop @tmc!

**Pull request closed without merging**
