### PR TITLE
Update translations for 1.2.0

### PR DESCRIPTION
**Pull request by rmol**
## Status

Ready for review

## Description of Changes

Updates translations for 1.2.0. 

Also updates `securedrop/translations/messages.pot`. This file is only really used in the i18n repo, but it's useful to have it up to date when reviewing translation changes at release time, and confusing when it doesn't reflect the current source strings.

Also updates the desktop icon templates to add Czech and Slovak. I missed this in 1.1.0.

Documentation updates to prevent those last two problems will be submitted in a separate PR.

## Testing

For each supported language, check that each of the 21 source strings changed for 1.2.0 has a plausible-looking translation.

Check out this branch, then run `securedrop/bin/dev-shell ./i18n_tool.py --verbose translate-messages --compile` to create the .mo files.

Then save this script as `check_translations.py`:

```
#!/usr/bin/env python3

import gettext
import os
import sys


SUPPORTED_LANGUAGES = [
    "ar",
    "ca",
    "cs",
    "de_DE",
    "el",
    "en_US",
    "es_ES",
    "fr_FR",
    "hi",
    "is",
    "it_IT",
    "nb_NO",
    "nl",
    "pt_BR",
    "ro",
    "ru",
    "sk",
    "sv",
    "tr",
    "zh_Hant",
]


TESTS = [
    "UPDATE SUBMISSION PREFERENCES",
    "Can't scan the barcode? You can manually pair FreeOTP with this account by entering the following two-factor secret into the app:",
    "Please wait for a new code from your two-factor mobile app or security key before trying again.",
    "Once you have configured your YubiKey, enter the 6-digit verification code below:",
    "RESET MOBILE APP CREDENTIALS",
    "Submit Messages",
    "Submission Preferences",
    "Once you have paired FreeOTP with this account, enter the 6-digit code below:",
    "There was a problem verifying the two-factor code. Please try again.",
    "Prevent sources from uploading documents.  Sources will still be able to send messages.",
    "To reset two-factor authentication for mobile apps such as FreeOTP, choose the first option. For security keys like the YubiKey, choose the second one.",
    "You must enter a message.",
    "Can't scan the barcode? You can manually pair FreeOTP with your SecureDrop account by entering the following two-factor secret into the app:",
    "RESET SECURITY KEY CREDENTIALS",
    "You're almost done! To finish resetting your two-factor authentication, follow the instructions below to set up FreeOTP. Once you've added the entry for your account in the app, enter one of the 6-digit codes from the app to confirm that two-factor authentication is set up correctly.",
    "Reset two-factor authentication for security keys, like a YubiKey",
    "You're almost done! To finish adding this new user, have them follow the instructions below to set up two-factor authentication with FreeOTP. Once they've added an entry for this account in the app, have them enter one of the 6-digit codes from the app to confirm that two-factor authentication is set up correctly.",
    "Once you have paired FreeOTP with this account, enter the 6-digit verification code below:",
    "Your two-factor credentials have been reset successfully.",
    'The two-factor code for user "{user}" was verified successfully.',
    'If you are already familiar with GPG, you can optionally encrypt your messages with our <a href="{url}" class="text-link">public key</a> before submission.',
]


if __name__ == "__main__":
    translation_dir = sys.argv[1]

    for lang in SUPPORTED_LANGUAGES:
        print("Checking {}...".format(lang))
        os.environ["LANGUAGE"] = lang
        gettext.bindtextdomain("messages", translation_dir)
        missing = False
        for i, t in enumerate(TESTS, 1):
            translation = gettext.gettext(t)
            print("  {}: {}".format(i, translation))
            if lang != "en_US" and translation == t:
                missing = True
                print('MISSING TRANSLATION FOR "{}"'.format(t), file=sys.stderr)

        if not missing:
            print("Looks good.")
```

When run with the translations directory as its only argument (e.g. `check_translations.py securedrop/translations`, from the root of your working copy), you should see the 21 strings translated for each supported language, with no reports of missing translations, and no unexpected markup (that doesn't match the source string) or other suspicious content in the translated strings.

### If you made changes to the server application code:

- [x] Linting (`make lint`) and tests (`make test`) pass in the development container

### CODE REVIEW

**Comment by kushaldas** [comment]
All tests passed for `ro`.

**Comment by kushaldas** [comment]
All tests passed for `ru`.

**Comment by kushaldas** [comment]
All tests passed for `sk`.

**Comment by emkll** [comment]
All tests passed locally for:
:white_check_mark: hi
:white_check_mark: is
:white_check_mark: it_IT
:white_check_mark: nb_NO
:white_check_mark: nl
:white_check_mark: pt_BR

**Comment by kushaldas** [comment]
The following languages passed: `ro ru sk sv tr zh_Hant`.

**Comment by redshiftzero** [comment]
Merging despite translation-test job still running as we ran locally

**Pull request merged**
