### PR TITLE
Make the diagram vectorish, smoother and clearer

### PR DESCRIPTION
**Pull request by mark-in**
This is how it looks like:
securedrop

### CODE REVIEW

**Comment by fowlslegs** [comment]
Nice work!

How did you create this? Ideally, this could solve #976.

A few things:

* OSSEC also sends alert emails from the monitor server to the Admin's email.
* The Admin also uses TBB on Tails to access the web interface of the SecureDrop application running on the App Server.
* This doesn't illustrate how journalists and sources can carry out conversations over SecureDrop. The arrows to and from the App Server should be bidirectional.

Also, we may be switching to recommending FreeOTP as a HOTP/ TOTP app because Google Authenticator closed its source a couple years back (at least I'm pushing for that). Do leave that as is for now though.

**Comment by mark-in** [comment]
> Nice work! How did you create this? Ideally, this could solve #976.

Thanks. Just simple Inkscape and graphics from Tango project.

> A few things:
> * OSSEC also sends alert emails from the monitor server to the Admin's email.

Email notifications are super-duper extreme because it leaks tons of sensitive metadata. I think this must be optional and not be included in overview diagram.
I looks reasonable to store PGP encrypted (or maybe not) on special authenticated HS hosted on MS. Or to host simple IMAP server on MS via HS with push notifications. Anyway there must not be any third party involved.

> * The Admin also uses TBB on Tails to access the web interface of the SecureDrop application running on the App Server.

Fixed in 4d2d387.

> * This doesn't illustrate how journalists and sources can carry out conversations over SecureDrop. The arrows to and from the App Server should be bidirectional.

Fixed in d8b5a15.

> Also, we may be switching to recommending FreeOTP as a HOTP/ TOTP app because Google Authenticator closed its source a couple years back (at least I'm pushing for that). Do leave that as is for now though.

I don't like GA either for the same reason. Fixed in 2d96f9b.

**Comment by mark-in** [comment]
Please notify me before merge. Maybe I need to save result diagram in Inkscape SVG (w/ Inkscape extentions) to make it more convenient to edit for Inkscape users.
Unfortunately this format leaks lots of metadata. That's why I pushed plain SVG for the first time.

**Comment by garrettr** [comment]
Awesome work, @mark-in! This is a great improvement over our current diagram, and I'm really happy we'll be able to incorporate it in an open format (e.g. not Microsoft Visio, :rage:).

To me, this looks ready to merge, but can you explain a little more about the pros/cons of SVG vs. "Inkscape  SVG" first?

**Comment by garrettr** [comment]
> Email notifications are super-duper extreme because it leaks tons of sensitive metadata. I think this must be optional and not be included in overview diagram.
I looks reasonable to store PGP encrypted (or maybe not) on special authenticated HS hosted on MS. Or to host simple IMAP server on MS via HS with push notifications. Anyway there must not be any third party involved.

A couple of notes on this:

* OSSEC email notifications are technically optional (you can install SecureDrop without setting them up), but this is not recommended (how else would you receive notifications of unusual or potentially suspicious behavior on your instance?)
* These are notifications from OSSEC, and are not directly based on the behavior of sources (which, I agree, *would* leak sensitive metadata). The directories that are used to store data received from sources are specifically ignored by OSSEC, so we avoid sending file integrity change alerts (or similar) that could leak info about source behavior via OSSEC alerts.
* While we encourage organizations to use their own mail server to relay the OSSEC alert emails, most organizations do not actually run their own mail server, and so either directly or indirectly use a third party (typically Gmail, as seen it is [specially documented](https://docs.securedrop.org/en/latest/ossec_alerts.html#using-gmail-for-ossec-alerts)) to relay these emails. We consider this trade-off to be acceptable because the emails are encrypted and we are careful to avoid them leaking metadata about source behavior, but also think this situation could be improved.

We are well aware of the current limitations of SecureDrop's monitoring and are working on improving it (see #1123). In the meantime, it is best for diagrams to reflect the *current* state of SecureDrop, rather than an ideal but not-yet-implemented state.

**Comment by mark-in** [comment]
> can you explain a little more about the pros/cons of SVG vs. "Inkscape SVG" first?

In details it's explained at http://wiki.inkscape.org/wiki/index.php/Inkscape_SVG_vs._plain_SVG .
In short, "Inkscape svg is basically the same as plain svg, just with a few extra commands (in separate namespaces) added, which the Inkscape tools use to keep track of their work" and "should render identically with or without the inkscape extensions". I'm not sure if it's really useful but it can be.
The point is that there are a lot of metadata in these extentions (Inkscape version, name of the user, path to file on user's machine etc). It should not be included into project.
So the choice is between plain SVG and Inkscape SVG with extra data cut out (MAT doesn't support SVG). Now I tend to think that plain SVG is better for having less pain with cutting out metadata.

**Comment by mark-in** [comment]
>    OSSEC email notifications are technically optional (you can install SecureDrop without setting them up), but this is not recommended (how else would you receive notifications of unusual or potentially suspicious behavior on your instance?)

Maybe Pond?
Alerts should be visible only to the admin who can manage to install and use Pond (on Tails).

> While we encourage organizations to use their own mail server to relay the OSSEC alert emails, most organizations do not actually run their own mail server, and so either directly or indirectly use a third party (typically Gmail, as seen it is specially documented) to relay these emails. We consider this trade-off to be acceptable because the emails are encrypted and we are careful to avoid them leaking metadata about source behavior, but also think this situation could be improved.

Alerts should also be resistant to traffic analysis against MS. If one is sending email notifications then it can easily leak the location of SecureDrop Area in clearnet to ISP. 
One can send emails via Tor but then we have to incorporate one more Area in our diagram (it will become sophisticated).

**Comment by garrettr** [comment]
@mark-in Ok. In general, it seems like preserving *more* of people's work and work-in-progress is usually helpful, so I'd tend to prefer to use Inkscape SVG over normal SVG. For example, it appears only Inkscape SVG preserves layer information (I inferred this from reading various comments on this issue, and have not tested this myself, so I could be wrong), and layer information is generally very useful to encourage further work with a particular image.

> The point is that there are a lot of metadata in these extentions (Inkscape version, name of the user, path to file on user's machine etc). It should not be included into project.

Yeah, there's been an [issue](https://bugs.launchpad.net/inkscape/+bug/168958) for this on their issue tracker since 2007 and it still hasn't been fixed. :disappointed:

Given all of this, while I would prefer to use "Inkscape SVG", the metadata concerns are pretty annoying and I think it's probably best just to avoid them by using SVG instead. So this PR should be ready to merge, unless you have anything additional you want to add to this discussion!

**Comment by garrettr** [comment]
Re https://github.com/freedomofpress/securedrop/pull/1211#issuecomment-160693100: if you feel strongly about this, consider filing a follow-up issue. The discussion in this pull request should be focused on the diagram you've submitted, and any additional ideas you have about SecureDrop's architecture are best discussed in separate, focused issues.

**Comment by mark-in** [comment]
> Given all of this, while I would prefer to use "Inkscape SVG", the metadata concerns are pretty annoying and I think it's probably best just to avoid them by using SVG instead. So this PR should be ready to merge, unless you have anything additional you want to add to this discussion!

By the way there is some script (https://github.com/hartwork/svgstrip/) to strip private data from Inkscape SVG but it looks too messy and inconvenient for every-save usage (it also breaks formatting). I think that it's better to leave plain SVG for now.
Ready to merge.

**Comment by mark-in** [comment]
Should I fix something else?

**Comment by garrettr** [comment]
@mark-in Sorry, no! This is good to go, thanks for the reminder.

**Pull request merged**
