### PR TITLE
tests: makedirs is better than system("mkdir -p")

### PR DESCRIPTION
**Pull request by dachary**
## Status

Ready for review

## Description of Changes

makedirs is better than system("mkdir -p")

## Testing

* CI should pass

## Deployment

N/A

### CODE REVIEW

**Comment by dachary** [comment]
@emkll that was a test to see if you were actually reading the code. And no, I'm not making that up: 7 months ago I already knew you'd be with us.

**Comment by emkll** [comment]
Would there be a situation where the folder already exists? In which case I would suggest you check `if os.path.exists(self.log_dir).

`mkdir -p` returns 0 even if the specified folder exists, wheras normal `mkdir` returns 1 (and i suspect makedirs will throw an exception.

**Comment by conorsch** [comment]
Yes, @emkll is correct, `os.makedirs` raises an OSError if the directory already exists. Existence checking does seem the sane way to sidestep—we don't want to `pass` on OSError, since an OSError could also mean that the directory could not be created, due to permissions or otherwise.

Also, the default mode is `0777`, which I find a bit permissive, but as the codepath is only relevant to tests, should be fine.

Docs: https://docs.python.org/2/library/os.html#os.makedirs

**Comment by dachary** [comment]
> mkdir -p returns 0 even if the specified folder exists,

Ah! here is my excuse for using **mkdir -p** :-D

**Comment by dachary** [comment]
> I would suggest you check if os.path.exists(self.log_dir).

Done. And now we have a beautifully pythonic code :tada:

**Pull request merged**
