### PR TITLE
Responsive CSS for source index page

### PR DESCRIPTION
**Pull request by heartsucker**
## Status

Ready for review

## Description of Changes

Updates the source index page's HTML and associated SASS/CSS to allow for variable sized text. It also has the added advantage of making that page work on mobile.

screenshot_2017-08-31_19-40-36

screenshot_2017-08-31_19-44-10

## Testing

Launch the source interface. Try resizing the window.

### If you made changes to the app code:

- [x] Unit and functional tests pass on the development VM

### CODE REVIEW

**Comment by heartsucker** [comment]
Partially addresses #2235

**Comment by dachary** [comment]
@heartsucker fantastic PR ! Would you mind making it against wip-dachary-i18n-base instead of develop ? It will save me the trouble of a painful rebase when it is merged :-)

**Comment by redshiftzero** [comment]
This looks great. Each column expands nicely with the text now:

screen shot 2017-08-31 at 11 40 41 am

However - I wonder if it's possible to reduce the spacing between around the paragraph text in `div.index-column.index-left` so that each column appears more like a square as on current develop?

**Comment by heartsucker** [comment]
@dachary Once this is merged, I can do a cherry-pick and then make it work with your branch.

**Comment by dachary** [comment]
> Once this is merged, I can do a cherry-pick and then make it work with your branch.

I'm afraid that won't help because I have to rebase this branch every time a new i18n related PR is merged to reduce the pile. Would it be bad for this PR to be on top of the i18n changes ?

**Comment by redshiftzero** [comment]
As an alternative to cherry-picking into the internationalization branch or starting to merge PRs into other branches than `develop`, @heartsucker _could_ rebase `wip-dachary-i18n-base` branch (or prepare another rebased branch to use as reference for resolving any conflicts arising). What do you think @dachary? 

I'm biased because I want the changes in this PR in `develop` because the styling on the source interface index looks very bad in the Selenium screenshots even in English (fixing this is a blocker for e.g. #2016):

source-index

**Comment by dachary** [comment]
@redshiftzero I was hoping to avoid a conflict resolution if there was no specific incentive to merge this right now, lazy me. @heartsucker don't worry about it, I'll handle the conflicts, I'm used to it now :-)

**Comment by nsalontay** [comment]
# Source Interface Responsiveness Audit
Screens at iPhone 5 resolution.
## Index "/"
Reduce logo real estate
securedrop___protecting_journalists_and_sources

## Codename Sign In and Generation "/generate" 
Make input responsive and consider reversing buttons for clarity and proximity.
securedrop___protecting_journalists_and_sources

## File Upload "/lookup"
Upload module affects size of page and breaks layout somewhat.
securedrop___protecting_journalists_and_sources

**Pull request merged**
