### PR TITLE
Translations update from Weblate

### PR DESCRIPTION
**Pull request by weblate-fpf**
Translations update from [Weblate](https://weblate.securedrop.org) for [SecureDrop/SecureDrop](https://weblate.securedrop.org/projects/securedrop/securedrop/).

It also includes following components:

* [SecureDrop/desktop](https://weblate.securedrop.org/projects/securedrop/desktop/)

Current translation status:

Weblate translation status

### CODE REVIEW

**Review by zenmonkeykstop — DISMISSED** [review]
LGTM - approving despite static analysis fail as it's already been fixed in develop.

**Comment by zenmonkeykstop** [comment]
> LGTM - approving despite static analysis fail as it's already been fixed in develop.

Oh wait - it's likely to fail coz merge queue isn't it.

**Comment by cfm** [comment]
Discussed in today's stand-up:  While we can merge these pull requests at any time, we'll need to review any changes on release day no matter what, for the final merge and backport into the release branch.  So this can continue to accumulate Weblate's changes until then.

**Review by cfm — APPROVED** [review]
No red flags in the Weblate diff.

**Pull request merged**
