### PR TITLE
Prevent OSSEC alarms when the Tor HS is scanned

### LINKED ISSUE #1330: Spurious OSSEC alerts due to THS port scanning
We received a report on our private support portal about frequent OSSEC alerts triggered by the following message in `/var/log/tor/log`:

```
[timestamp redacted] [warn] connection_edge_process_relay_cell (at origin) failed.
```

After enabling `info`-level logging for Tor, we were able to correlate this `[warn]`-level message with preceding `[info]`-level messages:

```
[timestamp redacted] [info] rend_service_set_connection_addr_port(): No virtual port mapping exists for port 443 on service qn4qfeeslglmwxgb
[timestamp redacted] [info] connection_exit_begin_conn(): Didn't find rendezvous service (port 443)
[timestamp redacted] [warn] connection_edge_process_relay_cell (at origin) failed.
```

These messages are triggered by an attempt to open a connection to a hidden service on a port that it does not listen on (e.g. the Source Interface only listens on port 80, but these messages were triggered by attempts to connect on 443). You can easily reproduce it by trying to open a connection to a given hidden service on a port that it does not listen on.

At this point, we decided to analyze some of the logs from the Tor Hidden Services we operate (e.g. for our websites) using our new ELK stack, and found that we were seeing the same patterns.

These log messages appear to be caused by various automated crawlers that try various common "ports of interest" on publicly advertised hidden services (e.g. [OnionScan](https://github.com/s-rah/onionscan/blob/master/onionscan.go)). This type of crawling happens constantly and is usually benign (e.g. for research, testing new tools, etc.).

Since this event is typically benign, it should *not* trigger dozens of OSSEC alerts a day. These alerts are spurious, waste admin's time and attention, and make it difficult to separate signal from noise in the alerts sent by OSSEC. I propose that we develop a mitigation to avoid sending spurious alerts and include it in the next point release (0.3.8).

### PR DESCRIPTION
**Pull request by redshiftzero**
Adds a rule to fix #1330.

### CODE REVIEW

**Comment by garrettr** [comment]
This looks great. @fowlslegs Can you test this and confirm that it fixes the issue?

**Comment by garrettr** [comment]
Since #1330 targets 0.3.8, normally this PR should target the corresponding release integration branch (in this case, `release/0.3.8`), since it's usually easier to target the release integration branch first and then merge from there into develop, rather than the other way around, because develop has diverged so much from the current release series.

However, since this is such a small and localized change, it shouldn't be hard to merge it the other way. This comment should serve as a reminder that this also needs to be manually merged into release/0.3.8 once it's been tested.

**Comment by conorsch** [comment]
> This comment should serve as a reminder that this also needs to be manually merged into release/0.3.8 once it's been tested.

Rad, a simple cherry-pick would suffice once this has been tested. Thanks, @redshiftzero!

**Comment by fowlslegs** [comment]
> @fowlslegs Can you test this and confirm that it fixes the issue?

Yep. That's what I hoped to signify by assigning myself to the PR :wink:

**Comment by fowlslegs** [comment]
> This comment should serve as a reminder that this also needs to be manually merged into release/0.3.8 once it's been tested.

I also added it to the 0.3.8 milestone. That might be a better reminder.

**Comment by garrettr** [comment]
Hey @redshiftzero, just to give you an update - @fowlslegs tried to test this yesterday, but ran into some issues provisioning a virtualized production environment on the develop branch. Our resident Ansible guru @conorsch is on PTO until next Monday, so we're going to wait to finish testing this until he gets back and can fix the Ansible breakage.

**Comment by fowlslegs** [comment]
Closing in favor of #1374, which targets the next release branch (`release/0.3.9`).

**Pull request closed without merging**
