### PR TITLE
Fixes #4791 shows png files instead of SVG in source index

### LINKED ISSUE #4791: SVG in Tor warning banner not rendered if NoScript set to permit JS
## Steps to reproduce:
1. Set your Tor security level to "safest"
2. Set your NoScript setting to "Disable restrictions for this tab"
3. Load a SecureDrop source interface 

(Works with any live SecureDrop instance >= 0.14.0)

## Expected behavior

The security warning banner renders normally.

## Actual behavior

The security warning banner looks like this:

Screenshot from 2019-09-10 21-03-54

## Explanation

Tor enforces no consistency between the Tor security setting and the NoScript setting: You can have JavaScript enabled while your security level is nominally set to "safest" (which disables SVG rendering). The NoScript button is very visible, so it's not too much of an edge case to imagine that a user may have put their browser in this state intentionally or by accident.

These icons should probably be served up as PNG. That said, the banner is also incorrect in this situation (following the steps will not have any effect), so we may want to take this case into account in the next iteration on this warning.

### PR DESCRIPTION
**Pull request by kushaldas**
## Status

Ready for review

## Description of Changes

Fixes #4791

Adds 3 png files and also updates the source index tempate to use
the png files.

## Testing

- Set your Tor security level to "safest"
-  Set your NoScript setting to "Disable restrictions for this tab"
- Load a SecureDrop source interface

## Deployment

Any special considerations for deployment? Consider both:

1. Upgrading existing production instances.
2. New installs.

### If you made changes to the server application code:

- [ ] Linting (`make lint`) and tests (`make -C securedrop test`) pass in the development container

### If you made changes to `securedrop-admin`:

- [ ] Linting and tests (`make -C admin test`) pass in the admin development container

### If you made changes to the system configuration:

- [ ] [Configuration tests](https://docs.securedrop.org/en/latest/development/testing_configuration_tests.html) pass

### If you made non-trivial code changes:

- [ ] I have written a test plan and validated it for this PR

### If you made changes to documentation:

- [ ] Doc linting (`make docs-lint`) passed locally

### CODE REVIEW

**Comment by kushaldas** [comment]
>  rules.

We should at least keep the svgs as source file for the png files. And, I think we should remove the AppArmor rules as you suggested.

**Comment by kushaldas** [comment]
@emkll ping for bringing it back to view :)

**Comment by redshiftzero** [comment]
> I think we should remove the AppArmor rules as you suggested

It looks like the svg files that are no longer used are still whitelisted by AppArmor in this PR - want to update that prior to merge @kushaldas?

**Comment by redshiftzero** [comment]
hmm lint is failing but the failure looks unrelated to this diff - want to rebase on latest?

**Comment by eloquence** [comment]
Closing out this year+-old PR, @kushaldas feel free to reopen if you want to pick this up again.

**Pull request closed without merging**
