### PR TITLE
Merge fixes from 0.3.4 release into development branch

### PR DESCRIPTION
**Pull request by garrettr**
This was a simple `git merge 0.3.4` into develop, with some merge conflicts manually resolved. @conorsch and I went through these together and I am confident in the outcome of each of the merges.

The commits that Git chose to use in the merge are not exactly what was expected - as can be seen from the diff, it appears that in some places (e.g. `changelog.md` and some of the Debian release files) the diff jumps from 0.3.2 to 0.3.4, which would suggest that 0.3.3 was never merged back into develop from the `release/0.3.3` branch. However, this _did_ happen in 4bce6efd58e302c1e9e44f4997967c4812522565.

I am not sure what caused this unexpected behavior, but my guess is the tricky merge for 0.3.3 (remember, there were an enormous number of changes to the Ansible playbooks), which I think I actually ended up doing via rebase. This would've messed with Git's history and subsequent decision-making about the parent commits to use in the merge.

On the other hand, I have carefully reviewed the full diff ("Files changed") of this PR and it looks good to me. I have verified that it includes _all_ of the iSec fixes, the Tor directory permissions fix, and the documentation fixes from 0.3.4.

### CODE REVIEW

**Comment by garrettr** [comment]
@conorsch @dolanjs Review please

**Comment by conorsch** [comment]
A note on the recommended Ansible version (in `docs/develop.md`): we rolled back to 1.8.4 due to a bug in 1.9.1 that caused service restarts on Ubuntu to fail (see #1026). Fortunately 1.9.2 ([released 2015-06-25](https://github.com/ansible/ansible/blob/devel/CHANGELOG.md#192-dancing-in-the-street---jun-26-2015)) fixed the bug, and so recommending the most current release is now correct. Therefore the changes from #1026 are not present in PR.

In general it's good to have the docs say "install the latest version" wherever possible, and we can selectively recommend a specific version as needed.

**Comment by dolanjs** [comment]
We will need to update a couple of the spec tests for iptables and apparmor profiles but otherwise looks good to me.

**Comment by conorsch** [comment]
Looks like we lost some PEP8 cleanup. Mostly it's 5bfa86ba that's missing, which was part of #931. There have been several PEP8-related PRs recently:

* #926 
* #931 
* #956 

Wouldn't hurt to try remerging those from those feature branches, if static, or cherry-picking the commits provided by them, to make sure the PEP8 changes are included in the develop branch as far as is possible.

**Comment by conorsch** [comment]
@dolanjs Took care of the `dac_override` capability in the Apache AppArmor profile as part of #1070, see 305a126.

**Comment by garrettr** [comment]
@conorsch I don't want to bring the PEP8 changes back until we have linting included in an automated fashion to prevent regressions. Frankly the PEP8 PR's have done nothing good and a lot of bad (broke SQLAlchemy queries, make merges hellish, etc.). I'd rather do PEP8 all in one fell swoop once we have a mechanism in place to prevent backsliding and general confusion.

**Comment by conorsch** [comment]
All four commits related to iptables audit fixes (see #1073) are present in this PR.

**Comment by conorsch** [comment]
@garrettr Agreed on deferring PEP8 changes until style guidelines are at least superficially enforceable. Mostly wanted to cross-reference the issues so the history is traversable further down the line.

**Comment by garrettr** [comment]
Confirmed from @conorsch and @dolanjs that this is good to merge.

**Pull request merged**
