### PR TITLE
journalist: better error message with the HOTP secret length is not 40

### PR DESCRIPTION
**Pull request by dachary**
## Status

Ready for review

## Description of Changes

better error message with the HOTP secret length is not 40

## Testing

N/A

## Deployment

N/A

### If you made changes to the app code:

- [x] Unit and functional tests pass on the development VM

### CODE REVIEW

**Comment by dachary** [comment]
@ei8fdb here you go

**Comment by ei8fdb** [comment]
Merci 💥

**Comment by redshiftzero** [comment]
Good call on this string improvement @ei8fdb! 

Thanks for making the PR @dachary - looks like there's just one test update (`TestJournalistApp.test_admin_add_user_yubikey_odd_length`) and then we're good to merge

**Comment by ageis** [comment]
Just wanted to make a minor point for the future; HOTP/TOTP secrets are only 40 characters when they're based on SHA-1. There are some sites where they let you configure the HMAC for 2FA up to SHA256 and SHA512, so with an arbitrary change or algorithm deprecation you could have up to 64 or 128 characters in your HOTP secret.

@dachary I see with #2705 / #2757 we're now recommending FreeOTP everywhere; where this is explicitly configurable on the interface, if we are validating this string as 40 chars then I think you should also add a hint to the docs wherever journalist users are setting up 2FA that it _must_ be SHA1 with a 6-digit code. I'm not suggesting HMAC/SHA-1 is broken, but it may be prudent or necessary to support stronger hashes in the future, or there may come a time when it's not FreeOTP's default algorithm.

**Comment by dachary** [comment]
@ageis I'm unclear where and how that should be phrased. Would you mind drafting a pull request for review?

**Comment by kushaldas** [comment]
>@dachary I see with #2705 / #2757 we're now recommending FreeOTP everywhere; where this is explicitly configurable on the interface, if we are validating this string as 40 chars then I think you should also add a hint to the docs wherever journalist users are setting up 2FA that it must be SHA1 with a 6-digit code. I'm not suggesting HMAC/SHA-1 is broken, but it may be prudent or necessary to support stronger hashes in the future, or there may come a time when it's not FreeOTP's default algorithm.

This will be really helpful as the configuration window is otherwise very confusing.

**Comment by dachary** [comment]
@redshiftzero the test is fixed.

@kushaldas @ageis do you feel the (good points) you raised should be addressed in this PR? Or would it be ok if I make a separate issue to followup?

**Comment by ageis** [comment]
@dachary let's address that separately.

**Pull request merged**
