### PR TITLE
Docs: Fixes #2832 updates screenshots and text for admin

### LINKED ISSUE #2832: Update screenshots of admin instance configuration page
# Bug

## Description

The screenshots for the admin instance configuration pages are old in the documents, they need to updated with the latest screenshots.

## Steps to Reproduce

Please check the admin guide, the screenshots there don't show both "send test ossec alert" and "update logo" options in one page.

### PR DESCRIPTION
**Pull request by kushaldas**
## Status

Ready for review / Work in progress

## Description of Changes

Fixes #2832 

Changes proposed in this pull request:

## Testing

Check the admin document, specially the logo update, and sending test ossec alert emails sections.

### If you made changes to the app code:

- [ ] Unit and functional tests pass on the development VM

### If you made changes to the system configuration:

- [ ] [Configuration tests](https://docs.securedrop.org/en/latest/development/testing_configuration_tests.html) pass

### If you made changes to documentation:

- [x] Doc linting passed locally

### CODE REVIEW

**Comment by kushaldas** [comment]
Oh, thanks. I missed that point completely :(

**Comment by redshiftzero** [comment]
Hey @kushaldas - would you like to extend this PR to generate all the screenshots for 0.5.1 following the documentation link @dachary pasted above? Note that for release screenshots you should modify the string in `version.__version__` such that it reads `0.5.1` first.

**Comment by redshiftzero** [comment]
Ah, oops, looks like this one was missed. No worries, I'll do this now since the next `rc` will hopefully be the final release candidate.

**Comment by redshiftzero** [comment]
Closing in favor of #2846

**Pull request closed without merging**
