### PR TITLE
tests: db: reply returns prematurely

### PR DESCRIPTION
**Pull request by dachary**
Signed-off-by: Loic Dachary <loic@dachary.org>

### CODE REVIEW

**Comment by redshiftzero** [comment]
I suggest we just go and and merge this one in. It sounds like we are in agreement that the only line in the diff here is a solid change. Does that sound reasonable @fowlslegs?

**Comment by dachary** [comment]
@fowlslegs I repushed with the suggested change (commit outside of the loop). Block shifting is indeed an easy way to get things wrong in python. Not just with vim ;-)

**Comment by dachary** [comment]
@fowlslegs feel free to merge this one or #1795, I'm glad this is fixed either way.

**Comment by fowlslegs** [comment]
I don't care at all. I'm unable to merge either because I either need a SD team member to approve my PR, or we need to manually run the CI on this PR as those two things, respectively, are blockers to me being able to merge one of them due to our Github-enforced merge policies.

**Comment by dachary** [comment]
@fowlslegs I see ;-) I'll close this one in favor of your  #1795 so there is no duplicate.

**Pull request closed without merging**
