### PR TITLE
Replace "administrator" with "admin"

### LINKED ISSUE #2332: Use either "Admin" or "Administrator" but not both
# Feature request

## Description

The apps / docs should only use "admin" or "administrator" since it's possible these don't map nicely in other languages. Also for consistency.

### PR DESCRIPTION
**Pull request by rjmackay**
## Status

Ready for review

## Description of Changes

Fixes #2332

Changes proposed in this pull request:

Replace instances of Administrator/administrator with Admin/admin

## Testing

How should the reviewer test this PR?
Write out any special testing steps here.

## Deployment

Any special considerations for deployment? Consider both:

1. Upgrading existing production instances.
2. New installs.

### If you made changes to the server application code:

- [ ] Linting (`make ci-lint`) and tests (`make -C securedrop test`) pass in the development container

### If you made changes to `securedrop-admin`:

- [ ] Linting and tests (`make -C admin test`) pass in the admin development container

### If you made changes to the system configuration:

- [ ] [Configuration tests](https://docs.securedrop.org/en/latest/development/testing_configuration_tests.html) pass

### If you made non-trivial code changes:

- [ ] I have written a test plan and validated it for this PR

### If you made changes to documentation:

- [ ] Doc linting (`make docs-lint`) passed locally

### CODE REVIEW

**Comment by rjmackay** [comment]
I'm not 100% sure if how I've updated the translations is correct. I just ran `make translate` after I made the other code changes.

Apologies for not running linting yet, I'm having trouble figuring out how to make it run under OSX

**Comment by heartsucker** [comment]
Tagging @ninavizz to ensure this is an ok change to make.

**Comment by ninavizz** [comment]
Agree: the word "Admin" should be what consistently appears in all user-facing UI and messaging, and is how related functionality should be spoken to in documentation.

Only cautionary note, is that in documentation certain human workflow needs should use the word "administrator" as-appropriate. I don't see the latter happening a whole lot, but just wanted to throw it out there. Kinda like the stylistic difference between spelling the number ten, versus using alpha characters to show the value 10.

**Comment by heartsucker** [comment]
Hey @rjmackay. You don't need to update the `.pot` file. We'll do that when we're ready to merge the string changes into our translation service. Once you back that change out, I can review this :D

**Comment by rjmackay** [comment]
> You don't need to update the .pot file

@heartsucker  Does that apply to the .po files too?

**Comment by heartsucker** [comment]
@rjmackay Correct. You do not need to touch the `.po` and `.pot` files.

**Pull request merged**
