### PR TITLE
Backported changes for 0.5.2 bugfix release

### PR DESCRIPTION
**Pull request by redshiftzero**
## Status

Ready for review

## Description of Changes

These are the changes for the 0.5.2 release (no `rc` commit yet). I took a slightly different approach than used in the past for bugfix releases based on some useful suggestions from @conorsch and @dachary. The approach I took was to first `cherry-pick -x` from individual PRs into backport branches named `backport-pr-<PR number>`, then I merged these PRs into this branch. A nice feature of this is that we can easily see which cherry picked commits came from which PR in the git history. Note however that there's one PR I didn't create a backport branch for... PR #2922, which consists of two small commits on top of modifications in other backported changes, so cherry picking directly into this branch seemed like the cleanest approach.

Comments welcome especially if you think this is a weird thing to do, happy to change it up for next time

## Testing

Does Circle CI pass? 
Are there other changes you feel should be brought in for 0.5.2?

## Deployment

QA will discover this

### If you made changes to the app code:

- [ ] Unit and functional tests pass on the development VM

### If you made changes to the system configuration:

- [ ] [Configuration tests](https://docs.securedrop.org/en/latest/development/testing_configuration_tests.html) pass

### CODE REVIEW

**Comment by redshiftzero** [comment]
Ah right. Builds failing due to #2884, backporting changes from #2886...

**Comment by dachary** [comment]
@redshiftzero This looks really good (except for the angry CI but that's a different story ;-). No conflicts at all ?

**Comment by redshiftzero** [comment]
Nope no conflicts - it all went very smoothly. Now to appease CI 😇

**Comment by redshiftzero** [comment]
CI is failing on `staging-test` due to #2942

CI is failing on `staging-test-with-rebase` due to an incorrect automatic git merge (i.e. no conflicts were detected). In 314a773779527712fdb55f6b9ae035ecbe709eda notice that the diff appears in the stanza corresponding to `staging-test`, but in the original commit 8d7345b444b9853fae99e775a652920bb1401ec4 the diff appeared in the stanza corresponding to `staging-test-with-rebase`

**Comment by redshiftzero** [comment]
Gonna resolve by also backporting #2796 here, as that has CI only changes and should simply fix these CI issues (and will remove the still flaky Travis CI on `master`/`release` branches to boot).

**Comment by redshiftzero** [comment]
Yay backporting #2796 did the trick. Doing the merges this time I did encounter a couple of minor conflicts - where this happened (`.circleci/config.yml` and `securedrop/Dockerfile`) I've noted in the commit messages how they were resolved.

**Comment by dachary** [comment]
The GitHub display is inconvenient for review. Fortunately your consistent branch naming allows for a onliner to help review.

`git --no-pager log --format='%H %s' --graph origin/master..origin/backported-changes-for-0.5.2 | perl -p -e 's/"/ /g; if (/\w+\s+Merge branch .backport-pr-(\d+). into backported-changes-for-.*/) { s|\w+\s+Merge branch .backport-pr-(\d+). into backported-changes-for-.*|[Pull request $1](https://github.com/ceph/ceph/pull/$1)|; } else { s|(\w+)\s+(.*)|[$2](https://github.com/ceph/ceph/commit/$1)|;}  s/^\|\\  $//; s/^\|/   /;'`

* [Reimplements Ansible fail-fast playbook options](https://github.com/ceph/ceph/commit/ac500524737151178e64cfba4755fc0cbc25fc55)
* [Fixes broken ansible-config tests](https://github.com/ceph/ceph/commit/03ecd34472636df2564faba89d170271e9e8e787)
*   [Pull request 2928](https://github.com/ceph/ceph/pull/2928)

    * [Closes #2927, do not fail CI on vulnerable package :(. This change is TEMPORARY until Ansible in `securedrop/requirements/ansible.in` is upgraded to 2.4](https://github.com/ceph/ceph/commit/314a773779527712fdb55f6b9ae035ecbe709eda)
*   [Pull request 2922](https://github.com/ceph/ceph/pull/2922)

    * [Implements any_errors_fatal in all playbooks](https://github.com/ceph/ceph/commit/116230d14270642d7d6a390e2cace402d30e18a4)
    * [Adds test for any_errors_fatal Ansible option](https://github.com/ceph/ceph/commit/7e0b4756df8d583949d0d91792f5b8f492e1b325)
    * [Removes unused  upgrade  playbook](https://github.com/ceph/ceph/commit/ffd8596f44ce6e81a98c207b82ca2da66181c80e)
    * [Implements max_fail_percentage in all playbooks](https://github.com/ceph/ceph/commit/d8f8569afe24a62ddd6cf1da996d6304cf9b7c34)
    * [Adds Makefile target  ansible-config-lint ](https://github.com/ceph/ceph/commit/45dfba74b61179873809dadb105ad52f1814b1c7)
    * [Adds test for max_fail_percentage Ansible option](https://github.com/ceph/ceph/commit/67fac928fefe0094a8aefd5cbf415ae325f1e9cb)
*   [Pull request 2748](https://github.com/ceph/ceph/pull/2748)

    * [Reenables OSSEC connectivity config test](https://github.com/ceph/ceph/commit/70c980f1d415c6d24074c39fae1d5f021f3119ab)
    * [Clean-up systems with multiple agents](https://github.com/ceph/ceph/commit/0ae8af1140faec19ae9cb90442e4362c6cea1f9a)
    * [Purge existing agents from app + mon](https://github.com/ceph/ceph/commit/484c40d190c26b731bead96b9653ed9e2df2693d)
    * [Make registration detection less stringent](https://github.com/ceph/ceph/commit/6d1156ea6cd83c965b949de4cdcda1d0a2521515)
    * [Configure Postfix after OSSEC](https://github.com/ceph/ceph/commit/b594833cd1a1d2a71ac504299648cfe6f3e6d130)
    * [Add temporary iptables to the top of the chain](https://github.com/ceph/ceph/commit/d9d98ac73bdf3fb5e31c4c255935268dd79aabe4)
    * [Add fix for iptables OSSEC monitor temporary rules](https://github.com/ceph/ceph/commit/dc6c9632a9fc2206dd5be4f51f07eb7140f8cc88)
    * [Updates playbooks with new OSSEC role logic](https://github.com/ceph/ceph/commit/8690efe22bfdaa94e44a7500c5518b6db22ddedb)
    * [Creates combined  ossec  role for both hosts](https://github.com/ceph/ceph/commit/478a9a0c8866ae25a378c01d1368a35270dc371c)
    * [Creates  ossec-register  common workflow](https://github.com/ceph/ceph/commit/d36c056f85141a65809f0dc3cd577e1c655f5bbd)
    * [Ports OSSEC pubkey import to  become  pragma](https://github.com/ceph/ceph/commit/05a58189e890dff69f87b96dee2fa0f8edd634df)
    * [Breaks out postfix config into discrete role](https://github.com/ceph/ceph/commit/4a871323ab9704e3a5ed1b5290ce41828168f61c)
    * [Partial implementation of OSSEC iptables fix](https://github.com/ceph/ceph/commit/7e31b6063c3900a495fc79bec67c1b1aed82b23e)
*   [Pull request 2903](https://github.com/ceph/ceph/pull/2903)

    * [Replace aging PyCrypto library with PyCryptodome](https://github.com/ceph/ceph/commit/84f55d195ad67e7c4a9c81300907f672281c4dd3)
*   [Pull request 2796](https://github.com/ceph/ceph/pull/2796)

    * [Merge pull request #2886 from freedomofpress/use-xenial-gettext](https://github.com/ceph/ceph/commit/c4114d56e337c10e1804b1d4815c81eea08b4073)
    * [CI - Temporarily skip junit for test script calls](https://github.com/ceph/ceph/commit/afa4a291d1c104b132eb4b9b1f1687c4527a0512)
    * [Fix syntax on application tests pytest command](https://github.com/ceph/ceph/commit/a5272d0ab80cf6d4b49cefeb3c05d56c4b0bd9c6)
    * [CI - Potential fix for Circle to parse errors](https://github.com/ceph/ceph/commit/d2e1ed491bd983b5c98a81e7d6654fcd12196661)
    * [CI - also dump raw artifacts in test-with-rebase](https://github.com/ceph/ceph/commit/bdf075d331f3e2c5c9eed9c83e23c03a5fcf7948)
    * [CI - Add app/testinfra results into combinedf junit](https://github.com/ceph/ceph/commit/54cdbb166198757560ce9bac02b19ef58d55f573)
    * [Dump raw application and testinfra output in CI](https://github.com/ceph/ceph/commit/652b2742584ad2cdc313423dca3b505af3edcab6)
    * [CI - Break-out test XML cleanup/merge from script](https://github.com/ceph/ceph/commit/b8587362257efd492d9193f8d1b5a55cc8af1bc8)
    * [Docs: Remove Travis CI from developer documentation.](https://github.com/ceph/ceph/commit/71305939071f61a6a53a3ed6ca644f82410ec823)
    * [Remove Travis CI and run pages-layout tests on Circle CI](https://github.com/ceph/ceph/commit/55dfaa5da5b2f9078f05bfb631588480ccef5e80)
    * [Use Xenial to install gettext 0.19.*](https://github.com/ceph/ceph/commit/4227c99cb02ce31a16b9924c1f29d57036c86e5f)
    * [REVERTME -- Temporary testing region in branch](https://github.com/ceph/ceph/commit/07d99bbabdefbb34d200b9a30c28380ff888a49b)
    * [CI - Do not skip ec2 tear-down if keypair rm dies](https://github.com/ceph/ceph/commit/99a05b398b796773cf1355a8f6374f9622ea0fb8)
    * [Remove regular staging-test in bid to keep complexity down](https://github.com/ceph/ceph/commit/b800faa78a5e0f8f7cf135331c0f314ae80b97a6)
* [i18n: add new languages securedrop-confiure.yml](https://github.com/ceph/ceph/commit/9f5e80f3ffec0f5ef4916d3a78dc77d0a622496f)

**Comment by dachary** [comment]
How is [Use Xenial to install gettext 0.19.*](https://github.com/freedomofpress/securedrop/commit/4227c99cb02ce31a16b9924c1f29d57036c86e5f) different from the original commit ?

<pre>
commit=4227c99cb02ce31a16b9924c1f29d57036c86e5f ; picked_from=$(git show --no-patch --pretty=%b $commit  | perl -ne 'print if(s/.*cherry pick.* from commit (\w+).*/$1/)') ; diff -u --ignore-matching-lines '^[^+-]'   <(git show $picked_from) <(git show $commit)
--- /dev/fd/63	2018-01-27 11:42:08.348420006 +0100
+++ /dev/fd/62	2018-01-27 11:42:08.340419907 +0100
@@ -40,19 +47,19 @@
      - apt
 -
 diff --git a/securedrop/Dockerfile b/securedrop/Dockerfile
-index ac875036..340bd96e 100644
+index d579da5e..909b4034 100644
 --- a/securedrop/Dockerfile
 +++ b/securedrop/Dockerfile
-@@ -19,10 +19,10 @@ RUN curl -LO https://launchpad.net/~ubuntu-mozilla-security/+archive/ubuntu/ppa/
+@@ -23,10 +23,10 @@ RUN curl -LO https://launchpad.net/~ubuntu-mozilla-security/+archive/ubuntu/ppa/
  #
  # This can be removed when upgrading to something more recent than trusty
  #
--RUN echo deb http://archive.ubuntu.com/ubuntu/ zesty main > /etc/apt/sources.list.d/zesty.list && \
-+RUN echo deb http://archive.ubuntu.com/ubuntu/ xenial main > /etc/apt/sources.list.d/xenial.list && \
-     apt-get update && \
-     apt-get install -y gettext && \
--    rm /etc/apt/sources.list.d/zesty.list && \
-+    rm /etc/apt/sources.list.d/xenial.list && \
-     apt-get update
+-RUN echo deb http://archive.ubuntu.com/ubuntu/ zesty main > /etc/apt/sources.list.d/zesty.list
++RUN echo deb http://archive.ubuntu.com/ubuntu/ xenial main > /etc/apt/sources.list.d/xenial.list
+ RUN apt-get update
+ RUN apt-get install -y gettext
+-RUN rm /etc/apt/sources.list.d/zesty.list
++RUN rm /etc/apt/sources.list.d/xenial.list
+ RUN apt-get update
  
  COPY requirements requirements
</pre>

**Comment by dachary** [comment]
I think backporting https://github.com/freedomofpress/securedrop/pull/2822 would avoid the two conflicts. However I also don't think it's worth the effort. This only impacts a develop use case that is not even mainline.

**Comment by dachary** [comment]
Verified this branch is based on master:
<pre>
$ git --no-pager log --oneline origin/master..origin/backported-changes-for-0.5.2 | wc -l
43
$ git --no-pager log --oneline origin/master..origin/release/0.5.2
$ 
</pre>

**Comment by dachary** [comment]
I'm merging this even though I'm not 100% sure these are **all** that's needed for 0.5.2. If more PRs need backporting, they can be added later.

**Pull request merged**
