### PR TITLE
Document using the Unsafe Browser for the pfSense WebGUI

### LINKED ISSUE #1050: Update docs to use Unsafe Browser for LAN access
There are currently some steps of the install and admin documentation that direct the reader to access LAN addresses using the Tor Browser: for example, to configure the local firewall using the pfSense WebGUI. While this currently works in Tails, they have an [open ticket](https://labs.riseup.net/code/issues/7976) to block LAN access from the Tor Browser. The upstream issue is currently targeted for Tails 1.4.1, which is currently scheduled for release on [**6/30/15**](https://tails.boum.org/contribute/calendar/).

To fix this issue, change the documentation and update the screenshots to use the *Unsafe Browser* for any access to web resources on the LAN.

### PR DESCRIPTION
**Pull request by garrettr**
Resolves #1050.

### CODE REVIEW

**Comment by conorsch** [comment]
Note that #1025 also affects this file and is marked for 0.3.4. I just checked, and its current state, there are no merge conflicts. Adding a few screenshots in #1025 shouldn't affect that.

**Comment by conorsch** [comment]
:+1: Strong docs, looks great!

**Comment by dolanjs** [comment]
lgtm

**Comment by harlo** [comment]
:+1: looks great

**Pull request merged**
