### PR TITLE
Stopgap for #2760: ignore errors on host checks in validate role

### PR DESCRIPTION
**Pull request by redshiftzero**
## Status

Ready for review

## Description of Changes

Stopgap for #2760 (intentionally not closing that issue until we understand _why_ this is an intermittent failure). 

## Testing

Run `./securedrop-admin sdconfig` and ensure the host checks do not cause a failure

## Deployment

Admins will need to check out 0.5.1 in their admin workstation to get this (when shipped)

## Checklist

Requires manual testing in Tails

### CODE REVIEW

**Comment by conorsch** [comment]
Looks great. Will test locally in prod VMs to be absolutely sure.

**Comment by msheiny** [comment]
@conorsch i made a change and tested in prod VMs so I'm not going to hit merge here unless ya'll are on the same page.

**Comment by conorsch** [comment]
OK, @msheiny, tested your changes and those work, as well. Normally I'd prefer the smallest diff possible, but I can see the scary red error text being confusing to Admins, so I agree with the change. We can always cleanly revert your commit as part of properly addressing #2760.

**Comment by dachary** [comment]
For the record I object to removing this check without understanding why it does not work.

**Comment by redshiftzero** [comment]
Fair @dachary. Unfortunately for many users this validation erroneously reporting a failure means that they are unable to proceed with an install or update (unless they are sufficiently technical to modify the playbook themselves, which is not something most admins can do). Since this validation feature is not necessary, I think removing this from production SecureDrops until we have a validation check that works (at minimum for all SecureDrop testers) - as will be provided by your work in #2758 - is the most conservative course of action. What do you think?

**Comment by conorsch** [comment]
@dachary There are now two changes in this PR:

* @redshiftzero's setting of ignore_errors=yes
* @msheiny's full removal of the known-to-be-bad failing checks, pending final resolution

Do you object to either, or both? My concern at present is that the failure rate is so high, it's preventing Admins from running the playbooks with an otherwise working config. We are intentionally leaving #2760 open to dig into the root cause, since you're right: we don't understand the _why_ yet.

But given that code freeze is a few hours away, I do not think it's realistic to understand the problem adequately at present, and instead suggest we'll need to do so as part of the 0.5.2 work. Thoughts?

**Comment by dachary** [comment]
Ho, sorry, I should have clarified that I object on principle. I don't really have strong feelings otherwise I would have formally object with a negative review ;-)

**Pull request merged**
