### PR TITLE
Integrate build and staging playbooks

### LINKED ISSUE #1040: Fix install_local_pkgs role
The Ansible role `install_local_pkgs` is broken, and should be removed. It's currently being skipped in the Vagrantfile by default for for the `*-staging` hosts, as well as in the online integration tests (still under development) via environment variables, and yet the role is explicitly included in the `securedrop-staging.yml` playbook. 

At a later date, if necessary, we can reimplement the role dynamically, so it doesn't need to be manually excluded all over the place. Doing so will be simpler after some reorganizing of the Ansible layout. 

The rewritten role should provide the following functionality:
- [x] automatically rebuild the app-code deb package as part of the staging playbook
- [x] ensure presence of build vm (otherwise build steps are skipped without error, by default)
- [x] add tags to target rebuilding-and-reinstalling
- [x] provide helpful error messages to developers if packages are missing
- [x] works in digitalocean and virtualbox

### PR DESCRIPTION
**Pull request by conorsch**
Rewrites the `install-local-packages` role to be more friendly to first-time developers. Includes error-handling and provides informative messages that link out to the docs, explaining the need to build the OSSEC packages separately.
### Major changes
- Consolidates all package building into `build-debian-package`, customized via vars in wrapper roles:
  - `build-securedrop-app-code`
  - `build-securedrop-ossec-agent`
  - `build-securedrop-ossec-server`
- Chains the building of Debian packages to the staging playbook, so packages are automatically rebuilt on each run of the staging playbook
- Provides an easy method for rebuild-and-reinstall in staging: `ANSIBLE_ARGS="-t rebuild" vagrant provision /staging/`, and also the external repo for OSSEC base packages
### Minor changes
- Removes sundry bash scripts for building packages
- Updates Serverspec tests with new regression checks for building deb packages
- Creates `ossec_version` variable to provide a single point of change for future updates
- Updates developer documentation to include mention of the `rebuild` tag

Also included here are a few changes to the CI scripts, that were convenient to make while updating the spectests. The changes aren't sufficient yet to activate the automatic Snap-CI runs for PRs, but getting quite close. 

Resolves #1040. Nudges forward—but does not resolve—issues #1023, #1067, and #1208.

### CODE REVIEW

**Comment by garrettr** [comment]
@conorsch Shoot, I broke this by merging #1225. Should I have merged this before #1225, or can this be easily updated to merge on top of it?

**Comment by conorsch** [comment]
@garrettr Not a problem. Rebased the PR on top of the latest develop—the merge conflict was related to the sundry comments I'd added to the `aa-status` parsing block. Left the most verbose in place (see 2ff4d5e) and now we're good to go.

**Comment by garrettr** [comment]
Reviewed this during triage session; requires further testing. Is primarily useful for working on the application code in the staging environment, as well as for automated testing. Let's review this and ideally merge it once we're doing more active development on the application code again.

**Comment by conorsch** [comment]
Rebased on top of latest develop branch. Marking as "in progress" because this requires further review to make sure it still works as advertised. Just ran a build and it seems to work well, but I noticed the helpful error messages pointing to the dev docs assume that the OSSEC package building is covered in the docs, which is isn't. Updated #1208 accordingly.

**Comment by conorsch** [comment]
Badly out of date, going to take a look at this prior to the hackathon—perhaps I can get a more narrowly scoped version up for review, so first-time devs have a sane build and staging environment.

**Comment by conorsch** [comment]
The `develop` has diverged too far since submission for a rebase to be feasible. Will get creative, and likely reimplement a subset of this functionality for review in a separate PR.

**Comment by fowlslegs** [comment]
0.4 milestone @conorsch?

**Comment by conorsch** [comment]
@fowlslegs Yes, 0.4 is reasonable here, as we touch-up the Ansible config. It would help greatly with testing the output of builds, as well. But assign the milestone to #1040, which this PR is supposed to resolve. The goal is to provide a way to test built versions of the app code, served over Tor, in the staging environment. This PR may get merged, or perhaps the pared down #1464.

**Pull request closed without merging**
