### PR TITLE
Update TBB to 10.0.1

### LINKED ISSUE #5577: Tor Browser 9.5.4 no longer available
## Description

Tor Browser 9.5.4 is no longer available on Tor's servers, and the dev container cannot be built.

## Steps to Reproduce
Run `make dev`

## Expected Behavior
Dev server should start, server should come up

## Actual Behavior
Observe the following error
```
--2020-10-14 13:16:49--  https://www.torproject.org/dist/torbrowser/9.5.4/tor-browser-linux64-9.5.4_en-US.tar.xz
Resolving www.torproject.org (www.torproject.org)... 116.202.120.166, 95.216.163.36, 116.202.120.165, ...
Connecting to www.torproject.org (www.torproject.org)|116.202.120.166|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://dist.torproject.org/torbrowser/9.5.4/tor-browser-linux64-9.5.4_en-US.tar.xz [following]
--2020-10-14 13:16:50--  https://dist.torproject.org/torbrowser/9.5.4/tor-browser-linux64-9.5.4_en-US.tar.xz
Resolving dist.torproject.org (dist.torproject.org)... 116.202.120.165, 116.202.120.166, 38.229.72.19, ...
Connecting to dist.torproject.org (dist.torproject.org)|116.202.120.165|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2020-10-14 13:16:51 ERROR 404: Not Found.
```

### PR DESCRIPTION
**Pull request by emkll**
## Status

Ready for review
## Description of Changes

Fixes #5577 

Update the Tor Browser version to 10.0.1 in the dev container.

## Testing

- Clear docker cache of the dev container
- [ ] `make dev` should complete successfully
- [ ] CI is passing

## Deployment

Dev env only

### If you made non-trivial code changes:

- [x] I have written a test plan and validated it for this PR

### CODE REVIEW

**Comment by kushaldas** [comment]
Kicking the CI for the first time.

**Comment by zenmonkeykstop** [comment]
Not a problem with the SI or JI themselves, but with a helper function changing the tbb security level setting in `about:config`. Fixing.

**Comment by zenmonkeykstop** [comment]
Spoke too soon - also some issues with having multiple windows open.

**Review by kushaldas — APPROVED** [review]
Works well locally.

- Clear docker cache of the dev container
- [x] `make dev` should complete successfully
- [x] CI is passing

Approved.

**Pull request merged**
