### PR TITLE
Revert "Don't start redis server twice on Travis"

### LINKED ISSUE #2272: travis: fails to run redis
# Bug

## Description

travis fails consistently because redis is not running

## Steps to Reproduce

push a pull request

## Expected Behavior

travis runs redis

## Actual Behavior

travis does not run redis

## Comments

revert e16b36c5eeab2e53862440dfd39d6828ebdcdb76 which was no longer needed but is now needed again

# Feature request

## Description

A short summary of the idea.

## User Stories

If appropriate

### PR DESCRIPTION
**Pull request by dachary**
## Status

Ready for review

## Description of Changes

Fixes #2272

This reverts commit e16b36c5eeab2e53862440dfd39d6828ebdcdb76.

## Testing

If travis passes for this PR it means it works. It fails for all other PRs.

## Deployment

Test only.

### CODE REVIEW

**Comment by msheiny** [comment]
circleci status issues affecting this :( rebuilding here --- https://circleci.com/gh/freedomofpress/securedrop/1873 🎲

**Comment by dachary** [comment]
Although it would be tempting to figure out how to properly understand why redis does not run, I'm hopeful https://github.com/freedomofpress/securedrop/pull/2256 will remove redis and we won't need to worry about this anymore.

**Comment by redshiftzero** [comment]
Restarted CircleCI build here (there was an interruption in CircleCI builds that is now resolved)

**Comment by dachary** [comment]
re-targeted to release/0.4.3

**Pull request merged**
