### PR TITLE
Fixes Xenial docker build

### LINKED ISSUE #5476: making new docker builder image is broken in xenial
## Description

The Dockerfile to create a new builder image for `Xenial` is broken.

## Steps to Reproduce

- [ ] cd molecule/builder-xenial
- [ ] make

## Expected Behavior

- This should create a new docker image

## Actual Behavior

Failing with error like:

```
127 added, 0 removed; done.
Running hooks in /etc/ca-certificates/update.d...
done.
Processing triggers for sgml-base (1.26+nmu4ubuntu1) ...
Removing intermediate container 708a61c9db0b
 ---> 261ecf55e951
Step 5/10 : RUN echo "deb https://deb.debian.org/debian unstable main contrib" > /etc/apt/sources.list.d/debian-unstable.list
 ---> Running in e49db1f15227
Removing intermediate container e49db1f15227
 ---> c6977474d067
Step 6/10 : COPY aptpreferences.conf /etc/apt/preferences.d/debian-unstable
 ---> 39ef5cc1127a
Step 7/10 : RUN apt-get install -y debian-archive-keyring
 ---> Running in 83fb83c6eb33
Reading package lists...
Building dependency tree...
Reading state information...
E: Unable to locate package debian-archive-keyring
The command '/bin/sh -c apt-get install -y debian-archive-keyring' returned a non-zero code: 100
make: *** [Makefile:7: build-container] Error 100

```

## Comments

- Most probably missing `apt update` step after adding the debian repo and needs apt https magic.

### PR DESCRIPTION
**Pull request by conorsch**
## Status

Ready for review  

## Description of Changes

Fixes #5476. Refs #5471 

Changes proposed in this pull request:

We need a recent version of dh-virtualenv. As for Focal, for Xenial we now pull from the Debian [sic] unstable [sic] repos to get a recent version. In Focal, we could reuse the already-available debian-archive-keyring to verify integrity, but in Xenial, the debian-archive-keyring is too old, Jessie-era (2014-11 vs 2018-09, judging by the timestamps). So for Xenial, we must fetch the required key over HTTPS and provide that to apt manually.

We must also explicitly reference the "unstable" target for dh-virtualenv, since an older version of the package is available in
Xenial, and will be preferrred to the unstable version given the cautious apt preferences we configure.

## Testing

- [ ] `make dev` results in a working container
- [ ] `cd molecule/builder-xenial && make` builds successfully
- [ ] run an interactive shell inside the latest xenial build container and confirm that `apt-cache policy dh-virtualenv` shows `1.2.1-1` (not 0.11-1 from Xenial)
- [ ] `make debs` builds xenial packages without error

## Deployment
Affects packaging build logic, will be used for upcoming release. No implications for admin intervention, but we must be confident in the build logic prior to entering QA period.

### If you made changes to the server application code:

- [ ] Linting (`make lint`) and tests (`make test`) pass in the development container

### If you made changes to `securedrop-admin`:

- [ ] Linting and tests (`make -C admin test`) pass in the admin development container

### If you made changes to the system configuration:

- [ ] [Configuration tests](https://docs.securedrop.org/en/latest/development/testing_configuration_tests.html) pass

### If you made non-trivial code changes:

- [ ] I have written a test plan and validated it for this PR

### If you made changes to documentation:

- [ ] Doc linting (`make docs-lint`) passed locally

### If you added or updated a code dependency:

Choose one of the following:

- [ ] I have performed a diff review and pasted the contents to [the packaging wiki](https://github.com/freedomofpress/securedrop-debian-packaging/wiki)
- [ ] I would like someone else to do the diff review

### CODE REVIEW

**Comment by conorsch** [comment]
CI is failing on the make-debs command, which I ommitted from the test plan. Will update, marking WIP until CI is passing. @rmol if you've already started review, I welcome comments, but might be best to hold off until we confirm the packages are building correctly.

**Comment by rmol** [comment]
Was just about to comment. I've been seeing that same error locally:

<details>
<summary>invalid command 'bdist_wheel'</summary>

```
Install SecureDrop Python requirements in container...
      xenial-sd-app failed | msg: non-zero return code | stdout: Collecting alembic==0.9.9
      Downloading alembic-0.9.9.tar.gz (1.0 MB)
    Collecting argon2-cffi==20.1.0
      Downloading argon2-cffi-20.1.0.tar.gz (1.8 MB)
      Installing build dependencies: started
      Installing build dependencies: finished with status 'done'
      Getting requirements to build wheel: started
      Getting requirements to build wheel: finished with status 'done'
      Installing backend dependencies: started
      Installing backend dependencies: finished with status 'done'
        Preparing wheel metadata: started
        Preparing wheel metadata: finished with status 'error' | stderr:     ERROR: Command errored out with exit status 1:
         command: /usr/bin/python3 /tmp/tmprp5x3t24 prepare_metadata_for_build_wheel /tmp/tmpzcqyz2fk
             cwd: /tmp/pip-install-3r_amccn/argon2-cffi
        Complete output (20 lines):
        running dist_info
        creating /tmp/pip-modern-metadata-1h4jng6z/argon2_cffi.egg-info
        writing /tmp/pip-modern-metadata-1h4jng6z/argon2_cffi.egg-info/PKG-INFO
        writing dependency_links to /tmp/pip-modern-metadata-1h4jng6z/argon2_cffi.egg-info/dependency_links.txt
        writing requirements to /tmp/pip-modern-metadata-1h4jng6z/argon2_cffi.egg-info/requires.txt
        writing top-level names to /tmp/pip-modern-metadata-1h4jng6z/argon2_cffi.egg-info/top_level.txt
        writing manifest file '/tmp/pip-modern-metadata-1h4jng6z/argon2_cffi.egg-info/SOURCES.txt'
        reading manifest file '/tmp/pip-modern-metadata-1h4jng6z/argon2_cffi.egg-info/SOURCES.txt'
        reading manifest template 'MANIFEST.in'
        warning: no files found matching '*.txt'
        warning: no files found matching '.coveragerc'
        warning: no previously-included files found matching 'src/argon2/_ffi.py'
        warning: no previously-included files found matching '.gitmodules'
        warning: no previously-included files found matching 'extras/libargon2/.git'
        warning: no previously-included files found matching '*.yml'
        warning: no previously-included files matching '*.pyc' found under directory 'tests'
        no previously-included directories found matching 'docs/_build'
        writing manifest file '/tmp/pip-modern-metadata-1h4jng6z/argon2_cffi.egg-info/SOURCES.txt'
        creating '/tmp/pip-modern-metadata-1h4jng6z/argon2_cffi.dist-info'
        error: invalid command 'bdist_wheel'
        ----------------------------------------
    ERROR: Command errored out with exit status 1: /usr/bin/python3 /tmp/tmprp5x3t24 prepare_metadata_for_build_wheel /tmp/tmpzcqyz2fk Check the logs for full command output.
```
</details>

Which suggests we need `python3-wheel` or `python-pip-whl` installed, maybe? But while looking into this I found the new build image has Python 3.8 installed? I was still investigating that when I saw your comment. Ideas?

**Comment by rmol** [comment]
The installation of `dh-virtualenv` from Debian unstable was pulling in `python3-virtualenv` and newer Python 3 bits. Including `virtualenv` in the big package list installed earlier prevents that and solves the problem above.

**Comment by conorsch** [comment]
Thanks, @rmol. I'll pull down the changes and confirm.

**Comment by conorsch** [comment]
Thanks for the collab, @rmol. CI is now passing. Take a gander at the most recent commits, which try to flesh out the tests a bit to make the py3 & dh-virtualenv required versions more obvious. Will port those over to Focal when reviewing #5465.

**Review by kushaldas — APPROVED** [review]
The diff looks good, tested with the following steps:

- [x] `make dev` results in a working container
- [x] `cd molecule/builder-xenial && make` builds successfully
- [x] run an interactive shell inside the latest xenial build container and confirm that `apt-cache policy dh-virtualenv` shows `1.2.1-1` (not 0.11-1 from Xenial)
- [x] `make build-debs` builds xenial packages without error

**Pull request merged**
