### PR TITLE
align logout message with timeout msg

### PR DESCRIPTION
**Pull request by KwadroNaut**
## Status

Ready for review

## Algining the wording on logout due to session timeout and actual logging out

One could argue if restarting browsers is sufficient. 

## Checklist

I believe we're already in the string freeze, so for release n+1.

### CODE REVIEW

**Comment by KwadroNaut** [comment]
FYI:
securedrop/source_templates/logout_flashed_message.html
securedrop/source_templates/session_timeout.html

**Comment by dachary** [comment]
Removing myself from the reviewers list because I'm not a native English speaker. Reminder: this must not be merged before 0.5 is branched because we are in **string freeze** mode.

**Comment by dachary** [comment]
@KwadroNaut could you please explain why someone not using tor should restart the browser ? 

I'm inclined to think we should display the tor related part of the message only to Tor users. And people not using tor will get the "We recommend using Tor Browser to access SecureDrop". And maybe the recommendation to restart the browser.

**Comment by dachary** [comment]
@KwadroNaut I rebased your commit which was conflicting in a trivial way.

**Comment by KwadroNaut** [comment]
@dachary the difference is Tor browser bundle vs. a browser that is manually configured to use Tor. They're all Tor users. Rationale for closing the browser, is closing the session. I don't know who initially introduced this wording, but that's how I'd read it.

**Comment by dachary** [comment]
> They're all Tor users. 

Oh, of course. Not like the development environment where we use a regular browser. Thanks for spelling that out.

**Comment by dachary** [comment]
> They're all Tor users. 

Oh, of course. Not like the development environment where we use a regular browser. Thanks for spelling that out.

When I restart Firefox in the development environment, the session is still active (i.e. http://localhost:8080/lookup#codename-hint-visible shows the same codename). If I had tor, would it be different ? Does tor use the same circuit in this case or another circuit always ? (I did not try ;-)

**Comment by KwadroNaut** [comment]
> When I restart Firefox in the development environment, the session is still active (i.e. http://localhost:8080/lookup#codename-hint-visible shows the same codename). If I had tor, would it be different ? Does tor use the same circuit in this case or another circuit always ? (I did not try ;-)

It might be old behavior described, these days browsers do their best to 'restore browsing sessions', I'm not sure. Circuits: you should get a new one, by restarting. Hitting new identity is what I personally would recommend though: https://www.torproject.org/projects/torbrowser/design/#new-identity

**Comment by dachary** [comment]
I tried the following:

* installed tor on my laptop
* sudo apt-key add ~/software/securedrop/securedrop/install_files/ansible-base/roles/tor-hidden-services/files/tor-signing-key.pub
* sudo apt-add-repository http://deb.torproject.org/torproject.org
* sudo apt-get install tor
* configured firefox to use it as a socks5 proxy
* go to http://bot.whatismyipaddress.com/ => 2a02:c207:3002:267::1
* exit with File => Quit
* start firefox 
* go to http://bot.whatismyipaddress.com/ => 2a02:c207:3002:267::1
* sudo systemctl restart tor
* go to http://bot.whatismyipaddress.com/ => 2c0f:f930:0:5::38

Is there something specific to what I did ? Should I get a new circuit, hence a new IP ? Is my installation not typical for some reason ?

**Comment by dachary** [comment]
I tried the following:

* installed tor on my laptop
* sudo apt-key add ~/software/securedrop/securedrop/install_files/ansible-base/roles/tor-hidden-services/files/tor-signing-key.pub
* sudo apt-add-repository http://deb.torproject.org/torproject.org
* sudo apt-get install tor
* configured firefox to use it as a socks5 proxy
* go to http://bot.whatismyipaddress.com/ => 2a02:c207:3002:267::1
* exit with File => Quit
* start firefox 
* go to http://bot.whatismyipaddress.com/ => 2a02:c207:3002:267::1
* sudo systemctl restart tor
* go to http://bot.whatismyipaddress.com/ => 2c0f:f930:0:5::38

Is there something specific to what I did ? Should I get a new circuit, hence a new IP ? Is my installation not typical for some reason ?

**Comment by dachary** [comment]
When network.proxy.socks_remote_dns is set to true in about:config the exit node varies much more frequently. Control-R on  http://bot.whatismyipaddress.com/ shows a different IP > 50% of the time. And I've not been given the same exit node after restarting firefox (tried 10 times).

**Comment by KwadroNaut** [comment]
@dachary I only wanted to make sure the wording was the same for both (minor). Now it seems you want to discuss the whole thing (not so minor).
So, let's dissect it:

> Thank you for exiting your session! Please select "New Identity" from the green onion button in the Tor browser to clear all history of your SecureDrop usage from this device.  If you are not using Tor Browser, restart your browser.

The new identity is clear and preferred, it does it very best to remove any content that is related to your recent visit to that SD instance (see design docs link).

The second sentence however is different: what are people using? We can presume they're using Tor; that's what we recommend everywhere on how to host any SD instance. Is it safe to presume that they use, for example, Firefox that is manually configured to use a SOCKS proxy? **DNS must also be forwarded to the socks proxy**, otherwise you can't resolve the onion. What happens when you close and restart the browser? Normally the used circuit would be marked as dirty (because used). Cleaned up after 10 minutes if not used. When closing a browser, and reopening, you should thus get a new circuit. When not closed, your session might stick along longer, especially if you have several tabs open. Such a setup will probably not bother trying to use new circuits for different tabs.

Also for learning/debugging I'd recommend to not use such a website but rather have a look at one of these:
* which exit used: https://stem.torproject.org/tutorials/examples/exit_used.html 
* another list containing several circuit viewers: https://stem.torproject.org/tutorials/double_double_toil_and_trouble.html

**Comment by dachary** [comment]
> Now it seems you want to discuss the whole thing (not so minor).

It's me being ignorant, I really appreciate you taking the time to educate me <3

**Comment by dachary** [comment]
> When closing a browser, and reopening, you should thus get a new circuit. 

That's also what I observe but I don't know how certain this is. When we ask for a new circuit to the tor browser we know for sure we'll have one. If we recommend to restart the browser as an alternative, user will naturally think a new circuit will always be used. Now... instead of spaming this issue with (excellent) tutorials about tor for my selfish benefit I'll let someone with actual expertise review this ;-)

**Comment by dachary** [comment]
@redshiftzero would you mind taking a look ?

**Comment by redshiftzero** [comment]
So for background, the main reason we encourage sources to restart the browser is to get rid of any identifying cookies on the source's computer. Since Tor Browser treats all cookies as session cookies (via [`network.cookie.lifetimePolicy`](https://developer.mozilla.org/en-US/docs/Cookies_Preferences_in_Mozilla)), a restart/"Get new identity" is sufficient. 

However, @KwadroNaut makes a good point in the PR description: if a user is NOT using Tor Browser, this won't work. Indeed, they will have larger problems than the cookies. They probably have a lot of identifying information lying around that in the course of a leak investigation could lead to their identification, e.g. their browsing history, cached browser content. A browser restart will not remove (at least some of) these items. If this is a concern for their threat model (for some SecureDrop sources this might not be an issue), then they should really be using Tor Browser, since it was designed for precisely this use case (a related ticket is #2342: we should do everything possible to get sources to use Tor Browser, interested in your feedback @KwadroNaut on that ticket if you have any thoughts on that).

Also, right now the flashed message discussed in this PR currently _is not displayed_ if a user is not using Tor Browser (this is due to the use of the `hide-if-not-tor-browser`  class - see [source_app/main.py](https://github.com/freedomofpress/securedrop/blob/develop/securedrop/source_app/main.py#L236)). 

Unfortunately given all this, I think it makes sense to close this one. I will do that now, but feel free to continue discussion in this PR.

**Pull request closed without merging**
