### PR TITLE
Enable seccomp sandboxing for Tor

### PR DESCRIPTION
**Pull request by ageis**
One-line change to the App+Mon torrc to utilize the seccomp2 syscall filtering facility on Linux to limit which system calls Tor can invoke. This feature first appeared in 0.2.5.1-alpha (2013-10-02) with the disclaimer "This is an experimental, Linux-only feature to provide defense-in-depth against unknown attacks." Since then it has improved and seen many bugfixes through 2014. Now all builds of Tor for jessie, trusty or later include seccomp support, and it's being used in production on Tails.

I've only tested it in the virtual staging environment; we should probably increase our automated testing coverage before making this change. 

**An important note**:
Per #982, the 'Sandbox' value can't be changed without a full restart. If you try to do a Tor reload after changing this line, Tor will fail to parse the config and actually exit. So if this is updated as part of a playbook run we will have to include a Tor restart and a wait period for the SSH connection to come back, otherwise merging this change could be catastrophic and lock you out requiring a reboot or console access.

### CODE REVIEW

**Comment by garrettr** [comment]
> So if this is updated as part of a playbook run we will have to include a Tor restart and a wait period for the SSH connection to come back, otherwise merging this change could be catastrophic and lock you out requiring console access.

We should include the required changes to the playbooks to support this before merging this (mainly so we don't forget to do it).

Otherwise I think this a good change to make and agree that it seems to have seen enough testing in the broader ecosystem.

**Comment by dolanjs** [comment]
@ageis you did change this in the correct spot in the playbook but will need to make the changes to the spec tests for this also.
`spec_tests/spec/common-staging/tor_spec.rb`

Also explain or paste the output of testing that shows the affected features still work please.

**Comment by ageis** [comment]
I added the line to the spec test.

Per [our task which installs torrc](https://github.com/freedomofpress/securedrop/blob/develop/install_files/ansible-base/roles/common-app/tasks/app_configure_tor_hidden_services.yml), Tor is restarted [via a handler](https://github.com/freedomofpress/securedrop/blob/develop/install_files/ansible-base/roles/common-app/handlers/main.yml) right after the file is put in place. I don't know what that means for running the playbook over Tor, as there is not a wait task, but if the restart is already there I think that means this is safe to merge.

**Comment by ageis** [comment]
I should add that I tested with Sandbox enabled in the staging environment and all of the interfaces and sshd were reachable. Nothing untoward was noticed in the logs (AppArmor, syslog, OSSEC) either.

**Comment by garrettr** [comment]
We need to keep an eye on this patch, as it will be extremely annoying if there's any way it could lead to breakage of running (or re-running, or re-running just specific parts of, via tags) the Ansible playbooks. I think the best course of action is to merge it now, so we can start exercising it during development (in the staging and production environments), and hopefully any bugs it might have will shake out before the next stable release.

**Pull request merged**
