### PR TITLE
Persistent SecureDrop Tails setup — admin automatic, journalist interactive

### PR DESCRIPTION
**Pull request by ageis**
Why not copy the launcher to the Desktop when `./install.sh` is run? It won't persist across reboots, but it will slightly increase usability and decrease steps post-install.

Only drawback: it could train the journalist or admin to expect it there and not look in the `~/Persistent` folder which they must do on subsequent boots.

### CODE REVIEW

**Comment by ageis** [comment]
Actually, I just worked out a way to make the launcher persist on the Desktop using the Dotfiles persistence. This is implemented in the second commit. Tested and working!

**Comment by micahflee** [comment]
Awesome!

**Comment by garrettr** [comment]
@ageis Since you already have the dotfiles working, why not just get rid of the requirement to double-click the launcher, and just auto-run the program to setup the torrc at boot? That would close #896.

**Comment by ageis** [comment]
This most recent commit eliminates the need for the launcher, makes the `torrc_additions` persistent, and installs persistent desktop bookmarks for both interfaces. It also runs `securedrop_init` on its own at the end. Resolves #896.

I have tested this and it's reliable.

Unfortunately, to create the launchers, `install.sh` now has a dependency on the Admin Workstation post-install, requiring the THS files generated by Ansible. If we choose to keep or fork that, then we should eliminate manual editing of torrc_additions too and handle that step automatically.

We don't have to have a separate script for journalists - I could just add some more stuff, like checking for the presence of files to figure out if it's an Admin vs. Journalist workstation, and launching gedit or setting up launchers based on that.

**Comment by ageis** [comment]
The latest commit adds the handling discussed above so that `install.sh` works for both admins and journalists. The journalist setup is interactive while the admin's is fully automatic.

We should decide whether we want to merge this in time for 0.3.1 - I need to know within a couple days either way because of documentation.

**Comment by garrettr** [comment]
@ageis There's a lot of good stuff in this PR, but:

1. It won't merge right now
2. We merged #925, which makes the torrc changes auto-run on boot and obviates the need for the Desktop launcher.

Can you rework this to include the improvements that you think would still be relevant, given #925?

**Comment by garrettr** [comment]
Closing this in favor of #955.

**Pull request closed without merging**
