### PR TITLE
Slims down upgrade testing logic

### LINKED ISSUE #3208: [xenial] Deprecate Vagrantfile in favor of Molecule scenarios
# Feature request

## Description

We've started to use [Molecule](https://molecule.readthedocs.io/en/latest/) for testing various aspects of the SD development environment, including most recently the potential introduction of local upgrade testing (#3075). Let's continue in that direction and adopt Molecule as a wrapper for all Vagrant calls, as we did with the build VM in #2160. 

Doing so will allow improvements such as:

* Evaluating Xenial as a potential migration path (#3206)
* Ditch custom `tesitnfra/test.py` script (#2437)
* Tighter workflow integration, such as `molecule test -s staging` performing essentially:
  * `vagrant up /staging/ --no-provision`
  * `vagrant provision /staging/`
  * `vagrant provision /staging/` # idempotence check
  * `flake8 testinfra/`
  * `ansible-lint install_files/ansible-base/securedrop-staging.yml`
  * `./testinfra/test.py app-staging`
  * `./testinfra/test.py mon-stagng`
  * `vagrant destroy -f /staging/`

For more information, see the [Molecule docs on scenarios](https://molecule.readthedocs.io/en/latest/configuration.html#scenario). Note that we're already using Molecule for the CI staging scenario (#2218); we should rename that scenario to `staging-aws` for clarity, IMO. 

One potential shortcoming is that Molecule v2 requires one provider, e.g. VirtualBox _or_ KVM/libvirt, whereas raw Vagrantfiles support multiple. If that turns out to be a problem we can always provide a Vagrantfile template to Molecule and customize at will. 

## User Stories

As a maintainer, I want to lean on community-maintained test harnesses where possible. 

As a developer, I want to deal with a minimum of fuss to provision and test dev environments for a complicated project like SecureDrop.

### LINKED ISSUE #5512: Support in-place upgrades for Focal VMs
## Description

We currently have a (libvirt-only) `upgrade` molecule scenario that is updated at every SecureDrop release that can be use to test upcoming SecureDrop versions automatically.

We should add a new molecule scenario for upgrade-focal, upload new focal boxes new boxes on the latest release that supports Focal, and ensure the upgrade is working

### LINKED ISSUE #5883: Upgrade scenario is broken
## Description

The `upgrade` scenario, used for testing in-place upgrades on Xenial, is no longer behaving well. First reported in https://github.com/freedomofpress/securedrop/pull/5870#issuecomment-804508509

## Steps to Reproduce
1. Check out latest `develop` branch
2. Run `echo 1.7.1 > molecule/shared/stable.ver` to use an existing box (1.8.0 boxes are unmerged, in #5870)
2. Run `make upgrade-start`

## Expected Behavior
Scenario prep is completed, process exits 0, three (3) VMs are configured and ready for upgrade: app, mon, & apt.

## Actual Behavior

Scenario prep hangs while creating the app server. If you run `virt-manager`, you can see that `upgrade_apt` was created fine (directly from the upstream Bento box), box 

## Comments

Suggestions to fix, any other relevant information.

### PR DESCRIPTION
**Pull request by conorsch**
## Status

Ready for review

## Description of Changes

Resolves a few issues:

* Closes #5512 
* Closes #5883 
* Closes #3208 

Changes proposed in this pull request:

Makes a few changes to refresh the upgrade testing logic for
compatibility with Focal VMs. Specifically:

  * Prod VMs are now configured via Molecule
  * Removes all use of custom-built Vagrant boxes
  * Clarifies upgrade steps (see also related docs PR)

Docs will be updated separately.

## Testing
The docs PR at https://github.com/freedomofpress/securedrop-docs/pull/227 should be reviewed in tandem with this PR. Check those docs and make sure the procedures there work for the use case of SD pre-release QA. At a high-level, those steps are:

0. Make sure you're using libvirt-based VMs (upgrade scenario does not support Qubes env)
1. `molecule create -s libvirt-prod-focal`
2. Boot up admin workstation and install against those prod VMs with `./securedrop-admin install`
3. `make build-debs` on host (ok to run this in parallel with step 2 to save time)
4. `make upgrade-start` on host, to set up local apt repo
5. Back in admin workstation, run the playbook `securedrop-apt-local.yml` (make sure to source the admin venv first, see docs)
6. Confirm you can upgrade packages inside the VMs

## Deployment
Dev-only.

### CODE REVIEW

**Review by zenmonkeykstop — COMMENTED** [review]
- [x] molecule prod VM scenario works great
- [x] `make upgrade-start` also good, no issues setting up apt server
- [ ] Repeated fails on the `securedrop-apt-local.yml` playbook, failing to add the 10.0.1.7 repo
- [x] once repo added, `sudo unattended-upgrades -d` works fine, upgrading packages to local versions.

This is a good simplification overall and spares the effort of maintaining the upgrade boxes - there is some flakiness on my system wrt. the playbook `Add local repo` step, which occasionally fails for one or both servers with an "apt cache update failed" message (this is existing code tho so not the fault of this PR).

Holding off on approving to poke at that playbook error but otherwise this looks OK to go.

**Comment by conorsch** [comment]
> Add local repo step, which occasionally fails for one or both servers with an "apt cache update failed" message 

Might be more straightforward to debug if you break that up into several tasks, like a `copy` to write the repo, then a separate task to update apt lists afterward. I've seen that error before while testing, but it was inconsistent, and I don't have a better suggestion for debugging than separating the steps involved.

**Comment by zenmonkeykstop** [comment]
Context for the many fun and interesting ways in which this can fail both deterministically and non- : https://github.com/ansible/ansible/issues/30754

**Comment by zenmonkeykstop** [comment]
Can't reproduce the apt cache update failure on two fresh installs, calling it a flake and merging.

**Review by zenmonkeykstop — APPROVED** [review]
Approved, LGTM as apt cache issue is unrelated to changes.

**Pull request merged**
