### PR TITLE
Apparmor: allow apache2 to execute /usr/bin/file

### LINKED ISSUE #3020: AppArmor denied /usr/bin/file for apache2
# Bug

## Description

```


OSSEC HIDS Notification.
2018 Feb 14 05:11:43

Received From: (app) 10.20.2.2->/var/log/syslog
Rule: 100012 fired (level 7) -> "Apparmor denied event"
Portion of the log(s):

Feb 14 05:11:42 app kernel: [ 2122.691210] audit: type=1400 audit(1518585102.440:46): apparmor="DENIED" operation="exec" profile="/usr/sbin/apache2" name="/usr/bin/file" pid=2693 comm="apache2" requested_mask="x" denied_mask="x" fsuid=33 ouid=0



 --END OF NOTIFICATION
```
## Steps to Reproduce

- Open ossec alert emails with title `OSSEC Notification - (app) - Alert level 7`
- Observe a large amount of errors pasted above

## Expected Behavior

AppArmor rules should not alert on nominal apache2 behavior

## Actual Behavior

AppArmor and in turn ossec alert on what appears to be nominal webserver behavior

### PR DESCRIPTION
**Pull request by emkll**
## Status

Ready for review

## Description of Changes

Fixes #3020.
AppArmor profile now allows `/usr/sbin/apache2` to execute `/usr/bin/file`

Changes proposed in this pull request:

## Testing

- set up prod environment (vms or physical)
- `make build-debs`
- `scp` and install `securedrop-app-code` package
- observe no AppArmor denied messages in `/var/log/syslog` and no ossec email alerts full of apparmor denied messages.

## Deployment

New and existing installs should be covered by the updated `securedrop-app-code` deb package

### If you made changes to the app code:

- [ ] Unit and functional tests pass on the development VM

### If you made changes to the system configuration:

- [x] [Configuration tests](https://docs.securedrop.org/en/latest/development/testing_configuration_tests.html) pass

### If you made changes to documentation:

- [ ] Doc linting passed locally

### CODE REVIEW

**Comment by dachary** [comment]
> scp and install securedrop-app-code package

I'm curious to understand why:

      ANSIBLE_ARGS="--tags rebuild" vagrant provision app-staging

would not work ?

**Comment by emkll** [comment]
@dachary yes `vagrant provision` should work for staging environments! I was using the manual scp method because I wanted to use prod vms to test the (absence of) email alerts

**Comment by dachary** [comment]
@emkll it fixes this particular message but there seems to be more. Going in the right direction !

<pre>
$ make build-debs
$ vagrant up /staging/
$ tor-browser $(cat install_files/ansible-base/app-source-ths)
# submit document
$ vagrant ssh app-staging
root@app-staging:~# grep -i apparmor /var/log/syslog | grep -i denied
Feb 21 10:12:22 app-staging kernel: [  399.126077] audit: type=1400 audit(1519207942.865:16): apparmor="DENIED" operation="open" profile="/usr/sbin/apache2" name="/etc/magic" pid=1746 comm="file" requested_mask="r" denied_mask="r" fsuid=33 ouid=0
Feb 21 10:12:22 app-staging kernel: [  399.126292] audit: type=1400 audit(1519207942.865:17): apparmor="DENIED" operation="open" profile="/usr/sbin/apache2" name="/usr/share/file/magic.mgc" pid=1746 comm="file" requested_mask="r" denied_mask="r" fsuid=33 ouid=0
Feb 21 10:12:22 app-staging kernel: [  399.126418] audit: type=1400 audit(1519207942.865:18): apparmor="DENIED" operation="open" profile="/usr/sbin/apache2" name="/usr/share/file/magic/" pid=1746 comm="file" requested_mask="r" denied_mask="r" fsuid=33 ouid=0
Feb 21 10:12:22 app-staging kernel: [  399.129656] audit: type=1400 audit(1519207942.869:19): apparmor="DENIED" operation="open" profile="/usr/sbin/apache2" name="/etc/magic" pid=1747 comm="file" requested_mask="r" denied_mask="r" fsuid=33 ouid=0
Feb 21 10:12:22 app-staging kernel: [  399.129673] audit: type=1400 audit(1519207942.869:20): apparmor="DENIED" operation="open" profile="/usr/sbin/apache2" name="/usr/share/file/magic.mgc" pid=1747 comm="file" requested_mask="r" denied_mask="r" fsuid=33 ouid=0
Feb 21 10:12:22 app-staging kernel: [  399.129782] audit: type=1400 audit(1519207942.869:21): apparmor="DENIED" operation="open" profile="/usr/sbin/apache2" name="/usr/share/file/magic/" pid=1747 comm="file" requested_mask="r" denied_mask="r" fsuid=33 ouid=0
Feb 21 10:12:22 app-staging kernel: [  399.134135] audit: type=1400 audit(1519207942.873:22): apparmor="DENIED" operation="open" profile="/usr/sbin/apache2" name="/etc/magic" pid=1748 comm="file" requested_mask="r" denied_mask="r" fsuid=33 ouid=0
Feb 21 10:12:22 app-staging kernel: [  399.134156] audit: type=1400 audit(1519207942.873:23): apparmor="DENIED" operation="open" profile="/usr/sbin/apache2" name="/usr/share/file/magic.mgc" pid=1748 comm="file" requested_mask="r" denied_mask="r" fsuid=33 ouid=0
Feb 21 10:12:22 app-staging kernel: [  399.134267] audit: type=1400 audit(1519207942.873:24): apparmor="DENIED" operation="open" profile="/usr/sbin/apache2" name="/usr/share/file/magic/" pid=1748 comm="file" requested_mask="r" denied_mask="r" fsuid=33 ouid=0
Feb 21 10:12:22 app-staging kernel: [  399.137587] audit: type=1400 audit(1519207942.877:25): apparmor="DENIED" operation="open" profile="/usr/sbin/apache2" name="/etc/magic" pid=1749 comm="file" requested_mask="r" denied_mask="r" fsuid=33 ouid=0
root@app-staging:~# 
</pre>

**Comment by emkll** [comment]
In my testing (both physical instance and prod vms) I have not managed to reproduced @dachary 's findings. Could someone else test this PR? If the behavior @dachary is describing is true, this will introduce more denied messages (thus larger email volume), which would be an unfortunate regression.

**Comment by dachary** [comment]
@emkll did you figure out why `/usr/bin/file` is called at all ? When called it will definitely try `/etc/magic`, that's what it is meant to do. I think we need to understand that first. That would allow us to repeat the conditions under which `/usr/bin/file` is called for sure.

**Comment by redshiftzero** [comment]
@emkll I tested this PR in the staging environment and I reproduce @dachary's findings:

```
Feb 22 23:12:25 app-staging kernel: [   79.154321] audit: type=1400 audit(1519341145.473:27): apparmor="DENIED" operation="open" profile="/usr/sbin/apache2" name="/usr/share/file/magic.mgc" pid=1608 comm="file" requested_mask="r" denied_mask="r" fsuid=33 ouid=0
Feb 22 23:12:25 app-staging kernel: [   79.154392] audit: type=1400 audit(1519341145.473:28): apparmor="DENIED" operation="open" profile="/usr/sbin/apache2" name="/usr/share/file/magic/" pid=1608 comm="file" requested_mask="r" denied_mask="r" fsuid=33 ouid=0
Feb 22 23:12:25 app-staging kernel: [   79.156782] audit: type=1400 audit(1519341145.473:29): apparmor="DENIED" operation="open" profile="/usr/sbin/apache2" name="/etc/magic" pid=1609 comm="file" requested_mask="r" denied_mask="r" fsuid=33 ouid=0
```

**Comment by conorsch** [comment]
Agreed with @redshiftzero (and @dachary):
```
DENIED" operation="open" profile="/usr/sbin/apache2" name="/etc/magic" pid=1721 comm="file" requested_mask="r" denied_mask="r" fsuid=33 ouid=0
Feb 22 23:16:22 app-staging kernel: [  188.873346] audit: type=1400 audit(1519341382.576:21): apparmor="DENIED" operation="open" profile="/usr/sbin/apache2" name="/usr/share/file/magic.mgc" pid=1721 comm="file" requested_mask="r" denied_mask="r" fsuid=33 ouid=0
Feb 22 23:16:22 app-staging kernel: [  188.873551] audit: type=1400 audit(1519341382.576:22): apparmor="DENIED" operation="open" profile="/usr/sbin/apache2" name="/usr/share/file/magic/" pid=1721 comm="file" requested_mask="r" denied_mask="r" fsuid=33 ouid=0
Feb 22 23:16:22 app-staging kernel: [  188.879671] audit: type=1400 audit(1519341382.580:23): apparmor="DENIED" operation="open" profile="/usr/sbin/apache2" name="/etc/magic" pid=1722 comm="file" requested_mask="r" denied_mask="r" fsuid=33 ouid=0
Feb 22 23:16:22 app-staging kernel: [  188.879700] audit: type=1400 audit(1519341382.580:24): apparmor="DENIED" operation="open" profile="/usr/sbin/apache2" name="/usr/share/file/magic.mgc" pid=1722 comm="file" requested_mask="r" denied_mask="r" fsuid=33 ouid=0
Feb 22 23:16:22 app-staging kernel: [  188.879866] audit: type=1400 audit(1519341382.580:25): apparmor="DENIED" operation="open" profile="/usr/sbin/apache2" name="/usr/share/file/magic/" pid=1722 comm="file" requested_mask="r" denied_mask="r" fsuid=33 ouid=0
Feb 22 23:16:22 app-staging kernel: [  188.887811] audit: type=1400 audit(1519341382.588:26): apparmor="DENIED" operation="open" profile="/usr/sbin/apache2" name="/etc/magic" pid=1723 comm="file" requested_mask="r" denied_mask="r" fsuid=33 ouid=0
Feb 22 23:16:22 app-staging kernel: [  188.887851] audit: type=1400 audit(1519341382.588:27): apparmor="DENIED" operation="open" profile="/usr/sbin/apache2" name="/usr/share/file/magic.mgc" pid=1723 comm="file" requested_mask="r" denied_mask="r" fsuid=33 ouid=0
Feb 22 23:16:22 app-staging kernel: [  188.888720] audit: type=1400 audit(1519341382.592:28): apparmor="DENIED" operation="open" profile="/usr/sbin/apache2" name="/usr/share/file/magic/" pid=1723 comm="file" requested_mask="r" denied_mask="r" fsuid=33 ouid=0
Feb 22 23:16:22 app-staging kernel: [  188.894408] audit: type=1400 audit(1519341382.596:29): apparmor="DENIED" operation="open" profile="/usr/sbin/apache2" name="/etc/magic" pid=1724 comm="file" requested_mask="r" denied_mask="r" fsuid=33 ouid=0
```

Simply loading the Source Interface was enough to trigger that flurry.

**Comment by dachary** [comment]
`secure_tempfile.py`  has
```
from Cryptodome.Cipher import AES
```

which indirectly indirectly calls `Cryptodome/Util/_raw_api.py` and uses  `platform.architecture()` which relies on `/usr/bin/file`

```
   # Get data from the 'file' system command                                                                                                  
    if executable:
        output = _syscmd_file(executable, '')
    else:
        output = ''
```

Since it only happens when the module is loaded, we can safely assume the list of files displayed by apparmor by the reproducer above is exhaustive and adding them to apparmor will be enough.

**Comment by emkll** [comment]
Thanks for testing and @dachary for the thorough investigation!

I managed to reproduce the behaviour described by everyone else, it seems like a reboot was required to properly flush the AppArmor rules on my production instance, I did observe the messages in staging vms.

Given that the library is called at a particularly critical portion of the application code, I did further testing (despite it being within test coverage) to ensure submissions were properly streamed encrypted to `/tmp`. I can confirm that they were properly encrypted, as expected.

Added read permissions for the files described above, as well as `/usr/bin/python2.7` which was the final denied mask. 

Squashed commits and ready for re-review.

**Pull request merged**
