### PR TITLE
update flake8 and remove the '# noqa' statements

### LINKED ISSUE #6427: Update flake8/pyflakes so it understands new mypy comments
*This is a good first issue for new contributors to take on, if you have any questions, please ask on the task or in our [Gitter room](https://gitter.im/freedomofpress/securedrop)!*

The old version of flake8/pyflakes doesn't understand advanced mypy type comments like `# type: ignore[override]`. This was fixed in https://github.com/PyCQA/pyflakes/pull/455 (pyflakes 2.2.0 I believe).

```
securedrop/store.py:32:    from tempfile import _TemporaryFileWrapper  # type: ignore # noqa: F401
securedrop/journalist_app/sessions.py:125:    def save_session(  # type: ignore[override] # noqa
```

(the second instance is from the unmerged sessions PR)

### PR DESCRIPTION
**Pull request by lb803**
(as they are no longer required). Addressing the issue: https://github.com/freedomofpress/securedrop/issues/6427

## Status

Ready for review

## Description of Changes

Fixes https://github.com/freedomofpress/securedrop/issues/6427.

 - removed the '# noqa' statements;
 - re-generated the list of python pip packages with $`make update-python3-requirements`
 - removed noqa from `./securedrop/.pylint-dictionary`

Changes proposed in this pull request:

 - Simple dependency update (flake8)

## Testing

How should the reviewer test this PR?
I don't think so, $`make test` does not report errors.

## Deployment

Any special considerations for deployment? Consider both:

1. Upgrading existing production instances.
2. New installs.

### If you made changes to the server application code:

- [ ] Linting (`make lint`) and tests (`make test`) pass in the development container

### If you made changes to `securedrop-admin`:

- [x] Linting and tests (`make -C admin test`) pass in the admin development container

### If you made changes to the system configuration:

- [ ] [Configuration tests](https://docs.securedrop.org/en/latest/development/testing_configuration_tests.html) pass

### If you added or removed a file deployed with the application:

- [ ] I have updated AppArmor rules to include the change

### If you made non-trivial code changes:

- [ ] I have written a test plan and validated it for this PR

Choose one of the following:

- [ ] I have opened a PR in the [docs repo](https://github.com/freedomofpress/securedrop-docs) for these changes, or will do so later
- [ ] I would appreciate help with the documentation
- [ ] These changes do not require documentation

### If you added or updated a production code dependency:

Production code dependencies are defined in:

- `admin/requirements.in`
- `admin/requirements-ansible.in`
- `securedrop/requirements/python3/securedrop-app-code-requirements.in`

If you changed another `requirements.in` file that applies only to development
or testing environments, then no diff review is required, and you can skip
(remove) this section.

Choose one of the following:

- [ ] I have performed a diff review and pasted the contents to [the packaging wiki](https://github.com/freedomofpress/securedrop-debian-packaging/wiki)
- [x] I would like someone else to do the diff review

### CODE REVIEW

**Comment by lb803** [comment]
Hi! :)
The linter is not very happy about 3 conflicts which I should have solved with [this commit](https://github.com/freedomofpress/securedrop/pull/6702/commits/724ec7accd23375a25de55faed9be7ee4048511e). Is there something I can do to help the linter run?

**Comment by cfm** [comment]
Hi, @lb803, and sorry for our delay in reviewing this pull request last month (year!).  Our CI workflow includes a special ["test with rebase"](https://developers.securedrop.org/en/latest/testing_continuous_integration.html?highlight=rebase) job that requires that a branch rebase cleanly onto our current `develop`, rather than merging *from* `develop` as you did here.  That's fixable by rebasing locally, for example:

```sh-session
(.venv) user@sd-dev:~/securedrop$ git reset --hard 6427-update-flake8-pyflakes^
HEAD is now at bc4f13ba2 update flake8 and remove the '# noqa' statements (as they are no longer required). Addressing the issue: https://github.com/freedomofpress/securedrop/issues/6427
(.venv) user@sd-dev:~/securedrop$ git rebase -m develop
Auto-merging securedrop/tests/utils/__init__.py
CONFLICT (content): Merge conflict in securedrop/tests/utils/__init__.py
Auto-merging securedrop/tests/test_source.py
Auto-merging securedrop/tests/test_journalist.py
CONFLICT (content): Merge conflict in securedrop/tests/test_journalist.py
Auto-merging securedrop/store.py
Auto-merging securedrop/source_app/main.py
Auto-merging securedrop/management/run.py
CONFLICT (content): Merge conflict in securedrop/management/run.py
Auto-merging securedrop/journalist_app/utils.py
Auto-merging securedrop/journalist_app/sessions.py
Auto-merging securedrop/i18n_tool.py
Auto-merging molecule/testinfra/app/test_appenv.py
Auto-merging admin/tests/test_integration.py
error: could not apply bc4f13ba2... update flake8 and remove the '# noqa' statements (as they are no longer required). Addressing the issue: https://github.com/freedomofpress/securedrop/issues/6427
Resolve all conflicts manually, mark them as resolved with
"git add/rm <conflicted_files>", then run "git rebase --continue".
You can instead skip this commit: run "git rebase --skip".
To abort and get back to the state before "git rebase", run "git rebase --abort".
Could not apply bc4f13ba2... update flake8 and remove the '# noqa' statements (as they are no longer required). Addressing the issue: https://github.com/freedomofpress/securedrop/issues/6427
(.venv) user@sd-dev:~/securedrop$ git status
interactive rebase in progress; onto cedb13b47
Last command done (1 command done):
   pick bc4f13ba2 update flake8 and remove the '# noqa' statements (as they are no longer required). Addressing the issue: https://github.com/freedomofpress/securedrop/issues/6427
No commands remaining.
You are currently rebasing branch '6427-update-flake8-pyflakes' on 'cedb13b47'.
  (fix conflicts and then run "git rebase --continue")
  (use "git rebase --skip" to skip this patch)
  (use "git rebase --abort" to check out the original branch)

Changes to be committed:
  (use "git restore --staged <file>..." to unstage)
[...]

Unmerged paths:
  (use "git restore --staged <file>..." to unstage)
  (use "git add <file>..." to mark resolution)
	both modified:   securedrop/management/run.py
	both modified:   securedrop/tests/test_journalist.py
	both modified:   securedrop/tests/utils/__init__.py
```

I've taken the liberty of resolving the conflicts in these "unmerged paths" in a44e26dd5, which is now giving [meaningful `lint` results](https://app.circleci.com/pipelines/github/freedomofpress/securedrop/5330/workflows/ed503ca1-85a5-4ede-ac16-db37fc4a6842/jobs/66765) based on your changes.  You should be able to continue work on these changes by doing `git reset --hard a44e26dd5` on your branch and then testing them locally with `make lint`.

Please let me know if you'd like to discuss further!

**Comment by rocodes** [comment]
This will be resolved by https://github.com/freedomofpress/securedrop/pull/6885 as we migrate away from flake8 - but thank you @lb803 for your contribution, and we'd love to stay in touch in case there are other areas you're interested in working on. :)

**Comment by zenmonkeykstop** [comment]
Closing as per @rocodes' comment

**Pull request closed without merging**
