### PR TITLE
Improve unit test coverage of securedrop app code

### PR DESCRIPTION
**Pull request by redshiftzero**
This PR adds some more unit tests for the securedrop app code mostly for the admin interface which was an old "TODO" in the code (seen in the diff below). There are new tests for the functionality in `store.py`, `journalist.py` and `template_filters.py`.

### CODE REVIEW

**Comment by redshiftzero** [comment]
Just rebased this on `develop` - once the issues on Travis CI's side are resolved, I think this one should be ready to merge in. Take a peek and let me know what you think @garrettr

**Comment by conorsch** [comment]
@redshiftzero Given the recent changes to the Travis config in #1439, can you rebase this PR yet again on top of the latest `develop`? Then we can confirm the test suite passes in current Travis config, and debug here prior to merge if not.

**Comment by redshiftzero** [comment]
Ah so in anticipation of potential merge, I rebased this earlier today on develop (the Travis build is from 2 hours ago), so I think this should be good. But let me know if I should rebase again, I am happy to.

**Comment by conorsch** [comment]
Great, wasn't sure based on the commit history as presented in the PR. Looks like we do have a [recent passing build](https://travis-ci.org/freedomofpress/securedrop/builds/172778562), and it indeed includes the `ansible==1.8.4` changes from #1439. Thanks!

**Comment by fowlslegs** [comment]
This was going to get merged yesterday, and we had gone over some of it during in-person review, but I wanted to do a once-over to look at everything a little more closely before merging. Looks good! And I'm pretty sure that #1444 doesn't affect anything herein because in almost every case you're only processing a single request object per test method, do not log in multiple users in any method, and in general do not use the `assertContext` method or make assertions about the request context. So going to go ahead and merge now. Thanks for this one it was very much needed :smile_cat:

**Pull request merged**
