### PR TITLE
Add docs for CI docker changes

### LINKED ISSUE #1711: Update documentation to reflect latest CI docker changes
In #1708 a docker container was added to the CI environment in place of a full blown virtualmachine instance, specifically for the `build` portion of the staging tests. The current documentation doesn't mention this new flow, so it will need to be updated to more accurately reflect the state of things.

Maybe mention a blurb about setting up a local docker environment or at the very least point to external documentation. Really the rest of the tooling is the same as mentioned in the docs. This is only a small change.

### PR DESCRIPTION
**Pull request by redshiftzero**
## Status

Ready for review

## Description of Changes

Fixes #1711. 

Changes proposed in this pull request:
  * Adds a note about requiring docker to run the build container in "local CI"
  * @msheiny feel free to push commits directly to this branch 😃 

## Testing

Check that this is accurate and add anything that is missing

### If you made changes to the docs

- [x] Docs linting passes locally

### CODE REVIEW

**Comment by fowlslegs** [comment]
Not sure why CircleCI failed (something something AWS security groups--I should have taken better note before restarting the build). Anyway, it looked like a one-off failure unrelated to your changes. Set to merge when the CircleCI rebuild passes.

**Comment by redshiftzero** [comment]
Ah thanks for your review @fowlslegs! There's still a pending PR review from @msheiny (he knows best what docs need to be added since he made the changes to CI) so let's not merge quite yet

**Comment by fowlslegs** [comment]
^ Roger that.

**Comment by msheiny** [comment]
> Anyway, it looked like a one-off failure unrelated to your changes. Set to merge when the CircleCI rebuild passes.

Yeah been seeing a bunch of these unfortunately :( Going to have to shake that out post `.4` -- seems to fail fast though and a restart of the job will fix for now.

**Comment by msheiny** [comment]
heyyy @redshiftzero - peep the latest changes I added in. Otherwise, this PR is good for me (pending a long fun game of CI)

**Comment by redshiftzero** [comment]
LGTM, thanks @msheiny!

**Comment by fowlslegs** [comment]
Here was the first failure before retrying:

```
testinfra/functional/test_tor_interfaces.py::test_www[docker://apptestclient-site0] 
[gw4] FAILED testinfra/functional/test_tor_interfaces.py::test_www[docker://apptestclient-site0] 

------------ generated xml file: /root/sd/apptestclient-results.xml ------------
=================================== FAILURES ===================================
____________________ test_www[docker://apptestclient-site0] ____________________
[gw4] linux2 -- Python 2.7.13 /usr/bin/python
Command = <command>
site = {'check_string': 'SUBMIT DOCUMENTS', 'error_string': 'ERROR', 'file': 'app-source-ths'}

    @pytest.mark.parametrize('site', sdvars.tor_url_files)
    @pytest.mark.skipif(os.environ.get('FPF_CI', 'false') == "false",
                        reason="Can only assure Tor is configured in CI atm")
    def test_www(Command, site):
        """
        Ensure tor interface is reachable and returns expected content.
        """
    
        # Extract Onion URL from saved onion file, fetched back from app-staging.
        onion_url_filepath = os.path.join(os.path.dirname(__file__),
                                          "../../install_files/ansible-base/{}".format(site['file']))
        onion_url_raw = open(onion_url_filepath,'ro').read()
        onion_url = re.search("\w+\.onion", onion_url_raw).group()
    
        # Fetch Onion URL via curl to confirm interface is rendered correctly.
        curl_tor = 'curl -s --socks5-hostname "${{TOR_PROXY}}":9050 {}'.format(onion_url)
        curl_tor_status = '{} -o /dev/null -w "%{{http_code}}"'.format(curl_tor)
    
>       site_scrape = Command.check_output(curl_tor)
E       AssertionError: Unexpected exit code 7 for CommandResult(command='curl -s --socks5-hostname "${TOR_PROXY}":9050 7r5pz2yk6qydotnp.onion', exit_status=7, stdout=None, stderr=None)
E       assert 7 == 0
E        +  where 7 = CommandResult(command='curl -s --socks5-hostname "${TOR_PROXY}":9050 7r5pz2yk6qydotnp.onion', exit_status=7, stdout=None, stderr=None).rc

testinfra/functional/test_tor_interfaces.py:25: AssertionError
----------------------------- Captured stderr call -----------------------------
INFO:testinfra:RUN CommandResult(command='docker exec apptestclient /bin/sh -c \'curl -s --socks5-hostname "${TOR_PROXY}":9050 7r5pz2yk6qydotnp.onion\'', exit_status=7, stdout=None, stderr=None)
============================ pytest-warning summary ============================
WP1 None Module already imported so can not be re-written: testinfra
================ 1 failed, 1 pytest-warnings in 121.40 seconds =================
Traceback (most recent call last):
  File "./testinfra/test.py", line 134, in <module>
    run_testinfra(target_host)
  File "./testinfra/test.py", line 131, in run_testinfra
    subprocess.check_call(testinfra_command)
  File "/usr/lib/python2.7/subprocess.py", line 186, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['testinfra', '-vv', '-n', '8', '--connection', 'docker', '--ssh-config', '/root/.ssh/sshconfig-securedrop-ci-470', '--junit-xml=./apptestclient-results.xml', '--junit-prefix=apptestclient', '--hosts', 'apptestclient', 'testinfra/functional']' returned non-zero exit status 1
```

**Comment by fowlslegs** [comment]
Do we have an issue I can paste CircleCI failures in or should I open one?

**Pull request merged**
