### PR TITLE
Update docs to reflect Yubikey personalization gui tweaks

### LINKED ISSUE #5229: Yubikey personalization GUI has changed [low priority] [HOTP]
## Description

The Yubikey personalization GUI has changed and the configuration options for HOTP are slightly different (for reference in https://docs.securedrop.org/en/release-1.2.2/yubikey_setup.html#download-and-launch-the-yubikey-personalization-tool). There is no "Hide secret" checkbox; instead there is a Generate button beside the secret key field. Filing to follow up on after QA/at some lower-priority time. 

## Steps to Reproduce
on Tails, install the `yubikey-personalization-gui` package, launch the gui and navigate to OATH-HOTP tab. compare with https://docs.securedrop.org/en/release-1.2.2/yubikey_setup.html#download-and-launch-the-yubikey-personalization-tool

## Expected Behavior
docs match software 

## Actual Behavior
docs are out of date

## Comments
Can be assigned to me to fix

### PR DESCRIPTION
**Pull request by rocodes**
## Status

Ready for review

## Description of Changes
Fixes #5229.
Docs change; updates to Yubikey instructions to reflect tweaks to `yubikey-personalization-gui`. 

## Testing

manual review 

## Deployment

n/a

### If you made changes to documentation:

- [x] Doc linting (`make docs-lint`) passed locally

### CODE REVIEW

**Comment by eloquence** [comment]
(Taking a look at this now.)

**Comment by eloquence** [comment]
- The screenshots in this PR don't appear to show the GUI that the text describes. That is, the screenshots show "Hide secret" but the text speaks to "Hide values".
- I am not able to reproduce the original issue. With a 2018 YubiKey, I am still getting the same GUI that's in our docs on Tails 4.7:

Screenshot from 2020-06-17 04-57-13

**Comment by rocodes** [comment]
You're right-- the "hide values" is in OTP mode, not HOTP, this is 100% my mistake  The only change in this PR then is adding the "configuration successful" screenshot, see 6e2bec091.

**Comment by eloquence** [comment]
LGTM :-). Awaiting final approval by a maintainer.

**Pull request merged**
