### PR TITLE
move meta dep. from grsecurity role -> playbook

### LINKED ISSUE #2728: Install-fpf-repo role should not be a dependency of grsecurity role
# Feature request

## Description

Ansible meta dependencies (as defined in a role's `meta/main.yml`) should not be used in securedrop. They are annoying to track down for developers coming back in later, trying to determine what is being run.

Let's make sure all role calls are done at the playbook level.

## User Stories

As a securedrop maintainer, I want to immediately be able to look at a role playbook and visually see all roles that are being called.

### PR DESCRIPTION
**Pull request by msheiny**
## Status

Ready for review

## Description of Changes

During a security audit of trying to track down dependencies, this was
overlooked at first pass and makes the logic trickier to debug. Lets
stop using meta dependencies and instead always use top-level
dependencies.

Fixes #2728

Changes proposed in this pull request:

## Testing

How should the reviewer test this PR?

Does it pass CI and not contain any other nits? 👍 

## Deployment

Any special considerations for deployment? Consider both:

1. Upgrading existing production instances. -- nope
2. New installs. -- nope

### CODE REVIEW

**Comment by dachary** [comment]
> Ready for review / Work in progress

@msheiny not merging because I'm not sure if you want to check something more. Feel free to merge though. Happy to get rid of the only `meta` left in the ansible tree ;-)

**Comment by msheiny** [comment]
Actually...I take back my original comments ... we should test this in prod... because:
* the staging environment doesnt install grsecurity  ( we have an agenda to fix that, let me make an official ticket though)
* and staging uses a separate playbook which happens to include the fpf-role separately (we should also make a ticket to utilize the same exact playbook in prod and in staging)

**Comment by dachary** [comment]
I'm confused: when I do `vagrant up /staging/` I get
<pre>
vagrant@app-staging:~$ uname -a
Linux app-staging 3.14.79-grsec #1 SMP Wed Jun 21 19:57:53 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
</pre>
CircleCI does a different staging ?

**Comment by msheiny** [comment]
Update: 

We already have a ticket for production install testing in CI --> #1681 
Grsec support in CI staging is now tracking under --> https://github.com/freedomofpress/ansible-role-grsecurity-build/issues/11

>CircleCI does a different staging ?

Yeah CircleCI does a number of tweaks. The relevant piece is that it skips tags for `grsec` completely. This is because the currently compiled grsec kernel doesnt have the modules for Xen that are needed to run in AWS (the system will just fall over).

**Comment by dachary** [comment]
If I do `vagrant provision app-staging` on my laptop using your branch, it will however install grsec and therefore verify there is no regression, right ?

**Comment by conorsch** [comment]
Thanks right, @dachary. It's only the _CI_ staging that skips grsec installs—local VMs will still freceive grsec-patched kernels.

**Comment by msheiny** [comment]
> I stand by my approval then :-)

The @dachary stamp of approval!!! 🎖  I DID IT!!!! Woooooooooooo!

**Pull request merged**
