### PR TITLE
Add API endpoints for replies

### LINKED ISSUE #3676: [reply refactor] Add journalist interface API endpoints for replies
We should add (at least) two new API endpoints for the client to use:

`GET /api/v1/replies` 
and
`GET /api/v1/sources/<source_uuid>/replies`

Such that journalists can get replies across all sources and then download replies per-source

Epic: #3097

### PR DESCRIPTION
**Pull request by redshiftzero**
## Status

Work in progress

## Description of Changes

Fixes #3676 

Changes proposed in this pull request:
 * Adds API endpoints for getting, deleting and downloading replies to sources

## Testing

0. Provision staging VM on `develop`, add test data (at least 1 user and 1 reply)
1.  `make build-debs`
2. `vagrant provision /staging/`
3. Ensure that API responses contain UUIDs for reply and user

## Deployment

Deployed in securedrop-app-code package

### If you made changes to the server application code:

- [ ] Linting (`make ci-lint`) and tests (`make -C securedrop test`) pass in the development container

### If you made non-trivial code changes:

- [x] I have written a test plan and validated it for this PR

### If you made changes to documentation:

- [x] Doc linting (`make docs-lint`) passed locally

### CODE REVIEW

**Comment by redshiftzero** [comment]
Ready for review! 

And ready for QA when you get a chance @zenmonkeykstop (this one can be tested via the molecule upgrade scenario if you prefer)

**Comment by redshiftzero** [comment]
Thanks for your review and for testing this @emkll! Today I tried to reproduce your error, but was unable to, and the migrations occurred without issue in my staging VMs. My detailed testing steps were: 

1. `git checkout develop`
2. `make build-debs`
3. `vagrant up /staging/` (doesn't necessarily _need_ to be fresh staging VMs but you should blow away the old database if you keep old VMs around)
4. Add an admin user via `./manage.py add-admin`
5. Submit two documents as two sources
6. Verify you can login, and send at least one reply to each source
7. `git checkout reply-api-endpoints`
8. `make build-debs`
9. `vagrant provision /staging/` (i.e., I didn't use SCP, but I'm not sure how this could cause a difference)
10. Peeked in the database to verify the UUIDs were now on each row in the `replies` and `journalists` tables:

```
# sqlite3 /var/lib/securedrop/db.sqlite
...
sqlite> select * from replies;
1|a7fac647-20be-4525-ab82-1021b0ac4010|1|2|2-weighted_foundry-reply.gpg|1121|0
2|8a269ea8-f746-4a45-ac4f-35be3923d72d|1|2|3-weighted_foundry-reply.gpg|1123|0
3|e65d870c-a954-461a-ac89-f4f88116b28e|1|1|2-greasy_faience-reply.gpg|1118|0
sqlite> select * from journalists;                                                                                           
1|97e80835-ed5d-4fec-884b-43365b5eed00|test|||passwordhashwassnippedouthere|1|2fatokenwassnippedouthere|1|0|188900|2018-08-20 18:40:43.627670|2018-08-20 22:10:48.744209
```

✅ 

Can you verify you used 20fdff320a6ebe257cace3026f10040c6757df1f to build the deb package for upgrade?

**Comment by redshiftzero** [comment]
No worries, thanks for taking another look at this one!

**Comment by heartsucker** [comment]
Wait dang it, the page was out of date and it got merged already. Blagh.

**Pull request merged**
