### PR TITLE
SecureDrop i18n

### LINKED ISSUE #127: Transifex
It is maybe the time to propose (at least User-Interface) level some other languages?

### PR DESCRIPTION
**Pull request by kcchu**
screen shot 2014-11-16 at 1 53 23 pm
- Integrates with Flask-Babel to add i18n and l10n support
- Languages are selected by Accept-Languages header or manual override
  by query parameter
- Adds a language selection menu in page footer
- Tags strings in source and journalist interface for translation
- Integrates with Transifex to collaborate on translation (https://www.transifex.com/projects/p/securedrop-app-code/)
- Fully translates into Italian and Traditional Chinese
- Setup vagrant to compiles translation files while running provision
- Unit tests
- resolve #127

Todo:
- build_deb_packages.sh does not compile translation files
- Relative time format is not localized

### CODE REVIEW

**Comment by yozel** [comment]
It has been 4 month since this pull request is posted? Now What? What's current situation?

**Comment by joweiser** [comment]
I'm currently working on a German translation which is nearly finished. Is there already a standard for how to contribute translations?

**Comment by semente** [comment]
About what @runasand pointed out about the reviewing process of Transifex translations, I suggest that only pull requests from the coordinator(s) of a language could be accepted.

**Comment by edwincheese** [comment]
I guess some of you are from Aaron Swartz Hackathon today. You may already notice that this pull request was created exactly one year ago, began at Aaron Swartz Hackathon last year (with @gdamdam who is a great guy now working for Internet Archive). I really appreciate to all your work to continue this effort. i18n is crucial in bring SecureDrop to many parts of the world where people literally die for whistleblowing. However, you can see that this pull request was sitting here for a year and the project members didn't follow it up. They seems to be uninterested in this effort. So, if you are in the Hackathon and seeing @garrettr around, please talk to him and see what he is thinking about it.

**Comment by alexandervlpl** [comment]
Mentioning @RaedsLab, @jdunck, @flamsmark, @toholdaquill, @heartsucker, and @yuvadm who discussed this in related issues (#127, #1168).

Ladies and gents, is there any good reason why after *years* of discussion (and at least one decent PR) this much-needed software is still only for English speakers? I'd like to contribute a Russian translation, and can work on integrating the localization functionality.

About reviewing translations contributed by volunteers: isn't it enough that they'll be verified by the community like the rest of the code base? Once it's clear to interested people around the world that this project is for them and their countries too, I think there will be enough volunteers to ensure that translations are correct.

**Comment by heartsucker** [comment]
@alexandervlpl Three PR's, actually.

https://github.com/freedomofpress/securedrop/pull/1103
https://github.com/freedomofpress/securedrop/pull/1192

**Comment by alexandervlpl** [comment]
So who makes the decisions here? Is it possible to get some progress on this?

**Comment by heartsucker** [comment]
@alexandervlpl: Some combination of @garrettr, @conorsch, and @fowlslegs. Maybe some others.

**Comment by fowlslegs** [comment]
We're postponing internationalization because we're currently focusing on research into (i) Tor website fingerprinting attacks (see https://github.com/freedomofpress/FingerprintSecureDrop, a work-in-progress) and (ii) a rearchitecture of the SecureDrop system with the fundamental motivation of making it easier to use, deploy, and maintain (also, a number of other projects I won't all name here). 

When we do internationalization, we want to do it right. That why we think it's (i) important we wait until we've wrapped up (or gotten to a stable point) other projects, (ii) test out internationalization on a smaller project (since we don't have organizational experience with the process yet), and most importantly (iii) wait until the next major version of SecureDrop is released, which will include a rewrite (and reduction in size) of at least half of our over 100 pages (printed) of documentation.

We don't think it would be wise to invest our time and our contributors time translating scores of pages that will need to be rewrittten a year later, and we don't have the time or resources to handle what we'd need to in order to feel comfortable merging this PR right now.

The contribution is really appreciated, and I believe there is probably a solid amount of work here than can eventually contribute to the internationalization of Securedrop 1.0.

**Comment by alexandervlpl** [comment]
That's reasonable. Thanks for all your hard work, and please keep us posted!

**Comment by redshiftzero** [comment]
I know that there is a lot of demand for internationalization of SecureDrop and we appreciate this is incredibly important. We really want to translate and localize SecureDrop, but given some of the other [improvements](https://github.com/freedomofpress/securedrop/milestones) we're working on and that we're a small team, we don't currently have the bandwidth to add this feature and begin managing translations. We really appreciate this contribution, but given that we can't add this right now and that this PR has been pending merge for several years, I am going to close this PR for now.

**Comment by alexandervlpl** [comment]
@redshiftzero : With all due respect, you're making it sound like every member of your team will need to personally learn 10 languages by next week and get translating, instead of working on critical issues and features.

The way I see it, "we either localise or we fix bugs" is just a false dichotomy. Plenty of important open source projects leave localisation to the community while core developers work on the actual code-base. It's one of the big reasons for making a project open source in the first place. My two cents.

**Comment by dachary** [comment]
@alexandervlpl the i18n/l10n effort has resumed as a community driven project which is going to be gradually merged into SecureDrop. As of this week end it is complete (both source & journalist interfaces) and the i18n commits are at https://github.com/dachary/securedrop/commits/wip-i18n-base . The l10n effort is complete for French and 50% of the work done for German by @heartsucker is still valid and was resurrected. It is happening at http://weblate.securedrop.club/

The discussions about translation happen in the [translation category of the SecureDrop forum](https://forum.securedrop.club/t/about-the-translations-category). It would be great to hear what you think about all this :-)

**Comment by dachary** [comment]
@kcchu years later the italian translation is still 30% good ! It was imported in http://weblate.securedrop.club/projects/securedrop/securedrop/ . I'm however having trouble with zh_Hant . It would be great if you could take a quick look. I'm hoping this is something simple and me just being ignorant :-) https://forum.securedrop.club/t/zh-hant-does-not-render-as-expected

**Comment by dachary** [comment]
@kcchu traditional chinese was imported https://weblate.securedrop.club/projects/securedrop/securedrop/zh_Hant/ and is still 34% good. Would you know someone willing to complete the translation ?

**Comment by kcchu** [comment]
@dachary I can certainly help completing the translation to both Traditional Chinese (for Taiwan and Hong Kong) and Simplified Chinese (for PRC). However, because of the expierence I got from my initial i18n efforts, I will wait until most of the patches are merged into mainline or the i18n project get a clear roadmap.

**Comment by dachary** [comment]
@kcchu it's great to know you're still interested :-) FWIW, my work is done as an external contributor and I am fully aware of the past troubles. I believe SecureDrop should be a community driven project to avoid that kind of problems. It is good that FPF is a driving force for SecureDrop but divergence of opinions on large features such as i18n need to be resolved with a compromise, not with an unilateral decision.

This discussion is beyond the scope of this issue, of course :-) I [started a thread in the forum](https://forum.securedrop.club/t/securedrop-governance/) and it would be great to hear what you have to say about it, if you have the time.

**Comment by dachary** [comment]
@kcchu would you be interested in [reviewing the Chinese translation](https://forum.securedrop.club/t/chinese-translation-100-complete-and-ready-for-review) ? I'm happy to report the i18n work you initiated years ago is finally complete and has been merged a few weeks ago. The 0.5 release to be published tomorrow will have official support for seven new languages. I'm hoping the next release (late january 2018) can also feature Chinese :-)

**Comment by kcchu** [comment]
Yes, I can take this.

**Pull request closed without merging**
