### PR TITLE
source: allow testing of tor2web

### PR DESCRIPTION
**Pull request by dachary**
## Status

Ready for review

## Description of Changes

Although it is possible to manually install an extension to the tor
browser to add a custom header and set X-tor2web in this way, it makes
the development environment more complicated. Besides, no other
source/journalist feature needs that kind of fixture and the effort does
not seem worth the reward.

Add a global variable TEST_X_TOR2WEB that allows tests to simulate the
presence of tor2web.

## Testing

pytest tests

## Deployment

This is only for tests, there are not deployment side effects.

### If you made changes to the app code:

- [x] Unit and functional tests pass on the development VM

### CODE REVIEW

**Comment by dachary** [comment]
I do not like this test only modification. The alternative makes the development environment significantly more complicated. My preference would be to install a firefox plugin that allows to set custom headers and pretend tor2web is active. I'd be happy to spend the time doing that if people  think it's worth the effort.

**Comment by heartsucker** [comment]
> Add a global variable

This would go against some of the goals in 0.4.1 which would be to eliminate global state and use the `init_app()` Flask pattern.

Also, the better pattern would be to to just add it to the headers in the `GET` in the tests, no?

**Comment by heartsucker** [comment]
Ah, this would be for the Selenium tests. Maybe this one could wait until after we make the apps more Flask-y?

**Comment by dachary** [comment]
> Ah, this would be for the Selenium tests. 

Right, used [to generate screenshots](https://github.com/freedomofpress/securedrop/pull/1983/commits/9d64df5be71bc6615fd5f863b7bffc80d2a2271f#diff-848022a05ebb3b6032b0f390ac5bfc07R25) and verify it renders as it should, including with l10n.

Do you see a way to do the same without this ugly global variable ?

**Comment by heartsucker** [comment]
Yeesh. I don't know enough about Selenium or the python driver, but I imagine it might be possible to have it set a custom header or user agent.

What you could do would be to set up a tiny flask app that takes a request and proxies it (with all headers / params / body) but adds a `X-Tor2Web` and `Forwarded` headers the way Tor2Web actually does. Then point the driver at this app for the Tor2Web stuff, and have the proxy point at the real app.

**Comment by heartsucker** [comment]
Though once we have the the `init_app()` pattern, that could be injected into it as `init_app(..., force_tor2web=False)` and then use that. It wouldn't be global, but just on a per app basis. This would feel wrong in the sense that I think it's not always a good engineering practice to add things just to allow for testing if it makes the API / code too complex. Granted, there are other philosophies on this like the "Java dependency inject all things" approach. Different strokes, y'know.

**Comment by dachary** [comment]
I think you have me convinced. We can just wait for the refactor and not test this specific message in the meantime, it's too much work for a transient patch. I like the proxy idea, simpler than installing a firefox plugin in the test environment...

Unless someone else has a brilliant idea in the next few days I'll close this pull request and create an issue to remember this needs work post-refactor.

**Comment by dachary** [comment]
> Can you wait for a few weeks until we have time to work on that proposed refactor, or do you need this functionality urgently?

this is just for the visual validation of a single message. I think we can complete i18n without that :) Closing this for now and I'll create an issue as a reminder later. Thanks @garrettr @heartsucker for a quick review. I did not like the commit and to be honest I'm happy to kill it ;-)

**Pull request closed without merging**
