### PR TITLE
tails_printing_guide.rst: fix style issues

### PR DESCRIPTION
**Pull request by championshuttler**
Ref Issue : #3013

r? @kushaldas

### CODE REVIEW

**Comment by heartsucker** [comment]
Hey @championshuttler. Can you link to the original issue? This one is linked to itself.

**Comment by championshuttler** [comment]
Hi @heartsucker , fixed :)

It was totally by mistake

**Comment by jroes** [comment]
LGTM

**Comment by zenmonkeykstop** [comment]
Hi @championshuttler, apologies for the delay in review - do you have cycles available to address it? If not, no problem, I can make the edit and kick off the approval process.

**Comment by championshuttler** [comment]
Hi @zenmonkeykstop made the requested changes :)

**Comment by zenmonkeykstop** [comment]
Thanks @championshuttler - I've rebased your changes onto the current develop to allow CI to run. Will advise if there's anything else required.

**Pull request merged**
