### PR TITLE
l18n: do not update messages.pot if there is no change

### PR DESCRIPTION
**Pull request by dachary**
## Status

Ready for review

## Description of Changes

The creation date is modified regardless: remove it before comparing
messages.pot with the previous version so we don't update translations
on every run.

## Testing

Verify the following command run multiple times does not change the content of messages.pot

* ./manage.py translate --extract-update

## Deployment

It is not used during deployment, only during development when updating the messages.pot file from the source files.

### If you made changes to the app code:

- [x] Unit and functional tests pass on the development VM

### CODE REVIEW

**Comment by dachary** [comment]
https://circleci.com/gh/freedomofpress/securedrop/2204?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link

<pre>
test_apache_logging_journalist_interface failed
</pre>

relaunching to verify this is not a transient error. If it's not I'm in trouble because there is no indication of the source of the disconnect.

**Comment by dachary** [comment]
> I am unable to test this:

Could you please run again with `./manage.py --verbose translate --extract-update` ?

**Comment by heartsucker** [comment]
```
vagrant@development:/vagrant/securedrop$ ./manage.py --verbose translate --extract-update
2017-09-21 09:26:34,915 DEBUG :sh: 
        set -xe

        mkdir -p translations

        pybabel extract         --charset=utf-8         --mapping=babel.cfg         --output=translations/messages.pot         --project=SecureDrop         --version=0.4.3         --msgid-bugs-address='securedrop@freedom.press'         --copyright-holder='Freedom of the Press Foundation'         . source_templates journalist_templates

        # we do not handle fuzzy translations yet
        sed -i '/^#, fuzzy$/d' translations/messages.pot
        # remove this line so the file does not change if no
        # strings are modified
        sed -i '/^"POT-Creation-Date/d' translations/messages.pot
        
2017-09-21 09:26:34,920 DEBUG + mkdir -p translations
2017-09-21 09:26:34,922 DEBUG + pybabel extract --charset=utf-8 --mapping=babel.cfg --output=translations/messages.pot --project=SecureDrop --version=0.4.3 --msgid-bugs-address=securedrop@freedom.press --copyright-holder=Freedom of the Press Foundation . source_templates journalist_templates
2017-09-21 09:26:34,994 DEBUG extracting messages from config.py (silent="False")
...
2017-09-21 09:26:36,178 DEBUG writing PO template file to translations/messages.pot
2017-09-21 09:26:36,219 DEBUG + sed -i /^#, fuzzy$/d translations/messages.pot
2017-09-21 09:26:36,275 DEBUG + sed -i /^"POT-Creation-Date/d translations/messages.pot
2017-09-21 09:26:36,347 DEBUG :sh: 
            set -xe
            pybabel update             --input-file translations/messages.pot             --output-dir translations             --no-fuzzy-matching --ignore-obsolete
            
2017-09-21 09:26:36,352 DEBUG + pybabel update --input-file translations/messages.pot --output-dir translations --no-fuzzy-matching --ignore-obsolete
2017-09-21 09:26:36,417 DEBUG Traceback (most recent call last):
2017-09-21 09:26:36,417 DEBUG File "/usr/local/bin/pybabel", line 11, in <module>
2017-09-21 09:26:36,418 DEBUG sys.exit(main())
2017-09-21 09:26:36,418 DEBUG File "/usr/local/lib/python2.7/dist-packages/babel/messages/frontend.py", line 908, in main
2017-09-21 09:26:36,419 DEBUG return CommandLineInterface().run(sys.argv)
2017-09-21 09:26:36,420 DEBUG File "/usr/local/lib/python2.7/dist-packages/babel/messages/frontend.py", line 832, in run
2017-09-21 09:26:36,420 DEBUG return cmdinst.run()
2017-09-21 09:26:36,421 DEBUG File "/usr/local/lib/python2.7/dist-packages/babel/messages/frontend.py", line 714, in run
2017-09-21 09:26:36,422 DEBUG raise DistutilsOptionError('no message catalogs found')
2017-09-21 09:26:36,422 DEBUG distutils.errors.DistutilsOptionError: no message catalogs found
Traceback (most recent call last):
  File "./manage.py", line 423, in <module>
    _run_from_commandline()
  File "./manage.py", line 416, in _run_from_commandline
    rc = args.func(args)
  File "./manage.py", line 312, in translate
    messages_file=messages_file))
  File "./manage.py", line 60, in sh
    cmd=command
subprocess.CalledProcessError: Command '
            set -xe
            pybabel update             --input-file translations/messages.pot             --output-dir translations             --no-fuzzy-matching --ignore-obsolete
            ' returned non-zero exit status 1
```

**Comment by dachary** [comment]
translations/messages.pot does not exist apparently. I checked it is indeed commited to the wip-dachary-i18n-pot-creation-date branch. Do you have that file ?

**Comment by heartsucker** [comment]
@dachary Yes, I have the file. Not sure why it's breaking. :/

**Comment by dachary** [comment]
@heartsucker ho, my bad, it's not about the messages.pot file missing. It is because update is unhappy that there are no .po files in the translation subdirectories. In this case pybabel update should do nothing but it fails instead. To prevent that from happening `manage.py` tests if there is more than just messages.pot in the translation directory and, if it is the case, assumes that there is at least one valid .po file. I suspect you have empty directories/files lingering in the translations directory and `manage.py` incorrectly assumes it is ok to call `pybabel update`. You can just remove the spurious files and the command should work.

**Comment by dachary** [comment]
@heartsucker rebased (trivial conflict). Have you been able to make it work ?

**Comment by dachary** [comment]
@redshiftzero your approval was discarded because of the rebase (conflict because of fuzzy translation activation).

**Pull request merged**
