### PR TITLE
Reorganize Debian packaging, have debhelper do most of the work

### PR DESCRIPTION
**Pull request by legoktm**
## Status

Ready for review

## Diffs
These are slightly out of date now, but gives a general idea of the *expected* changes.

* [securedrop-config](https://gist.github.com/legoktm/3cff068fea0be430bc925159d7e55f0d), only metadata changes, version number now follows SecureDrop ("2.5.0")
* [securedrop-keyring](https://gist.github.com/legoktm/4bc6549379ff5b54ba0a321d053b3371), only metadata changes
* [securedrop-ossec-agent](https://gist.github.com/legoktm/9b999c483eaf6e25ef4ffd299796f64b), mypy fixes plus metadata changes
* [securedrop-ossec-server](https://gist.github.com/legoktm/b5fae9a97ae2f29e7beb497852337774), mypy fixes plus metadata changes
* securedrop-app-code:
  * [debdiff](https://gist.github.com/legoktm/768df9f184aa8260b81be65dc35ec25a), shows removal of non-reproducible RECORD files, plus the addition of setup.py.
  * [full diffoscope](https://gist.github.com/legoktm/6e13f00dad969dd0b69db4c3bc165e64) this is absurdly long because SOURCES.txt no longer contains every file in the package (it was entirely useless to begin with).
  * [diffoscope without SOURCES.txt](https://gist.github.com/legoktm/0f2ec8bc5011581bc51a961c31241812), shows removal of RECORD files, removal of debuginfo, and subtle changes to the binary `.so` files, because those are not reproducible (yet!). 

## Description of Changes
It's recommended to review this by stepping through the commits one-by-one. The first 7 commits are all cleanup.

Then the important commits:
* `Reorganize Debian packaging, have debhelper do most of the work` - moves stuff around, sets up `<package>.install` files that control what gets installed. All packaging logic removed from ansible except translations. This is step 1 on #6310.
* `Fix some reproducibility issues in securedrop-app-code` - drop `RECORD` files and debugging info. All packages should be reproducible except for the compiled Build IDs in securedrop-app-code. This is towards #308. The remaining issue is #5901.
* `Compile translations via debian/rules` - ports translation ansible logic to a bash script.

And then the remaining stuff is just fixing lint issues and other minor things as a result of the changes.

### Package building
* [x] Run `make build-debs` without this PR, save the debs somewhere ("originals")
* [x] Run `make build-debs` with this PR, with no errors
* [x] Run debdiff and/or diffoscope against the "originals" and the new packages, they should roughly match the diffs I posted above. Visual review that nothing that's needed is missing

### Package testing
* [x] Install the packages on both an app and mon server (staging or physical, doesn't matter). No errors during installation
* [x] Basic testing of SecureDrop functionality that nothing is broken
* [x] Run verification tests from an admin workstation, they should pass

## Deployment

Any special considerations for deployment?

Not really, diffoscope should help us feel confident about how minimal the changes really are.

## Checklist

- [x] Linting (`make lint`) and tests (`make test`) pass in the development container
- [ ] [Configuration tests](https://docs.securedrop.org/en/latest/development/testing_configuration_tests.html) pass
- [ ] I have written a test plan and validated it for this PR
- [x] These changes do not require documentation

### CODE REVIEW

**Comment by legoktm** [comment]
Notes for myself when I do the next rebase:
* [x] Make sure that i18n.json is included properly
* [x] Drop MANIFEST.in
* [x] Update update_version.sh (and grep for some more things that might be accessing those obsolete paths directly)

**Comment by cfm** [comment]
I've read through the commits (thanks for laying it out so narratively, @legoktm!) and think this looks great.  The plan we've just discussed is that I'll aim to:
1. step through the test plan, including diffing, next week, with the goal of approving _without_ merging; and
2. merge the week of October 17 _after_ the SecureDrop 2.5.0 release, to avoid the risk of messy backports from `develop` while `release/2.5.0` is still open.

**Review by cfm — CHANGES_REQUESTED** [review]
Diff-and-test plan looks great, with one necessary change requested inline.  @legoktm, I'm pleased to be able to affirm, and I'd like to highlight to any other reviewers, your observation that

> diffoscope should help us feel confident about how minimal the changes really are[.]  (https://github.com/freedomofpress/securedrop/pull/6544#issue-1373617159)

This proposal builds (very nearly) the same packages we currently use, in a much more intuitive, Debian-idiomatic, and maintainable way.

**Nit:**  This branch, with its arbitrary number of `m`s, is not very ergonomic to test.  ;-)


## Package building
* [x] Run `make build-debs` without this PR, save the debs somewhere ("originals")
* [x] Run `make build-debs` with this PR, with no errors
* [x] Run debdiff and/or diffoscope against the "originals" and the new packages, they should roughly match the diffs I posted above. Visual review that nothing that's needed is missing
    * [x] [`securedrop-config`](https://gist.github.com/legoktm/3cff068fea0be430bc925159d7e55f0d), only metadata changes, version number now follows SecureDrop ("2.5.0")
    * [x] [`securedrop-keyring`](https://gist.github.com/legoktm/4bc6549379ff5b54ba0a321d053b3371), only metadata changes
    * [x] [`securedrop-ossec-agent`](https://gist.github.com/legoktm/9b999c483eaf6e25ef4ffd299796f64b), mypy fixes plus metadata change
    * [x] [`securedrop-ossec-server`](https://gist.github.com/legoktm/b5fae9a97ae2f29e7beb497852337774), mypy fixes plus metadata changes
    * [x] `securedrop-app-code`:
        * [x] [debdiff](https://gist.github.com/legoktm/768df9f184aa8260b81be65dc35ec25a), shows removal of non-reproducible RECORD files, plus the addition of setup.py.
        * ~[full diffoscope](https://gist.github.com/legoktm/6e13f00dad969dd0b69db4c3bc165e64) this is absurdly long because SOURCES.txt no longer contains every file in the package (it was entirely useless to begin with).~
        * [x] [diffoscope without SOURCES.txt](https://gist.github.com/legoktm/0f2ec8bc5011581bc51a961c31241812), shows removal of RECORD files, removal of debuginfo, and subtle changes to the binary `.so` files, because those are not reproducible (yet!).
    * **Also checked** `securedrop-grsec`: unchanged according to `debdiff`; metadata-only changes according to Diffoscope


## Package testing
* [x] Install the packages on both an app and mon server (staging or physical, doesn't matter). No errors during installation

```sh-session
root@sd-staging:~/securedrop# make staging
```

Required patch:
    
```patch
--- a/install_files/ansible-base/group_vars/securedrop_application_server.yml
+++ b/install_files/ansible-base/group_vars/securedrop_application_server.yml
@@ -6,9 +6,9 @@ ip_info:
 
 ### Used by the install_local_deb_pkgs role ###
 local_deb_packages:
-  - "securedrop-keyring-0.1.6+{{ securedrop_version }}+{{ securedrop_target_distribution }}-amd64.deb"
-  - "securedrop-config-0.1.4+{{ securedrop_version }}+{{ securedrop_target_distribution }}-amd64.deb"
-  - "securedrop-ossec-agent-3.6.0+{{ securedrop_version }}+{{ securedrop_target_distribution }}-amd64.deb"
+  - "securedrop-keyring_0.1.6+{{ securedrop_version }}+{{ securedrop_target_distribution }}_all.deb"
+  - "securedrop-config_{{ securedrop_version }}+{{ securedrop_target_distribution }}_all.deb"
+  - "securedrop-ossec-agent_3.6.0+{{ securedrop_version }}+{{ securedrop_target_distribution }}_all.deb"
   -  securedrop-grsec-{{ grsec_version }}+{{ securedrop_target_distribution }}-amd64.deb
   - "{{ securedrop_app_code_deb }}.deb"
   - "ossec-agent-3.6.0+{{ securedrop_target_distribution }}-amd64.deb"
diff --git a/install_files/ansible-base/group_vars/securedrop_monitor_server.yml b/install_files/ansible-base/group_vars/securedrop_monitor_server.yml
index 722fdc5ff..a5979b050 100644
--- a/install_files/ansible-base/group_vars/securedrop_monitor_server.yml
+++ b/install_files/ansible-base/group_vars/securedrop_monitor_server.yml
@@ -6,9 +6,9 @@ ip_info:
 
 ### Used by the install_local_deb_pkgs role ###
 local_deb_packages:
-  - "securedrop-keyring-0.1.6+{{ securedrop_version }}+{{ securedrop_target_distribution }}-amd64.deb"
-  - "securedrop-config-0.1.4+{{ securedrop_version }}+{{ securedrop_target_distribution }}-amd64.deb"
-  - "securedrop-ossec-server-3.6.0+{{ securedrop_version }}+{{ securedrop_target_distribution }}-amd64.deb"
+  - "securedrop-keyring_0.1.6+{{ securedrop_version }}+{{ securedrop_target_distribution }}_all.deb"
+  - "securedrop-config_{{ securedrop_version }}+{{ securedrop_target_distribution }}_all.deb"
+  - "securedrop-ossec-server_3.6.0+{{ securedrop_version }}+{{ securedrop_target_distribution }}_all.deb"
   - securedrop-grsec-{{ grsec_version }}+{{ securedrop_target_distribution }}-amd64.deb
   - ossec-server-3.6.0+{{ securedrop_target_distribution }}-amd64.deb
```

* [x] Basic testing of SecureDrop functionality that nothing is broken
* [ ] Run verification tests from an admin workstation, they should pass

```sh-session
root@sd-staging:~/securedrop# make testinfra
[...]
    =========================== short test summary info ============================
    FAILED ../testinfra/common/test_automatic_updates.py::test_unattended_upgrades_functional[ansible:/mon-staging]
    FAILED ../testinfra/common/test_grsecurity.py::test_grsecurity_paxtest[ansible:/app-staging]
    = 2 failed, 469 passed, 13 skipped, 3 xfailed, 1 xpassed, 2 warnings in 38.24s =
```

Not worried about `test_unattended_upgrades_functional`.  `test_grsecurity_paxtest` is failing with:
    
```sh-session
    E               AssertionError: Unexpected exit code 1 for CommandResult(command=b'sudo /bin/sh -c \'paxtest blackhat /tmp/paxtest.log | grep -P \'"\'"\'^(Executable|Return)\'"\'"\'\'', exit_status=1, stdout=None, stderr=b"Warning: Permanently added '192.168.121.150' (ECDSA) to the list of known hosts.\r\n/bin/sh: 1: paxtest: not found\n")
    E               assert 1 == 0
    E                 +1
    E                 -0
    
    ../testinfra/common/test_grsecurity.py:127: AssertionError
```

I'll see if I can reproduce on `develop`.

**Comment by cfm** [comment]
<https://github.com/freedomofpress/securedrop/pull/6544#pullrequestreview-1141461110>:

> `test_grsecurity_paxtest` is failing with:  [...]  I'll see if I can reproduce on `develop`.

Nay; this passes on both fresh `develop` and fresh `hmmmmmm`, so this seems to be a flake after multiple `make {build-debs,staging,testinfra}` invocations across branches.  An investigation for another day.

**Comment by legoktm** [comment]
Pushed your patch (can rebase it into the stack post-review). The PR needs to be rebased (yay for strict yamllint validation), which I will do next week!

**Comment by cfm** [comment]
Thanks, @legoktm!  Can you resolve the current conflicts for a final review and merge (barring feedback to the contrary from anyone else) on Thursday?

**Comment by legoktm** [comment]
Done.

**Review by cfm — CHANGES_REQUESTED** [review]
Thanks for rebasing (and signing), @legoktm.  I've pushed your latest head at c51c86fa6e34b83435fde59ca06ee7372ce6c744 to `stg-6544` to verify in `staging-test-with-rebase` the failure I see locally:

https://app.circleci.com/pipelines/github/freedomofpress/securedrop/5050/workflows/3d3b9a23-e26f-4c5b-a9e1-920bf2dcca13/jobs/65647?invite=true#step-104-107

```sh-session
$ make build-debs
[...]
    TASK [build-securedrop-app-code-deb-pkg : Build securedrop-app-code Debian package] ***
fatal: [focal-sd-app]: FAILED! => {"changed": true, "cmd": ["dpkg-buildpackage", "-us", "-uc"], "delta": "0:00:00.154732", "end": "2022-10-27 19:33:01.044973", "msg": "non-zero return code", "rc": 25, "start": "2022-10-27 19:33:00.890241", "stderr": " dpkg-source --before-build .\ndpkg-source: error: source package has two conflicting values - securedrop and securedrop-app-code\ndpkg-buildpackage: error: dpkg-source --before-build . subprocess returned exit status 25", "stderr_lines": [" dpkg-source --before-build .", "dpkg-source: error: source package has two conflicting values - securedrop and securedrop-app-code", "dpkg-buildpackage: error: dpkg-source --before-build . subprocess returned exit status 25"], "stdout": "dpkg-buildpackage: info: source package securedrop-app-code\ndpkg-buildpackage: info: source version 2.6.0~rc1+focal\ndpkg-buildpackage: info: source distribution focal\ndpkg-buildpackage: info: source changed by SecureDrop Team <securedrop@freedom.press>\ndpkg-buildpackage: info: host architecture amd64", "stdout_lines": ["dpkg-buildpackage: info: source package securedrop-app-code", "dpkg-buildpackage: info: source version 2.6.0~rc1+focal", "dpkg-buildpackage: info: source distribution focal", "dpkg-buildpackage: info: source changed by SecureDrop Team <securedrop@freedom.press>", "dpkg-buildpackage: info: host architecture amd64"]}
```

I can resolve this with the following patch, but I suspect you'll want to take a look at why the [changelog rebased since the v2.5.0 release](https://github.com/freedomofpress/securedrop/compare/8a0fbcce567f15573dceb5575238d998ab03a079..029e2354af693b9d5633dc5f05a6484a1c5d6ced#diff-1b85760e0397f93d9392ea05259f01e2b906814f25704d99c29142466bec6382) is failing in this way.

```patch
--- a/securedrop/debian/changelog
+++ b/securedrop/debian/changelog
@@ -1,4 +1,4 @@
-securedrop-app-code (2.6.0~rc1+focal) focal; urgency=medium
+securedrop (2.6.0~rc1+focal) focal; urgency=medium

   *
```

I'll block off time for another review on Monday.  :-)

**Comment by legoktm** [comment]
Bah, messed up in the rebase. The source package is now named "securedrop", so the changelog entry is supposed to start with that.

**Comment by legoktm** [comment]
I also pushed it to the https://github.com/freedomofpress/securedrop/tree/stg-6544 branch, GitHub is smart enough to show the passing staging-test-with-rebase job on this PR too :)

**Review by cfm — APPROVED** [review]
The rebase-level diff looks good, so I'm approving based on this final review (below).  Thanks so much for your direction and work on this, @legoktm, and for your patience with this back-and-forth review!


## Package building
https://github.com/freedomofpress/securedrop/pull/6544#pullrequestreview-1141461110

## Package testing
* [x] Install the packages on both an app and mon server (staging or physical, doesn't matter). No errors during installation

```sh-session
root@sd-staging:~/securedrop# make build-debs
root@sd-staging:~/securedrop# make staging
```

* [x] Basic testing of SecureDrop functionality that nothing is broken
* [x] Run verification tests from an admin workstation, they should pass

```sh-session
root@sd-staging:~/securedrop# make testinfra
[...]
    ====== 471 passed, 13 skipped, 3 xfailed, 1 xpassed, 2 warnings in 48.06s ======
Verifier completed successfully.
```

**Pull request merged**
