### PR TITLE
Reorganizes top-level Ansible vars for cleaner variable precedence

### LINKED ISSUE #1736: Fix intermittent custom_notification test failure
The `custom_notification` test is occasionally failing in the staging environment. When I tested #1731 it did not fail (using docker and AWS) but I have seen it fail with staging provisioned locally using vagrant. @conorsch mentioned that this is a test failure only occurring in the vagrant environment. We should resolve this for 0.4.

### PR DESCRIPTION
**Pull request by conorsch**
## Status

Ready for review.

## Description of Changes

Fixes #1736, which pointed out a problem caused by our use of nested groups in the Vagrant Ansible config. Takes most of the top-level vars and shoves them into role defaults, which simplifies [variable precedence](https://docs.ansible.com/ansible/playbooks_variables.html#variable-precedence-where-should-i-put-a-variable) and makes it a clear-cut case where and how to override elements where appropriate.

Although the diff looks substantial, note that the vars have _moved_ to a more convenient location. In a few cases, a few vars were removed, only if they were never included anywhere (and were therefore left over from previous versions of the Ansible config). In other cases, vars were used by unnecessarily providing too much indirection, such as `non_default_securedrop_user` which just pointed to `securedrop_user`. Removed the former and preserved the latter. The functionality change that allows the test to pass is the removal of the nested group memberships within the `Vagrantfile`.

This PR was originally submitted from a fork as #1824. Resubmitting from origin, so CI runs (see #1826). 

## Testing

Run the application test suite _locally_ in Vagrant and confirm that 100% passes. You'll need to do so on a fresh staging build, since bad variable precedence from a previous build likely poisoned your config.py.

## Deployment

Affects the dev env. Made sure not to alter the way variables land on different hosts, just cleaned up the layout so it's more intuitive and consistent with best practices. We can now properly use host var overrides where appropriate and be confident the override will take effect (#1736 showed that sometimes it didn't).

### If you made changes to the app code:

- [x] Unit and functional tests pass on the development VM
- [x] Unit and functional tests pass on the app-staging VM

### If you made changes to the system configuration:

- :red_circle:  [Configuration tests](https://docs.securedrop.org/en/latest/development/testing_configuration_tests.html) pass

The development VM currently has broken config tests due to merge of #1770. Opened #1816 to track and will resolve there.

### CODE REVIEW

**Comment by msheiny** [comment]
Im still pressing through review -- but I think that #1816 should get resolved first and that this PR should be rebased on that to ensure proper dev CI tests run against these changes.

**Comment by conorsch** [comment]
Well it's hard to do separately, unfortunately, since the resolution for #1816 edited a lot of the same files as this one did, so I've got that resolution queued up in a separate branch. Will open a PR immediately, then you can confirm the changes in Travis as well as Circle.

**Comment by conorsch** [comment]
@msheiny Done—see #1859 for inclusion of the Travis changes.

**Comment by conorsch** [comment]
Thanks @msheiny, just what I was looking for. Will rebase #1859 on top of the latest develop post-merge to expedite review there.

**Pull request merged**
