### PR TITLE
Update builder images

### PR DESCRIPTION
**Pull request by emkll**
## Status

Ready for review 

## Description of Changes

Updates xenial and trusty builder images with latest security updates.

## Testing

- Check out this branch locally
- [ ] `make build-debs` completes without error (all tests pass)
- [ ] `make build-debs` completes without error (all tests pass) when this commit is cherry-picked ontop of 0.12.1 (it will fail on develop due to cryptography library update)

## Deployment

Dev only

### If you made non-trivial code changes:

- [x] I have written a test plan and validated it for this PR

### CODE REVIEW

**Comment by conorsch** [comment]
Reviewing!

**Comment by zenmonkeykstop** [comment]
Tested on Qubes (debian-9 vm).

- `make build-debs` ran successfully. 

- `make build-debs-trusty` failed with error:
```
    TASK [build-securedrop-app-code-deb-pkg : Install pip dependencies for SecureDrop.] ***
    fatal: [trusty-sd-app]: FAILED! => {"changed": false, "cmd": "/usr/bin/pip2 install -r /tmp/securedrop-app-code_0.13.0~rc1+xenial_amd64/var/www/securedrop/requirements/securedrop-app-code-requirements.txt", "msg": "stdout: Downloading/unpacking alembic==0.9.9 (from -r /tmp/securedrop-app-code_0.13.0~rc1+xenial_amd64/var/www/securedrop/requirements/securedrop-app-code-requirements.txt (line 7))\n  Running setup.py (path:/tmp/pip_build_root/alembic/setup.py) egg_info for package alembic\n    \n    warning: no files found matching '*.jpg' under directory 'docs'\n    warning: no files found matching '*.sty' under directory 'docs'\n    warning: no files found matching '*.dat' under directory 'tests'\n    no previously-included directories found matching 'docs/build/output'\nDownloading/unpacking argon2-cffi==18.1.0 (from -r /tmp/securedrop-app-code_0.13.0~rc1+xenial_amd64/var/www/securedrop/requirements/securedrop-app-code-requirements.txt (line 8))\n  Running setup.py (path:/tmp/pip_build_root/argon2-cffi/setup.py) egg_info for package argon2-cffi\n    \n    warning: no files found matching '*.txt'\n    warning: no previously-included files found matching 'src/argon2/_ffi.py'\n    warning: no previously-included files found matching '.gitmodules'\n    warning: no previously-included files found matching 'extras/libargon2/.git'\n    warning: no previously-included files found matching 'appveyor.yml'\n    warning: no previously-included files found matching '.readthedocs.yml'\n    warning: no previously-included files found matching '.travis.yml'\n    warning: no previously-included files matching '*.pyc' found under directory 'tests'\n    no previously-included directories found matching 'docs/_build'\nDownloading/unpacking asn1crypto==0.24.0 (from -r /tmp/securedrop-app-code_0.13.0~rc1+xenial_amd64/var/www/securedrop/requirements/securedrop-app-code-requirements.txt (line 9))\nDownloading/unpacking babel==2.5.1 (from -r /tmp/securedrop-app-code_0.13.0~rc1+xenial_amd64/var/www/securedrop/requirements/securedrop-app-code-requirements.txt (line 10))\nDownloading/unpacking cffi==1.11.5 (from -r /tmp/securedrop-app-code_0.13.0~rc1+xenial_amd64/var/www/securedrop/requirements/securedrop-app-code-requirements.txt (line 11))\n  Running setup.py (path:/tmp/pip_build_root/cffi/setup.py) egg_info for package cffi\n    \nDownloading/unpacking click==6.7 (from -r /tmp/securedrop-app-code_0.13.0~rc1+xenial_amd64/var/www/securedrop/requirements/securedrop-app-code-requirements.txt (line 12))\nDownloading/unpacking cryptography==2.6.1 (from -r /tmp/securedrop-app-code_0.13.0~rc1+xenial_amd64/var/www/securedrop/requirements/securedrop-app-code-requirements.txt (line 13))\n  Running setup.py (path:/tmp/pip_build_root/cryptography/setup.py) egg_info for package cryptography\n    Traceback (most recent call last):\n      File \"<string>\", line 17, in <module>\n      File \"/tmp/pip_build_root/cryptography/setup.py\", line 28, in <module>\n        \"cryptography requires setuptools 18.5 or newer, please upgrade to a \"\n    RuntimeError: cryptography requires setuptools 18.5 or newer, please upgrade to a newer version of setuptools\n    Complete output from command python setup.py egg_info:\n    Traceback (most recent call last):\n\n  File \"<string>\", line 17, in <module>\n\n  File \"/tmp/pip_build_root/cryptography/setup.py\", line 28, in <module>\n\n    \"cryptography requires setuptools 18.5 or newer, please upgrade to a \"\n\nRuntimeError: cryptography requires setuptools 18.5 or newer, please upgrade to a newer version of setuptools\n\n----------------------------------------\nCleaning up...\nCommand python setup.py egg_info failed with error code 1 in /tmp/pip_build_root/cryptography\nStoring debug log for failure in /root/.pip/pip.log\n"}
```

**Comment by conorsch** [comment]
I can reproduce the error that @zenmonkeykstop reports, but it's because I missed @emkll's stipulation 

> when this commit is cherry-picked on top of 0.12.1 (it will fail on develop due to cryptography library update)

However, cherry-picking shows conflicts for me. What I did:

```
git fetch
git checkout release/0.12.0
git checkout -b test-trusty-builder
git cherry-pick c93a0485612df40337e9eb1c65636ef6c76936b1
```

Can anyone recommend a different workflow for cherry-picking?

**Comment by zenmonkeykstop** [comment]
If you cherry-pick into `release/0.12.1` there are no conflicts, but `make build-debs-trusty` goes back to being `make-build-debs` and vice versa for Xenial.

**Comment by emkll** [comment]
> If you cherry-pick into release/0.12.1 there are no conflicts, but make build-debs-trusty goes back to being make-build-debs and vice versa for Xenial.

good catch, updating test plan

**Comment by zenmonkeykstop** [comment]
Tested on Qubes (debian-9):
```
git checkout release/0.12.1
git checkout -b test-trusty-builder
git cherry-pick c93a0485612df40337e9eb1c65636ef6c76936b1
```
- Tested trusty build with `make build-debs` - :heavy_check_mark: 
- Tested xenial build with `make build-debs-xenial` - :heavy_check_mark: 

LGTM!

**Pull request merged**
