### PR TITLE
Add label images

### LINKED ISSUE #1141: Add labeling best-practices
Labeling is mostly an install-time affair, but the discussion should probably go in `hardware.md` since that's what you look at when purchasing materials. It can be referenced from elsewhere, especially in `install.md`.

### PR DESCRIPTION
**Pull request by huertanix**
## Status

Ready for review.

## Description of Changes

Fixes #1141 .

Changes proposed in this pull request:
Inclusion of printable labels and a note on what to do with them.

## Testing

How should the reviewer test this PR?
make docs, preview locally in dev environment. The Sphinx download tag "should work" in other environments, but these are famous last words.

## Deployment
Assuming image assets are uploaded to a real local filesystem and not into some cloud thing with special replication processes and CDN URLs, git copying the image assets into the directory should just work.

### If you made changes to the app code:

- [ ] Unit and functional tests pass on the development VM

### If you made changes to the system configuration:

- [ ] Testinfra tests pass on the development VM

^ I didn't think the docs were in the scope of unit/integration tests, but I'm happy to run them anyway if required!

### CODE REVIEW

**Comment by garrettr** [comment]
I didn't know about the `:download:` directive, cool!

**Comment by dachary** [comment]
@huertanix these labels are great :-) Do you still have the source files for translation purposes ?

**Comment by fowlslegs** [comment]
Awesome work @huertanix

**Comment by huertanix** [comment]
@dachary We do! I'll have to think about where they could live in the repo, but in the meantime I could also directly send you some .xcf files if you want to get a head start on that.

**Comment by dachary** [comment]
cool. @redshiftzero suggested https://github.com/freedomofpress/securedrop/tree/develop/docs/diagrams is where assests are kept in source form

**Comment by huertanix** [comment]
@dachary There's already a /docs/labels directory, I'll add them there since they're not diagrams.

**Pull request merged**
