### PR TITLE
Upgrade cffi to 1.14.0 and ruamel.yaml to 0.16.10

### LINKED ISSUE #5384: Docs build fails on Ubuntu 20.04
As reported here https://github.com/freedomofpress/securedrop/pull/5371#issuecomment-659318974 `make docs` targets (which depend on a virtualenv) currently fail on Ubuntu 20.04 due to incompatibilities with the pinned version of the requirements. Given that we can expect an increasing number of developers to be on 20.04 (especially after the August 6 point release which will trigger `do-release-upgrade` notifications), we should aim to resolve.

### PR DESCRIPTION
**Pull request by gonzalo-bulnes**
## Status

Ready for review

## Description of Changes

Fixes #5384

Changes proposed in this pull request:

- upgrade **cffi**: [from v1.10.0](https://github.com/freedomofpress/securedrop/blob/1.5.0-rc1/securedrop/requirements/python3/develop-requirements.txt#L109), to **v1.14.0**
- upgrade **ruamel.yaml**: [from v0.15.07](https://github.com/freedomofpress/securedrop/blob/1.5.0-rc1/securedrop/requirements/python3/develop-requirements.txt#L531), to **v0.16.10**

Both are the most recent versions available for those packages.
**Note**: strictly speaking, upgrading **cffi** to v1.12.2 and **ruamel.yaml** to v0.16.0 would be [_sufficient_](https://gist.github.com/gonzalo-bulnes/9d44d3f24067efbc05c78dea1e1dd53e) to fix the issue.

Once upgraded, the development dependencies can be installed and `make docs-lint` can be run successfully.

## Considerations

I attempted to upgrade the packages running [`make update-pip-requirements`][docs], but the goal `update-admin-pip-requirements` ([relevant code][code]) failed:

```
make update-pip-requirements

███ Updating admin pip requirements...
Traceback (most recent call last):
  File "/opt/admin/.venv3/bin/pip-compile", line 5, in <module>
    from piptools.scripts.compile import cli
  File "/opt/admin/.venv3/lib/python3.5/site-packages/piptools/scripts/compile.py", line 11, in <module>
    from .._compat import InstallCommand, install_req_from_line, parse_requirements
  File "/opt/admin/.venv3/lib/python3.5/site-packages/piptools/_compat/__init__.py", line 7, in <module>
    from .pip_compat import (
  File "/opt/admin/.venv3/lib/python3.5/site-packages/piptools/_compat/pip_compat.py", line 40, in <module>
    PackageFinder = do_import("index", "PackageFinder")
  File "/opt/admin/.venv3/lib/python3.5/site-packages/piptools/_compat/pip_compat.py", line 24, in do_import
    return getattr(imported, package)
AttributeError: module 'pip._internal.index' has no attribute 'PackageFinder'
make[1]: *** [Makefile:10: update-pip-requirements] Error 1
make: *** [Makefile:26: update-admin-pip-requirements] Error 2
```

:warning: I worked around this by executing `make update-python3-requirements` only, which resulted in the requirements file that you see in this PR.

Unless I'm missing something, neither `admin/requirements.txt` or `admin/requirements-dev.txt` ([relevant code][admin]) are used to generate `securedrop/requirements/python3/develop-requirements.txt`, this patch is correct and the admin dependencies can be treated as a distinct issue.

I think it's worth confirming I'm understanding that correctly though; I am not familiar with `pip-compile` and wouldn't know if there was more happening than what I see.

  [docs]: https://docs.securedrop.org/en/master/development/tips_and_tricks.html#upgrading-or-adding-python-dependencies
  [code]: https://github.com/freedomofpress/securedrop/blob/1.5.0-rc1/Makefile#L50-L51
  [admin]: https://github.com/freedomofpress/securedrop/blob/1.5.0-rc1/admin/Makefile#L7-L11

## Testing

- [ ] Check that the assumptions described above are correct

- Verify that `make docs-lint` succeeds, after a fresh install of the development dependencies [following the documentation guidelines][dg] on:
  - [ ] Ubuntu 20.04
  - [ ] Ubuntu 18.04
  - [ ] Ubuntu 16.04
- Verify that `make docs-linkcheck` succeeds, after a fresh install of the development dependencies [following the documentation guidelines][dg] on:
  - [ ] Ubuntu 20.04
  - [ ] Ubuntu 18.04
  - [ ] Ubuntu 16.04

:seedling: It may be quicker to review [this Dockerfile][gist] and use it for testing. (Note: testing `make docs-linkcheck` takes time —sometimes enough to timeout?—, so testing `make docs-lint` first/separately may make sense.).

  [dg]: https://docs.securedrop.org/en/master/development/documentation_guidelines.html#documentation-guidelines
  [gist]: https://gist.github.com/gonzalo-bulnes/b9aa0b02610b9abbe7dd7ec5f6d27fb0

## Deployment

This PR upgrades Python dependencies, which requires caution. That being said, they are advertised as _development_ dependencies and I wouldn't expect them to affect production deployments (existing or new).

### If you made changes that affect the documentation linting tools:

- [x] Doc linting (`make docs-lint`) passed locally
- [ ] Doc links linting (`make docs-linkcheck`) passed locally — at the moment on my machine the process gets killed after a while, I'll open the PR for CI to kick in and come back to this.

### If you added or updated a code dependency:

Choose one of the following:

- [ ] I have performed a diff review and pasted the contents to [the packaging wiki](https://github.com/freedomofpress/securedrop-debian-packaging/wiki)
- [x] I would like someone else to do the diff review (:pear: I'd be happy to learn how to do it though. If someone has bandwidth to pair or docs to point to, please comment here or ping me in Gitter?)

### CODE REVIEW

**Comment by gonzalo-bulnes** [comment]
I suspect the Circle CI builds may not have triggered because I initially opened a draft PR? (Also I don't see the card in Projects...)
I'll touch the commit see if it helps.

**Edit**: it didn't seem to have had any effect.

**Comment by eloquence** [comment]
That's odd, @gonzalo-bulnes, normally in cases like this pushing again has indeed resolved stuck CI. Can you try another force-push to your branch?

**Comment by conorsch** [comment]
I took the liberty of rebasing and force-pushing in an attempt to kickstart CI, but it still appears stuck. I'm tempted to cherry-pick this commit into a fresh branch and see if that resolves. @gonzalo-bulnes do you perhaps have CircleCI enabled in your personal account for this repo? That may be interfering with the CircleCI config here, preventing it from running.

**Comment by eloquence** [comment]
Hm, not sure if it was my amend+force-push that did it, but it looks like CI is happy now.

**Comment by gonzalo-bulnes** [comment]
> [...] you perhaps have CircleCI enabled in your personal account for this repo?

I don't @conorsch. Thanks @eloquence too!

For troubleshooting if you want to, or future reference: I did open this PR in a probably _unusual_ way. I had set up "Open draft PR" before deciding that it was "Ready for review". Then I wrote back "Ready to review" (note the misspelling /for/to/) and forgot moving back to a non-draft PR.

As a result, I first opened a "draft" PR in GitHub terms and I thought that was why the build hadn't started.
Seeing that I turned the PR into a non-draft PR expecting the build to start... and noticed my misspelling. When the build failed to start after force-pushing I thought maybe CircleCI was relying on the wording of PR template to trigger builds and decided to stop there until getting your feedback :slightly_smiling_face: (that hypothesis seems invalidated now, by the way).

**Review by kushaldas — APPROVED** [review]
This is good in my eyes, no need for diff-review as we are not updating any of the actual runtime dependencies.

**Comment by gonzalo-bulnes** [comment]
> @gonzalo-bulnes do you perhaps have CircleCI enabled in your personal account for this repo?

Cricling back to this (no pun intended): I think I know why Circle CI was not building my pull requests on push. When signing in I initially granted access to my personal repo to Circle CI, then (mistakenly) thought that wasn't necessary and revoked it.

Today I signed back into Circle CI, had to grant permissions again to do so, and the builds were created when I pushed changes. Even though the pull requests are created in this repository, the branch is in mine, so in hindsight it makes sense that Circle CI would need to pull from it. (Being a public repo, why circle CI needs permission is a different question. ¡?)

**Pull request merged**
