### PR TITLE
Add pip-{compile,sync} to dev vm provisioning

### PR DESCRIPTION
**Pull request by heartsucker**
Ansible errors out otherwise because it can't find the `requirements.txt` files.

### CODE REVIEW

**Comment by heartsucker** [comment]
Now that I'm looking at the code base more, I can't figure out for the life of me why this is needed. The commit this branches from (6230a4a) has both the `.txt` and `.in` files committed to the repo, yet with out this current change, the provisioning breaks every time including on fresh VMs. Am I taking crazy pills?

**Comment by garrettr** [comment]
> Now that I'm looking at the code base more, I can't figure out for the life of me why this is needed.

It shouldn't be. Can you give a more detailed STR? When I run `vagrant destroy -f development && vagrant up development` on the latest develop, provisioning is successful.

What version of Ansible are you running?

**Comment by conorsch** [comment]
Also can create and destroy development VMs fine. Running Ansible v1.8.4 in a virtualenv specifically for SecureDrop.

**Comment by heartsucker** [comment]
@conorsch / @garrettr 

STR
```
vagrant destroy -f development
vagrant up development --no-provision
vagrant ssh -c 'sudo ln -s /opt/VBoxGuestAdditions-4.3.10/lib/VBoxGuestAdditions /usr/lib/VBoxGuestAdditions'
vagrant reload
vagrant provision
```

I tried this multiple times yesterday with the same results, but today when I did it again, vagrant downloaded VBoxGuestAdditions version `4.3.36` over `4.3.10`. The problem has gone away. I have no idea what the underlying problem was, but as of commit f292ba6, everything works.

This can probably be close, though keeping the `pip-sync` task in might help keep people's dev VMs in sync with whatever the current list of requirements is.

**Comment by conorsch** [comment]
Definitely can't reproduce the failure with those steps. Sounds like this is still related to the virtualbox guest additions divergence, as discussed in #1381. Have you tried the [vagrant-vbguest plugin](https://github.com/dotless-de/vagrant-vbguest)? To try it:

```
vagrant plugin install vagrant-vbguest
```

I don't use it myself, but it may help with your use case, since your vbguest version is far out of sync with what's inside the base boxes. If it doesn't resolve your issue with running the VMs under Debian Jessie, make sure to remove the plugin (i.e. `vagrant plugin uninstall vagrant-vbguest`), otherwise it will aggressively run on every up and add additional provisioning time.

**Comment by heartsucker** [comment]
@conorsch I already have that plugin installed and was using it during the previous attempts (forgot to mention). I can no longer reproduce the issue, so I think this can be closed or the current modified change (only adding `pip-sync` instead of `pip install`) should be merged in.

**Comment by garrettr** [comment]
> This can probably be close, though keeping the pip-sync task in might help keep people's dev VMs in sync with whatever the current list of requirements is.

That should not be necessary with the current `pip-compile`-based workflow. The idea is that the `requirements/*.in` files list direct dependencies of SecureDrop, and we use `pip-compile` to generate the `requirements/*.txt` files from the `*.in` files, which contain all of the dependencies (including dependencies of dependencies, and so on, for SecureDrop).

Whenever the `*.in` files are updated, `pip_update.sh` should be run to update the `*.txt` files in tandem. This has been the practice for all of the pull requests related to updating the Python dependencies so far (see #1306 and #1379 for examples).

I can *sort-of* see why it may seem appropriate to use pip-sync to keep a development environment's Python dependencies in sync over time, but IMHO if there is a pull request that updates the Python dependencies, you should just re-provision your VMs (which is fast because we use Ansible). I think that the synchronization of state between the configuration and the environment is best handled by the configuration management tool (Ansible) and not by a multitude of specialized tools such as `pip-sync`.

If it can be shown that Ansible is insufficient for this purpose, or that using `pip-sync` in this manner would be a useful addition for a specific use case, then I would consider including it.

**Comment by heartsucker** [comment]
You're right. I suppose the fact that we don't yet use virtual environments makes `pip-sync` a little useless for now.

**Comment by conorsch** [comment]
> Whenever the *.in files are updated, pip_update.sh should be run to update the *.txt files in tandem. This has been the practice for all of the pull requests related to updating the Python dependencies so far (see #1306 and #1379 for examples).

Thanks for clarifying, @garrettr. Our dev docs don't mention that anywhere. Admittedly it's a recent change, but we need to document that for sanity. I think the best solution here is to update thedev docs with detailed explanation on managing Python dependencies via `pip_update.sh`, then we can close this issue. Will update #1208 with an item for the pip dependencies, then we can close this issue.

**Comment by garrettr** [comment]
I totally agree, @conorsch. We should've made sure it was documented in #1306 before it was merged. Thanks for adding a todo item to #1208 so we don't forget!

**Comment by conorsch** [comment]
Thanks for your active participation here, @heartsucker. Closing this issue out, since we're deferring to resolving this problem with better developer documentation in #1208. If these problems bite you again, please let me know!

**Pull request closed without merging**
