### PR TITLE
[qt-journalist-gui] Add unit test suite and CI job

### LINKED ISSUE #3229: [qt-journalist-updater] Add CI job for test suite
# Description

[See epic #3076 for primary feature, PRs for this ticket should go into `qt-journalist-updater]

We should add a CI job for running tests in `qt-journalist-updater` branch

### LINKED ISSUE #3234: [qt-journalist-updater] Unit test coverage of all existing functionality
## Description

[See epic #3076 for primary feature, PRs for this ticket should go into `qt-journalist-updater`]

We have a decent test suite started, but we should make sure everything is covered prior to refactoring or adding any more bells and whistles. 

## User Stories

As a SecureDrop developer, I want complete test coverage such that I detect regressions before they make it to users.

### PR DESCRIPTION
**Pull request by redshiftzero**
## Status

Ready for review

## Description of Changes

This PR:
* Fixes #3234 (add more tests)
* Fixes #3229 (add CI job)

## Testing

Does the CI job `updater-gui-tests` pass? Do the tests pass when executed locally? Is important functionality not tested? 

## Deployment

not yet...

## Checklist

- [x] `python3 test_gui.py` passes and `make flake8` passes

### CODE REVIEW

**Comment by redshiftzero** [comment]
This one should be good to go @kushaldas (rebased on latest `qt-journalist-updater`)

**Comment by redshiftzero** [comment]
I bet you are hitting #3243... I will tackle that issue today as it also needs resolving such that there is a more predictable time for #3230

**Comment by redshiftzero** [comment]
Ok I've fixed the underlying issue in #3246, I bet if you apply the changes there in your Tails VM then the UI should _not_ get stuck (and the fact that the UI does get stuck due to a bug like #3246 will be handled by #3228). 

Once #3246 is merged in, I propose we rebase the journalist GUI branch on latest develop (preserving merge commits) so we can keep cooking on this branch on top of these bugfixes we need in develop - does that sound like a reasonable workflow?

**Comment by kushaldas** [comment]
@redshiftzero Thank you, now we have to wait for #3257 to merge.

**Pull request merged**
