### PR TITLE
Dev docs: Explains libvirt cleanup procedures

### PR DESCRIPTION
**Pull request by conorsch**
## Status

Ready for review.

## Description of Changes

Refs #4993. May not resolve, pending further investigation of root cause.

Updates developer documentation with specific steps for managing the staging environment VMs on Debian hosts.

## Testing

* Check out this branch. 
* Run `make clean` (be aware this will destroy all non-version-controlled files, including config)
* Run `make staging`, confirm no errors.
* Run `make clean` again after staging run, confirm no errors.

If you encounter errors, try to investigate and determine where exactly the failure occurred. For instance, was it during VM removal? Try setting `MOLECULE_DEBUG=1` and see if that yields more useful information. 

## Deployment
No concerns for production deployments, these changes are dev-env only.

### If you made non-trivial code changes:

- [x] I have written a test plan and validated it for this PR

### If you made changes to documentation:

- [x] Doc linting (`make docs-lint`) passed locally

### CODE REVIEW

**Comment by creviera** [comment]
I ran a test (it's late so I'll look into failures tomorrow - I probably forgot some manual steps):

1. `make clean`
2. `make staging` and saw one failure reminding me to run `make build-debs`

```
    TASK [Fail if package is missing from build dir] *******************************
    failed: [localhost] (item=securedrop-keyring-0.1.3+1.3.0~rc1-amd64.deb) => {"changed": false, "item": "securedrop-keyring-0.1.3+1.3.0~rc1-amd64.deb", "msg": "run 'make build-debs' - ../../build/xenial/securedrop-keyring-0.1.3+1.3.0~rc1-amd64.deb missing"}
    failed: [localhost] (item=securedrop-config-0.1.3+1.3.0~rc1-amd64.deb) => {"changed": false, "item": "securedrop-config-0.1.3+1.3.0~rc1-amd64.deb", "msg": "run 'make build-debs' - ../../build/xenial/securedrop-config-0.1.3+1.3.0~rc1-amd64.deb missing"}
    failed: [localhost] (item=securedrop-ossec-agent-3.0.0+1.3.0~rc1-amd64.deb) => {"changed": false, "item": "securedrop-ossec-agent-3.0.0+1.3.0~rc1-amd64.deb", "msg": "run 'make build-debs' - ../../build/xenial/securedrop-ossec-agent-3.0.0+1.3.0~rc1-amd64.deb missing"}
    failed: [localhost] (item=securedrop-app-code_1.3.0~rc1+xenial_amd64.deb) => {"changed": false, "item": "securedrop-app-code_1.3.0~rc1+xenial_amd64.deb", "msg": "run 'make build-debs' - ../../build/xenial/securedrop-app-code_1.3.0~rc1+xenial_amd64.deb missing"}
    failed: [localhost] (item=ossec-agent-3.0.0-amd64.deb) => {"changed": false, "item": "ossec-agent-3.0.0-amd64.deb", "msg": "run 'make build-debs' - ../../build/xenial/ossec-agent-3.0.0-amd64.deb missing"}
    failed: [localhost] (item=securedrop-keyring-0.1.3+1.3.0~rc1-amd64.deb) => {"changed": false, "item": "securedrop-keyring-0.1.3+1.3.0~rc1-amd64.deb", "msg": "run 'make build-debs' - ../../build/xenial/securedrop-keyring-0.1.3+1.3.0~rc1-amd64.deb missing"}
    failed: [localhost] (item=securedrop-config-0.1.3+1.3.0~rc1-amd64.deb) => {"changed": false, "item": "securedrop-config-0.1.3+1.3.0~rc1-amd64.deb", "msg": "run 'make build-debs' - ../../build/xenial/securedrop-config-0.1.3+1.3.0~rc1-amd64.deb missing"}
    failed: [localhost] (item=securedrop-ossec-server-3.0.0+1.3.0~rc1-amd64.deb) => {"changed": false, "item": "securedrop-ossec-server-3.0.0+1.3.0~rc1-amd64.deb", "msg": "run 'make build-debs' - ../../build/xenial/securedrop-ossec-server-3.0.0+1.3.0~rc1-amd64.deb missing"}
    failed: [localhost] (item=ossec-server-3.0.0-amd64.deb) => {"changed": false, "item": "ossec-server-3.0.0-amd64.deb", "msg": "run 'make build-debs' - ../../build/xenial/ossec-server-3.0.0-amd64.deb missing"}
    
    NO MORE HOSTS LEFT *************************************************************
    
    NO MORE HOSTS LEFT *************************************************************
    	to retry, use: --limit @/home/creviera/workspace/freedomofpress/securedrop/install_files/ansible-base/securedrop-staging.retry
    
    PLAY RECAP *********************************************************************
    localhost                  : ok=3    changed=0    unreachable=0    failed=1   
    
ERROR: 
Makefile:198: recipe for target 'staging' failed
make: *** [staging] Error 2
```
3. `make build-debs` failed:

```
--> Inventory /home/creviera/workspace/freedomofpress/securedrop/molecule/builder-xenial/../../install_files/ansible-base/group_vars linked to /home/creviera/.cache/molecule/securedrop/builder-xenial/inventory/group_vars
--> Scenario: 'builder-xenial'
--> Action: 'create'
--> Sanity checks: 'docker'
    
    PLAY [Create] ******************************************************************
    
    TASK [debug] *******************************************************************
    ok: [localhost] => {
        "msg": "Building with Docker image quay.io/freedomofpress/sd-docker-builder-xenial@sha256:1e61e825bd7bc221eacb071ae200924f99fb1728e736d9a707fd183d22f0dfcb"
    }
    
    TASK [Create builders] *********************************************************
    failed: [localhost] (item={'name': 'xenial-sd-app', 'groups': ['builders']}) => {"changed": false, "item": {"groups": ["builders"], "name": "xenial-sd-app"}, "msg": "Error pulling image quay.io/freedomofpress/sd-docker-builder-xenial:sha256:1e61e825bd7bc221eacb071ae200924f99fb1728e736d9a707fd183d22f0dfcb - 500 Server Error: Internal Server Error (\"b'{\"message\":\"Get https://quay.io/v2/: dial tcp: lookup quay.io on 75.75.76.76:53: write udp 10.36.10.6:35307->75.75.76.76:53: write: operation not permitted\"}'\")"}
    failed: [localhost] (item={'name': 'xenial-sd-generic-ossec-agent', 'groups': ['builders']}) => {"changed": false, "item": {"groups": ["builders"], "name": "xenial-sd-generic-ossec-agent"}, "msg": "Error pulling image quay.io/freedomofpress/sd-docker-builder-xenial:sha256:1e61e825bd7bc221eacb071ae200924f99fb1728e736d9a707fd183d22f0dfcb - 500 Server Error: Internal Server Error (\"b'{\"message\":\"Get https://quay.io/v2/: dial tcp: lookup quay.io on 75.75.76.76:53: write udp 10.36.10.6:54055->75.75.76.76:53: write: operation not permitted\"}'\")"}
    failed: [localhost] (item={'name': 'xenial-sd-generic-ossec-server', 'groups': ['builders']}) => {"changed": false, "item": {"groups": ["builders"], "name": "xenial-sd-generic-ossec-server"}, "msg": "Error pulling image quay.io/freedomofpress/sd-docker-builder-xenial:sha256:1e61e825bd7bc221eacb071ae200924f99fb1728e736d9a707fd183d22f0dfcb - 500 Server Error: Internal Server Error (\"b'{\"message\":\"Get https://quay.io/v2/: dial tcp: lookup quay.io on 75.75.76.76:53: write udp 10.36.10.6:52729->75.75.76.76:53: write: operation not permitted\"}'\")"}
    failed: [localhost] (item={'name': 'xenial-sd-generic-ossec-agent2', 'groups': ['builders']}) => {"changed": false, "item": {"groups": ["builders"], "name": "xenial-sd-generic-ossec-agent2"}, "msg": "Error pulling image quay.io/freedomofpress/sd-docker-builder-xenial:sha256:1e61e825bd7bc221eacb071ae200924f99fb1728e736d9a707fd183d22f0dfcb - 500 Server Error: Internal Server Error (\"b'{\"message\":\"Get https://quay.io/v2/: dial tcp: lookup quay.io on 75.75.76.76:53: write udp 10.36.10.6:38137->75.75.76.76:53: write: operation not permitted\"}'\")"}
    failed: [localhost] (item={'name': 'xenial-sd-generic-ossec-server2', 'groups': ['builders']}) => {"changed": false, "item": {"groups": ["builders"], "name": "xenial-sd-generic-ossec-server2"}, "msg": "Error pulling image quay.io/freedomofpress/sd-docker-builder-xenial:sha256:1e61e825bd7bc221eacb071ae200924f99fb1728e736d9a707fd183d22f0dfcb - 500 Server Error: Internal Server Error (\"b'{\"message\":\"Get https://quay.io/v2/: dial tcp: lookup quay.io on 75.75.76.76:53: write udp 10.36.10.6:49115->75.75.76.76:53: write: operation not permitted\"}'\")"}
    failed: [localhost] (item={'name': 'xenial-sd-grsec', 'groups': ['builders']}) => {"changed": false, "item": {"groups": ["builders"], "name": "xenial-sd-grsec"}, "msg": "Error pulling image quay.io/freedomofpress/sd-docker-builder-xenial:sha256:1e61e825bd7bc221eacb071ae200924f99fb1728e736d9a707fd183d22f0dfcb - 500 Server Error: Internal Server Error (\"b'{\"message\":\"Get https://quay.io/v2/: dial tcp: lookup quay.io on 75.75.76.76:53: write udp 10.36.10.6:58601->75.75.76.76:53: write: operation not permitted\"}'\")"}
    failed: [localhost] (item={'name': 'xenial-sd-config', 'groups': ['builders']}) => {"changed": false, "item": {"groups": ["builders"], "name": "xenial-sd-config"}, "msg": "Error pulling image quay.io/freedomofpress/sd-docker-builder-xenial:sha256:1e61e825bd7bc221eacb071ae200924f99fb1728e736d9a707fd183d22f0dfcb - 500 Server Error: Internal Server Error (\"b'{\"message\":\"Get https://quay.io/v2/: dial tcp: lookup quay.io on 75.75.76.76:53: write udp 10.36.10.6:40222->75.75.76.76:53: write: operation not permitted\"}'\")"}
    failed: [localhost] (item={'name': 'xenial-sd-keyring', 'groups': ['builders']}) => {"changed": false, "item": {"groups": ["builders"], "name": "xenial-sd-keyring"}, "msg": "Error pulling image quay.io/freedomofpress/sd-docker-builder-xenial:sha256:1e61e825bd7bc221eacb071ae200924f99fb1728e736d9a707fd183d22f0dfcb - 500 Server Error: Internal Server Error (\"b'{\"message\":\"Get https://quay.io/v2/: dial tcp: lookup quay.io on 75.75.76.76:53: write udp 10.36.10.6:56794->75.75.76.76:53: write: operation not permitted\"}'\")"}
    failed: [localhost] (item={'name': 'xenial-sd-sec-update', 'groups': ['builders']}) => {"changed": false, "item": {"groups": ["builders"], "name": "xenial-sd-sec-update"}, "msg": "Error pulling image quay.io/freedomofpress/sd-docker-builder-xenial:sha256:1e61e825bd7bc221eacb071ae200924f99fb1728e736d9a707fd183d22f0dfcb - 500 Server Error: Internal Server Error (\"b'{\"message\":\"Get https://quay.io/v2/: dial tcp: lookup quay.io on 75.75.76.76:53: write udp 10.36.10.6:57286->75.75.76.76:53: write: operation not permitted\"}'\")"}
    failed: [localhost] (item={'name': 'xenial-sd-dpkg-verification', 'groups': ['testers']}) => {"changed": false, "item": {"groups": ["testers"], "name": "xenial-sd-dpkg-verification"}, "msg": "Error pulling image quay.io/freedomofpress/sd-docker-builder-xenial:sha256:1e61e825bd7bc221eacb071ae200924f99fb1728e736d9a707fd183d22f0dfcb - 500 Server Error: Internal Server Error (\"b'{\"message\":\"Get https://quay.io/v2/: dial tcp: lookup quay.io on 75.75.76.76:53: write udp 10.36.10.6:45541->75.75.76.76:53: write: operation not permitted\"}'\")"}
    
    PLAY RECAP *********************************************************************
    localhost                  : ok=1    changed=0    unreachable=0    failed=1   
    
ERROR: 
An error occurred during the test sequence action: 'create'. Cleaning up.
--> Inventory /home/creviera/workspace/freedomofpress/securedrop/molecule/builder-xenial/../../install_files/ansible-base/group_vars linked to /home/creviera/.cache/molecule/securedrop/builder-xenial/inventory/group_vars
--> Scenario: 'builder-xenial'
--> Action: 'cleanup'
Skipping, cleanup playbook not configured.
```

**Comment by emkll** [comment]
@creviera based on the output you've pasted above, it seems like the Quay.io image registry was having server issues. I would recommend you try `make build-debs` again and see if you can reliably reproduce that error.

**Comment by zenmonkeykstop** [comment]
Tested as described (on Ubuntu 18.04).  `MOLECULE_DEBUG=1 make clean`  is frozen at `Removing Molecule staging environment` after successful `make staging`. 

Looking at virt-manager, app_staging was powered off but not removed, and mon-staging is still running. Killing `make clean` and rerunning it doesn't help. 

Steps taken to clean out old VMs manually:
- kill stalled vagrant processes
- destroy and undefine domains via `virsh`
- delete volumes via `virsh`
- `make clean`then completes successfully.

After following above steps, running `make-build-debs` and `make staging` works again. But the subsequent `make clean` still freezes.

**Comment by creviera** [comment]
I will run through this again and see what happens

**Comment by creviera** [comment]
```
Run make clean (be aware this will destroy all non-version-controlled files, including config)
Run make staging, confirm no errors.
Run make clean again after staging run, confirm no errors.
```

this all worked for me the second time through once the registry was back up (seems to be down a lot)

**Pull request merged**
